# **Start Section:**

In [63]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [64]:
!pip install git+https://github.com/DaneshSelwal/treeffuser.git

Collecting git+https://github.com/DaneshSelwal/treeffuser.git
  Cloning https://github.com/DaneshSelwal/treeffuser.git to /tmp/pip-req-build-f75x3ipx
  Running command git clone --filter=blob:none --quiet https://github.com/DaneshSelwal/treeffuser.git /tmp/pip-req-build-f75x3ipx
  Resolved https://github.com/DaneshSelwal/treeffuser.git to commit 9717581990db9e7dedaa8c593ec724997e52bdb8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: einops<0.9.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.8.2)
Requirement already satisfied: jaxtyping<0.3.0,>=0.2.19 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.2.38)
Collecting lightgbm==4.3.0 (from treeffuser==0.1.3)
  Using cached lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Requirement already satisfied: ml-collections<0.2.0,>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.1.1)
Requirement already satisfied: numpy<2.0,>=1.24 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (2.2.2)
Collecting scikit-learn==1.5.0 (from treeffuser==0.1.3)
  Using cached scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy<2.0,>=1.13 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (1.16.3)
Requirement already satisfied: tqdm<5.0.0,>=4.66.4 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (3.6.0)
Requirement already satisfied: wadler-lindig>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from jaxtyping<0.3.0,>=0.2.19->treeffuser==0.1.3) (0.1.7)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (6.0.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.17.0)
Requirement already satisfied: contextlib2 in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (21.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2026.1)
Using cached lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
Using cached scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
Installing collected packages: scikit-learn, lightgbm
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 4.6.0
    Uninstalling lightgbm-4.6.0:
      Successfully uninstalled lightgbm-4.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
ngboost 0.5.8 requires scikit-learn<2.0,>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
interpret-core 0.7.4 requires scikit-learn>=1.6.0, but you have scikit-learn 1.5.0 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed lightgbm-4.3.0 scikit-learn-1.5.0

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-Datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, which is not installed.
puncc 0.8.0 requires scikit-learn, which is not installed.
mapie 0.6.0 requires scikit-learn, which is not installed.
skorch 1.3.1 requires scikit-learn>=0.22.0, which is not installed.
pytorch-tabnet2 4.5.3 requires scikit-learn, which is not installed.
pytorch-tabnet2 4.5.3 requires torch; python_version != "3.13", which is not installed.
ngboost 0.5.8 requires scikit-learn<2.0,>=1.6, which is not installed.
interpret-core 0.7.4 requires scikit-learn>=1.6.0, which is not installed.
gpboost 1.6.1 requires scikit-learn!=0.22.0, which is not installed.
bayesian-optimization 3.2.0 requires scikit-learn>=1.0.0, which is not installed.
umap-learn 0.5.12 requires scikit-learn>=1.6, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
pynndescent 0.6.0 requires scikit-learn>=0.18, which is not installed.
libpysal 4.14.1 requires scikit-learn>=1.4.0, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
pysal 25.7 requires scikit-learn>=1.1, which is not installed.
cufflinks 0.17.3 requires plotly>=4.1.1, which is not installed.
peft 0.19.1 requires torch>=1.13.0, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
segregation 2.5.4 requires scikit-learn>=0.21.3, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
ydf-tf 2.20.0 requires tensorflow==2.20.0, which is not installed.
spopt 0.7.0 requires scikit-learn>=1.4.0, which is not installed.
hdbscan 0.8.42 requires scikit-learn>=1.6, which is not installed.
accelerate 1.13.0 requires torch>=2.0.0, which is not installed.
mapclassify 2.10.0 requires scikit-learn>=1.4, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
fastai 2.8.7 requires scikit-learn, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
keras-hub 0.26.0 requires tensorflow-text; platform_system != "Windows", which is not installed.
dopamine-rl 4.1.2 requires tensorflow>=2.2.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow-probability>=0.13.0, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
imbalanced-learn 0.14.1 requires scikit-learn<2,>=1.4.2, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
sentence-transformers 5.4.1 requires scikit-learn>=0.22.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
geemap 0.37.2 requires plotly, which is not installed.
esda 2.9.0 requires scikit-learn>=1.4, which is not installed.
spreg 1.9.0 requires scikit-learn>=0.22, which is not installed.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
pytorch-tabnet2 4.5.3 requires torch; python_version != "3.13", which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
timm 1.0.26 requires torchvision, which is not installed.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, but you have lightgbm 4.6.0 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ngboost
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from pathlib import Path
from scipy.stats import norm, kstest
from pytorch_tabnet import TabNetRegressor
from treeffuser import Treeffuser, Samples
from treeffuser._score_models import TreeBasedScoreModel
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# Go to find & replace button and replace (noise_uncertainty_analysis) with your folder name. Rename your train and test Dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (str) with actual data label name.

In [3]:
feature_names = ['A', 'B', 'C', 'D', 'O']

In [4]:
train_data_path = "./drive/MyDrive/noise_uncertainty_analysis/data/train.csv"
test_data_path = "./drive/MyDrive/noise_uncertainty_analysis/data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (189, 8)
First 5 rows of training data:
         C    mp     FA      CA       F       W_P    Adm    str
0  280.80  70.2  858.0  1183.0    0.00  0.450000  0.610  21.56
1  372.15   0.0  975.0   525.0   52.85  0.493081  7.000  34.00
2  360.00  75.0  975.0   525.0   40.00  0.509722  7.000  28.00
3  364.30   0.0  975.0   525.0  110.40  0.503706  7.000  42.00
4  315.00  31.5  780.0  1110.0    0.00  0.370000  5.355  25.82

Shape of test data: (95, 8)
First 5 rows of test data:
         C     mp     FA     CA      F       W_P   Adm   str
0  364.30    0.0  975.0  525.0  60.40  0.503706   7.0  34.0
1  344.30   75.0  975.0  525.0  55.40  0.532965   7.0  36.0
2  390.00    0.0  975.0  525.0  60.00  0.470513   7.0  36.0
3  352.15   75.0  975.0  525.0  47.85  0.521085   7.0  35.0
4  400.00  160.0  801.0  801.0  40.00  0.300000  10.3  44.6

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (189, 7)
Shape of y_train: (189,)
Shape of X_test: (95, 7)
Shape of y_test: (95,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[-1.56879184  0.95792014 -0.09685034  1.33138508 -0.85369002  0.16810471
  -0.08799752]
 [ 0.40300047 -0.7708921   0.73537613 -0.93459372  0.061075    0.78285857
  -0.0664621 ]
 [ 0.14074238  1.07612953  0.73537613 -0.93459372 -0.16134185  1.020321
  -0.0664621 ]
 [ 0.233558   -0.7708921   0.73537613 -0.93459372  1.05719093  0.93447436
  -0.0664621 ]
 [-0.83058388  0.00485698 -0.65166799  1.07999229 -0.85369002 -0.97347298
  -0.07200604]]

First five rows of normalized X_test:
[[ 0.233558   -0.7708921   0.73537613 -0.93459372  0.19175572  0.93447436
  -0.0664621 ]
 [-0.19814256  1.07612953  0.73537613 -0.93459372  0.1052122   1.35199213
  -0.0664621 ]
 [ 0.78829322 -0.7708921   0.73537613 -0.93459372  0.18483223  0.4608195
  -0.0664621 ]
 [-0.02870009  1.07612953  0.73537613 -0.93459372 -0.02546852  1.18246784
  -0.0664621 ]
 [ 1.0041435   3.1694207  -0.50229401  0.01587763 -0.16134185 -1.97235346
  -0.05534052]]

# **Functions:**

In [8]:
# Define the model classes
model_classes = {
    'Random Forest': RandomForestRegressor,
    'Gradient Boosting': GradientBoostingRegressor,
    'XGBoost': XGBRegressor,
    'LightGBM': LGBMRegressor,
    'GPBoost': GPBoostRegressor,
    'CatBoost': CatBoostRegressor,
    'HistGradientBoosting': HistGradientBoostingRegressor,
    'TabNet': TabNetRegressor,
    'NGBoost': NGBRegressor
}

def _ensure_excel_file(path):
    import os
    import pandas as pd
    if not os.path.exists(path):
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        pd.DataFrame().to_excel(path)
    return path

In [9]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'TabNet' : 'TabNet',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [10]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_plots(predictions_df, y_test, excel_path):
    # 1. Predicted vs. Actual Plot
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x='Actual', y='Mean', data=predictions_df)
    plt.plot([predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             [predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             color='red', linestyle='--')
    plt.title('Predicted str vs. Actual str')
    plt.xlabel('Actual str')
    plt.ylabel('Predicted Mean str')
    plt.tight_layout()
    predicted_vs_actual_path = 'predicted_vs_actual.png'
    _ensure_parent_dir(predicted_vs_actual_path)
    plt.savefig(_ensure_parent_dir(predicted_vs_actual_path))
    plt.close()

    # 2. Uncertainty Bands
    plt.figure(figsize=(12, 8))
    plt.errorbar(x=range(len(predictions_df)), y=predictions_df['Mean'],
                 yerr=predictions_df['StdDev'], fmt='o', markersize=4, ecolor='red', elinewidth=1, capsize=5, alpha=0.7)
    plt.plot(range(len(predictions_df)), predictions_df['Mean'], color='black', linewidth=0.5, alpha=0.7)
    plt.title('Predicted Mean with Uncertainty Bands', fontsize=16)
    plt.xlabel('Sample Number', fontsize=14)
    plt.ylabel('Predicted Mean str')
    plt.tight_layout()
    uncertainty_bands_path = 'uncertainty_bands.png'
    _ensure_parent_dir(uncertainty_bands_path)
    plt.savefig(_ensure_parent_dir(uncertainty_bands_path))
    plt.close()

    # 3. Histogram of Standard Deviations
    plt.figure(figsize=(12, 8))
    sns.histplot(predictions_df['StdDev'], bins=20, kde=True)
    plt.title('Distribution of Predicted Standard Deviations')
    plt.xlabel('Standard Deviation')
    plt.ylabel('Frequency')
    plt.tight_layout()
    histogram_stddev_path = 'histogram_stddev.png'
    _ensure_parent_dir(histogram_stddev_path)
    plt.savefig(_ensure_parent_dir(histogram_stddev_path))
    plt.close()

    # 4. Residual Plot
    residuals = predictions_df['Actual'] - predictions_df['Mean']
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x=predictions_df['Mean'], y=residuals)
    plt.axhline(0, color='red', linestyle='--')
    plt.title('Residual Plot')
    plt.xlabel('Predicted Mean str')
    plt.ylabel('Residuals')
    plt.tight_layout()
    residual_plot_path = 'residual_plot.png'
    _ensure_parent_dir(residual_plot_path)
    plt.savefig(_ensure_parent_dir(residual_plot_path))
    plt.close()

    # Plot the standard deviation of the predictions
    plt.figure(figsize=(12, 6))
    plt.plot(
        predictions_df['StdDev'],
        label='Standard Deviation',
        color='green',
        marker='o',
        linestyle='dashed'
    )
    plt.xlabel('Sample Number')
    plt.ylabel('Standard Deviation')
    plt.title('Standard Deviation of Predictions')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    stddev_plot_path = 'stddev_plot.png'
    _ensure_parent_dir(stddev_plot_path)
    plt.savefig(_ensure_parent_dir(stddev_plot_path))
    plt.close()

    # Plot the actual vs predicted mean with confidence intervals
    plt.figure(figsize=(12, 6))
    plt.plot(
        y_test,
        label='Actual str',
        color='black',
        marker='o',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    plt.plot(
        predictions_df['Mean'],
        label='Predicted Mean str',
        color='red',
        marker='x',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    confidence_interval = 1.96 * predictions_df['StdDev']
    plt.fill_between(
        np.arange(len(predictions_df)),
        predictions_df['Mean'] - confidence_interval,
        predictions_df['Mean'] + confidence_interval,
        color='blue',
        alpha=0.2,
        label='95% Confidence Interval'
    )
    plt.xlabel('Sample Number')
    plt.ylabel(' str')
    plt.title('Predictions with Confidence Intervals')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    prediction_plot_path = 'prediction_plot.png'
    _ensure_parent_dir(prediction_plot_path)
    plt.savefig(_ensure_parent_dir(prediction_plot_path))
    plt.close()

    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(_ensure_parent_dir(excel_path), engine='xlsxwriter')

    # Write the dataframe to a worksheet.
    writer
    predictions_df.to_excel(writer, sheet_name='Predictions', index=False)

    # Access the XlsxWriter workbook and worksheet objects from the writer object.
    workbook = writer.book

    # Insert the plots into new worksheets.
    worksheet_predicted_vs_actual = workbook.add_worksheet('Predicted vs Actual')
    worksheet_predicted_vs_actual.insert_image('A1', predicted_vs_actual_path)

    worksheet_uncertainty_bands = workbook.add_worksheet('Uncertainty Bands')
    worksheet_uncertainty_bands.insert_image('A1', uncertainty_bands_path)

    worksheet_histogram_stddev = workbook.add_worksheet('Histogram StdDev')
    worksheet_histogram_stddev.insert_image('A1', histogram_stddev_path)

    worksheet_residual_plot = workbook.add_worksheet('Residual Plot')
    worksheet_residual_plot.insert_image('A1', residual_plot_path)

    worksheet_stddev = workbook.add_worksheet('StdDev Plot')
    worksheet_stddev.insert_image('A1', stddev_plot_path)

    worksheet_prediction = workbook.add_worksheet('Predictions Plot')
    worksheet_prediction.insert_image('A1', prediction_plot_path)

    # Close the Pandas Excel writer and output the Excel file.
    writer.close()
    print(f"Excel file saved at {excel_path}")

    # Optionally, remove the image files now that they're embedded in the Excel file
    if os.path.exists(str(predicted_vs_actual_path)): os.remove(str(predicted_vs_actual_path))
    if os.path.exists(str(uncertainty_bands_path)): os.remove(str(uncertainty_bands_path))
    if os.path.exists(str(histogram_stddev_path)): os.remove(str(histogram_stddev_path))
    if os.path.exists(str(residual_plot_path)): os.remove(str(residual_plot_path))
    if os.path.exists(str(stddev_plot_path)): os.remove(str(stddev_plot_path))
    if os.path.exists(str(prediction_plot_path)): os.remove(str(prediction_plot_path))

In [11]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_crps_decomposition(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    # -------------------------------
    # Total CRPS
    # -------------------------------
    crps_values = ps.crps_gaussian(
        y_true, mu=mu_pred, sig=sigma_pred
    )
    total_crps = np.mean(crps_values)

    # -------------------------------
    # Uncertainty (climatology)
    # -------------------------------
    global_mu = np.mean(y_true)
    global_sigma = np.std(y_true)

    uncertainty = np.mean(
        ps.crps_gaussian(y_true, mu=global_mu, sig=global_sigma)
    )

    # -------------------------------
    # Reliability & Resolution
    # -------------------------------
    sort_idx = np.argsort(mu_pred)
    y_sorted = y_true[sort_idx]
    mu_sorted = mu_pred[sort_idx]
    sigma_sorted = sigma_pred[sort_idx]

    bins = np.array_split(np.arange(len(y_true)), n_bins)

    bin_results = []
    reliability_sum = 0.0

    for i, b in enumerate(bins):
        bin_y = y_sorted[b]
        bin_mu = mu_sorted[b]
        bin_sigma = sigma_sorted[b]

        bin_crps = np.mean(
            ps.crps_gaussian(bin_y, mu=bin_mu, sig=bin_sigma)
        )

        reliability_sum += bin_crps

        bin_results.append({
            "Bin": i + 1,
            "Bin_Size": len(b),
            "Mean_Pred_Mu": np.mean(bin_mu),
            "Mean_Pred_Sigma": np.mean(bin_sigma),
            "Bin_CRPS": bin_crps
        })

    reliability = reliability_sum / n_bins
    resolution = uncertainty - (total_crps - reliability)

    # -------------------------------
    # Summary table
    # -------------------------------
    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Total_CRPS": total_crps,
        "Reliability": reliability,
        "Resolution": resolution,
        "Uncertainty": uncertainty,
        "Num_Bins": n_bins
    }])

    bin_df = pd.DataFrame(bin_results)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_summary = f"CRPS_Summary_{model_name}"
    sheet_bins = f"CRPS_Bins_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)
        writer
        bin_df.to_excel(writer, sheet_name=sheet_bins, index=False)

    print(f"✅ CRPS decomposition saved to:\n{excel_path}")
    print(f"   Sheets: {sheet_summary}, {sheet_bins}")

    return summary_df

In [12]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_pit_results(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):
    """
    Generate PIT values, histogram, calibration diagnostics,
    and save everything to Excel with the PIT plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Compute PIT values
    # -------------------------------
    pit_values = norm.cdf(y_true, loc=mu_pred, scale=sigma_pred)

    pit_df = pd.DataFrame({"PIT_Value": pit_values})

    # -------------------------------
    # Histogram data
    # -------------------------------
    hist_density, bin_edges = np.histogram(
        pit_values, bins=n_bins, range=(0, 1), density=True
    )
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    hist_df = pd.DataFrame({
        "Bin_Center": bin_centers,
        "Density": hist_density
    })

    # -------------------------------
    # Calibration diagnostics
    # -------------------------------
    pit_mean = pit_values.mean()
    pit_var = pit_values.var()
    ks_stat, ks_pvalue = kstest(pit_values, 'uniform')

    if ks_pvalue > 0.05:
        diagnosis = "Well-calibrated (Uniform PIT)"
    elif pit_var < 1/12:
        diagnosis = "Over-dispersed (Under-confident)"
    elif pit_var > 1/12:
        diagnosis = "Under-dispersed (Over-confident)"
    else:
        diagnosis = "Biased or miscalibrated"

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_PIT": pit_mean,
        "Variance_PIT": pit_var,
        "Ideal_Variance_(1/12)": 1/12,
        "KS_Statistic": ks_stat,
        "KS_pvalue": ks_pvalue,
        "Calibration_Diagnosis": diagnosis
    }])

    # -------------------------------
    # Create PIT plot in memory
    # -------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(
        pit_values,
        bins=n_bins,
        density=True,
        color="skyblue",
        edgecolor="black",
        alpha=0.75
    )
    ax.axhline(1, color="red", linestyle="--", label="Perfect Calibration")
    ax.set_xlabel("PIT Value")
    ax.set_ylabel("Density")
    ax.set_title(f"PIT Histogram – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_values = f"PIT_Values_{model_name}"
    sheet_hist = f"PIT_Histogram_{model_name}"
    sheet_summary = f"PIT_Summary_{model_name}"
    sheet_plot = f"PIT_Plot_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        writer
        pit_df.to_excel(writer, sheet_name=sheet_values, index=False)
        writer
        hist_df.to_excel(writer, sheet_name=sheet_hist, index=False)
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        # Create empty sheet for plot
        workbook = writer.book
        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print(f"✅ PIT values, histogram, summary, and EMBEDDED plot saved to:")
    print(f"   {excel_path}")

    return pit_df

In [13]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_calibration_curve(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_quantiles=10
):
    """
    Generate quantile calibration curve (reliability diagram),
    compute calibration errors, and save everything to Excel
    with the plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()
    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Quantiles
    # -------------------------------
    quantiles = np.linspace(0, 1, n_quantiles + 1)

    observed_freq = []
    predicted_q = []

    for q in quantiles:
        # Predicted value at quantile q
        thresh = norm.ppf(q, loc=mu_pred, scale=sigma_pred)

        # Observed frequency
        obs = np.mean(y_true <= thresh)

        predicted_q.append(q)
        observed_freq.append(obs)

    predicted_q = np.array(predicted_q)
    observed_freq = np.array(observed_freq)

    # -------------------------------
    # Calibration metrics
    # -------------------------------
    mce = np.mean(np.abs(observed_freq - predicted_q))
    rmsce = np.sqrt(np.mean((observed_freq - predicted_q) ** 2))

    calib_df = pd.DataFrame({
        "Predicted_Quantile": predicted_q,
        "Observed_Frequency": observed_freq,
        "Absolute_Error": np.abs(observed_freq - predicted_q)
    })

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_Calibration_Error (MCE)": mce,
        "RMS_Calibration_Error (RMSCE)": rmsce,
        "Num_Quantiles": n_quantiles
    }])

    # -------------------------------
    # Create calibration plot
    # -------------------------------
    fig, ax = plt.subplots(figsize=(7, 7))

    ax.plot([0, 1], [0, 1], 'k--', label="Perfect Calibration")
    ax.plot(
        predicted_q,
        observed_freq,
        'o-',
        color='teal',
        label=f"{model_name}"
    )

    ax.set_xlabel("Predicted Quantile (Confidence Level)")
    ax.set_ylabel("Observed Frequency")
    ax.set_title(f"Quantile Calibration Curve – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_curve = f"Calibration_Curve_{model_name}"
    sheet_summary = f"Calibration_Summary_{model_name}"
    sheet_plot = f"Calibration_Plot_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        writer
        calib_df.to_excel(writer, sheet_name=sheet_curve, index=False)
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        workbook = writer.book

        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print("✅ Calibration curve & metrics saved to Excel:")
    print(f"   {excel_path}")

    return calib_df

In [14]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
# Define the path to the folder
folder_path = "/content/drive/MyDrive/noise_uncertainty_analysis"

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

def plot_metrics_and_save_to_excel(writer, predictions_df, y_true, model_name):
    # Calculate metrics
    mean_pred = predictions_df['Mean']
    std_pred = predictions_df['StdDev']

    # Sharpness is the standard deviation
    sharpness = std_pred.mean()

    # CRPS for each prediction
    crps_values = ps.crps_gaussian(y_true, mean_pred, std_pred)

    # Negative Log Likelihood (NLL) for each prediction
    nll_values = -norm.logpdf(y_true, loc=mean_pred, scale=std_pred)
    nll = nll_values.mean()

    # Calibration (Validity)
    percentiles = np.linspace(0, 100, 101)
    calibration = [np.mean((y_true <= np.percentile(mean_pred + std_pred * np.random.randn(*mean_pred.shape), p))) for p in percentiles]

    # Create a DataFrame to store the metrics
    metrics_df = pd.DataFrame({
        'Mean Prediction': mean_pred,
        'Standard Deviation': std_pred,
        'CRPS': crps_values,
        'NLL': nll_values
    })

    # Add summary statistics
    summary_df = pd.DataFrame({
        'Metric': ['Sharpness', 'Mean CRPS', 'Mean NLL'],
        'Value': [sharpness, crps_values.mean(), nll]
    })

    # Write the metrics and summary to the Excel sheet
    metrics_sheet_name = f'{model_name} Metrics'
    writer
    metrics_df.to_excel(writer, sheet_name=metrics_sheet_name, index=False)

    summary_sheet_name = f'{model_name} Summary'
    writer
    summary_df.to_excel(writer, sheet_name=summary_sheet_name, index=False)

    # Plotting
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    # Sharpness plot
    axs[0, 0].hist(std_pred, bins=30, color='skyblue', edgecolor='black')
    axs[0, 0].set_title(f'Sharpness (StdDev) for {model_name}')
    axs[0, 0].set_xlabel('Standard Deviation')
    axs[0, 0].set_ylabel('Frequency')

    # CRPS plot (distribution)
    axs[0, 1].hist(crps_values, bins=30, color='lightgreen', edgecolor='black')
    axs[0, 1].set_title(f'CRPS Distribution for {model_name}')
    axs[0, 1].set_xlabel('CRPS')
    axs[0, 1].set_ylabel('Frequency')

    # NLL plot (distribution)
    axs[1, 0].hist(nll_values, bins=30, color='salmon', edgecolor='black')
    axs[1, 0].set_title(f'NLL Distribution for {model_name}')
    axs[1, 0].set_xlabel('NLL')
    axs[1, 0].set_ylabel('Frequency')

    # Calibration plot
    axs[1, 1].plot(percentiles, calibration, label='Calibration Curve')
    axs[1, 1].plot(percentiles, percentiles / 100, linestyle='--', label='Perfect Calibration')
    axs[1, 1].set_title(f'Calibration (Validity) for {model_name}')
    axs[1, 1].set_xlabel('Predicted Percentile')
    axs[1, 1].set_ylabel('Observed Frequency')
    axs[1, 1].legend()

    plt.tight_layout()

    # Save plots to images
    plot_image_path = f'{model_name}_plots.png'
    fig.savefig(_ensure_parent_dir(plot_image_path))
    plt.close(fig)

    # Insert the plot image into the Excel sheet
    sheet_name = f'{model_name} Plots'
    if sheet_name not in writer.sheets:  # Check if sheet already exists
        # If sheet doesn't exist, create a new one
        worksheet = writer.book.add_worksheet(sheet_name)
    else:
        # If sheet exists, get the existing sheet object to avoid duplicates
        worksheet = writer.sheets[sheet_name]
    worksheet.insert_image('A1', plot_image_path)

# **Class CARD**

In [15]:
class CARDRegressor:
    def __init__(
        self,
        base_model,
        hidden_dim=128,
        T=50,
        lr=1e-3,
        epochs=200,
        n_samples=100,
        device="cpu"
    ):
        self.base_model = base_model
        self.hidden_dim = hidden_dim
        self.T = T
        self.epochs = epochs
        self.n_samples = n_samples
        self.device = device

        self.mlp = None  # ← FIX
        self.loss_fn = torch.nn.MSELoss()
        self.optimizer = None

    def fit(self, X, y):
        # Base predictions
        y_pred = self.base_model.predict(X)
        residuals = y - y_pred

        X_t = torch.tensor(X, dtype=torch.float32)
        r_t = torch.tensor(residuals, dtype=torch.float32)

        # Build MLP HERE (now input dim is known)
        self.mlp = torch.nn.Sequential(
            torch.nn.Linear(X.shape[1] + 1, self.hidden_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(self.hidden_dim, self.hidden_dim),
            torch.nn.ReLU(),
            torch.nn.Linear(self.hidden_dim, 1)
        ).to(self.device)

        self.optimizer = torch.optim.Adam(self.mlp.parameters(), lr=1e-3)

        for _ in range(self.epochs):
            t = torch.randint(0, self.T, (len(X_t),), dtype=torch.float32)
            noise = torch.randn_like(r_t)

            pred_noise = self.mlp(
                torch.cat([X_t, t.unsqueeze(1)], dim=1)
            ).squeeze()

            loss = self.loss_fn(pred_noise, noise)

            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()

    def predict(self, X):
        base_pred = self.base_model.predict(X)
        X_t = torch.tensor(X, dtype=torch.float32)

        samples = []
        for _ in range(self.n_samples):
            t = torch.zeros(len(X_t))
            noise = torch.randn(len(X_t))

            pred_noise = self.mlp(
                torch.cat([X_t, t.unsqueeze(1)], dim=1)
            ).detach().squeeze()

            samples.append(base_pred + (noise - pred_noise).numpy())

        samples = np.stack(samples, axis=1)
        return samples.mean(axis=1), samples.std(axis=1)

# **Tuned Parameters**

In [52]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 13.386480292958343,
  'best_params': {'n_estimators': 100,
   'criterion': 'absolute_error',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.386480292958343,
  'test_rmse': 3.6587539262648345,
  'test_corr_coef': 0.9703857201117179,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 13.031080279414615,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 13.031080279414615,
  'test_rmse': 3.6098587616989413,
  'test_corr_coef': 0.9707198566155737,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 14.299335373065158,
  'best_params': {'n_estimators': 700,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'log2',
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 14.299335373065158,
  'test_rmse': 3.7814462012654837,
  'test_corr_coef': 0.9686598451590471,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 13.002555971496559,
  'best_params': {'n_estimators': 700,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 13.002555971496559,
  'test_rmse': 3.6059057075160132,
  'test_corr_coef': 0.9707614120536777,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 13.242745794750004, 'best_params': {'n_estimators': 100,
   'criterion': 'absolute_error',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001}, 'test_mse': 13.242745794750004, 'test_rmse': 3.6390583664940035, 'test_corr_coef': 0.9705533435061875, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 13.032712146115928,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 13.032712146115928,
  'test_rmse': 3.6100847837849916,
  'test_corr_coef': 0.9707060136472022,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 13.098183337721803,
  'best_params': {'n_estimators': 300,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.098183337721803,
  'test_rmse': 3.619141243129619,
  'test_corr_coef': 0.9708556688744011,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 13.05436043571211,
  'best_params': {'n_estimators': 300,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.05436043571211,
  'test_rmse': 3.613081847358583,
  'test_corr_coef': 0.970902748067831,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 10.829304123572543,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 10.829304123572543,
  'test_rmse': 3.29079080519752,
  'test_corr_coef': 0.9755020526141754,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 11.661624240805503,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 11.661624240805503,
  'test_rmse': 3.414912039980752,
  'test_corr_coef': 0.9744114769026063,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 9.84804317748675,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 9.84804317748675,
  'test_rmse': 3.138159202062054,
  'test_corr_coef': 0.9778974508000391,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 11.728091600997796,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 100,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 11.728091600997796,
  'test_rmse': 3.4246301407594073,
  'test_corr_coef': 0.9735794434938067,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 11.402302876275247, 'best_params': {'loss': 'huber',
   'learning_rate': 0.2,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.01}, 'test_mse': 11.402302876275247, 'test_rmse': 3.37672961255047, 'test_corr_coef': 0.9771847733785521, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 11.790788566395653,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 100,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 11.790788566395653,
  'test_rmse': 3.433771769701017,
  'test_corr_coef': 0.9735327051071399,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 10.826701502045989,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 10.826701502045989,
  'test_rmse': 3.2903953412995812,
  'test_corr_coef': 0.9760380316337317,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 11.261690705814173,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.01,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 11.261690705814173,
  'test_rmse': 3.3558442612573924,
  'test_corr_coef': 0.9762402043381541,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 12.971329740251232,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 12.971329740251232,
  'test_rmse': 3.6015732312770252,
  'test_corr_coef': 0.9707032290601142,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 12.677151527294752,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 12.677151527294752,
  'test_rmse': 3.560498775072778,
  'test_corr_coef': 0.9718695625297014,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 12.423187943362256,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 12.423187943362256,
  'test_rmse': 3.5246543012559766,
  'test_corr_coef': 0.9718710858597605,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 13.444006123809128,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 13.444006123809128,
  'test_rmse': 3.6666068951837647,
  'test_corr_coef': 0.9693491795386318,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 12.534815685757243,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_depth': 5,
   'min_child_weight': 3,
   'gamma': 0.1,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 12.534815685757243,
  'test_rmse': 3.540454163770129,
  'test_corr_coef': 0.9720865242064762,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 13.01825860252241,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 13.01825860252241,
  'test_rmse': 3.608082399630365,
  'test_corr_coef': 0.9705306976359102,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 12.995629257279962,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0.5,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 12.995629257279962,
  'test_rmse': 3.6049451115488518,
  'test_corr_coef': 0.9708011364370677,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 11.911728329119882,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 11.911728329119882,
  'test_rmse': 3.4513371798652015,
  'test_corr_coef': 0.9730112774860044,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 11.465139524319431,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 11.465139524319431,
  'test_rmse': 3.3860211937197664,
  'test_corr_coef': 0.9741951359293826,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 12.765266555529877,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 12.765266555529877,
  'test_rmse': 3.5728513200985397,
  'test_corr_coef': 0.9716795934742927,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 10.593776675543129,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.593776675543129,
  'test_rmse': 3.2548082394425526,
  'test_corr_coef': 0.9759119827720704,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 10.726692183195036,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.726692183195036,
  'test_rmse': 3.2751629246794787,
  'test_corr_coef': 0.9755942859381874,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 12.012802816253567,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 31,
   'max_depth': 5,
   'min_child_samples': 10,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 12.012802816253567,
  'test_rmse': 3.465949049864058,
  'test_corr_coef': 0.9737012091768482,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 11.27855307408184,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 11.27855307408184,
  'test_rmse': 3.358355709879738,
  'test_corr_coef': 0.9750286702009904,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 10.309598332015783,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.309598332015783,
  'test_rmse': 3.2108563237889958,
  'test_corr_coef': 0.977021422519045,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 10.037746636623021,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.037746636623021,
  'test_rmse': 3.1682403060094764,
  'test_corr_coef': 0.9776264961015804,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 10.901667280503618,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.901667280503618,
  'test_rmse': 3.3017672965403873,
  'test_corr_coef': 0.9759578752410472,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 10.47862493907079,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_depth': -1,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.5,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.47862493907079,
  'test_rmse': 3.2370704254110367,
  'test_corr_coef': 0.9769317908648607,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 10.684721268563525,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': 5,
   'num_leaves': 63,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.684721268563525,
  'test_rmse': 3.2687491902199417,
  'test_corr_coef': 0.9767022352368916,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 12.272039819671177,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 12.272039819671177,
  'test_rmse': 3.503147130748461,
  'test_corr_coef': 0.9720949658383836,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 10.638909732949003,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.638909732949003,
  'test_rmse': 3.2617341603737424,
  'test_corr_coef': 0.9767142557939993,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 10.866096507361197,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 31,
   'min_child_samples': 10,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.866096507361197,
  'test_rmse': 3.296376269081125,
  'test_corr_coef': 0.9753492057788247,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 11.503699657253586,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 11.503699657253586,
  'test_rmse': 3.391710432400382,
  'test_corr_coef': 0.9739972829080268,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 10.866096507361197,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 63,
   'min_child_samples': 10,
   'subsample': 0.6,
   'colsample_bytree': 1.0,
   'reg_alpha': 1.0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10.866096507361197,
  'test_rmse': 3.296376269081125,
  'test_corr_coef': 0.9753492057788247,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 10.919798187835573,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 10,
   'l2_leaf_reg': 1,
   'border_count': 32,
   'min_data_in_leaf': 5,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 10.919798187835573,
  'test_rmse': 3.3045117926609935,
  'test_corr_coef': 0.9763196998303095,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 10.919798187835573,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 10,
   'l2_leaf_reg': 1,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 10.919798187835573,
  'test_rmse': 3.3045117926609935,
  'test_corr_coef': 0.9763196998303095,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 11.855218020554956,
  'best_params': {'iterations': 500,
   'learning_rate': 0.03,
   'depth': 8,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 11.855218020554956,
  'test_rmse': 3.443140720411374,
  'test_corr_coef': 0.9736540447216337,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 12.607187864148157,
  'best_params': {'iterations': 200,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12.607187864148157,
  'test_rmse': 3.55066020116656,
  'test_corr_coef': 0.971322712261391,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 11.821269468870975,
  'best_params': {'iterations': 500,
   'learning_rate': 0.03,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 32,
   'min_data_in_leaf': 5,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 11.821269468870975,
  'test_rmse': 3.438207304522369,
  'test_corr_coef': 0.9734884293063593,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 12.027038308322881,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 32,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12.027038308322881,
  'test_rmse': 3.4680020629063764,
  'test_corr_coef': 0.9732364988808638,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 11.652636892792769,
  'best_params': {'iterations': 200,
   'learning_rate': 0.1,
   'depth': 10,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 11.652636892792769,
  'test_rmse': 3.4135958889113938,
  'test_corr_coef': 0.9747368334479797,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 12.529309573247462,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 3,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12.529309573247462,
  'test_rmse': 3.5396764786131882,
  'test_corr_coef': 0.9721035382553069,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 11.787200156683458,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 11.787200156683458,
  'test_rmse': 3.433249212725965,
  'test_corr_coef': 0.9740301732040282,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 13.01778782749815,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.9,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 13.01778782749815,
  'test_rmse': 3.608017160089202,
  'test_corr_coef': 0.970563269407315,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 12.229892523132435,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12.229892523132435,
  'test_rmse': 3.497126323588045,
  'test_corr_coef': 0.9723061220102394,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 11.475107621268567,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 11.475107621268567,
  'test_rmse': 3.3874928223198593,
  'test_corr_coef': 0.974015347546475,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 13.357727325159095,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 13.357727325159095,
  'test_rmse': 3.6548224751907026,
  'test_corr_coef': 0.9703301488315333,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 12.074201542337628,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12.074201542337628,
  'test_rmse': 3.4747951799117063,
  'test_corr_coef': 0.9733753137108688,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 12.049261311520954,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12.049261311520954,
  'test_rmse': 3.471204590847528,
  'test_corr_coef': 0.9731028245083783,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 12.518679471941832,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12.518679471941832,
  'test_rmse': 3.5381745960229027,
  'test_corr_coef': 0.9721688812310673,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 57.150789619831066,
  'best_params': {'n_d': 8,
   'n_a': 64,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 57.150789619831066,
  'test_rmse': 7.55981412601071,
  'test_corr_coef': 0.9165437704275357,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 64.61811524711449,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 7,
   'gamma': 1.3,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 64.61811524711449,
  'test_rmse': 8.038539372741448,
  'test_corr_coef': 0.9445795088788163,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 60.884687637207904,
  'best_params': {'n_d': 32,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.5,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 60.884687637207904,
  'test_rmse': 7.802864066303341,
  'test_corr_coef': 0.9509496588137201,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 42.7407429742994,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 42.7407429742994,
  'test_rmse': 6.53764047453662,
  'test_corr_coef': 0.9597414136880744,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 41.707776667325746,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.5,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 41.707776667325746,
  'test_rmse': 6.458155825568608,
  'test_corr_coef': 0.938355662576757,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 55.317839938826495,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 55.317839938826495,
  'test_rmse': 7.437596381817616,
  'test_corr_coef': 0.9574978176787599,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 51.58994975454799,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.3,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 3,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 51.58994975454799,
  'test_rmse': 7.182614409429758,
  'test_corr_coef': 0.937347118124312,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 47.36691531108609,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 47.36691531108609,
  'test_rmse': 6.882362625660326,
  'test_corr_coef': 0.9297065611536723,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 10.545840005139208,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.1,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 10.545840005139208,
  'test_rmse': 3.2474359123990744,
  'test_corr_coef': 0.9765957955399636,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 9.984427233372632,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 100,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 9.984427233372632,
  'test_rmse': 3.159814430211469,
  'test_corr_coef': 0.97775014211043,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 10.452850001722435,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 400,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 10.452850001722435,
  'test_rmse': 3.233086760624038,
  'test_corr_coef': 0.976777912723613,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 10.382128296001117, 'best_params': {'learning_rate': 0.05,
   'max_iter': 400,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 10.382128296001117, 'test_rmse': 3.2221310178205225, 'test_corr_coef': 0.9769202112610341, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 10.550347312706231, 'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 10.550347312706231, 'test_rmse': 3.248129817711452, 'test_corr_coef': 0.9766545149805603, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting',
  'HyperbandPruner'): {'best_score': 10.487063272105305, 'best_params': {'learning_rate': 0.05,
   'max_iter': 400,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 10.487063272105305, 'test_rmse': 3.23837355351499, 'test_corr_coef': 0.9766194329102597, 'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting', 'ThresholdPruner'): {'best_score': 10.40769142601717,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 400,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 10.40769142601717,
  'test_rmse': 3.2260953838994237,
  'test_corr_coef': 0.9766945335976727,
  'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 10.318356266217195,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 400,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 10.318356266217195,
  'test_rmse': 3.2122198346653046,
  'test_corr_coef': 0.9771055983031024,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 14.496627958565755,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 51,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 14.496627958565755,
  'test_rmse': 3.807443756454684,
  'test_corr_coef': 0.9690437148790706,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 14.539617922744112,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 29,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 14.539617922744112,
  'test_rmse': 3.8130850925129,
  'test_corr_coef': 0.9689935902416109,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 14.442386821156454,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_leaves': 32,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 14.442386821156454,
  'test_rmse': 3.800314042438658,
  'test_corr_coef': 0.9704544091739867,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 15.433989897619893,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_leaves': 19,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 15.433989897619893,
  'test_rmse': 3.928611701049099,
  'test_corr_coef': 0.9668759632080998,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 15.275256998512873,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_leaves': 56,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 15.275256998512873,
  'test_rmse': 3.908357327383574,
  'test_corr_coef': 0.9672779427989531,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 15.167206941197199,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_leaves': 26,
   'min_split_gain': 0.5,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 1.0,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 15.167206941197199,
  'test_rmse': 3.8945098460778347,
  'test_corr_coef': 0.9675517690466688,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 14.629252877302713,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_leaves': 59,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 14.629252877302713,
  'test_rmse': 3.8248206333503685,
  'test_corr_coef': 0.9701936368266324,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 15.950208926775849,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_leaves': 24,
   'min_split_gain': 0.5,
   'reg_lambda': 1.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 1.0,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 15.950208926775849,
  'test_rmse': 3.993771266206397,
  'test_corr_coef': 0.965241150561115,
  'pruner': 'WilcoxonPruner'}}

# **Probabilistic Distribution using LGBM**

In [18]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

lgbm_model = LGBMRegressor(**best_params)
lgbm_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=lgbm_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)

card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_LGBM_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_LGBM_df.head())

        Mean    StdDev  Actual
0  32.636604  1.082179    34.0
1  33.764633  1.036379    36.0
2  33.732426  0.989250    36.0
3  33.474051  1.013425    35.0
4  48.481408  0.998303    44.6

In [19]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx

In [20]:
generate_and_save_crps_decomposition(
    predictions_LGBM_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx
   Sheets: CRPS_Summary_LightGBM, CRPS_Bins_LightGBM

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LightGBM    2.644881     2.679572    5.575243     5.540551        10

In [21]:
generate_and_save_pit_results(
    predictions_LGBM_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx

       PIT_Value
0   8.961405e-01
1   9.844933e-01
2   9.890534e-01
3   9.339324e-01
4   5.053589e-05
..           ...
90  1.833299e-07
91  9.988162e-01
92  9.983259e-01
93  2.110516e-05
94  5.470214e-01

[95 rows x 1 columns]

In [22]:
generate_and_save_calibration_curve(
    predictions_LGBM_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx",
    model_name="LightGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/LightGBM.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.315789        0.215789
2                  0.2            0.378947        0.178947
3                  0.3            0.410526        0.110526
4                  0.4            0.442105        0.042105
5                  0.5            0.473684        0.026316
6                  0.6            0.494737        0.105263
7                  0.7            0.547368        0.152632
8                  0.8            0.589474        0.210526
9                  0.9            0.621053        0.278947
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using XGBoost**

In [23]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

xgb_model = XGBRegressor(**best_params)
xgb_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=xgb_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)

card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_XGB_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_XGB_df.head())

        Mean    StdDev  Actual
0  32.011032  1.028041    34.0
1  35.718273  0.922281    36.0
2  34.460888  0.902895    36.0
3  35.239258  1.022026    35.0
4  47.250145  1.002706    44.6

In [24]:
generate_and_save_plots(predictions_XGB_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx

In [25]:
generate_and_save_crps_decomposition(
    predictions_XGB_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx
   Sheets: CRPS_Summary_XGBoost, CRPS_Bins_XGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  XGBoost    2.407681     2.429069    5.561939     5.540551        10

In [26]:
generate_and_save_pit_results(
    predictions_XGB_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx

    PIT_Value
0    0.973487
1    0.619995
2    0.955869
3    0.407453
4    0.004109
..        ...
90   0.000001
91   0.979302
92   0.999166
93   0.000395
94   0.337508

[95 rows x 1 columns]

In [27]:
generate_and_save_calibration_curve(
    predictions_XGB_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx",
    model_name="XGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/XGBoost.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.315789        0.215789
2                  0.2            0.347368        0.147368
3                  0.3            0.410526        0.110526
4                  0.4            0.452632        0.052632
5                  0.5            0.505263        0.005263
6                  0.6            0.536842        0.063158
7                  0.7            0.568421        0.131579
8                  0.8            0.621053        0.178947
9                  0.9            0.684211        0.215789
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using GPBoost**

In [28]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

gpboost_model = GPBoostRegressor(**best_params)
gpboost_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=gpboost_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)


card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_GPBoost_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GPBoost_df.head())

        Mean    StdDev  Actual
0  31.410004  0.909229    34.0
1  35.111584  1.004660    36.0
2  35.361724  1.044206    36.0
3  35.043232  1.042057    35.0
4  43.776097  1.045638    44.6

In [29]:
generate_and_save_plots(predictions_GPBoost_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx

In [30]:
generate_and_save_crps_decomposition(
    predictions_GPBoost_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx
   Sheets: CRPS_Summary_GPBoost, CRPS_Bins_GPBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  GPBoost    2.579929     2.606889    5.567511     5.540551        10

In [31]:
generate_and_save_pit_results(
    predictions_GPBoost_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx

       PIT_Value
0   9.978041e-01
1   8.117315e-01
2   7.294844e-01
3   4.834538e-01
4   7.846351e-01
..           ...
90  3.450645e-08
91  9.999967e-01
92  9.999946e-01
93  3.085204e-03
94  9.375298e-01

[95 rows x 1 columns]

In [32]:
generate_and_save_calibration_curve(
    predictions_GPBoost_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx",
    model_name="GPBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/GPBoost.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.315789        0.215789
2                  0.2            0.368421        0.168421
3                  0.3            0.389474        0.089474
4                  0.4            0.431579        0.031579
5                  0.5            0.484211        0.015789
6                  0.6            0.515789        0.084211
7                  0.7            0.526316        0.173684
8                  0.8            0.600000        0.200000
9                  0.9            0.663158        0.236842
10                 1.0            1.000000        0.000000

# **Probabilistic distributions using NGBoost**

In [33]:

best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

ngb_model = NGBRegressor(Dist=Normal, **best_params)

ngb_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=ngb_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=100
)

card_model.fit(X_train, y_train)

mean_pred, std_pred = card_model.predict(X_test)


predictions_NGB_df = pd.DataFrame({
    "Mean": mean_pred,
    "StdDev": std_pred,
    "Actual": y_test.ravel()
})

mse = mean_squared_error(y_test, mean_pred)
print(f"Mean Squared Error: {mse:.2f}")

print(predictions_NGB_df.head())

Mean Squared Error: 9.81
        Mean    StdDev  Actual
0  33.047414  1.003655    34.0
1  35.128112  0.953045    36.0
2  34.165208  0.943637    36.0
3  34.887223  0.874163    35.0
4  43.437747  1.091729    44.6

In [34]:
generate_and_save_plots(predictions_NGB_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx

In [35]:
generate_and_save_crps_decomposition(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx
   Sheets: CRPS_Summary_NGBoost, CRPS_Bins_NGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  NGBoost    1.853122     1.875729    5.563158     5.540551        10

In [36]:
generate_and_save_pit_results(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx

       PIT_Value
0   8.287194e-01
1   8.198635e-01
2   9.740754e-01
3   5.513258e-01
4   8.564711e-01
..           ...
90  2.798176e-08
91  8.940452e-01
92  9.768470e-01
93  6.187820e-02
94  5.672235e-01

[95 rows x 1 columns]

In [37]:
generate_and_save_calibration_curve(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx",
    model_name="NGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/NGBoost.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.252632        0.152632
2                  0.2            0.273684        0.073684
3                  0.3            0.347368        0.047368
4                  0.4            0.410526        0.010526
5                  0.5            0.431579        0.068421
6                  0.6            0.494737        0.105263
7                  0.7            0.505263        0.194737
8                  0.8            0.578947        0.221053
9                  0.9            0.694737        0.205263
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Gradient Boosting**

In [38]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

gbr_model = GradientBoostingRegressor(**best_params)
gbr_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=gbr_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)

card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_GBR_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GBR_df.head())

        Mean    StdDev  Actual
0  33.005558  0.945462    34.0
1  35.860566  1.008715    36.0
2  35.044052  0.937456    36.0
3  36.046350  0.984417    35.0
4  45.702312  1.004548    44.6

In [39]:
generate_and_save_plots(predictions_GBR_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx

In [40]:
generate_and_save_crps_decomposition(
    predictions_GBR_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx",
    model_name="Gradient Boosting",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx
   Sheets: CRPS_Summary_Gradient Boosting, CRPS_Bins_Gradient Boosting

,Model,Total_CRPS,Reliability,Resolution,Uncertainty,Num_Bins
0,Gradient Boosting,1.858634,1.870515,5.552432,5.540551,10

In [41]:
generate_and_save_pit_results(
    predictions_GBR_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx",
    model_name="GBoosting",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx

    PIT_Value
0    0.853555
1    0.554970
2    0.846071
3    0.143911
4    0.136251
..        ...
90   0.000081
91   0.524770
92   0.864291
93   0.463994
94   0.185976

[95 rows x 1 columns]

In [42]:
generate_and_save_calibration_curve(
    predictions_GBR_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx",
    model_name="GBoosting",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Gradient Boosting.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.315789        0.215789
2                  0.2            0.368421        0.168421
3                  0.3            0.431579        0.131579
4                  0.4            0.463158        0.063158
5                  0.5            0.547368        0.047368
6                  0.6            0.652632        0.052632
7                  0.7            0.673684        0.026316
8                  0.8            0.673684        0.126316
9                  0.9            0.747368        0.152632
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Catboost**

In [43]:

best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

catboost_model = CatBoostRegressor(**best_params)
catboost_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=catboost_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)

card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_CatBoost_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_CatBoost_df.head())

        Mean    StdDev  Actual
0  31.833903  0.984200    34.0
1  36.432221  0.979686    36.0
2  33.872332  1.000321    36.0
3  37.078265  0.986972    35.0
4  40.780544  1.067923    44.6

In [44]:
generate_and_save_plots(predictions_CatBoost_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx

In [45]:
generate_and_save_crps_decomposition(
    predictions_CatBoost_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx
   Sheets: CRPS_Summary_CatBoost, CRPS_Bins_CatBoost

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  CatBoost    2.356654     2.395646    5.579543     5.540551        10

In [46]:
generate_and_save_pit_results(
    predictions_CatBoost_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx

    PIT_Value
0    0.986127
1    0.329540
2    0.983289
3    0.017615
4    0.999826
..        ...
90   0.000202
91   0.997956
92   0.992045
93   0.000088
94   0.379165

[95 rows x 1 columns]

In [47]:
generate_and_save_calibration_curve(
    predictions_CatBoost_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx",
    model_name="CatBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.263158        0.163158
2                  0.2            0.336842        0.136842
3                  0.3            0.389474        0.089474
4                  0.4            0.442105        0.042105
5                  0.5            0.463158        0.036842
6                  0.6            0.515789        0.084211
7                  0.7            0.536842        0.163158
8                  0.8            0.578947        0.221053
9                  0.9            0.642105        0.257895
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using HGBM**

In [48]:


best_params = get_best_model_params(best_scores_autosampler, 'HGBR')


hgb_model = HistGradientBoostingRegressor(
    **best_params,
)
hgb_model.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=hgb_model,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)

card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_HGBR_df = pd.DataFrame({
    "Mean": mean,
    "StdDev": stddev,
    "Actual": y_test.values.ravel()
})

print(predictions_HGBR_df.head())

        Mean    StdDev  Actual
0  32.894907  0.961876    34.0
1  37.902482  1.026960    36.0
2  34.285206  1.037534    36.0
3  37.896947  0.947012    35.0
4  44.923087  1.017923    44.6

In [49]:
generate_and_save_plots(predictions_HGBR_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx

In [50]:
generate_and_save_crps_decomposition(
    predictions_HGBR_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx",
    model_name="HGBR",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx
   Sheets: CRPS_Summary_HGBR, CRPS_Bins_HGBR

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  HGBR    1.902422     1.924657    5.562787     5.540551        10

In [51]:
generate_and_save_pit_results(
    predictions_HGBR_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx",
    model_name="HGBR",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx

       PIT_Value
0   8.747000e-01
1   3.197429e-02
2   9.508102e-01
3   1.110245e-03
4   3.754708e-01
..           ...
90  2.232162e-09
91  5.599856e-01
92  9.535975e-01
93  1.503265e-02
94  1.296841e-01

[95 rows x 1 columns]

In [52]:
generate_and_save_calibration_curve(
    predictions_HGBR_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx",
    model_name="HGBR",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/HGBM.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.284211        0.184211
2                  0.2            0.336842        0.136842
3                  0.3            0.410526        0.110526
4                  0.4            0.442105        0.042105
5                  0.5            0.484211        0.015789
6                  0.6            0.547368        0.052632
7                  0.7            0.568421        0.131579
8                  0.8            0.642105        0.157895
9                  0.9            0.705263        0.194737
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using TabNet**

In [53]:
class TabNetMeanWrapper:
    def __init__(self, model):
        self.model = model

    def fit(self, X, y):
        X = np.asarray(X)
        y = np.asarray(y).reshape(-1, 1)

        self.model.fit(
            X,
            y,
            max_epochs=200,
            patience=30,
            batch_size=1024,
            virtual_batch_size=128,
            num_workers=0,
            drop_last=False
        )

    def predict(self, X):
        X = np.asarray(X)
        return self.model.predict(X).reshape(-1)

best_params = get_best_model_params(best_scores_autosampler, 'TabNet')

tabnet_base = TabNetMeanWrapper(
    TabNetRegressor(**best_params)
)

tabnet_base.fit(X_train, y_train)

card_model = CARDRegressor(
    base_model=tabnet_base,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=200
)

card_model.fit(X_train, y_train)

mean, stddev = card_model.predict(X_test)

predictions_TabNet_df = pd.DataFrame({
    "Mean": mean,
    "StdDev": stddev,
    "Actual": y_test.values
})

print(predictions_TabNet_df.head())

        Mean    StdDev  Actual
0  30.566771  0.997741    34.0
1  33.057095  1.066381    36.0
2  35.161186  1.030714    36.0
3  36.997349  1.017231    35.0
4  42.038887  1.006959    44.6

In [54]:
generate_and_save_plots(predictions_TabNet_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/TabNet.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/TabNet.xlsx

In [55]:
generate_and_save_crps_decomposition(
    predictions_TabNet_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/TabNet.xlsx",
    model_name="TabNet",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/TabNet.xlsx
   Sheets: CRPS_Summary_TabNet, CRPS_Bins_TabNet

    Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  TabNet    3.391851     3.430227    5.578928     5.540551        10

In [56]:
generate_and_save_pit_results(
    predictions_TabNet_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/TabNet.xlsx",
    model_name="TabNet",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/TabNet.xlsx

       PIT_Value
0   9.997102e-01
1   9.971074e-01
2   7.921255e-01
3   2.479319e-02
4   9.945112e-01
..           ...
90  3.262569e-07
91  7.564035e-01
92  3.284074e-01
93  2.336680e-16
94  5.596132e-02

[95 rows x 1 columns]

In [57]:
generate_and_save_calibration_curve(
    predictions_TabNet_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx",
    model_name="TabNet",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/CatBoost.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.347368        0.247368
2                  0.2            0.421053        0.221053
3                  0.3            0.431579        0.131579
4                  0.4            0.473684        0.073684
5                  0.5            0.494737        0.005263
6                  0.6            0.536842        0.063158
7                  0.7            0.536842        0.163158
8                  0.8            0.568421        0.231579
9                  0.9            0.621053        0.278947
10                 1.0            1.000000        0.000000

# **Probabilistic distributions using PGBM**

In [58]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters (safe-guard)
for key in ['Dist', 'Score']:
    best_params.pop(key, None)

# -------------------------
# Train PGBM as BASE model
# -------------------------
pgbm_model = PGBM()

def mseloss_objective(yhat, y, sample_weight=None):
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    return torch.sqrt(torch.mean((yhat - y) ** 2))

X_train_np = np.array(X_train)
y_train_np = np.array(y_train)
X_test_np = np.array(X_test)
y_test_np = np.array(y_test)

pgbm_model.train(
    (X_train_np, y_train_np),
    objective=mseloss_objective,
    metric=rmseloss_metric,
    params=best_params
)

# -------------------------
# 🔧 NUMPY-SAFE WRAPPER
# -------------------------
class PGBMWrapper:
    def __init__(self, model):
        self.model = model

    def predict(self, X):
        y_pred = self.model.predict(X)
        if torch.is_tensor(y_pred):
            y_pred = y_pred.detach().cpu().numpy()
        return y_pred

pgbm_wrapped = PGBMWrapper(pgbm_model)

# -------------------------
# CARD wrapper on top
# -------------------------
card_model = CARDRegressor(
    base_model=pgbm_wrapped,
    hidden_dim=128,
    T=50,
    epochs=200,
    n_samples=100
)

# Fit CARD (NOW SAFE)
card_model.fit(X_train_np, y_train_np)

# CARD predictions
mean_pred, std_pred = card_model.predict(X_test_np)

# Create prediction DataFrame
predictions_PGBM_df = pd.DataFrame({
    "Mean": mean_pred,
    "StdDev": std_pred,
    "Actual": y_test_np.ravel()
})

# Calculate and print MSE
mse = mean_squared_error(y_test_np, mean_pred)
print(f"Mean Squared Error: {mse:.2f}")

# Preview results
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/100, Train metric: 9.7862
Estimator 1/100, Train metric: 9.5276
Estimator 2/100, Train metric: 9.3246
Estimator 3/100, Train metric: 9.1083
Estimator 4/100, Train metric: 8.9585
Estimator 5/100, Train metric: 8.7616
Estimator 6/100, Train metric: 8.5626
Estimator 7/100, Train metric: 8.3759
Estimator 8/100, Train metric: 8.2146
Estimator 9/100, Train metric: 8.1378
Estimator 10/100, Train metric: 7.9641
Estimator 11/100, Train metric: 7.7932
Estimator 12/100, Train metric: 7.7220
Estimator 13/100, Train metric: 7.5836
Estimator 14/100, Train metric: 7.4620
Estimator 15/100, Train metric: 7.3932
Estimator 16/100, Train metric: 7.2816
Estimator 17/100, Train metric: 7.1584
Estimator 18/100, Train metric: 7.0412
Estimator 19/100, Train metric: 6.9517
Estimator 20/100, Train metric: 6.8483
Estimator 21/100, Train metric: 6.7380
Estimator 22/100, Train metric: 6.6463
Estimator 23/100, Train metric: 6.5593
Estimator 24/100, Train metric: 6.4619
Estimator 25/100, Train metric: 6.4233
Estimator 26/100, Train metric: 6.3270
Estimator 27/100, Train metric: 6.2786
Estimator 28/100, Train metric: 6.2388
Estimator 29/100, Train metric: 6.1978
Estimator 30/100, Train metric: 6.1271
Estimator 31/100, Train metric: 6.0552
Estimator 32/100, Train metric: 6.0042
Estimator 33/100, Train metric: 5.9273
Estimator 34/100, Train metric: 5.8459
Estimator 35/100, Train metric: 5.7792
Estimator 36/100, Train metric: 5.7314
Estimator 37/100, Train metric: 5.6672
Estimator 38/100, Train metric: 5.5995
Estimator 39/100, Train metric: 5.5368
Estimator 40/100, Train metric: 5.5051
Estimator 41/100, Train metric: 5.4403
Estimator 42/100, Train metric: 5.4084
Estimator 43/100, Train metric: 5.3502
Estimator 44/100, Train metric: 5.2955
Estimator 45/100, Train metric: 5.2402
Estimator 46/100, Train metric: 5.1745
Estimator 47/100, Train metric: 5.1452
Estimator 48/100, Train metric: 5.0968
Estimator 49/100, Train metric: 5.0469
Estimator 50/100, Train metric: 5.0007
Estimator 51/100, Train metric: 4.9706
Estimator 52/100, Train metric: 4.9358
Estimator 53/100, Train metric: 4.8900
Estimator 54/100, Train metric: 4.8570
Estimator 55/100, Train metric: 4.8163
Estimator 56/100, Train metric: 4.7776
Estimator 57/100, Train metric: 4.7421
Estimator 58/100, Train metric: 4.7208
Estimator 59/100, Train metric: 4.6840
Estimator 60/100, Train metric: 4.6399
Estimator 61/100, Train metric: 4.5914
Estimator 62/100, Train metric: 4.5582
Estimator 63/100, Train metric: 4.5289
Estimator 64/100, Train metric: 4.5027
Estimator 65/100, Train metric: 4.4780
Estimator 66/100, Train metric: 4.4424
Estimator 67/100, Train metric: 4.4113
Estimator 68/100, Train metric: 4.3781
Estimator 69/100, Train metric: 4.3547
Estimator 70/100, Train metric: 4.3280
Estimator 71/100, Train metric: 4.2929
Estimator 72/100, Train metric: 4.2608
Estimator 73/100, Train metric: 4.2338
Estimator 74/100, Train metric: 4.2093
Estimator 75/100, Train metric: 4.1850
Estimator 76/100, Train metric: 4.1607
Estimator 77/100, Train metric: 4.1346
Estimator 78/100, Train metric: 4.1089
Estimator 79/100, Train metric: 4.0955
Estimator 80/100, Train metric: 4.0738
Estimator 81/100, Train metric: 4.0465
Estimator 82/100, Train metric: 4.0320
Estimator 83/100, Train metric: 4.0088
Estimator 84/100, Train metric: 3.9787
Estimator 85/100, Train metric: 3.9632
Estimator 86/100, Train metric: 3.9442
Estimator 87/100, Train metric: 3.9288
Estimator 88/100, Train metric: 3.9087
Estimator 89/100, Train metric: 3.8956
Estimator 90/100, Train metric: 3.8706
Estimator 91/100, Train metric: 3.8575
Estimator 92/100, Train metric: 3.8428
Estimator 93/100, Train metric: 3.8291
Estimator 94/100, Train metric: 3.8013
Estimator 95/100, Train metric: 3.7802
Estimator 96/100, Train metric: 3.7621
Estimator 97/100, Train metric: 3.7412
Estimator 98/100, Train metric: 3.7262
Estimator 99/100, Train metric: 3.7123
Mean Squared Error: 17.68
        Mean    StdDev  Actual
0  30.349464  1.010728    34.0
1  34.474197  0.972185    36.0
2  34.352180  0.907814    36.0
3  34.405212  0.976370    35.0
4  50.142345  1.059334    44.6

In [59]:
generate_and_save_plots(predictions_PGBM_df, y_test, "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx")

Excel file saved at ./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx

In [60]:
generate_and_save_crps_decomposition(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx
   Sheets: CRPS_Summary_PGBM, CRPS_Bins_PGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  PGBM    2.779346     2.807704     5.56891     5.540551        10

In [61]:
generate_and_save_pit_results(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx

       PIT_Value
0   9.998480e-01
1   9.417292e-01
2   9.652497e-01
3   7.287982e-01
4   8.388101e-08
..           ...
90  3.487082e-12
91  9.884314e-01
92  9.981326e-01
93  1.923952e-07
94  3.815287e-01

[95 rows x 1 columns]

In [62]:
generate_and_save_calibration_curve(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx",
    model_name="PGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/PGBM.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.326316        0.226316
2                  0.2            0.378947        0.178947
3                  0.3            0.410526        0.110526
4                  0.4            0.452632        0.052632
5                  0.5            0.494737        0.005263
6                  0.6            0.536842        0.063158
7                  0.7            0.536842        0.163158
8                  0.8            0.557895        0.242105
9                  0.9            0.600000        0.300000
10                 1.0            1.000000        0.000000

# **Matrix Evaulation**

In [63]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

# Create a Pandas Excel writer using XlsxWriter as the engine.
folder_path = "/content/drive/MyDrive/noise_uncertainty_analysis"
excel_path = os.path.join(folder_path, "/content/drive/MyDrive/noise_uncertainty_analysis/probabilistic_distribution_card/Matrix Evaluation.xlsx")
with pd.ExcelWriter(_ensure_parent_dir(excel_path), engine='xlsxwriter') as writer:
    plot_metrics_and_save_to_excel(writer, predictions_NGB_df, y_test, 'NGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_PGBM_df, y_test, 'PGBM')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_df, y_test, 'LGBM')
    plot_metrics_and_save_to_excel(writer, predictions_XGB_df, y_test, 'XGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_TabNet_df, y_test, "TabNet")
    plot_metrics_and_save_to_excel(writer, predictions_HGBR_df, y_test, "HGBM")
    plot_metrics_and_save_to_excel(writer, predictions_CatBoost_df, y_test, "CatBoost")
    plot_metrics_and_save_to_excel(writer, predictions_GPBoost_df, y_test, "GPBoost")
    plot_metrics_and_save_to_excel(writer, predictions_GBR_df, y_test, "GradientBoosting")