# **Start Section:**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-Datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 90.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cufflinks 0.17.3 requires plotly>=4.1.1, which is not installed.
imbalanced-learn 0.14.1 requires scikit-learn<2,>=1.4.2, which is not installed.
libpysal 4.14.1 requires scikit-learn>=1.4.0, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
geemap 0.37.2 requires plotly, which is not installed.
esda 2.9.0 requires scikit-learn>=1.4, which is not installed.
mapclassify 2.10.0 requires scikit-learn>=1.4, which is not installed.
keras-hub 0.26.0 requires tensorflow-text; platform_system != "Windows", which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow>=2.2.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow-probability>=0.13.0, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
accelerate 1.13.0 requires torch>=2.0.0, which is not installed.
cuml-cu12 26.2.0 requires scikit-learn>=1.5, which is not installed.
sentence-transformers 5.4.1 requires scikit-learn>=0.22.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
peft 0.19.1 requires torch>=1.13.0, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
spreg 1.9.0 requires scikit-learn>=0.22, which is not installed.
umap-learn 0.5.12 requires scikit-learn>=1.6, which is not installed.
hdbscan 0.8.42 requires scikit-learn>=1.6, which is not installed.
pysal 25.7 requires scikit-learn>=1.1, which is not installed.
spopt 0.7.0 requires scikit-learn>=1.4.0, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
segregation 2.5.4 requires scikit-learn>=0.21.3, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
ydf-tf 2.20.0 requires tensorflow==2.20.0, which is not installed.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 87.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 6.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
timm 1.0.26 requires torchvision, which is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 95.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 123.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 116.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 34.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 11.6 MB/s eta 0:00:00
  Building wheel for autograd-gamma (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 66.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 18.7 MB/s eta 0:00:00
  Building wheel for pgbm (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 27.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.7/449.7 kB 29.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 39.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for shap (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 20.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.0/244.0 kB 21.9 MB/s eta 0:00:00
  Building wheel for lime (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 105.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 82.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 102.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 99.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 71.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 778.9/778.9 kB 49.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 95.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 12.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 16.1 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 426.8 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 20.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 63.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
distributed 2026.1.1 requires dask<2026.1.2,>=2026.1.1, but you have dask 2025.12.0 which is incompatible.
rapids-dask-dependency 26.2.0 requires dask==2026.1.1, but you have dask 2025.12.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 97.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 76.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 21.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 9.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for cp (setup.py) ... done

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
import ngboost
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from optuna.samplers import BaseSampler
from optuna.samplers import GridSampler
from optuna.samplers import TPESampler
from optuna.samplers import PartialFixedSampler
from optuna.samplers import CmaEsSampler
from optuna.samplers import QMCSampler
from optuna.samplers import NSGAIIISampler
from optuna.samplers import NSGAIISampler
from optuna.samplers import BruteForceSampler
from optuna.samplers import GPSampler
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from openpyxl.drawing.image import Image
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from openpyxl.utils.dataframe import dataframe_to_rows
from scipy.stats import genpareto
from pytorch_tabnet import TabNetRegressor
import torch.nn as nn
import warnings
import io
import time
import numpy as np
import pandas as pd
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from openpyxl import load_workbook
from openpyxl.drawing.image import Image
from openpyxl.utils.dataframe import dataframe_to_rows

In [2]:
# Go to find & replace button and replace (streamflow_uncertainty_analysis) with your folder name. Rename your train and test Dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (str) with actual data label name.

In [3]:
feature_names = ['pH', 'Salinity', 'Turbidity ', 'Water Temperature']

In [4]:
train_data_path = "./drive/MyDrive/streamflow_uncertainty_analysis/data/train.csv"
test_data_path = "./drive/MyDrive/streamflow_uncertainty_analysis/data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (189, 8)
First 5 rows of training data:
         C    mp     FA      CA       F       W_P    Adm    str
0  280.80  70.2  858.0  1183.0    0.00  0.450000  0.610  21.56
1  372.15   0.0  975.0   525.0   52.85  0.493081  7.000  34.00
2  360.00  75.0  975.0   525.0   40.00  0.509722  7.000  28.00
3  364.30   0.0  975.0   525.0  110.40  0.503706  7.000  42.00
4  315.00  31.5  780.0  1110.0    0.00  0.370000  5.355  25.82

Shape of test data: (95, 8)
First 5 rows of test data:
         C     mp     FA     CA      F       W_P   Adm   str
0  364.30    0.0  975.0  525.0  60.40  0.503706   7.0  34.0
1  344.30   75.0  975.0  525.0  55.40  0.532965   7.0  36.0
2  390.00    0.0  975.0  525.0  60.00  0.470513   7.0  36.0
3  352.15   75.0  975.0  525.0  47.85  0.521085   7.0  35.0
4  400.00  160.0  801.0  801.0  40.00  0.300000  10.3  44.6

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (189, 7)
Shape of y_train: (189,)
Shape of X_test: (95, 7)
Shape of y_test: (95,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[-1.56879184  0.95792014 -0.09685034  1.33138508 -0.85369002  0.16810471
  -0.08799752]
 [ 0.40300047 -0.7708921   0.73537613 -0.93459372  0.061075    0.78285857
  -0.0664621 ]
 [ 0.14074238  1.07612953  0.73537613 -0.93459372 -0.16134185  1.020321
  -0.0664621 ]
 [ 0.233558   -0.7708921   0.73537613 -0.93459372  1.05719093  0.93447436
  -0.0664621 ]
 [-0.83058388  0.00485698 -0.65166799  1.07999229 -0.85369002 -0.97347298
  -0.07200604]]

First five rows of normalized X_test:
[[ 0.233558   -0.7708921   0.73537613 -0.93459372  0.19175572  0.93447436
  -0.0664621 ]
 [-0.19814256  1.07612953  0.73537613 -0.93459372  0.1052122   1.35199213
  -0.0664621 ]
 [ 0.78829322 -0.7708921   0.73537613 -0.93459372  0.18483223  0.4608195
  -0.0664621 ]
 [-0.02870009  1.07612953  0.73537613 -0.93459372 -0.02546852  1.18246784
  -0.0664621 ]
 [ 1.0041435   3.1694207  -0.50229401  0.01587763 -0.16134185 -1.97235346
  -0.05534052]]

# **Functions:**

In [8]:
# Define the model classes
model_classes = {
    'Random Forest': RandomForestRegressor,
    'Gradient Boosting': GradientBoostingRegressor,
    'XGBoost': XGBRegressor,
    'LightGBM': LGBMRegressor,
    'GPBoost': GPBoostRegressor,
    'CatBoost': CatBoostRegressor,
    'HistGradientBoosting': HistGradientBoostingRegressor,
    'TabNet': TabNetRegressor,
    'NGBoost': NGBRegressor
}

def _ensure_excel_file(path):
    import os
    import pandas as pd
    if not os.path.exists(path):
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        pd.DataFrame().to_excel(path)
    return path

In [9]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'TabNet' : 'TabNet',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [10]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test.to_numpy()[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test.to_numpy()[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.to_numpy().ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]
    cum_weights = np.cumsum(weights)
    cum_weights = cum_weights / cum_weights[-1]
    return np.interp(q, cum_weights, values)

In [11]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_NEXCP(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    strategies_names = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # =========================================================
    # NexCP – Split
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    res = np.abs(y_train.to_numpy() - yhat_train)
    weights = decay ** np.arange(len(res) - 1, -1, -1)
    q = weighted_quantile(res, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_test
    int_pred["NexCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Full
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train.to_numpy() - yhat_train), 1 - alpha)

    y_pred["NexCP-Full"] = yhat_test
    int_pred["NexCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Jackknife+ after Bootstrap
    # =========================================================
    rng = np.random.default_rng(SEED)
    lowers_t, uppers_t, preds_t = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train.iloc[idx])

        yte = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train.iloc[idx].to_numpy() - model.predict(X_train[idx])),
            1 - alpha,
        )

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-J+aB"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers_t, axis=0), np.max(uppers_t, axis=0)]

    # =========================================================
    # NexCP – CV+
    # =========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers_t, uppers_t, preds_t = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train.iloc[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train.iloc[cal].to_numpy() - y_cal), 1 - alpha)

        yte = model.predict(X_test)

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-CV+"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers_t, axis=0), np.mean(uppers_t, axis=0)]

    # =========================================================
    # Metrics
    # =========================================================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    y_true = y_test.to_numpy()

    summary_rows = []

    print("\n===== NEXCP RESULTS =====")

    for s in strategies_names:
        cov = coverage(y_true, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_true, alpha)

        summary_rows.append([
            strategies_names[s],
            cov,
            wid,
            rmse,
            cwc_val,
        ])

        print(f"{strategies_names[s]} - Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary_rows,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    idx = np.arange(len(y_test))
    plot_buffers = {}

    for s in strategies_names:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_test, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(
            idx,
            int_pred[s][:, 0],
            int_pred[s][:, 1],
            color="gray",
            alpha=0.5,
            label="Prediction interval",
        )
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(strategies_names[s])
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("str")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # Excel Export
    # =========================================================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary sheet ----
        sheet_name = "NEXCP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name, 0)
        for r_idx, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)

            sheet_name = f"NEXCP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        results_dict = {}
        for s in strategies_names:
            results_dict[f"{s}_true"] = y_true
            results_dict[f"{s}_pred"] = y_pred[s]
            results_dict[f"{s}_lower"] = int_pred[s][:, 0]
            results_dict[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(results_dict)

        sheet_name = "NEXCP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r_idx, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))

    return summary_df

In [12]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_online_super(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    STRATEGY_NAMES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    ALL_STRATEGIES = list(STRATEGY_NAMES.keys())
    if strategies == "all":
        strategies = ALL_STRATEGIES

    # =========================================================
    # Base model
    # =========================================================
    base_model = model_class(**model_params)
    base_model.fit(X_train, y_train)

    yhat_train = base_model.predict(X_train)

    X_all = np.vstack([X_train, X_test])
    y_all = np.concatenate([y_train.to_numpy(), y_test.to_numpy()])

    n_train = len(X_train)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train
    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # =========================================================
    # Online methods (UNCHANGED LOGIC)
    # =========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_hat_all[n_train:] - q,
                                         y_hat_all[n_train:] + q]

    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(X_train[idx], y_train.iloc[idx])
            res = np.abs(y_train.iloc[idx] - m.predict(X_train[idx]))
            q = np.quantile(res, 1 - alpha)
            p = m.predict(X_test)
            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)
        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, int(t / 2)), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            grad = alpha - (r_t <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_hat_all[n_train:] - q,
                                       y_hat_all[n_train:] + q]

    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            preds.append(yhat)
            res = np.abs(y_all[:t] - m.predict(X_all[:t]))
            q = np.quantile(res, 1 - alpha)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # =========================================================
    # METRICS
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rows = []
    for s in y_pred:
        ymin, ymax = int_pred[s].T
        cov = np.mean((y_true >= ymin) & (y_true <= ymax))
        wid = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc = wid * (1 + (cov < (1 - alpha)) * (1 - cov))

        rows.append([STRATEGY_NAMES[s], cov, wid, rmse, cwc])

    summary_df = pd.DataFrame(
        rows, columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"]
    )

    print("\n===== ONLINE CP RESULTS =====")
    print(summary_df)

    # =========================================================
    # PLOTTING (SAVE ONLY)
    # =========================================================
    plot_buffers = {}
    idx = np.arange(len(y_test))

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_true, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(idx,
                        int_pred[s][:, 0],
                        int_pred[s][:, 1],
                        color="gray",
                        alpha=0.5,
                        label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(f"{STRATEGY_NAMES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("str")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # EXCEL EXPORT (APPEND SAFE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary ----
        sheet_name = "ONLINECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        values = {}
        for s in y_pred:
            values[f"{s}_true"] = y_true
            values[f"{s}_pred"] = y_pred[s]
            values[f"{s}_lower"] = int_pred[s][:, 0]
            values[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(values)

        sheet_name = "ONLINECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))

    return summary_df

In [13]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_COP(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,          # Learning rate for COP
    T_burnin=50,      # Window size for distribution estimation
    scale=0.5,        # Scale factor for the integrator
    random_state=123,
):
    """
    Conformal Optimistic Prediction (COP)
    ✔ Implements the Distribution-Informed Gradient logic from the repository.
    ✔ Matches the "Excel-safe" and plotting structure of your previous functions.
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # 1. Train Base Model & Generate Test Predictions
    # =========================================================
    # COP is an online calibration method, but we usually start with a pre-trained model
    # or an online model. Here we fit on Train and calibrate on Test stream.
    model = model_class(**model_params)
    model.fit(X_train, y_train)

    # Predict on test set
    y_pred_test = model.predict(X_test).ravel()
    y_true_test = y_test.to_numpy().ravel()

    # Calculate non-conformity scores (Absolute Residuals)
    # This assumes symmetric intervals.
    scores = np.abs(y_true_test - y_pred_test)
    T_test = len(scores)

    # =========================================================
    # 2. COP Initialization
    # =========================================================
    # Initialize quantiles based on training data residuals if possible
    y_pred_train = model.predict(X_train).ravel()
    scores_train = np.abs(y_train.to_numpy().ravel() - y_pred_train)
    init_q = np.quantile(scores_train, 1 - alpha)

    # Arrays to store history
    qs = np.zeros(T_test)          # Final adaptive quantile
    qts = np.zeros(T_test)         # Base quantile term
    integrators = np.zeros(T_test) # Optimistic integrator term
    covereds = np.zeros(T_test)    # Coverage boolean

    # Set initial values
    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # 3. Online COP Loop
    # =========================================================
    # Logic adapted from `core/methods.py` function `COP`

    for t in range(T_test - 1):
        # 1. Observe coverage at current step t
        covereds[t] = 1 if qs[t] >= scores[t] else 0

        # 2. Calculate Standard Gradient
        # If covered, we decrease q (grad is positive). If not, increase q.
        grad = alpha if covereds[t] else -(1 - alpha)

        # 3. Calculate Distribution-Informed Gradient (The "Optimistic" part)
        if t < T_burnin:
            grad_i = 0
        else:
            # Look at the window of recent scores
            window_s = scores[t - T_burnin : t]

            # Calculate ECDF at the predicted next quantile step
            # logic: np.mean(window_s <= qts[t] - lr * grad) - (1 - alpha)
            current_target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= current_target) - (1 - alpha)

        # 4. Update Terms
        integrator = -scale * grad_i

        # Update base quantile (Gradient Descent)
        qts[t + 1] = qts[t] - lr * grad

        # Update integrator state
        integrators[t + 1] = lr * integrator

        # Combine for final quantile
        qs[t + 1] = qts[t + 1] + integrators[t + 1]

        # Safety: Ensure quantile implies non-negative width
        qs[t + 1] = max(0, qs[t + 1])

    # Handle the final step coverage for metrics
    covereds[-1] = 1 if qs[-1] >= scores[-1] else 0

    # =========================================================
    # 4. Construct Prediction Intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # 5. Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== CONFORMAL OPTIMISTIC PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Avg Width: {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # 6. Summary Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true": y_true_test,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score_residual": scores,
        "adaptive_q": qs
    })

    # =========================================================
    # 7. Plotting
    # =========================================================
    idx = np.arange(len(y_true_test))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")

    ax.set_title(f"Conformal Optimistic Prediction (COP) - {model_name}")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("str")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # 8. Excel Export
    # =========================================================
    if excel_file_path:
        try:
            wb = load_workbook(_ensure_excel_file(excel_file_path))
        except FileNotFoundError:
            # Create a new workbook if it doesn't exist
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active) # Remove default sheet

        # ---- Summary ----
        sheet_name = "COP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))

    return summary_df

In [14]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_EXTREME(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):
    """
    Extreme Conformal Prediction (upper-tail, single-sided)
    ✔ Same structure as NexCP & OnlineCP
    ✔ No return values
    ✔ Excel-safe
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Train / calibration split
    # =========================================================
    X_fit, X_calib, y_fit, y_calib = train_test_split(
        X_train,
        y_train,
        test_size=calib_size,
        random_state=random_state,
        shuffle=True,
    )

    # =========================================================
    # Train model
    # =========================================================
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(X_test).ravel()
    y_pred_calib = model.predict(X_calib).ravel()

    # =========================================================
    # Nonconformity scores (upper tail only)
    # =========================================================
    scores = y_calib.to_numpy().ravel() - y_pred_calib
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few calibration exceedances for GPD fitting.")

    # =========================================================
    # Peaks-over-threshold
    # =========================================================
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # =========================================================
    # Bootstrap GPD extreme quantile
    # =========================================================
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        resampled = np.random.choice(excesses, size=n_exc, replace=True)
        xi_b, _, sigma_b = genpareto.fit(resampled, floc=0)

        q_b = (
            u
            + (sigma_b / xi_b)
            * ((n_scores / (n_scores * alpha)) ** xi_b - 1)
        )
        boot_q.append(q_b)

    q_extreme = np.quantile(boot_q, 0.95)

    # =========================================================
    # Finite prediction intervals (for plotting & width)
    # =========================================================
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # =========================================================
    # Metrics
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rmse = np.sqrt(mean_squared_error(y_true, y_pred_test))
    coverage = np.mean(y_true <= ymax)
    width = q_extreme  # meaningful one-sided width

    print(f"\n===== EXTREME CONFORMAL PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"q_extreme: {q_extreme:.3f}")
    print(f"u        : {u:.3f}")
    print(f"#Exceed. : {len(scores)}")

    # =========================================================
    # Summary table
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # =========================================================
    # Values table
    # =========================================================
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true)),
        "y_true": y_true,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (y_true <= ymax).astype(int),
        "residual": y_true - y_pred_test,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(y_true))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.scatter(idx, y_true, s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme Conformal Prediction ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("str")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe, SAME FILE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary ----
        sheet_name = "EXTREMECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))

In [15]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path



import os
try:
    from tqdm.auto import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    print("[Info] Install tqdm for progress bars: pip install tqdm")


# ═══════════════════════════════════════════════════════════
# AlphaNet Architecture  (FIXED)
# ═══════════════════════════════════════════════════════════
class AlphaNet(nn.Module):
    """
    Maps a feature vector (sum of LOO scores) → learned α̃.
    Output is clamped to (alpha_min, 1) so that the conformal
    denominator α̃·(n+1)−1 is always positive.
    """

    def __init__(self, input_dim, alpha_min=0.05):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
        self.alpha_min = alpha_min  # lower bound for valid α̃
        self._initialize_near_one()

    def _initialize_near_one(self):
        """Bias output toward α̃ ≈ 1 at init (sigmoid(5) ≈ 0.993)."""
        with torch.no_grad():
            self.fc2.weight.data.normal_(0, 0.01)
            self.fc2.bias.data.fill_(5.0)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        raw = self.sigmoid(self.fc2(x)).squeeze(-1)
        # Remap from (0,1) → (alpha_min, 1) so denominator stays positive
        return self.alpha_min + (1.0 - self.alpha_min) * raw


def _interval_size(scores, alpha, eps=1e-8):
    """
    Conformal interval width = 2 * Σscores / (α̃·(n+1) − 1).
    Denominator is clamped to be strictly positive.
    """
    n = len(scores)
    denom = alpha * (n + 1) - 1
    denom = torch.clamp(denom, min=eps)   # ← KEY FIX: prevent negative/zero
    r = scores.sum() / denom
    return 2 * r


def _fmt_time(seconds):
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}min"
    else:
        return f"{seconds/3600:.1f}hr"


# ═══════════════════════════════════════════════════════════
# Main function  (CORRECTED + PROGRESS TRACKING)
# ═══════════════════════════════════════════════════════════
def conformal_predictions_AlphaNet(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet.
    - FIXED: α̃ clamped to valid range (no negative intervals)
    - FIXED: LOO scores precomputed (massive speedup)
    - ADDED: tqdm progress bars + ETA estimates
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # --- numpy-ify if pandas ---
    y_train_np = y_train.to_numpy().ravel() if hasattr(y_train, "to_numpy") else np.asarray(y_train).ravel()
    y_test_np  = y_test.to_numpy().ravel()  if hasattr(y_test,  "to_numpy") else np.asarray(y_test).ravel()
    X_train_np = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    X_test_np  = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)

    # =================================================================
    # 1.  Split training data → fit + calibration
    # =================================================================
    n_total = len(X_train_np)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = X_train_np[fit_idx],   y_train_np[fit_idx]
    X_calib, y_calib = X_train_np[calib_idx],  y_train_np[calib_idx]
    n_calib = len(X_calib)

    # Compute alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01   # small margin above threshold
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =================================================================
    # 2.  Train base regression model
    # =================================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =================================================================
    # 3.  PRECOMPUTE all LOO scores  (KEY SPEEDUP)
    # =================================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(base_model.predict(loo_X).ravel() - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =================================================================
    # 4.  Train AlphaNet (multiple runs, keep best)
    # =================================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net   = None
    best_loss  = np.inf
    history    = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        Dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(Dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores instead of calling predict()
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =================================================================
    # 5.  Compute conformal intervals on the TEST set
    # =================================================================
    print(f"  [Step 5/9] Computing conformal intervals on test set...")

    scores_calib = np.abs(base_model.predict(X_calib).ravel() - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(X_test_np).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =================================================================
    # 6.  Metrics
    # =================================================================
    y_true_test = y_test_np
    is_covered  = ((y_true_test >= ymin) & (y_true_test <= ymax)).astype(int)
    coverage    = is_covered.mean()
    avg_width   = np.mean(ymax - ymin)
    rmse        = np.sqrt(mean_squared_error(y_true_test, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =================================================================
    # 7.  Summary & values DataFrames
    # =================================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true":       y_true_test,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =================================================================
    # 8.  Plotting (SAVE ONLY — NO SHOW)
    # =================================================================
    print(f"  [Step 8/9] Generating plots...")
    idx = np.arange(len(y_true_test))

    # --- PI plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal – {model_name}")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("str")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training curves ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =================================================================
    # 9.  Excel Export
    # =================================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(_ensure_excel_file(excel_file_path))
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_Summary")
        ws = wb.create_sheet(sn, 0)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        sn = _unique_sheet(wb, "AlphaNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_pi), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_tc), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet Conformal complete in {_fmt_time(total_time)}")
    return summary_df

# **Tuned Parameters**

In [15]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 11396.714504124559,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 11396.714504124559,
  'test_rmse': 106.75539566750038,
  'test_corr_coef': 0.8545175710230449,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11396.714504124559,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 11396.714504124559,
  'test_rmse': 106.75539566750038,
  'test_corr_coef': 0.8545175710230445,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 12070.291743991513,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'log2',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 12070.291743991513,
  'test_rmse': 109.86487948380734,
  'test_corr_coef': 0.8452553059844832,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 11716.981138270823,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 11716.981138270823,
  'test_rmse': 108.24500514236591,
  'test_corr_coef': 0.8433099870855542,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 11439.192756209346, 'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05}, 'test_mse': 11439.192756209346, 'test_rmse': 106.9541619396335, 'test_corr_coef': 0.8533935563954336, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 11504.645347044134,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11504.645347044134,
  'test_rmse': 107.2597098030949,
  'test_corr_coef': 0.8532357616223099,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 11439.192756209348,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 11439.192756209348,
  'test_rmse': 106.95416193963351,
  'test_corr_coef': 0.8533935563954336,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 11734.35251996622,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 40,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'log2',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11734.35251996622,
  'test_rmse': 108.32521645473975,
  'test_corr_coef': 0.8529602600912333,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 7894.46813379009,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 1.0,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7894.46813379009,
  'test_rmse': 88.85081954484207,
  'test_corr_coef': 0.8941590289814214,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7979.404009165202,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 7979.404009165202,
  'test_rmse': 89.3275098117327,
  'test_corr_coef': 0.9028811706719992,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 8035.925747823539,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 8035.925747823539,
  'test_rmse': 89.64332517161297,
  'test_corr_coef': 0.8908089630271125,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 9421.813509142628,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 9421.813509142628,
  'test_rmse': 97.06602654452601,
  'test_corr_coef': 0.8749406418115374,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7832.37345464286, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.01}, 'test_mse': 7832.37345464286, 'test_rmse': 88.5006974811095, 'test_corr_coef': 0.8959547030435522, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 8915.412611307433,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.01,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 8915.412611307433,
  'test_rmse': 94.4214626624023,
  'test_corr_coef': 0.8893245816512504,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7908.923722871204,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 200,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'log2',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7908.923722871204,
  'test_rmse': 88.93212986806964,
  'test_corr_coef': 0.8933287186955804,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 7826.507523618409,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 7826.507523618409,
  'test_rmse': 88.46755068169577,
  'test_corr_coef': 0.9025977077608344,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 9592.75,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9592.75,
  'test_rmse': 97.94258522215962,
  'test_corr_coef': 0.8744618085762377,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 10609.2060546875,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 10609.2060546875,
  'test_rmse': 103.00100026061641,
  'test_corr_coef': 0.8661842817660108,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 9704.4892578125,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9704.4892578125,
  'test_rmse': 98.51136613514453,
  'test_corr_coef': 0.8697166555588549,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 10378.65234375,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 10378.65234375,
  'test_rmse': 101.8756710100601,
  'test_corr_coef': 0.8599670105990299,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 9919.0126953125,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9919.0126953125,
  'test_rmse': 99.59424027177727,
  'test_corr_coef': 0.8679753126698246,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 9796.1591796875,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9796.1591796875,
  'test_rmse': 98.97554839296168,
  'test_corr_coef': 0.8695228483465185,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 9558.4912109375,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9558.4912109375,
  'test_rmse': 97.76753659030946,
  'test_corr_coef': 0.8742564436069653,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 10723.3310546875,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 10723.3310546875,
  'test_rmse': 103.55351782864501,
  'test_corr_coef': 0.8554622717330934,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 8093.7407934217545,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8093.7407934217545,
  'test_rmse': 89.96521990981712,
  'test_corr_coef': 0.8889794794195334,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 9544.473558946216,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 9544.473558946216,
  'test_rmse': 97.69582160433585,
  'test_corr_coef': 0.8763579708230304,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 10096.33246815347,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10096.33246815347,
  'test_rmse': 100.4805079015501,
  'test_corr_coef': 0.8671432153117224,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 7404.388873890984,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 63,
   'max_depth': 3,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7404.388873890984,
  'test_rmse': 86.04875870046577,
  'test_corr_coef': 0.9036610692100672,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 7826.370797911004,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 31,
   'max_depth': 5,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7826.370797911004,
  'test_rmse': 88.46677793336323,
  'test_corr_coef': 0.8968692934394386,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 7716.182725214737,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.001,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7716.182725214737,
  'test_rmse': 87.8418051113178,
  'test_corr_coef': 0.8996131442228372,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 7852.782654987631,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 10,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7852.782654987631,
  'test_rmse': 88.61592777253777,
  'test_corr_coef': 0.8942173174465775,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 8390.306495329174,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8390.306495329174,
  'test_rmse': 91.59861623042771,
  'test_corr_coef': 0.8848324592834348,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 7544.111602140408,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7544.111602140408,
  'test_rmse': 86.85684545354158,
  'test_corr_coef': 0.899140689349327,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 8298.997243869338,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8298.997243869338,
  'test_rmse': 91.09883228598125,
  'test_corr_coef': 0.8859850624403404,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 7404.2396920244355,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 1.0,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7404.2396920244355,
  'test_rmse': 86.0478918511339,
  'test_corr_coef': 0.90198786970229,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 7421.776367870293,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7421.776367870293,
  'test_rmse': 86.14973225652122,
  'test_corr_coef': 0.9027127769989374,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 7694.459345833749,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 10,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7694.459345833749,
  'test_rmse': 87.7180673854238,
  'test_corr_coef': 0.8952650394354964,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 8137.497471873475,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8137.497471873475,
  'test_rmse': 90.20807875059458,
  'test_corr_coef': 0.9025758228683337,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 8523.395691254658,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 10,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8523.395691254658,
  'test_rmse': 92.32223833537972,
  'test_corr_coef': 0.8844228113820186,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 8901.75039358178,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8901.75039358178,
  'test_rmse': 94.34908793190202,
  'test_corr_coef': 0.8769681275078564,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 12059.717630039499,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12059.717630039499,
  'test_rmse': 109.81674567223115,
  'test_corr_coef': 0.834682576760058,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 12200.843128318063,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 128,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12200.843128318063,
  'test_rmse': 110.45742676849784,
  'test_corr_coef': 0.828657462741331,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 11828.352768700503,
  'best_params': {'iterations': 200,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 1,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 11828.352768700503,
  'test_rmse': 108.75823080898522,
  'test_corr_coef': 0.8402340352771763,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 12266.04121988882,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12266.04121988882,
  'test_rmse': 110.75216124251851,
  'test_corr_coef': 0.8284396615075661,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 12200.843128318063,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12200.843128318063,
  'test_rmse': 110.45742676849784,
  'test_corr_coef': 0.828657462741331,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 12200.843128318063,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 128,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12200.843128318063,
  'test_rmse': 110.45742676849784,
  'test_corr_coef': 0.828657462741331,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 12295.893812610366,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.01,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12295.893812610366,
  'test_rmse': 110.88685139641385,
  'test_corr_coef': 0.8292402939039899,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 12469.34371865179,
  'best_params': {'iterations': 500,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 9,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12469.34371865179,
  'test_rmse': 111.66621565474398,
  'test_corr_coef': 0.8262490043890625,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 12061.97957465404,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12061.97957465404,
  'test_rmse': 109.8270439129363,
  'test_corr_coef': 0.8313969676088081,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 11887.17702290286,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 11887.17702290286,
  'test_rmse': 109.02833128550974,
  'test_corr_coef': 0.835197276506235,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 12187.317404589345,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12187.317404589345,
  'test_rmse': 110.39618383164041,
  'test_corr_coef': 0.8296624201996675,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 12090.956098491108,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12090.956098491108,
  'test_rmse': 109.9588836724487,
  'test_corr_coef': 0.8280868500336911,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 12186.9424450075,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12186.9424450075,
  'test_rmse': 110.39448557336323,
  'test_corr_coef': 0.8265686728872818,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 12328.252116504349,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12328.252116504349,
  'test_rmse': 111.03266238591394,
  'test_corr_coef': 0.8267596939517394,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 12168.541471178041,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12168.541471178041,
  'test_rmse': 110.3111121835785,
  'test_corr_coef': 0.8303252321842222,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 11952.222521790789,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 11952.222521790789,
  'test_rmse': 109.32622065081546,
  'test_corr_coef': 0.8343780376436447,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 10192.0947265625,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.3,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 10192.0947265625,
  'test_rmse': 100.95590486228382,
  'test_corr_coef': 0.8680742873891645,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 7993.10546875,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 1.3,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 7993.10546875,
  'test_rmse': 89.40416919109533,
  'test_corr_coef': 0.9007085605894374,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 9981.9013671875,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 5,
   'gamma': 1.3,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9981.9013671875,
  'test_rmse': 99.90946585377934,
  'test_corr_coef': 0.8959780812686795,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 9387.9111328125,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 5,
   'gamma': 1.5,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9387.9111328125,
  'test_rmse': 96.89123351889221,
  'test_corr_coef': 0.8799101544458534,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 10727.46875,
  'best_params': {'n_d': 32,
   'n_a': 32,
   'n_steps': 7,
   'gamma': 1.5,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 10727.46875,
  'test_rmse': 103.5734944375249,
  'test_corr_coef': 0.8761904698139649,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 7730.98291015625,
  'best_params': {'n_d': 16,
   'n_a': 64,
   'n_steps': 7,
   'gamma': 2.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 7730.98291015625,
  'test_rmse': 87.92600815547269,
  'test_corr_coef': 0.8954141726546125,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 9506.19921875,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 7,
   'gamma': 1.5,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 3,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9506.19921875,
  'test_rmse': 97.49973958298555,
  'test_corr_coef': 0.8727852275919926,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 9029.6494140625,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9029.6494140625,
  'test_rmse': 95.02446744950744,
  'test_corr_coef': 0.8804388946225445,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 8849.916118658877,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 500,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 1.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8849.916118658877,
  'test_rmse': 94.07399278577941,
  'test_corr_coef': 0.8792088280317188,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 13912.001349439612,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 13912.001349439612,
  'test_rmse': 117.94914730272369,
  'test_corr_coef': 0.8016637520482625,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 9029.10721281066,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 100,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 9029.10721281066,
  'test_rmse': 95.02161445066412,
  'test_corr_coef': 0.8773438467284207,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 8317.046438364536, 'best_params': {'learning_rate': 0.01,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 1.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 8317.046438364536, 'test_rmse': 91.1978422900703, 'test_corr_coef': 0.886267177095813, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 8062.298200739737, 'best_params': {'learning_rate': 0.01,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 8062.298200739737, 'test_rmse': 89.7903012621059, 'test_corr_coef': 0.9036784928536276, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting', 'HyperbandPruner'): {'best_score': 8062.298200739737,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8062.298200739737,
  'test_rmse': 89.7903012621059,
  'test_corr_coef': 0.9036784928536276,
  'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting', 'ThresholdPruner'): {'best_score': 8104.540855275137,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8104.540855275137,
  'test_rmse': 90.02522343918474,
  'test_corr_coef': 0.9033273747525989,
  'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 8349.441232137877,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8349.441232137877,
  'test_rmse': 91.37527691962349,
  'test_corr_coef': 0.8854457951837483,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 8845.042530599296,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_leaves': 32,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 8845.042530599296,
  'test_rmse': 94.04808626760725,
  'test_corr_coef': 0.8777931131479602,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 9175.70378659374,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_leaves': 44,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'studentt'},
  'test_mse': 9175.70378659374,
  'test_rmse': 95.78989396900771,
  'test_corr_coef': 0.8755252327260262,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 8644.407437002892,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_leaves': 33,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 10,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 8644.407437002892,
  'test_rmse': 92.97530552250362,
  'test_corr_coef': 0.8825926843420658,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 8490.129698451294,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 42,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 8490.129698451294,
  'test_rmse': 92.14189979836152,
  'test_corr_coef': 0.8829833457176368,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 7773.717983434995,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_leaves': 24,
   'min_split_gain': 0.5,
   'reg_lambda': 1.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 10,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 7773.717983434995,
  'test_rmse': 88.16869049404667,
  'test_corr_coef': 0.8954213036678549,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 7763.821071455185,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_leaves': 31,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 256,
   'distribution': 'studentt'},
  'test_mse': 7763.821071455185,
  'test_rmse': 88.11254775260551,
  'test_corr_coef': 0.8964381399574919,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 7663.838249707027,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_leaves': 36,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 5,
   'max_bin': 256,
   'distribution': 'normal'},
  'test_mse': 7663.838249707027,
  'test_rmse': 87.54335068814208,
  'test_corr_coef': 0.9023151129811368,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 7710.988354850527,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_leaves': 28,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 7710.988354850527,
  'test_rmse': 87.81223351475879,
  'test_corr_coef': 0.9001164496423207,
  'pruner': 'WilcoxonPruner'}}

# **Conformal Predictions with Lightgbm**

In [17]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

In [18]:
conformal_predictions_NEXCP(
    model_class=LGBMRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/LightGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 91.579% | Width: 13.148
NexCP Full - Coverage: 91.579% | Width: 13.335
NexCP Jackknife+ aB - Coverage: 96.842% | Width: 19.729
NexCP CV+ - Coverage: 95.789% | Width: 19.029

              Strategy  Coverage      Width      RMSE        CWC
0          NexCP Split  0.915789  13.147629  4.031488  85.878635
1           NexCP Full  0.915789  13.334689  4.031488  87.100485
2  NexCP Jackknife+ aB  0.968421  19.728529  4.181276  19.728529
3            NexCP CV+  0.957895  19.028794  4.292426  19.028794

In [19]:
conformal_predictions_online_super(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/LightGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.915789  13.334689  4.031488  14.457610
1            Online CV+  0.915789  13.670775  4.031488  14.821998
2  Online Jackknife+ aB  0.957895  18.579927  4.211608  18.579927
3                 SAOCP  0.915789  13.430675  4.031488  14.561679
4                SF-OGD  1.000000  35.617571  4.031488  35.617571
5                  FACI  0.915789  14.414820  4.031488  15.628699
6            MFCS Split  0.915789  13.334689  4.031488  14.457610
7             MFCS Full  0.915789  12.903749  3.932569  13.990381

               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.915789  13.334689  4.031488  14.457610
1            Online CV+  0.915789  13.670775  4.031488  14.821998
2  Online Jackknife+ aB  0.957895  18.579927  4.211608  18.579927
3                 SAOCP  0.915789  13.430675  4.031488  14.561679
4                SF-OGD  1.000000  35.617571  4.031488  35.617571
5                  FACI  0.915789  14.414820  4.031488  15.628699
6            MFCS Split  0.915789  13.334689  4.031488  14.457610
7             MFCS Full  0.915789  12.903749  3.932569  13.990381

In [20]:
conformal_predictions_COP(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/LightGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (LightGBM) =====
Coverage : 91.579%
Avg Width: 13.438
RMSE     : 4.031
Final q  : 6.834

  Strategy  Coverage      Width      RMSE  Alpha    LR  Scale
0      COP  0.915789  13.438289  4.031488   0.05  0.05    0.5

In [21]:
conformal_predictions_EXTREME(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/LightGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (LightGBM) =====
Coverage : 98.947%
Width    : 19.113
RMSE     : 5.565
q_extreme: 19.113
u        : 17.445
#Exceed. : 31

In [22]:
conformal_predictions_AlphaNet(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/LightGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base LightGBM model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 26.8498 | Size: 13.6918 | α̃: 0.6579 | ⏱ 0.71s/epoch | ETA: 33.4min
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 27.6300 | Size: 7.8059 | α̃: 0.9912 | ⏱ 0.03s/epoch | ETA: 3.0min
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 25.2840 | Size: 10.5334 | α̃: 0.7375 | ⏱ 0.03s/epoch | ETA: 1.5min
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 24.9721 | Size: 12.2590 | α̃: 0.6357 | ⏱ 0.03s/epoch | ETA: 1.0min
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 24.9648 | Size: 12.2029 | α̃: 0.6381 | ⏱ 0.03s/epoch | ETA: 44s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 24.9653 | Size: 12.1937 | α̃: 0.6386 | ⏱ 0.03s/epoch | ETA: 35s
  ✓ Run 1 complete | Final loss: 24.9653

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 27.6426 | Size: 7.7981 | α̃: 0.9922 | ⏱ 0.04s/epoch | ETA: 34s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 24.9686 | Size: 12.1900 | α̃: 0.6389 | ⏱ 0.04s/epoch | ETA: 28s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 24.9650 | Size: 12.3902 | α̃: 0.6287 | ⏱ 0.04s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 24.9633 | Size: 12.3476 | α̃: 0.6308 | ⏱ 0.03s/epoch | ETA: 19s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 24.9697 | Size: 12.3447 | α̃: 0.6312 | ⏱ 0.03s/epoch | ETA: 16s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 24.9716 | Size: 12.3303 | α̃: 0.6321 | ⏱ 0.03s/epoch | ETA: 13s
  ✓ Run 2 complete | Final loss: 24.9716

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 27.7362 | Size: 7.7369 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 13s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 24.9901 | Size: 12.0988 | α̃: 0.6446 | ⏱ 0.03s/epoch | ETA: 11s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 24.9638 | Size: 12.2930 | α̃: 0.6335 | ⏱ 0.03s/epoch | ETA: 9s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 24.9650 | Size: 12.3447 | α̃: 0.6310 | ⏱ 0.03s/epoch | ETA: 8s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 24.9632 | Size: 12.4317 | α̃: 0.6266 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 24.9651 | Size: 12.4800 | α̃: 0.6243 | ⏱ 0.04s/epoch | ETA: 5s
  ✓ Run 3 complete | Final loss: 24.9651

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 27.5733 | Size: 7.8481 | α̃: 0.9863 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 25.1679 | Size: 10.8946 | α̃: 0.7137 | ⏱ 0.03s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 24.9669 | Size: 12.2521 | α̃: 0.6357 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 24.9632 | Size: 12.3502 | α̃: 0.6307 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 24.9625 | Size: 12.3597 | α̃: 0.6301 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 24.9629 | Size: 12.4197 | α̃: 0.6272 | ⏱ 0.04s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 24.9629
  [Step 4/9] Training done in 17s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (LightGBM)
=======================================================
  Learned α̃     : 0.6219
  Half-width (r) : 6.2602
  Coverage       : 84.211%
  Avg Width      : 12.5205
  RMSE           : 4.7813
  Total time     : 18s
    ├─ Precompute: 1s
    └─ Training  : 17s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 18s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.842105,12.520474,4.781313,0.05,0.6219,20.0,18.02

# **Conformal Predictions with XGBoost**

In [23]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

In [24]:
conformal_predictions_NEXCP(
    model_class=XGBRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/XGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 87.368% | Width: 11.443
NexCP Full - Coverage: 88.421% | Width: 11.690
NexCP Jackknife+ aB - Coverage: 95.789% | Width: 17.090
NexCP CV+ - Coverage: 94.737% | Width: 18.177

              Strategy  Coverage      Width      RMSE         CWC
0          NexCP Split  0.873684  11.443431  3.785789  531.119316
1           NexCP Full  0.884211  11.690234  3.785789  325.324482
2  NexCP Jackknife+ aB  0.957895  17.090214  3.967964   17.090214
3            NexCP CV+  0.947368  18.176989  3.967231   38.910170

In [25]:
conformal_predictions_online_super(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/XGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.884211  11.690237  3.785789  13.043844
1            Online CV+  0.884211  12.163334  3.785789  13.571721
2  Online Jackknife+ aB  0.947368  16.806837  4.016101  17.691407
3                 SAOCP  0.873684  12.183532  3.785789  13.722505
4                SF-OGD  1.000000  33.973119  3.785789  33.973119
5                  FACI  0.905263  13.096592  3.785789  14.337322
6            MFCS Split  0.884211  11.690237  3.785789  13.043844
7             MFCS Full  0.894737  10.775698  3.545639  11.909982

               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.884211  11.690237  3.785789  13.043844
1            Online CV+  0.884211  12.163334  3.785789  13.571721
2  Online Jackknife+ aB  0.947368  16.806837  4.016101  17.691407
3                 SAOCP  0.873684  12.183532  3.785789  13.722505
4                SF-OGD  1.000000  33.973119  3.785789  33.973119
5                  FACI  0.905263  13.096592  3.785789  14.337322
6            MFCS Split  0.884211  11.690237  3.785789  13.043844
7             MFCS Full  0.894737  10.775698  3.545639  11.909982

In [26]:
conformal_predictions_COP(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/XGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (XGBoost) =====
Coverage : 88.421%
Avg Width: 11.924
RMSE     : 3.786
Final q  : 6.163

  Strategy  Coverage      Width      RMSE  Alpha    LR  Scale
0      COP  0.884211  11.923806  3.785789   0.05  0.05    0.5

In [27]:
conformal_predictions_EXTREME(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/XGBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (XGBoost) =====
Coverage : 100.000%
Width    : 21.706
RMSE     : 5.386
q_extreme: 21.706
u        : 17.689
#Exceed. : 31

In [28]:
conformal_predictions_AlphaNet(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/XGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base XGBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 24.2185 | Size: 11.4618 | α̃: 0.6378 | ⏱ 0.07s/epoch | ETA: 19s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 23.1675 | Size: 11.9515 | α̃: 0.5608 | ⏱ 0.05s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 23.1311 | Size: 11.5147 | α̃: 0.5808 | ⏱ 0.04s/epoch | ETA: 9s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 23.1300 | Size: 11.3761 | α̃: 0.5877 | ⏱ 0.04s/epoch | ETA: 8s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 23.1296 | Size: 11.4106 | α̃: 0.5860 | ⏱ 0.05s/epoch | ETA: 8s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 23.1310 | Size: 11.4046 | α̃: 0.5863 | ⏱ 0.06s/epoch | ETA: 7s
  ✓ Run 1 complete | Final loss: 23.1310

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 26.5369 | Size: 6.6801 | α̃: 0.9928 | ⏱ 0.05s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 26.6202 | Size: 6.6379 | α̃: 0.9991 | ⏱ 0.03s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 26.6230 | Size: 6.6362 | α̃: 0.9993 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 26.6199 | Size: 6.6374 | α̃: 0.9991 | ⏱ 0.03s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 26.6123 | Size: 6.6413 | α̃: 0.9985 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 26.5828 | Size: 6.6567 | α̃: 0.9963 | ⏱ 0.03s/epoch | ETA: 4s
  ✓ Run 2 complete | Final loss: 26.5828

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 26.6308 | Size: 6.6322 | α̃: 0.9999 | ⏱ 0.05s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 23.5479 | Size: 9.5245 | α̃: 0.7012 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 23.1503 | Size: 11.8945 | α̃: 0.5628 | ⏱ 0.04s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 23.1310 | Size: 11.3772 | α̃: 0.5877 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 23.1310 | Size: 11.5161 | α̃: 0.5807 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 23.1299 | Size: 11.5042 | α̃: 0.5813 | ⏱ 0.05s/epoch | ETA: 2s
  ✓ Run 3 complete | Final loss: 23.1299

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 26.4777 | Size: 6.7132 | α̃: 0.9882 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 23.9435 | Size: 8.7835 | α̃: 0.7580 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 23.1542 | Size: 11.0027 | α̃: 0.6076 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 23.1301 | Size: 11.4510 | α̃: 0.5840 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 23.1301 | Size: 11.3524 | α̃: 0.5889 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 23.1298 | Size: 11.4771 | α̃: 0.5826 | ⏱ 0.04s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 23.1298
  [Step 4/9] Training done in 8s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (XGBoost)
=======================================================
  Learned α̃     : 0.5725
  Half-width (r) : 5.8378
  Coverage       : 86.316%
  Avg Width      : 11.6757
  RMSE           : 4.0609
  Total time     : 8s
    ├─ Precompute: 1s
    └─ Training  : 8s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 8s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.863158,11.67568,4.060938,0.05,0.572501,20.0,8.47

# **Conformal Predictions with GPBoost**

In [29]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

In [30]:
conformal_predictions_NEXCP(
    model_class=GPBoostRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/GPBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 87.368% | Width: 13.423
NexCP Full - Coverage: 88.421% | Width: 13.564
NexCP Jackknife+ aB - Coverage: 98.947% | Width: 19.211
NexCP CV+ - Coverage: 100.000% | Width: 19.989

              Strategy  Coverage      Width      RMSE         CWC
0          NexCP Split  0.873684  13.423326  3.955671  623.011385
1           NexCP Full  0.884211  13.563731  3.955671  377.461534
2  NexCP Jackknife+ aB  0.989474  19.211316  4.009396   19.211316
3            NexCP CV+  1.000000  19.989262  3.974207   19.989262

In [31]:
conformal_predictions_online_super(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/GPBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.884211  13.563731  3.955671  15.134268
1            Online CV+  0.894737  13.990874  3.955671  15.463598
2  Online Jackknife+ aB  0.989474  19.104058  4.043654  19.104058
3                 SAOCP  0.894737  14.115838  3.955671  15.601715
4                SF-OGD  1.000000  35.846613  3.955671  35.846613
5                  FACI  0.894737  14.255992  3.955671  15.756623
6            MFCS Split  0.884211  13.563731  3.955671  15.134268
7             MFCS Full  0.873684  13.018744  4.006835  14.663217

               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.884211  13.563731  3.955671  15.134268
1            Online CV+  0.894737  13.990874  3.955671  15.463598
2  Online Jackknife+ aB  0.989474  19.104058  4.043654  19.104058
3                 SAOCP  0.894737  14.115838  3.955671  15.601715
4                SF-OGD  1.000000  35.846613  3.955671  35.846613
5                  FACI  0.894737  14.255992  3.955671  15.756623
6            MFCS Split  0.884211  13.563731  3.955671  15.134268
7             MFCS Full  0.873684  13.018744  4.006835  14.663217

In [32]:
conformal_predictions_COP(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/GPBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GPBoost) =====
Coverage : 89.474%
Avg Width: 13.815
RMSE     : 3.956
Final q  : 7.049

  Strategy  Coverage      Width      RMSE  Alpha    LR  Scale
0      COP  0.894737  13.815226  3.955671   0.05  0.05    0.5

In [33]:
conformal_predictions_EXTREME(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/GPBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (GPBoost) =====
Coverage : 100.000%
Width    : 18.409
RMSE     : 4.591
q_extreme: 18.409
u        : 13.765
#Exceed. : 33

In [34]:
conformal_predictions_AlphaNet(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/GPBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base GPBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 25.3079 | Size: 11.4070 | α̃: 0.6950 | ⏱ 0.04s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 24.1829 | Size: 12.5368 | α̃: 0.5823 | ⏱ 0.03s/epoch | ETA: 7s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 24.1494 | Size: 11.8816 | α̃: 0.6134 | ⏱ 0.04s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 24.1481 | Size: 11.8821 | α̃: 0.6133 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 24.1479 | Size: 11.9045 | α̃: 0.6122 | ⏱ 0.03s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 24.1483 | Size: 11.9644 | α̃: 0.6092 | ⏱ 0.03s/epoch | ETA: 5s
  ✓ Run 1 complete | Final loss: 24.1483

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 27.1391 | Size: 7.2889 | α̃: 0.9925 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 24.2861 | Size: 12.1797 | α̃: 0.6053 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 24.1587 | Size: 12.2051 | α̃: 0.5977 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 24.1489 | Size: 11.9893 | α̃: 0.6080 | ⏱ 0.05s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 24.1474 | Size: 11.9981 | α̃: 0.6075 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 24.1489 | Size: 11.8594 | α̃: 0.6145 | ⏱ 0.04s/epoch | ETA: 4s
  ✓ Run 2 complete | Final loss: 24.1489

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 27.2329 | Size: 7.2338 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 24.2210 | Size: 11.4206 | α̃: 0.6400 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 24.1558 | Size: 12.2491 | α̃: 0.5953 | ⏱ 0.05s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 24.1489 | Size: 12.0657 | α̃: 0.6042 | ⏱ 0.05s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 24.1485 | Size: 11.9727 | α̃: 0.6088 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 24.1493 | Size: 11.8240 | α̃: 0.6163 | ⏱ 0.04s/epoch | ETA: 2s
  ✓ Run 3 complete | Final loss: 24.1493

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 27.0744 | Size: 7.3303 | α̃: 0.9872 | ⏱ 0.05s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 24.1657 | Size: 11.5162 | α̃: 0.6325 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 24.1501 | Size: 12.0575 | α̃: 0.6046 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 24.1501 | Size: 11.8584 | α̃: 0.6146 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 24.1512 | Size: 12.0276 | α̃: 0.6062 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 24.1516 | Size: 11.9517 | α̃: 0.6100 | ⏱ 0.03s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 24.1516
  [Step 4/9] Training done in 8s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GPBoost)
=======================================================
  Learned α̃     : 0.5911
  Half-width (r) : 6.1632
  Coverage       : 84.211%
  Avg Width      : 12.3264
  RMSE           : 4.2884
  Total time     : 8s
    ├─ Precompute: 0s
    └─ Training  : 8s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 8s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.842105,12.326429,4.288365,0.05,0.591135,20.0,8.34

# **Conformal Predictions with NGBoost**

In [35]:
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

In [36]:
conformal_predictions_NEXCP(
    model_class=NGBRegressor,
    best_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/NGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 71.579% | Width: 5.796
NexCP Full - Coverage: 68.421% | Width: 5.408
NexCP Jackknife+ aB - Coverage: 97.895% | Width: 12.410
NexCP CV+ - Coverage: 96.842% | Width: 15.718

              Strategy  Coverage      Width      RMSE           CWC
0          NexCP Split  0.715789   5.796028  3.292574  7.062379e+05
1           NexCP Full  0.684211   5.407987  3.056596  3.195814e+06
2  NexCP Jackknife+ aB  0.978947  12.410107  3.172144  1.241011e+01
3            NexCP CV+  0.968421  15.718282  3.092510  1.571828e+01

In [37]:
conformal_predictions_online_super(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/NGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.705263   5.579477  3.292574   7.223954
1            Online CV+  0.757895   6.727027  3.292574   8.355675
2  Online Jackknife+ aB  0.915789  11.287780  3.234836  12.238330
3                 SAOCP  0.821053   7.795958  3.292574   9.191025
4                SF-OGD  0.989474  27.154173  3.292574  27.154173
5                  FACI  0.915789  10.967914  3.292574  11.891528
6            MFCS Split  0.705263   5.579477  3.292574   7.223954
7             MFCS Full  0.757895   5.752471  2.918876   7.145174

               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.705263   5.579477  3.292574   7.223954
1            Online CV+  0.757895   6.727027  3.292574   8.355675
2  Online Jackknife+ aB  0.915789  11.287780  3.234836  12.238330
3                 SAOCP  0.821053   7.795958  3.292574   9.191025
4                SF-OGD  0.989474  27.154173  3.292574  27.154173
5                  FACI  0.915789  10.967914  3.292574  11.891528
6            MFCS Split  0.705263   5.579477  3.292574   7.223954
7             MFCS Full  0.757895   5.752471  2.918876   7.145174

In [38]:
conformal_predictions_COP(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/NGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (NGBoost) =====
Coverage : 75.789%
Avg Width: 6.356
RMSE     : 3.293
Final q  : 3.711

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.757895  6.355572  3.292574   0.05  0.05    0.5

In [39]:
conformal_predictions_EXTREME(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/NGBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (NGBoost) =====
Coverage : 100.000%
Width    : 19.829
RMSE     : 4.383
q_extreme: 19.829
u        : 14.845
#Exceed. : 30

In [40]:
conformal_predictions_AlphaNet(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/NGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base NGBoost model...
  [Step 2/9] Done in 2s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 8s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 25.3723 | Size: 12.9068 | α̃: 0.6233 | ⏱ 0.08s/epoch | ETA: 20s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 22.3399 | Size: 8.8120 | α̃: 0.6764 | ⏱ 0.05s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 21.8798 | Size: 10.3769 | α̃: 0.5751 | ⏱ 0.04s/epoch | ETA: 9s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 21.8561 | Size: 10.7463 | α̃: 0.5555 | ⏱ 0.05s/epoch | ETA: 8s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 21.8557 | Size: 10.8056 | α̃: 0.5525 | ⏱ 0.06s/epoch | ETA: 8s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 21.8559 | Size: 10.8414 | α̃: 0.5507 | ⏱ 0.05s/epoch | ETA: 7s
  ✓ Run 1 complete | Final loss: 21.8559

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 25.8165 | Size: 5.9533 | α̃: 0.9932 | ⏱ 0.06s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 21.8768 | Size: 10.8119 | α̃: 0.5532 | ⏱ 0.04s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 21.8575 | Size: 10.6734 | α̃: 0.5592 | ⏱ 0.05s/epoch | ETA: 6s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 21.8563 | Size: 10.8282 | α̃: 0.5514 | ⏱ 0.07s/epoch | ETA: 6s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 21.8587 | Size: 10.8545 | α̃: 0.5502 | ⏱ 0.03s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 21.8567 | Size: 10.7750 | α̃: 0.5541 | ⏱ 0.03s/epoch | ETA: 5s
  ✓ Run 2 complete | Final loss: 21.8567

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 25.9104 | Size: 5.9126 | α̃: 0.9999 | ⏱ 0.05s/epoch | ETA: 5s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 21.9051 | Size: 10.4355 | α̃: 0.5735 | ⏱ 0.03s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 21.8610 | Size: 11.0121 | α̃: 0.5424 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 21.8570 | Size: 10.9139 | α̃: 0.5472 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 21.8561 | Size: 10.8135 | α̃: 0.5521 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 21.8565 | Size: 10.7157 | α̃: 0.5570 | ⏱ 0.04s/epoch | ETA: 2s
  ✓ Run 3 complete | Final loss: 21.8565

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 25.7638 | Size: 5.9779 | α̃: 0.9893 | ⏱ 0.05s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 22.1210 | Size: 12.4313 | α̃: 0.4845 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 21.8652 | Size: 11.0182 | α̃: 0.5424 | ⏱ 0.04s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 21.8573 | Size: 10.8119 | α̃: 0.5523 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 21.8562 | Size: 10.7280 | α̃: 0.5564 | ⏱ 0.05s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 21.8566 | Size: 10.8959 | α̃: 0.5480 | ⏱ 0.04s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 21.8566
  [Step 4/9] Training done in 9s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (NGBoost)
=======================================================
  Learned α̃     : 0.5411
  Half-width (r) : 5.5120
  Coverage       : 87.368%
  Avg Width      : 11.0240
  RMSE           : 3.3250
  Total time     : 18s
    ├─ Precompute: 8s
    └─ Training  : 9s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 18s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.873684,11.02403,3.325023,0.05,0.541121,20.0,17.92

# **Conformal Predictions with Gradient Boosting**

In [41]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

In [42]:
conformal_predictions_NEXCP(
    model_class=GradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 81.053% | Width: 7.347
NexCP Full - Coverage: 81.053% | Width: 7.376
NexCP Jackknife+ aB - Coverage: 97.895% | Width: 16.983
NexCP CV+ - Coverage: 96.842% | Width: 18.487

              Strategy  Coverage      Width      RMSE          CWC
0          NexCP Split  0.810526   7.347284  3.103573  7855.354413
1           NexCP Full  0.810526   7.375707  3.103573  7885.742903
2  NexCP Jackknife+ aB  0.978947  16.983307  3.390188    16.983307
3            NexCP CV+  0.968421  18.486912  3.596523    18.486912

In [43]:
conformal_predictions_online_super(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.810526   7.375707  3.103573   8.773209
1            Online CV+  0.842105   8.413961  3.103573   9.742481
2  Online Jackknife+ aB  0.968421  15.919838  3.464471  15.919838
3                 SAOCP  0.863158   9.638176  3.103573  10.957084
4                SF-OGD  1.000000  29.658589  3.103573  29.658589
5                  FACI  0.905263  11.749279  3.103573  12.862368
6            MFCS Split  0.810526   7.375707  3.103573   8.773209
7             MFCS Full  0.842105   7.314144  3.424970   8.469008

               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.810526   7.375707  3.103573   8.773209
1            Online CV+  0.842105   8.413961  3.103573   9.742481
2  Online Jackknife+ aB  0.968421  15.919838  3.464471  15.919838
3                 SAOCP  0.863158   9.638176  3.103573  10.957084
4                SF-OGD  1.000000  29.658589  3.103573  29.658589
5                  FACI  0.905263  11.749279  3.103573  12.862368
6            MFCS Split  0.810526   7.375707  3.103573   8.773209
7             MFCS Full  0.842105   7.314144  3.424970   8.469008

In [44]:
conformal_predictions_COP(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GradientBoosting) =====
Coverage : 83.158%
Avg Width: 7.932
RMSE     : 3.104
Final q  : 4.256

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.831579  7.931907  3.103573   0.05  0.05    0.5

In [45]:
conformal_predictions_EXTREME(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/Gradient Boosting.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (GradientBoosting) =====
Coverage : 100.000%
Width    : 17.396
RMSE     : 4.275
q_extreme: 17.396
u        : 15.599
#Exceed. : 32

In [46]:
conformal_predictions_AlphaNet(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/Gradient Boosting.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base GradientBoosting model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 28.3022 | Size: 16.8286 | α̃: 0.5737 | ⏱ 0.04s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 26.3813 | Size: 6.3947 | α̃: 0.9993 | ⏱ 0.03s/epoch | ETA: 7s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 26.3834 | Size: 6.3937 | α̃: 0.9995 | ⏱ 0.03s/epoch | ETA: 7s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 26.3823 | Size: 6.3943 | α̃: 0.9994 | ⏱ 0.04s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 26.3800 | Size: 6.3952 | α̃: 0.9992 | ⏱ 0.04s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 26.3760 | Size: 6.3971 | α̃: 0.9989 | ⏱ 0.03s/epoch | ETA: 5s
  ✓ Run 1 complete | Final loss: 26.3760

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 26.2954 | Size: 6.4364 | α̃: 0.9930 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 23.5434 | Size: 14.3468 | α̃: 0.4598 | ⏱ 0.03s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 22.7680 | Size: 12.0324 | α̃: 0.5368 | ⏱ 0.03s/epoch | ETA: 4s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 22.7138 | Size: 11.1120 | α̃: 0.5801 | ⏱ 0.03s/epoch | ETA: 4s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 22.7136 | Size: 11.1916 | α̃: 0.5761 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 22.7134 | Size: 11.2619 | α̃: 0.5726 | ⏱ 0.03s/epoch | ETA: 3s
  ✓ Run 2 complete | Final loss: 22.7134

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 26.3893 | Size: 6.3909 | α̃: 0.9999 | ⏱ 0.05s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 22.9829 | Size: 9.7367 | α̃: 0.6623 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 22.7282 | Size: 10.8632 | α̃: 0.5932 | ⏱ 0.04s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 22.7139 | Size: 11.3405 | α̃: 0.5687 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 22.7132 | Size: 11.2639 | α̃: 0.5725 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 22.7130 | Size: 11.2945 | α̃: 0.5709 | ⏱ 0.03s/epoch | ETA: 2s
  ✓ Run 3 complete | Final loss: 22.7130

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 26.2385 | Size: 6.4661 | α̃: 0.9886 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 26.3462 | Size: 6.4114 | α̃: 0.9967 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 26.2961 | Size: 6.4360 | α̃: 0.9930 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 23.6651 | Size: 8.4238 | α̃: 0.7621 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 22.7262 | Size: 11.1127 | α̃: 0.5807 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 22.7161 | Size: 11.3535 | α̃: 0.5681 | ⏱ 0.03s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 22.7161
  [Step 4/9] Training done in 7s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GradientBoosting)
=======================================================
  Learned α̃     : 0.5643
  Half-width (r) : 5.7083
  Coverage       : 88.421%
  Avg Width      : 11.4165
  RMSE           : 3.8270
  Total time     : 7s
    ├─ Precompute: 0s
    └─ Training  : 7s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 7s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.884211,11.416507,3.827018,0.05,0.564347,20.0,7.49

# **Conformal Predictions with CatBoost**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

In [ ]:
conformal_predictions_NEXCP(
    model_class=CatBoostRegressor,
    best_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/CatBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 90.137% | Width: 403.201
NexCP Full - Coverage: 97.808% | Width: 2322.019
NexCP Jackknife+ aB - Coverage: 99.452% | Width: 2805.545
NexCP CV+ - Coverage: 98.630% | Width: 3435.510

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.901370   403.201161  318.650026  4990.022051
1           NexCP Full  0.978082  2322.018806  318.650026  2322.018806
2  NexCP Jackknife+ aB  0.994521  2805.545278  326.105875  2805.545278
3            NexCP CV+  0.986301  3435.510450  345.271559  3435.510450

In [ ]:
conformal_predictions_online_super(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/CatBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.978082  2322.018806  318.650026  2322.018806
1            Online CV+  0.975342  1918.016560  318.650026  1918.016560
2  Online Jackknife+ aB  0.994521  2801.143014  309.497407  2801.143014
3                 SAOCP  0.917808   533.741293  318.650026   577.610440
4                SF-OGD  0.978082  2367.520140  318.650026  2367.520140
5                  FACI  0.912329   730.803575  318.650026   794.874025
6            MFCS Split  0.978082  2322.018806  318.650026  2322.018806
7             MFCS Full  0.972603  1915.581218  335.922892  1915.581218

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.978082  2322.018806  318.650026  2322.018806
1            Online CV+  0.975342  1918.016560  318.650026  1918.016560
2  Online Jackknife+ aB  0.994521  2801.143014  309.497407  2801.143014
3                 SAOCP  0.917808   533.741293  318.650026   577.610440
4                SF-OGD  0.978082  2367.520140  318.650026  2367.520140
5                  FACI  0.912329   730.803575  318.650026   794.874025
6            MFCS Split  0.978082  2322.018806  318.650026  2322.018806
7             MFCS Full  0.972603  1915.581218  335.922892  1915.581218

In [ ]:
conformal_predictions_COP(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/CatBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (CatBoost) =====
Coverage : 97.808%
Avg Width: 2321.356
RMSE     : 318.650
Final q  : 1160.498

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.978082  2321.355696  318.650026   0.05  0.05    0.5

In [ ]:
conformal_predictions_EXTREME(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/CatBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (CatBoost) =====
Coverage : 100.000%
Width    : 384387.410
RMSE     : 354.928
q_extreme: 384387.410
u        : 1653.807
#Exceed. : 88

In [ ]:
conformal_predictions_AlphaNet(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/CatBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base CatBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 2s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 63097.2984 | Size: 63097.0610 | α̃: 0.0118 | ⏱ 0.26s/epoch | ETA: 54s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 63094.6621 | Size: 63094.4236 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 46s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 63053.7708 | Size: 63053.5323 | α̃: 0.0118 | ⏱ 0.22s/epoch | ETA: 39s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 63098.4247 | Size: 63098.1860 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 63098.4210 | Size: 63098.1825 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 32s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 63070.2834 | Size: 63070.0449 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 29s
  ✓ Run 1 complete | Final loss: 63070.2834

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 651.9024 | Size: 631.9024 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 29s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 651.9140 | Size: 631.9140 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 651.9160 | Size: 631.9160 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 26s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 651.9239 | Size: 631.9239 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 24s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 651.9213 | Size: 631.9213 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 22s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 651.9216 | Size: 631.9216 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 651.9216

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 651.8864 | Size: 631.8864 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 651.9213 | Size: 631.9213 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 17s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 651.9063 | Size: 631.9063 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 15s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 651.9245 | Size: 631.9245 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 13s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 651.6051 | Size: 631.6051 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 651.8628 | Size: 631.8628 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 651.8628

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 651.8728 | Size: 631.8728 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 651.8244 | Size: 631.8244 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 651.9225 | Size: 631.9225 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 651.8949 | Size: 631.8949 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 651.9256 | Size: 631.9256 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 651.8487 | Size: 631.8487 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 651.8487
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (CatBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 315.9351
  Coverage       : 90.959%
  Avg Width      : 631.8703
  RMSE           : 417.9207
  Total time     : 41s
    ├─ Precompute: 2s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 41s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.909589,631.8703,417.920733,0.05,1.0,20.0,41.05

# **Conformal Predictions with HistGradientBoosting**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'HGBR')

In [ ]:
conformal_predictions_NEXCP(
    model_class=HistGradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/HGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 90.685% | Width: 368.674
NexCP Full - Coverage: 96.986% | Width: 1908.645
NexCP Jackknife+ aB - Coverage: 99.726% | Width: 4074.878
NexCP CV+ - Coverage: 98.904% | Width: 3957.616

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.906849   368.673813  311.769342  3557.622337
1           NexCP Full  0.969863  1908.645042  311.769342  1908.645042
2  NexCP Jackknife+ aB  0.997260  4074.878183  349.770090  4074.878183
3            NexCP CV+  0.989041  3957.616328  371.836137  3957.616328

In [ ]:
conformal_predictions_online_super(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/HGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.969863  1908.645042  311.769342  1908.645042
1            Online CV+  0.969863  1762.715954  311.769342  1762.715954
2  Online Jackknife+ aB  0.997260  3707.518105  331.040137  3707.518105
3                 SAOCP  0.923288   597.594852  311.769342   643.437745
4                SF-OGD  0.972603  1953.713059  311.769342  1953.713059
5                  FACI  0.890411   652.584086  311.769342   724.100151
6            MFCS Split  0.969863  1908.645042  311.769342  1908.645042
7             MFCS Full  0.961644  1954.526647  467.281839  1954.526647

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.969863  1908.645042  311.769342  1908.645042
1            Online CV+  0.969863  1762.715954  311.769342  1762.715954
2  Online Jackknife+ aB  0.997260  3707.518105  331.040137  3707.518105
3                 SAOCP  0.923288   597.594852  311.769342   643.437745
4                SF-OGD  0.972603  1953.713059  311.769342  1953.713059
5                  FACI  0.890411   652.584086  311.769342   724.100151
6            MFCS Split  0.969863  1908.645042  311.769342  1908.645042
7             MFCS Full  0.961644  1954.526647  467.281839  1954.526647

In [ ]:
conformal_predictions_COP(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/HGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (HGBR) =====
Coverage : 96.986%
Avg Width: 1908.140
RMSE     : 311.769
Final q  : 953.961

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.969863  1908.139804  311.769342   0.05  0.05    0.5

In [ ]:
conformal_predictions_EXTREME(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/HGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (HGBR) =====
Coverage : 100.000%
Width    : 233488.926
RMSE     : 328.523
q_extreme: 233488.926
u        : 2604.861
#Exceed. : 73

In [ ]:
conformal_predictions_AlphaNet(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/HGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base HGBR model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 63230.2980 | Size: 63230.0610 | α̃: 0.0118 | ⏱ 0.21s/epoch | ETA: 44s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 63227.0085 | Size: 63226.7706 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 63112.2904 | Size: 63112.0512 | α̃: 0.0118 | ⏱ 0.20s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 63230.4566 | Size: 63230.2179 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 31s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 63230.2066 | Size: 63229.9679 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 29s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 63194.2856 | Size: 63194.0477 | α̃: 0.0118 | ⏱ 0.23s/epoch | ETA: 28s
  ✓ Run 1 complete | Final loss: 63194.2856

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 653.1941 | Size: 633.1941 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 28s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 653.2453 | Size: 633.2453 | α̃: 1.0000 | ⏱ 0.29s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 653.2245 | Size: 633.2245 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 25s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 653.2462 | Size: 633.2462 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 653.2221 | Size: 633.2221 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 21s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 653.2458 | Size: 633.2458 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 19s
  ✓ Run 2 complete | Final loss: 653.2458

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 653.2213 | Size: 633.2213 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 19s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 653.2482 | Size: 633.2482 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 17s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 653.2253 | Size: 633.2253 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 15s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 653.2457 | Size: 633.2457 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 653.1375 | Size: 633.1375 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 653.1932 | Size: 633.1932 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 653.1932

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 653.2056 | Size: 633.2056 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 653.1281 | Size: 633.1281 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 653.2440 | Size: 633.2440 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 653.2178 | Size: 633.2178 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 653.2465 | Size: 633.2465 | α̃: 1.0000 | ⏱ 0.25s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 653.1684 | Size: 633.1684 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 653.1684
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (HGBR)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 316.6019
  Coverage       : 89.863%
  Avg Width      : 633.2039
  RMSE           : 448.2493
  Total time     : 40s
    ├─ Precompute: 1s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 40s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.89863,633.203857,448.249279,0.05,1.0,20.0,40.01

# **Conformal Predictions with PGBM**

In [47]:
class PGBMWrapper(BaseEstimator, RegressorMixin):
    def __init__(self, **params):
        self.params = params
        self.model = None

    def fit(self, X, y):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        y_ = y.to_numpy() if hasattr(y, "to_numpy") else np.array(y)
        self.model = PGBM()
        self.model.train(
            train_set=(X_, y_),
            objective=mseloss_objective,
            metric=rmseloss_metric,
            params=self.params
        )
        return self

    def predict(self, X):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        return self.model.predict(X_).numpy()

In [48]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()
def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params=best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Define the quantiles you want to predict
quantiles = [0.05, 0.1, 0.15, 0.2, 0.3,
             0.4, 0.5, 0.6, 0.7, 0.8,
             0.85, 0.9, 0.95]

# DataFrame to store predictions
predictions_PGBM_df = pd.DataFrame()

# Calculate and store quantiles
for q in quantiles:
    predictions_PGBM_df[q] = np.quantile(pred_dist, q, axis=0)

# Add actual str to the DataFrame
predictions_PGBM_df['Actual'] = y_test.ravel()

# Print the DataFrame with predictions for each quantile
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/100, Train metric: 9.7862
Estimator 1/100, Train metric: 9.5276
Estimator 2/100, Train metric: 9.3246
Estimator 3/100, Train metric: 9.1083
Estimator 4/100, Train metric: 8.9585
Estimator 5/100, Train metric: 8.7616
Estimator 6/100, Train metric: 8.5626
Estimator 7/100, Train metric: 8.3759
Estimator 8/100, Train metric: 8.2146
Estimator 9/100, Train metric: 8.1378
Estimator 10/100, Train metric: 7.9641
Estimator 11/100, Train metric: 7.7932
Estimator 12/100, Train metric: 7.7220
Estimator 13/100, Train metric: 7.5836
Estimator 14/100, Train metric: 7.4620
Estimator 15/100, Train metric: 7.3932
Estimator 16/100, Train metric: 7.2816
Estimator 17/100, Train metric: 7.1584
Estimator 18/100, Train metric: 7.0412
Estimator 19/100, Train metric: 6.9517
Estimator 20/100, Train metric: 6.8483
Estimator 21/100, Train metric: 6.7380
Estimator 22/100, Train metric: 6.6463
Estimator 23/100, Train metric: 6.5593
Estimator 24/100, Train metric: 6.4619
Estimator 25/100, Train metric: 6.4233
Estimator 26/100, Train metric: 6.3270
Estimator 27/100, Train metric: 6.2786
Estimator 28/100, Train metric: 6.2388
Estimator 29/100, Train metric: 6.1978
Estimator 30/100, Train metric: 6.1271
Estimator 31/100, Train metric: 6.0552
Estimator 32/100, Train metric: 6.0042
Estimator 33/100, Train metric: 5.9273
Estimator 34/100, Train metric: 5.8459
Estimator 35/100, Train metric: 5.7792
Estimator 36/100, Train metric: 5.7314
Estimator 37/100, Train metric: 5.6672
Estimator 38/100, Train metric: 5.5995
Estimator 39/100, Train metric: 5.5368
Estimator 40/100, Train metric: 5.5051
Estimator 41/100, Train metric: 5.4403
Estimator 42/100, Train metric: 5.4084
Estimator 43/100, Train metric: 5.3502
Estimator 44/100, Train metric: 5.2955
Estimator 45/100, Train metric: 5.2402
Estimator 46/100, Train metric: 5.1745
Estimator 47/100, Train metric: 5.1452
Estimator 48/100, Train metric: 5.0968
Estimator 49/100, Train metric: 5.0469
Estimator 50/100, Train metric: 5.0007
Estimator 51/100, Train metric: 4.9706
Estimator 52/100, Train metric: 4.9358
Estimator 53/100, Train metric: 4.8900
Estimator 54/100, Train metric: 4.8570
Estimator 55/100, Train metric: 4.8163
Estimator 56/100, Train metric: 4.7776
Estimator 57/100, Train metric: 4.7421
Estimator 58/100, Train metric: 4.7208
Estimator 59/100, Train metric: 4.6840
Estimator 60/100, Train metric: 4.6399
Estimator 61/100, Train metric: 4.5914
Estimator 62/100, Train metric: 4.5582
Estimator 63/100, Train metric: 4.5289
Estimator 64/100, Train metric: 4.5027
Estimator 65/100, Train metric: 4.4780
Estimator 66/100, Train metric: 4.4424
Estimator 67/100, Train metric: 4.4113
Estimator 68/100, Train metric: 4.3781
Estimator 69/100, Train metric: 4.3547
Estimator 70/100, Train metric: 4.3280
Estimator 71/100, Train metric: 4.2929
Estimator 72/100, Train metric: 4.2608
Estimator 73/100, Train metric: 4.2338
Estimator 74/100, Train metric: 4.2093
Estimator 75/100, Train metric: 4.1850
Estimator 76/100, Train metric: 4.1607
Estimator 77/100, Train metric: 4.1346
Estimator 78/100, Train metric: 4.1089
Estimator 79/100, Train metric: 4.0955
Estimator 80/100, Train metric: 4.0738
Estimator 81/100, Train metric: 4.0465
Estimator 82/100, Train metric: 4.0320
Estimator 83/100, Train metric: 4.0088
Estimator 84/100, Train metric: 3.9787
Estimator 85/100, Train metric: 3.9632
Estimator 86/100, Train metric: 3.9442
Estimator 87/100, Train metric: 3.9288
Estimator 88/100, Train metric: 3.9087
Estimator 89/100, Train metric: 3.8956
Estimator 90/100, Train metric: 3.8706
Estimator 91/100, Train metric: 3.8575
Estimator 92/100, Train metric: 3.8428
Estimator 93/100, Train metric: 3.8291
Estimator 94/100, Train metric: 3.8013
Estimator 95/100, Train metric: 3.7802
Estimator 96/100, Train metric: 3.7621
Estimator 97/100, Train metric: 3.7412
Estimator 98/100, Train metric: 3.7262
Estimator 99/100, Train metric: 3.7123
        0.05        0.1       0.15        0.2        0.3        0.4  \
0  28.917420  29.153340  29.549525  29.862493  30.053322  30.389876
1  32.129633  33.060398  33.245914  33.608536  33.859980  34.271648
2  32.461282  32.926042  33.264012  33.647013  34.201358  34.461139
3  33.015982  33.204100  33.489397  33.578069  33.949361  34.301329
4  48.352136  48.907943  49.248012  49.422239  49.828596  50.132539

         0.5        0.6        0.7        0.8       0.85        0.9  \
0  30.640059  30.892545  31.082622  31.316661  31.546590  31.768812
1  34.459641  34.658810  34.899059  35.058936  35.299631  35.748922
2  34.739494  35.001009  35.293649  35.520940  35.635183  35.912203
3  34.437868  34.624072  34.845481  35.133405  35.275297  35.619882
4  50.346783  50.625944  50.867766  51.138135  51.363610  51.614970

        0.95  Actual
0  32.600375    34.0
1  36.487990    36.0
2  36.193312    36.0
3  36.280572    35.0
4  52.036023    44.6

In [49]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

In [50]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path


import os
def to_numpy_1d(y):
    return y.to_numpy().ravel() if hasattr(y, "to_numpy") else np.asarray(y).ravel()


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values, weights = values[sorter], weights[sorter]
    cdf = np.cumsum(weights) / np.sum(weights)
    return np.interp(q, cdf, values)



# ============================================================
# NexCP for PGBM (Excel-safe, NexCP-style, NO RETURNS)
# ============================================================

def conformal_predictions_NEXCP_PGBM(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    # ========================================================
    # data conversion (PGBM-specific)
    # ========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    STRATEGIES = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # ========================================================
    # Fit base model
    # ========================================================
    base_model = model_class(**best_params)
    base_model.fit(Xtr, ytr)

    yhat_tr = base_model.predict(Xtr)
    yhat_te = base_model.predict(Xte)
    residuals = np.abs(ytr - yhat_tr)

    # ========================================================
    # NexCP – Split (Exponentially Weighted)
    # ========================================================
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_te
    int_pred["NexCP-Split"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Full
    # ========================================================
    q = np.quantile(residuals, 1 - alpha)
    y_pred["NexCP-Full"] = yhat_te
    int_pred["NexCP-Full"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Jackknife+ aB
    # ========================================================
    rng = np.random.default_rng(seed)
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(Xtr), len(Xtr), replace=True)
        m = model_class(**best_params)
        m.fit(Xtr[idx], ytr[idx])

        q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # ========================================================
    # NexCP – CV+
    # ========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    lowers, uppers, preds = [], [], []

    for tr_idx, cal_idx in kf.split(Xtr):
        m = model_class(**best_params)
        m.fit(Xtr[tr_idx], ytr[tr_idx])

        q = np.quantile(np.abs(ytr[cal_idx] - m.predict(Xtr[cal_idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== NEXCP (PGBM) RESULTS =====")

    for s in STRATEGIES:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in STRATEGIES:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("str")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary sheet ----
        sheet_name = "NEXCP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"NEXCP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        sheet_name = "NEXCP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))


conformal_predictions_NEXCP_PGBM(
    model_class=PGBMWrapper,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/PGBM.xlsx",
    alpha=0.05,
)

Streaming output truncated to the last 5000 lines.
Estimator 55/100, Train metric: 4.6866
Estimator 56/100, Train metric: 4.6509
Estimator 57/100, Train metric: 4.6194
Estimator 58/100, Train metric: 4.5757
Estimator 59/100, Train metric: 4.5257
Estimator 60/100, Train metric: 4.4828
Estimator 61/100, Train metric: 4.4520
Estimator 62/100, Train metric: 4.4132
Estimator 63/100, Train metric: 4.3662
Estimator 64/100, Train metric: 4.3429
Estimator 65/100, Train metric: 4.3135
Estimator 66/100, Train metric: 4.2783
Estimator 67/100, Train metric: 4.2459
Estimator 68/100, Train metric: 4.2090
Estimator 69/100, Train metric: 4.1731
Estimator 70/100, Train metric: 4.1366
Estimator 71/100, Train metric: 4.1059
Estimator 72/100, Train metric: 4.0707
Estimator 73/100, Train metric: 4.0444
Estimator 74/100, Train metric: 4.0250
Estimator 75/100, Train metric: 4.0034
Estimator 76/100, Train metric: 3.9866
Estimator 77/100, Train metric: 3.9631
Estimator 78/100, Train metric: 3.9468
Estimator 79/100, Train metric: 3.9157
Estimator 80/100, Train metric: 3.8914
Estimator 81/100, Train metric: 3.8568
Estimator 82/100, Train metric: 3.8300
Estimator 83/100, Train metric: 3.7977
Estimator 84/100, Train metric: 3.7752
Estimator 85/100, Train metric: 3.7510
Estimator 86/100, Train metric: 3.7257
Estimator 87/100, Train metric: 3.7043
Estimator 88/100, Train metric: 3.6761
Estimator 89/100, Train metric: 3.6581
Estimator 90/100, Train metric: 3.6350
Estimator 91/100, Train metric: 3.6119
Estimator 92/100, Train metric: 3.5873
Estimator 93/100, Train metric: 3.5659
Estimator 94/100, Train metric: 3.5472
Estimator 95/100, Train metric: 3.5208
Estimator 96/100, Train metric: 3.4949
Estimator 97/100, Train metric: 3.4720
Estimator 98/100, Train metric: 3.4517
Estimator 99/100, Train metric: 3.4333
Training on CPU
Estimator 0/100, Train metric: 10.1101
Estimator 1/100, Train metric: 9.8438
Estimator 2/100, Train metric: 9.5808
Estimator 3/100, Train metric: 9.3268
Estimator 4/100, Train metric: 9.1143
Estimator 5/100, Train metric: 8.8891
Estimator 6/100, Train metric: 8.6871
Estimator 7/100, Train metric: 8.4828
Estimator 8/100, Train metric: 8.3075
Estimator 9/100, Train metric: 8.1522
Estimator 10/100, Train metric: 8.0205
Estimator 11/100, Train metric: 7.8522
Estimator 12/100, Train metric: 7.6927
Estimator 13/100, Train metric: 7.5483
Estimator 14/100, Train metric: 7.4207
Estimator 15/100, Train metric: 7.2942
Estimator 16/100, Train metric: 7.1538
Estimator 17/100, Train metric: 7.0239
Estimator 18/100, Train metric: 6.8930
Estimator 19/100, Train metric: 6.7688
Estimator 20/100, Train metric: 6.6777
Estimator 21/100, Train metric: 6.5671
Estimator 22/100, Train metric: 6.4619
Estimator 23/100, Train metric: 6.3518
Estimator 24/100, Train metric: 6.2504
Estimator 25/100, Train metric: 6.1480
Estimator 26/100, Train metric: 6.0857
Estimator 27/100, Train metric: 5.9980
Estimator 28/100, Train metric: 5.9139
Estimator 29/100, Train metric: 5.8383
Estimator 30/100, Train metric: 5.7450
Estimator 31/100, Train metric: 5.6748
Estimator 32/100, Train metric: 5.6141
Estimator 33/100, Train metric: 5.5480
Estimator 34/100, Train metric: 5.4691
Estimator 35/100, Train metric: 5.3880
Estimator 36/100, Train metric: 5.3073
Estimator 37/100, Train metric: 5.2522
Estimator 38/100, Train metric: 5.1956
Estimator 39/100, Train metric: 5.1175
Estimator 40/100, Train metric: 5.0624
Estimator 41/100, Train metric: 4.9824
Estimator 42/100, Train metric: 4.9288
Estimator 43/100, Train metric: 4.8649
Estimator 44/100, Train metric: 4.8032
Estimator 45/100, Train metric: 4.7444
Estimator 46/100, Train metric: 4.6978
Estimator 47/100, Train metric: 4.6465
Estimator 48/100, Train metric: 4.6016
Estimator 49/100, Train metric: 4.5521
Estimator 50/100, Train metric: 4.5160
Estimator 51/100, Train metric: 4.4611
Estimator 52/100, Train metric: 4.4104
Estimator 53/100, Train metric: 4.3648
Estimator 54/100, Train metric: 4.3234
Estimator 55/100, Train metric: 4.2833
Estimator 56/100, Train metric: 4.2367
Estimator 57/100, Train metric: 4.1928
Estimator 58/100, Train metric: 4.1556
Estimator 59/100, Train metric: 4.1185
Estimator 60/100, Train metric: 4.0839
Estimator 61/100, Train metric: 4.0470
Estimator 62/100, Train metric: 4.0228
Estimator 63/100, Train metric: 3.9951
Estimator 64/100, Train metric: 3.9723
Estimator 65/100, Train metric: 3.9525
Estimator 66/100, Train metric: 3.9273
Estimator 67/100, Train metric: 3.9004
Estimator 68/100, Train metric: 3.8681
Estimator 69/100, Train metric: 3.8335
Estimator 70/100, Train metric: 3.8035
Estimator 71/100, Train metric: 3.7819
Estimator 72/100, Train metric: 3.7554
Estimator 73/100, Train metric: 3.7355
Estimator 74/100, Train metric: 3.7183
Estimator 75/100, Train metric: 3.6959
Estimator 76/100, Train metric: 3.6695
Estimator 77/100, Train metric: 3.6482
Estimator 78/100, Train metric: 3.6256
Estimator 79/100, Train metric: 3.6021
Estimator 80/100, Train metric: 3.5769
Estimator 81/100, Train metric: 3.5524
Estimator 82/100, Train metric: 3.5291
Estimator 83/100, Train metric: 3.5018
Estimator 84/100, Train metric: 3.4843
Estimator 85/100, Train metric: 3.4651
Estimator 86/100, Train metric: 3.4410
Estimator 87/100, Train metric: 3.4231
Estimator 88/100, Train metric: 3.4031
Estimator 89/100, Train metric: 3.3863
Estimator 90/100, Train metric: 3.3706
Estimator 91/100, Train metric: 3.3487
Estimator 92/100, Train metric: 3.3318
Estimator 93/100, Train metric: 3.3168
Estimator 94/100, Train metric: 3.2929
Estimator 95/100, Train metric: 3.2773
Estimator 96/100, Train metric: 3.2598
Estimator 97/100, Train metric: 3.2387
Estimator 98/100, Train metric: 3.2185
Estimator 99/100, Train metric: 3.1994
Training on CPU
Estimator 0/100, Train metric: 10.2381
Estimator 1/100, Train metric: 9.9429
Estimator 2/100, Train metric: 9.7498
Estimator 3/100, Train metric: 9.5252
Estimator 4/100, Train metric: 9.2800
Estimator 5/100, Train metric: 9.0673
Estimator 6/100, Train metric: 8.8431
Estimator 7/100, Train metric: 8.6656
Estimator 8/100, Train metric: 8.4904
Estimator 9/100, Train metric: 8.3623
Estimator 10/100, Train metric: 8.2090
Estimator 11/100, Train metric: 8.0288
Estimator 12/100, Train metric: 7.9032
Estimator 13/100, Train metric: 7.7553
Estimator 14/100, Train metric: 7.6065
Estimator 15/100, Train metric: 7.4681
Estimator 16/100, Train metric: 7.3149
Estimator 17/100, Train metric: 7.1941
Estimator 18/100, Train metric: 7.0668
Estimator 19/100, Train metric: 6.9815
Estimator 20/100, Train metric: 6.8633
Estimator 21/100, Train metric: 6.7863
Estimator 22/100, Train metric: 6.6741
Estimator 23/100, Train metric: 6.6141
Estimator 24/100, Train metric: 6.4911
Estimator 25/100, Train metric: 6.3790
Estimator 26/100, Train metric: 6.3025
Estimator 27/100, Train metric: 6.2100
Estimator 28/100, Train metric: 6.1233
Estimator 29/100, Train metric: 6.0202
Estimator 30/100, Train metric: 5.9208
Estimator 31/100, Train metric: 5.8428
Estimator 32/100, Train metric: 5.7897
Estimator 33/100, Train metric: 5.7263
Estimator 34/100, Train metric: 5.6597
Estimator 35/100, Train metric: 5.5819
Estimator 36/100, Train metric: 5.5039
Estimator 37/100, Train metric: 5.4387
Estimator 38/100, Train metric: 5.3894
Estimator 39/100, Train metric: 5.3242
Estimator 40/100, Train metric: 5.2689
Estimator 41/100, Train metric: 5.2201
Estimator 42/100, Train metric: 5.1635
Estimator 43/100, Train metric: 5.1016
Estimator 44/100, Train metric: 5.0472
Estimator 45/100, Train metric: 4.9718
Estimator 46/100, Train metric: 4.9205
Estimator 47/100, Train metric: 4.8602
Estimator 48/100, Train metric: 4.8306
Estimator 49/100, Train metric: 4.7832
Estimator 50/100, Train metric: 4.7244
Estimator 51/100, Train metric: 4.6630
Estimator 52/100, Train metric: 4.6084
Estimator 53/100, Train metric: 4.5657
Estimator 54/100, Train metric: 4.5319
Estimator 55/100, Train metric: 4.4953
Estimator 56/100, Train metric: 4.4639
Estimator 57/100, Train metric: 4.4375
Estimator 58/100, Train metric: 4.4075
Estimator 59/100, Train metric: 4.3587
Estimator 60/100, Train metric: 4.3211
Estimator 61/100, Train metric: 4.2810
Estimator 62/100, Train metric: 4.2601
Estimator 63/100, Train metric: 4.2157
Estimator 64/100, Train metric: 4.1774
Estimator 65/100, Train metric: 4.1427
Estimator 66/100, Train metric: 4.1087
Estimator 67/100, Train metric: 4.0796
Estimator 68/100, Train metric: 4.0453
Estimator 69/100, Train metric: 4.0200
Estimator 70/100, Train metric: 3.9965
Estimator 71/100, Train metric: 3.9605
Estimator 72/100, Train metric: 3.9364
Estimator 73/100, Train metric: 3.9054
Estimator 74/100, Train metric: 3.8794
Estimator 75/100, Train metric: 3.8457
Estimator 76/100, Train metric: 3.8237
Estimator 77/100, Train metric: 3.7964
Estimator 78/100, Train metric: 3.7677
Estimator 79/100, Train metric: 3.7386
Estimator 80/100, Train metric: 3.7215
Estimator 81/100, Train metric: 3.6973
Estimator 82/100, Train metric: 3.6676
Estimator 83/100, Train metric: 3.6435
Estimator 84/100, Train metric: 3.6271
Estimator 85/100, Train metric: 3.6055
Estimator 86/100, Train metric: 3.5909
Estimator 87/100, Train metric: 3.5707
Estimator 88/100, Train metric: 3.5446
Estimator 89/100, Train metric: 3.5183
Estimator 90/100, Train metric: 3.5050
Estimator 91/100, Train metric: 3.4800
Estimator 92/100, Train metric: 3.4544
Estimator 93/100, Train metric: 3.4359
Estimator 94/100, Train metric: 3.4138
Estimator 95/100, Train metric: 3.3915
Estimator 96/100, Train metric: 3.3741
Estimator 97/100, Train metric: 3.3460
Estimator 98/100, Train metric: 3.3313
Estimator 99/100, Train metric: 3.3133
Training on CPU
Estimator 0/100, Train metric: 9.8294
Estimator 1/100, Train metric: 9.5698
Estimator 2/100, Train metric: 9.3318
Estimator 3/100, Train metric: 9.1141
Estimator 4/100, Train metric: 8.9705
Estimator 5/100, Train metric: 8.8063
Estimator 6/100, Train metric: 8.5870
Estimator 7/100, Train metric: 8.3868
Estimator 8/100, Train metric: 8.1863
Estimator 9/100, Train metric: 8.0197
Estimator 10/100, Train metric: 7.8482
Estimator 11/100, Train metric: 7.6737
Estimator 12/100, Train metric: 7.5349
Estimator 13/100, Train metric: 7.4460
Estimator 14/100, Train metric: 7.3740
Estimator 15/100, Train metric: 7.2337
Estimator 16/100, Train metric: 7.1105
Estimator 17/100, Train metric: 6.9692
Estimator 18/100, Train metric: 6.8563
Estimator 19/100, Train metric: 6.7371
Estimator 20/100, Train metric: 6.6230
Estimator 21/100, Train metric: 6.4961
Estimator 22/100, Train metric: 6.3965
Estimator 23/100, Train metric: 6.3309
Estimator 24/100, Train metric: 6.2536
Estimator 25/100, Train metric: 6.1768
Estimator 26/100, Train metric: 6.0730
Estimator 27/100, Train metric: 5.9719
Estimator 28/100, Train metric: 5.9093
Estimator 29/100, Train metric: 5.8458
Estimator 30/100, Train metric: 5.7637
Estimator 31/100, Train metric: 5.6750
Estimator 32/100, Train metric: 5.5914
Estimator 33/100, Train metric: 5.5050
Estimator 34/100, Train metric: 5.4389
Estimator 35/100, Train metric: 5.3653
Estimator 36/100, Train metric: 5.3045
Estimator 37/100, Train metric: 5.2468
Estimator 38/100, Train metric: 5.1826
Estimator 39/100, Train metric: 5.1216
Estimator 40/100, Train metric: 5.0789
Estimator 41/100, Train metric: 5.0085
Estimator 42/100, Train metric: 4.9463
Estimator 43/100, Train metric: 4.8915
Estimator 44/100, Train metric: 4.8226
Estimator 45/100, Train metric: 4.7652
Estimator 46/100, Train metric: 4.7103
Estimator 47/100, Train metric: 4.6675
Estimator 48/100, Train metric: 4.6059
Estimator 49/100, Train metric: 4.5643
Estimator 50/100, Train metric: 4.5267
Estimator 51/100, Train metric: 4.4738
Estimator 52/100, Train metric: 4.4368
Estimator 53/100, Train metric: 4.3867
Estimator 54/100, Train metric: 4.3446
Estimator 55/100, Train metric: 4.3088
Estimator 56/100, Train metric: 4.2579
Estimator 57/100, Train metric: 4.2288
Estimator 58/100, Train metric: 4.1900
Estimator 59/100, Train metric: 4.1457
Estimator 60/100, Train metric: 4.1019
Estimator 61/100, Train metric: 4.0546
Estimator 62/100, Train metric: 4.0234
Estimator 63/100, Train metric: 3.9964
Estimator 64/100, Train metric: 3.9659
Estimator 65/100, Train metric: 3.9405
Estimator 66/100, Train metric: 3.9041
Estimator 67/100, Train metric: 3.8700
Estimator 68/100, Train metric: 3.8422
Estimator 69/100, Train metric: 3.8174
Estimator 70/100, Train metric: 3.7912
Estimator 71/100, Train metric: 3.7619
Estimator 72/100, Train metric: 3.7386
Estimator 73/100, Train metric: 3.7042
Estimator 74/100, Train metric: 3.6838
Estimator 75/100, Train metric: 3.6633
Estimator 76/100, Train metric: 3.6436
Estimator 77/100, Train metric: 3.6177
Estimator 78/100, Train metric: 3.5978
Estimator 79/100, Train metric: 3.5702
Estimator 80/100, Train metric: 3.5464
Estimator 81/100, Train metric: 3.5236
Estimator 82/100, Train metric: 3.5068
Estimator 83/100, Train metric: 3.4835
Estimator 84/100, Train metric: 3.4581
Estimator 85/100, Train metric: 3.4433
Estimator 86/100, Train metric: 3.4200
Estimator 87/100, Train metric: 3.3979
Estimator 88/100, Train metric: 3.3715
Estimator 89/100, Train metric: 3.3494
Estimator 90/100, Train metric: 3.3329
Estimator 91/100, Train metric: 3.3135
Estimator 92/100, Train metric: 3.2880
Estimator 93/100, Train metric: 3.2753
Estimator 94/100, Train metric: 3.2490
Estimator 95/100, Train metric: 3.2315
Estimator 96/100, Train metric: 3.2210
Estimator 97/100, Train metric: 3.2104
Estimator 98/100, Train metric: 3.1953
Estimator 99/100, Train metric: 3.1784
Training on CPU
Estimator 0/100, Train metric: 9.2168
Estimator 1/100, Train metric: 8.9812
Estimator 2/100, Train metric: 8.7510
Estimator 3/100, Train metric: 8.5637
Estimator 4/100, Train metric: 8.4058
Estimator 5/100, Train metric: 8.2392
Estimator 6/100, Train metric: 8.0677
Estimator 7/100, Train metric: 7.9037
Estimator 8/100, Train metric: 7.7466
Estimator 9/100, Train metric: 7.5788
Estimator 10/100, Train metric: 7.4513
Estimator 11/100, Train metric: 7.3501
Estimator 12/100, Train metric: 7.2599
Estimator 13/100, Train metric: 7.1320
Estimator 14/100, Train metric: 7.0013
Estimator 15/100, Train metric: 6.8725
Estimator 16/100, Train metric: 6.7465
Estimator 17/100, Train metric: 6.6493
Estimator 18/100, Train metric: 6.5111
Estimator 19/100, Train metric: 6.3930
Estimator 20/100, Train metric: 6.2983
Estimator 21/100, Train metric: 6.2016
Estimator 22/100, Train metric: 6.1113
Estimator 23/100, Train metric: 6.0448
Estimator 24/100, Train metric: 5.9369
Estimator 25/100, Train metric: 5.8761
Estimator 26/100, Train metric: 5.7847
Estimator 27/100, Train metric: 5.7349
Estimator 28/100, Train metric: 5.6799
Estimator 29/100, Train metric: 5.6202
Estimator 30/100, Train metric: 5.5255
Estimator 31/100, Train metric: 5.4514
Estimator 32/100, Train metric: 5.3774
Estimator 33/100, Train metric: 5.2988
Estimator 34/100, Train metric: 5.2134
Estimator 35/100, Train metric: 5.1484
Estimator 36/100, Train metric: 5.0659
Estimator 37/100, Train metric: 4.9954
Estimator 38/100, Train metric: 4.9326
Estimator 39/100, Train metric: 4.8714
Estimator 40/100, Train metric: 4.8218
Estimator 41/100, Train metric: 4.7606
Estimator 42/100, Train metric: 4.7206
Estimator 43/100, Train metric: 4.6520
Estimator 44/100, Train metric: 4.6007
Estimator 45/100, Train metric: 4.5493
Estimator 46/100, Train metric: 4.4952
Estimator 47/100, Train metric: 4.4446
Estimator 48/100, Train metric: 4.4089
Estimator 49/100, Train metric: 4.3684
Estimator 50/100, Train metric: 4.3245
Estimator 51/100, Train metric: 4.2772
Estimator 52/100, Train metric: 4.2434
Estimator 53/100, Train metric: 4.2015
Estimator 54/100, Train metric: 4.1582
Estimator 55/100, Train metric: 4.1239
Estimator 56/100, Train metric: 4.0873
Estimator 57/100, Train metric: 4.0542
Estimator 58/100, Train metric: 4.0153
Estimator 59/100, Train metric: 3.9811
Estimator 60/100, Train metric: 3.9495
Estimator 61/100, Train metric: 3.9238
Estimator 62/100, Train metric: 3.8815
Estimator 63/100, Train metric: 3.8452
Estimator 64/100, Train metric: 3.8210
Estimator 65/100, Train metric: 3.7976
Estimator 66/100, Train metric: 3.7621
Estimator 67/100, Train metric: 3.7380
Estimator 68/100, Train metric: 3.7092
Estimator 69/100, Train metric: 3.6914
Estimator 70/100, Train metric: 3.6662
Estimator 71/100, Train metric: 3.6488
Estimator 72/100, Train metric: 3.6239
Estimator 73/100, Train metric: 3.5999
Estimator 74/100, Train metric: 3.5798
Estimator 75/100, Train metric: 3.5580
Estimator 76/100, Train metric: 3.5347
Estimator 77/100, Train metric: 3.5073
Estimator 78/100, Train metric: 3.4892
Estimator 79/100, Train metric: 3.4713
Estimator 80/100, Train metric: 3.4542
Estimator 81/100, Train metric: 3.4307
Estimator 82/100, Train metric: 3.4122
Estimator 83/100, Train metric: 3.3934
Estimator 84/100, Train metric: 3.3762
Estimator 85/100, Train metric: 3.3575
Estimator 86/100, Train metric: 3.3358
Estimator 87/100, Train metric: 3.3158
Estimator 88/100, Train metric: 3.3002
Estimator 89/100, Train metric: 3.2808
Estimator 90/100, Train metric: 3.2648
Estimator 91/100, Train metric: 3.2522
Estimator 92/100, Train metric: 3.2397
Estimator 93/100, Train metric: 3.2152
Estimator 94/100, Train metric: 3.2053
Estimator 95/100, Train metric: 3.1888
Estimator 96/100, Train metric: 3.1768
Estimator 97/100, Train metric: 3.1653
Estimator 98/100, Train metric: 3.1514
Estimator 99/100, Train metric: 3.1379
Training on CPU
Estimator 0/100, Train metric: 9.2802
Estimator 1/100, Train metric: 9.0586
Estimator 2/100, Train metric: 8.8562
Estimator 3/100, Train metric: 8.6584
Estimator 4/100, Train metric: 8.4932
Estimator 5/100, Train metric: 8.3308
Estimator 6/100, Train metric: 8.1462
Estimator 7/100, Train metric: 7.9799
Estimator 8/100, Train metric: 7.8119
Estimator 9/100, Train metric: 7.6947
Estimator 10/100, Train metric: 7.5413
Estimator 11/100, Train metric: 7.3995
Estimator 12/100, Train metric: 7.2670
Estimator 13/100, Train metric: 7.1309
Estimator 14/100, Train metric: 7.0144
Estimator 15/100, Train metric: 6.9231
Estimator 16/100, Train metric: 6.8053
Estimator 17/100, Train metric: 6.6754
Estimator 18/100, Train metric: 6.5535
Estimator 19/100, Train metric: 6.4552
Estimator 20/100, Train metric: 6.3483
Estimator 21/100, Train metric: 6.2317
Estimator 22/100, Train metric: 6.1295
Estimator 23/100, Train metric: 6.0473
Estimator 24/100, Train metric: 5.9527
Estimator 25/100, Train metric: 5.8608
Estimator 26/100, Train metric: 5.7736
Estimator 27/100, Train metric: 5.6857
Estimator 28/100, Train metric: 5.5971
Estimator 29/100, Train metric: 5.5215
Estimator 30/100, Train metric: 5.4281
Estimator 31/100, Train metric: 5.3519
Estimator 32/100, Train metric: 5.3088
Estimator 33/100, Train metric: 5.2245
Estimator 34/100, Train metric: 5.1561
Estimator 35/100, Train metric: 5.1179
Estimator 36/100, Train metric: 5.0645
Estimator 37/100, Train metric: 5.0075
Estimator 38/100, Train metric: 4.9473
Estimator 39/100, Train metric: 4.8855
Estimator 40/100, Train metric: 4.8248
Estimator 41/100, Train metric: 4.7624
Estimator 42/100, Train metric: 4.7008
Estimator 43/100, Train metric: 4.6557
Estimator 44/100, Train metric: 4.5966
Estimator 45/100, Train metric: 4.5570
Estimator 46/100, Train metric: 4.5127
Estimator 47/100, Train metric: 4.4708
Estimator 48/100, Train metric: 4.4142
Estimator 49/100, Train metric: 4.3769
Estimator 50/100, Train metric: 4.3222
Estimator 51/100, Train metric: 4.2758
Estimator 52/100, Train metric: 4.2478
Estimator 53/100, Train metric: 4.1960
Estimator 54/100, Train metric: 4.1576
Estimator 55/100, Train metric: 4.1128
Estimator 56/100, Train metric: 4.0800
Estimator 57/100, Train metric: 4.0367
Estimator 58/100, Train metric: 3.9975
Estimator 59/100, Train metric: 3.9626
Estimator 60/100, Train metric: 3.9359
Estimator 61/100, Train metric: 3.8926
Estimator 62/100, Train metric: 3.8608
Estimator 63/100, Train metric: 3.8310
Estimator 64/100, Train metric: 3.8035

In [51]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_online_super_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    STRATEGIES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    if strategies == "all":
        strategies = list(STRATEGIES.keys())

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Base model (trained once)
    # --------------------------------------------------------
    base_model = model_class(**model_params)
    base_model.fit(Xtr, ytr)

    yhat_train = base_model.predict(Xtr)

    # --------------------------------------------------------
    # Streaming predictions
    # --------------------------------------------------------
    X_all = np.vstack([Xtr, Xte])
    y_all = np.concatenate([ytr, yte])

    n_train = len(Xtr)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train

    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # ========================================================
    # Online Split
    # ========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_pred["Online-Split"] - q,
                                          y_pred["Online-Split"] + q]

    # ========================================================
    # Online CV+
    # ========================================================
    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    # ========================================================
    # Online Jackknife+ aB
    # ========================================================
    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(Xtr[idx], ytr[idx])

            q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
            p = m.predict(Xte)

            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)

        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    # ========================================================
    # SAOCP
    # ========================================================
    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, int(t / 2)), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    # ========================================================
    # SF-OGD
    # ========================================================
    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            grad = alpha - (residuals[t] <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    # ========================================================
    # FACI
    # ========================================================
    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    # ========================================================
    # MFCS-Split ✅ (ADDED)
    # ========================================================
    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_pred["MFCS-Split"] - q,
                                       y_pred["MFCS-Split"] + q]

    # ========================================================
    # MFCS-Full
    # ========================================================
    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            q = np.quantile(np.abs(y_all[:t] - m.predict(X_all[:t])), 1 - alpha)
            preds.append(yhat)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== ONLINE CP (PGBM) RESULTS =====")

    for s in y_pred:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("str")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary ----
        sheet_name = "ONLINECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "ONLINECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))


conformal_predictions_online_super_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/PGBM.xlsx",
    alpha=0.05,
    strategies="all",
)

Streaming output truncated to the last 5000 lines.
Estimator 59/100, Train metric: 4.1194
Estimator 60/100, Train metric: 4.0779
Estimator 61/100, Train metric: 4.0506
Estimator 62/100, Train metric: 4.0151
Estimator 63/100, Train metric: 3.9828
Estimator 64/100, Train metric: 3.9520
Estimator 65/100, Train metric: 3.9249
Estimator 66/100, Train metric: 3.8954
Estimator 67/100, Train metric: 3.8720
Estimator 68/100, Train metric: 3.8418
Estimator 69/100, Train metric: 3.8205
Estimator 70/100, Train metric: 3.7954
Estimator 71/100, Train metric: 3.7728
Estimator 72/100, Train metric: 3.7594
Estimator 73/100, Train metric: 3.7447
Estimator 74/100, Train metric: 3.7239
Estimator 75/100, Train metric: 3.7054
Estimator 76/100, Train metric: 3.6757
Estimator 77/100, Train metric: 3.6535
Estimator 78/100, Train metric: 3.6426
Estimator 79/100, Train metric: 3.6225
Estimator 80/100, Train metric: 3.6051
Estimator 81/100, Train metric: 3.5838
Estimator 82/100, Train metric: 3.5687
Estimator 83/100, Train metric: 3.5481
Estimator 84/100, Train metric: 3.5299
Estimator 85/100, Train metric: 3.5159
Estimator 86/100, Train metric: 3.4969
Estimator 87/100, Train metric: 3.4739
Estimator 88/100, Train metric: 3.4604
Estimator 89/100, Train metric: 3.4403
Estimator 90/100, Train metric: 3.4287
Estimator 91/100, Train metric: 3.4106
Estimator 92/100, Train metric: 3.3941
Estimator 93/100, Train metric: 3.3708
Estimator 94/100, Train metric: 3.3470
Estimator 95/100, Train metric: 3.3291
Estimator 96/100, Train metric: 3.3088
Estimator 97/100, Train metric: 3.2894
Estimator 98/100, Train metric: 3.2743
Estimator 99/100, Train metric: 3.2634
Training on CPU
Estimator 0/100, Train metric: 9.4495
Estimator 1/100, Train metric: 9.1861
Estimator 2/100, Train metric: 8.9582
Estimator 3/100, Train metric: 8.8228
Estimator 4/100, Train metric: 8.5953
Estimator 5/100, Train metric: 8.3879
Estimator 6/100, Train metric: 8.1905
Estimator 7/100, Train metric: 8.0091
Estimator 8/100, Train metric: 7.8337
Estimator 9/100, Train metric: 7.6746
Estimator 10/100, Train metric: 7.5192
Estimator 11/100, Train metric: 7.3639
Estimator 12/100, Train metric: 7.2255
Estimator 13/100, Train metric: 7.1361
Estimator 14/100, Train metric: 6.9843
Estimator 15/100, Train metric: 6.9042
Estimator 16/100, Train metric: 6.7861
Estimator 17/100, Train metric: 6.6502
Estimator 18/100, Train metric: 6.5508
Estimator 19/100, Train metric: 6.4443
Estimator 20/100, Train metric: 6.3568
Estimator 21/100, Train metric: 6.2505
Estimator 22/100, Train metric: 6.1432
Estimator 23/100, Train metric: 6.0534
Estimator 24/100, Train metric: 5.9433
Estimator 25/100, Train metric: 5.8521
Estimator 26/100, Train metric: 5.7634
Estimator 27/100, Train metric: 5.6884
Estimator 28/100, Train metric: 5.6303
Estimator 29/100, Train metric: 5.5466
Estimator 30/100, Train metric: 5.4724
Estimator 31/100, Train metric: 5.4040
Estimator 32/100, Train metric: 5.3381
Estimator 33/100, Train metric: 5.2746
Estimator 34/100, Train metric: 5.2049
Estimator 35/100, Train metric: 5.1620
Estimator 36/100, Train metric: 5.1051
Estimator 37/100, Train metric: 5.0364
Estimator 38/100, Train metric: 4.9897
Estimator 39/100, Train metric: 4.9318
Estimator 40/100, Train metric: 4.8845
Estimator 41/100, Train metric: 4.8376
Estimator 42/100, Train metric: 4.7824
Estimator 43/100, Train metric: 4.7489
Estimator 44/100, Train metric: 4.7267
Estimator 45/100, Train metric: 4.6832
Estimator 46/100, Train metric: 4.6446
Estimator 47/100, Train metric: 4.6104
Estimator 48/100, Train metric: 4.5611
Estimator 49/100, Train metric: 4.5330
Estimator 50/100, Train metric: 4.4923
Estimator 51/100, Train metric: 4.4648
Estimator 52/100, Train metric: 4.4286
Estimator 53/100, Train metric: 4.3827
Estimator 54/100, Train metric: 4.3475
Estimator 55/100, Train metric: 4.3082
Estimator 56/100, Train metric: 4.2731
Estimator 57/100, Train metric: 4.2414
Estimator 58/100, Train metric: 4.2033
Estimator 59/100, Train metric: 4.1717
Estimator 60/100, Train metric: 4.1453
Estimator 61/100, Train metric: 4.1123
Estimator 62/100, Train metric: 4.0770
Estimator 63/100, Train metric: 4.0394
Estimator 64/100, Train metric: 4.0000
Estimator 65/100, Train metric: 3.9717
Estimator 66/100, Train metric: 3.9442
Estimator 67/100, Train metric: 3.9111
Estimator 68/100, Train metric: 3.8933
Estimator 69/100, Train metric: 3.8639
Estimator 70/100, Train metric: 3.8326
Estimator 71/100, Train metric: 3.8073
Estimator 72/100, Train metric: 3.7838
Estimator 73/100, Train metric: 3.7658
Estimator 74/100, Train metric: 3.7400
Estimator 75/100, Train metric: 3.7206
Estimator 76/100, Train metric: 3.6945
Estimator 77/100, Train metric: 3.6705
Estimator 78/100, Train metric: 3.6451
Estimator 79/100, Train metric: 3.6235
Estimator 80/100, Train metric: 3.6016
Estimator 81/100, Train metric: 3.5841
Estimator 82/100, Train metric: 3.5553
Estimator 83/100, Train metric: 3.5340
Estimator 84/100, Train metric: 3.5158
Estimator 85/100, Train metric: 3.4984
Estimator 86/100, Train metric: 3.4801
Estimator 87/100, Train metric: 3.4589
Estimator 88/100, Train metric: 3.4422
Estimator 89/100, Train metric: 3.4219
Estimator 90/100, Train metric: 3.4048
Estimator 91/100, Train metric: 3.3871
Estimator 92/100, Train metric: 3.3666
Estimator 93/100, Train metric: 3.3490
Estimator 94/100, Train metric: 3.3332
Estimator 95/100, Train metric: 3.3199
Estimator 96/100, Train metric: 3.3084
Estimator 97/100, Train metric: 3.2914
Estimator 98/100, Train metric: 3.2752
Estimator 99/100, Train metric: 3.2577
Training on CPU
Estimator 0/100, Train metric: 9.5068
Estimator 1/100, Train metric: 9.2537
Estimator 2/100, Train metric: 9.0132
Estimator 3/100, Train metric: 8.8269
Estimator 4/100, Train metric: 8.6747
Estimator 5/100, Train metric: 8.5115
Estimator 6/100, Train metric: 8.3311
Estimator 7/100, Train metric: 8.1230
Estimator 8/100, Train metric: 7.9475
Estimator 9/100, Train metric: 7.7602
Estimator 10/100, Train metric: 7.6314
Estimator 11/100, Train metric: 7.4623
Estimator 12/100, Train metric: 7.3052
Estimator 13/100, Train metric: 7.1425
Estimator 14/100, Train metric: 7.0499
Estimator 15/100, Train metric: 6.9039
Estimator 16/100, Train metric: 6.7657
Estimator 17/100, Train metric: 6.6316
Estimator 18/100, Train metric: 6.5405
Estimator 19/100, Train metric: 6.4179
Estimator 20/100, Train metric: 6.3419
Estimator 21/100, Train metric: 6.2237
Estimator 22/100, Train metric: 6.1164
Estimator 23/100, Train metric: 6.0435
Estimator 24/100, Train metric: 5.9731
Estimator 25/100, Train metric: 5.9190
Estimator 26/100, Train metric: 5.8715
Estimator 27/100, Train metric: 5.8026
Estimator 28/100, Train metric: 5.7242
Estimator 29/100, Train metric: 5.6632
Estimator 30/100, Train metric: 5.5948
Estimator 31/100, Train metric: 5.5167
Estimator 32/100, Train metric: 5.4456
Estimator 33/100, Train metric: 5.3878
Estimator 34/100, Train metric: 5.3243
Estimator 35/100, Train metric: 5.2595
Estimator 36/100, Train metric: 5.2186
Estimator 37/100, Train metric: 5.1479
Estimator 38/100, Train metric: 5.0891
Estimator 39/100, Train metric: 5.0292
Estimator 40/100, Train metric: 4.9683
Estimator 41/100, Train metric: 4.9108
Estimator 42/100, Train metric: 4.8595
Estimator 43/100, Train metric: 4.8231
Estimator 44/100, Train metric: 4.7839
Estimator 45/100, Train metric: 4.7300
Estimator 46/100, Train metric: 4.6969
Estimator 47/100, Train metric: 4.6519
Estimator 48/100, Train metric: 4.6002
Estimator 49/100, Train metric: 4.5647
Estimator 50/100, Train metric: 4.5165
Estimator 51/100, Train metric: 4.4668
Estimator 52/100, Train metric: 4.4236
Estimator 53/100, Train metric: 4.3797
Estimator 54/100, Train metric: 4.3336
Estimator 55/100, Train metric: 4.2998
Estimator 56/100, Train metric: 4.2618
Estimator 57/100, Train metric: 4.2291
Estimator 58/100, Train metric: 4.1915
Estimator 59/100, Train metric: 4.1597
Estimator 60/100, Train metric: 4.1333
Estimator 61/100, Train metric: 4.1040
Estimator 62/100, Train metric: 4.0778
Estimator 63/100, Train metric: 4.0414
Estimator 64/100, Train metric: 4.0079
Estimator 65/100, Train metric: 3.9840
Estimator 66/100, Train metric: 3.9530
Estimator 67/100, Train metric: 3.9166
Estimator 68/100, Train metric: 3.8900
Estimator 69/100, Train metric: 3.8595
Estimator 70/100, Train metric: 3.8368
Estimator 71/100, Train metric: 3.8172
Estimator 72/100, Train metric: 3.7962
Estimator 73/100, Train metric: 3.7655
Estimator 74/100, Train metric: 3.7490
Estimator 75/100, Train metric: 3.7220
Estimator 76/100, Train metric: 3.7011
Estimator 77/100, Train metric: 3.6863
Estimator 78/100, Train metric: 3.6621
Estimator 79/100, Train metric: 3.6422
Estimator 80/100, Train metric: 3.6227
Estimator 81/100, Train metric: 3.5998
Estimator 82/100, Train metric: 3.5685
Estimator 83/100, Train metric: 3.5382
Estimator 84/100, Train metric: 3.5203
Estimator 85/100, Train metric: 3.4971
Estimator 86/100, Train metric: 3.4826
Estimator 87/100, Train metric: 3.4634
Estimator 88/100, Train metric: 3.4411
Estimator 89/100, Train metric: 3.4258
Estimator 90/100, Train metric: 3.4068
Estimator 91/100, Train metric: 3.3934
Estimator 92/100, Train metric: 3.3719
Estimator 93/100, Train metric: 3.3550
Estimator 94/100, Train metric: 3.3383
Estimator 95/100, Train metric: 3.3226
Estimator 96/100, Train metric: 3.3090
Estimator 97/100, Train metric: 3.2935
Estimator 98/100, Train metric: 3.2764
Estimator 99/100, Train metric: 3.2560
Training on CPU
Estimator 0/100, Train metric: 9.4881
Estimator 1/100, Train metric: 9.2273
Estimator 2/100, Train metric: 9.0717
Estimator 3/100, Train metric: 8.8289
Estimator 4/100, Train metric: 8.6282
Estimator 5/100, Train metric: 8.4562
Estimator 6/100, Train metric: 8.2823
Estimator 7/100, Train metric: 8.1488
Estimator 8/100, Train metric: 7.9561
Estimator 9/100, Train metric: 7.7757
Estimator 10/100, Train metric: 7.5828
Estimator 11/100, Train metric: 7.4579
Estimator 12/100, Train metric: 7.3515
Estimator 13/100, Train metric: 7.2076
Estimator 14/100, Train metric: 7.0636
Estimator 15/100, Train metric: 6.9836
Estimator 16/100, Train metric: 6.8485
Estimator 17/100, Train metric: 6.7100
Estimator 18/100, Train metric: 6.5854
Estimator 19/100, Train metric: 6.4807
Estimator 20/100, Train metric: 6.3866
Estimator 21/100, Train metric: 6.2955
Estimator 22/100, Train metric: 6.1805
Estimator 23/100, Train metric: 6.0606
Estimator 24/100, Train metric: 5.9631
Estimator 25/100, Train metric: 5.8666
Estimator 26/100, Train metric: 5.8056
Estimator 27/100, Train metric: 5.7259
Estimator 28/100, Train metric: 5.6376
Estimator 29/100, Train metric: 5.5778
Estimator 30/100, Train metric: 5.4842
Estimator 31/100, Train metric: 5.4281
Estimator 32/100, Train metric: 5.3655
Estimator 33/100, Train metric: 5.3132
Estimator 34/100, Train metric: 5.2356
Estimator 35/100, Train metric: 5.1661
Estimator 36/100, Train metric: 5.1045
Estimator 37/100, Train metric: 5.0510
Estimator 38/100, Train metric: 5.0047
Estimator 39/100, Train metric: 4.9425
Estimator 40/100, Train metric: 4.8787
Estimator 41/100, Train metric: 4.8379
Estimator 42/100, Train metric: 4.7804
Estimator 43/100, Train metric: 4.7300
Estimator 44/100, Train metric: 4.6602
Estimator 45/100, Train metric: 4.6032
Estimator 46/100, Train metric: 4.5597
Estimator 47/100, Train metric: 4.5078
Estimator 48/100, Train metric: 4.4760
Estimator 49/100, Train metric: 4.4317
Estimator 50/100, Train metric: 4.3883
Estimator 51/100, Train metric: 4.3547
Estimator 52/100, Train metric: 4.3173
Estimator 53/100, Train metric: 4.2825
Estimator 54/100, Train metric: 4.2499
Estimator 55/100, Train metric: 4.2159
Estimator 56/100, Train metric: 4.1861
Estimator 57/100, Train metric: 4.1533
Estimator 58/100, Train metric: 4.1257
Estimator 59/100, Train metric: 4.1034
Estimator 60/100, Train metric: 4.0683
Estimator 61/100, Train metric: 4.0361
Estimator 62/100, Train metric: 4.0047
Estimator 63/100, Train metric: 3.9758
Estimator 64/100, Train metric: 3.9416
Estimator 65/100, Train metric: 3.9134
Estimator 66/100, Train metric: 3.8890
Estimator 67/100, Train metric: 3.8544
Estimator 68/100, Train metric: 3.8360
Estimator 69/100, Train metric: 3.8079
Estimator 70/100, Train metric: 3.7793
Estimator 71/100, Train metric: 3.7573
Estimator 72/100, Train metric: 3.7354
Estimator 73/100, Train metric: 3.7092
Estimator 74/100, Train metric: 3.6914
Estimator 75/100, Train metric: 3.6727
Estimator 76/100, Train metric: 3.6517
Estimator 77/100, Train metric: 3.6238
Estimator 78/100, Train metric: 3.6091
Estimator 79/100, Train metric: 3.5845
Estimator 80/100, Train metric: 3.5670
Estimator 81/100, Train metric: 3.5554
Estimator 82/100, Train metric: 3.5370
Estimator 83/100, Train metric: 3.5132
Estimator 84/100, Train metric: 3.5004
Estimator 85/100, Train metric: 3.4814
Estimator 86/100, Train metric: 3.4649
Estimator 87/100, Train metric: 3.4523
Estimator 88/100, Train metric: 3.4349
Estimator 89/100, Train metric: 3.4211
Estimator 90/100, Train metric: 3.4064
Estimator 91/100, Train metric: 3.3901
Estimator 92/100, Train metric: 3.3711
Estimator 93/100, Train metric: 3.3565
Estimator 94/100, Train metric: 3.3293
Estimator 95/100, Train metric: 3.3114
Estimator 96/100, Train metric: 3.2925
Estimator 97/100, Train metric: 3.2781
Estimator 98/100, Train metric: 3.2598
Estimator 99/100, Train metric: 3.2509
Training on CPU
Estimator 0/100, Train metric: 9.4698
Estimator 1/100, Train metric: 9.2116
Estimator 2/100, Train metric: 8.9795
Estimator 3/100, Train metric: 8.7399
Estimator 4/100, Train metric: 8.5103
Estimator 5/100, Train metric: 8.2960
Estimator 6/100, Train metric: 8.1737
Estimator 7/100, Train metric: 7.9748
Estimator 8/100, Train metric: 7.8239
Estimator 9/100, Train metric: 7.6609
Estimator 10/100, Train metric: 7.5070
Estimator 11/100, Train metric: 7.3582
Estimator 12/100, Train metric: 7.2362
Estimator 13/100, Train metric: 7.1218
Estimator 14/100, Train metric: 6.9643
Estimator 15/100, Train metric: 6.8269
Estimator 16/100, Train metric: 6.7101
Estimator 17/100, Train metric: 6.6570
Estimator 18/100, Train metric: 6.5435
Estimator 19/100, Train metric: 6.4217
Estimator 20/100, Train metric: 6.3035
Estimator 21/100, Train metric: 6.2001
Estimator 22/100, Train metric: 6.1094
Estimator 23/100, Train metric: 6.0211
Estimator 24/100, Train metric: 5.9433
Estimator 25/100, Train metric: 5.8680
Estimator 26/100, Train metric: 5.7925
Estimator 27/100, Train metric: 5.7110
Estimator 28/100, Train metric: 5.6207
Estimator 29/100, Train metric: 5.5438
Estimator 30/100, Train metric: 5.4512
Estimator 31/100, Train metric: 5.3973
Estimator 32/100, Train metric: 5.3323
Estimator 33/100, Train metric: 5.2832
Estimator 34/100, Train metric: 5.2288
Estimator 35/100, Train metric: 5.1681
Estimator 36/100, Train metric: 5.1269
Estimator 37/100, Train metric: 5.0630
Estimator 38/100, Train metric: 4.9929
Estimator 39/100, Train metric: 4.9351
Estimator 40/100, Train metric: 4.9014
Estimator 41/100, Train metric: 4.8423
Estimator 42/100, Train metric: 4.7908
Estimator 43/100, Train metric: 4.7660
Estimator 44/100, Train metric: 4.7350
Estimator 45/100, Train metric: 4.6874
Estimator 46/100, Train metric: 4.6527
Estimator 47/100, Train metric: 4.6088
Estimator 48/100, Train metric: 4.5708
Estimator 49/100, Train metric: 4.5333
Estimator 50/100, Train metric: 4.4857
Estimator 51/100, Train metric: 4.4548
Estimator 52/100, Train metric: 4.4114
Estimator 53/100, Train metric: 4.3645
Estimator 54/100, Train metric: 4.3285
Estimator 55/100, Train metric: 4.2978
Estimator 56/100, Train metric: 4.2664
Estimator 57/100, Train metric: 4.2333
Estimator 58/100, Train metric: 4.1966
Estimator 59/100, Train metric: 4.1629
Estimator 60/100, Train metric: 4.1441
Estimator 61/100, Train metric: 4.1147
Estimator 62/100, Train metric: 4.0858
Estimator 63/100, Train metric: 4.0572
Estimator 64/100, Train metric: 4.0391
Estimator 65/100, Train metric: 4.0097
Estimator 66/100, Train metric: 3.9850
Estimator 67/100, Train metric: 3.9587
Estimator 68/100, Train metric: 3.9288
Estimator 69/100, Train metric: 3.9075
Estimator 70/100, Train metric: 3.8911
Estimator 71/100, Train metric: 3.8677
Estimator 72/100, Train metric: 3.8406
Estimator 73/100, Train metric: 3.8156
Estimator 74/100, Train metric: 3.7951
Estimator 75/100, Train metric: 3.7820
Estimator 76/100, Train metric: 3.7633
Estimator 77/100, Train metric: 3.7408
Estimator 78/100, Train metric: 3.7266
Estimator 79/100, Train metric: 3.7132
Estimator 80/100, Train metric: 3.6843
Estimator 81/100, Train metric: 3.6573
Estimator 82/100, Train metric: 3.6378
Estimator 83/100, Train metric: 3.6225
Estimator 84/100, Train metric: 3.5984
Estimator 85/100, Train metric: 3.5810
Estimator 86/100, Train metric: 3.5531
Estimator 87/100, Train metric: 3.5326
Estimator 88/100, Train metric: 3.5147
Estimator 89/100, Train metric: 3.4979
Estimator 90/100, Train metric: 3.4813
Estimator 91/100, Train metric: 3.4666
Estimator 92/100, Train metric: 3.4469
Estimator 93/100, Train metric: 3.4298
Estimator 94/100, Train metric: 3.4125
Estimator 95/100, Train metric: 3.3956
Estimator 96/100, Train metric: 3.3808
Estimator 97/100, Train metric: 3.3677
Estimator 98/100, Train metric: 3.3572
Estimator 99/100, Train metric: 3.3382
Training on CPU
Estimator 0/100, Train metric: 9.4736
Estimator 1/100, Train metric: 9.2083
Estimator 2/100, Train metric: 9.0121
Estimator 3/100, Train metric: 8.7928
Estimator 4/100, Train metric: 8.5767
Estimator 5/100, Train metric: 8.3661
Estimator 6/100, Train metric: 8.2010
Estimator 7/100, Train metric: 8.0168
Estimator 8/100, Train metric: 7.8260
Estimator 9/100, Train metric: 7.6905
Estimator 10/100, Train metric: 7.5271
Estimator 11/100, Train metric: 7.4215
Estimator 12/100, Train metric: 7.3274
Estimator 13/100, Train metric: 7.1749
Estimator 14/100, Train metric: 7.0302
Estimator 15/100, Train metric: 6.8759
Estimator 16/100, Train metric: 6.7647
Estimator 17/100, Train metric: 6.6865
Estimator 18/100, Train metric: 6.5615
Estimator 19/100, Train metric: 6.4715
Estimator 20/100, Train metric: 6.3459
Estimator 21/100, Train metric: 6.2679
Estimator 22/100, Train metric: 6.1744
Estimator 23/100, Train metric: 6.0826
Estimator 24/100, Train metric: 5.9893
Estimator 25/100, Train metric: 5.9303
Estimator 26/100, Train metric: 5.8399
Estimator 27/100, Train metric: 5.7467
Estimator 28/100, Train metric: 5.6631
Estimator 29/100, Train metric: 5.5855
Estimator 30/100, Train metric: 5.4998
Estimator 31/100, Train metric: 5.4258
Estimator 32/100, Train metric: 5.3489
Estimator 33/100, Train metric: 5.2833
Estimator 34/100, Train metric: 5.2184
Estimator 35/100, Train metric: 5.1688
Estimator 36/100, Train metric: 5.1222
Estimator 37/100, Train metric: 5.0517
Estimator 38/100, Train metric: 4.9863
Estimator 39/100, Train metric: 4.9173
Estimator 40/100, Train metric: 4.8749
Estimator 41/100, Train metric: 4.8325
Estimator 42/100, Train metric: 4.7722
Estimator 43/100, Train metric: 4.7294
Estimator 44/100, Train metric: 4.6807
Estimator 45/100, Train metric: 4.6391
Estimator 46/100, Train metric: 4.6020
Estimator 47/100, Train metric: 4.5705
Estimator 48/100, Train metric: 4.5434
Estimator 49/100, Train metric: 4.5138
Estimator 50/100, Train metric: 4.4866
Estimator 51/100, Train metric: 4.4456
Estimator 52/100, Train metric: 4.4029
Estimator 53/100, Train metric: 4.3623
Estimator 54/100, Train metric: 4.3239
Estimator 55/100, Train metric: 4.2799
Estimator 56/100, Train metric: 4.2428
Estimator 57/100, Train metric: 4.2046
Estimator 58/100, Train metric: 4.1796
Estimator 59/100, Train metric: 4.1459
Estimator 60/100, Train metric: 4.1124
Estimator 61/100, Train metric: 4.0749
Estimator 62/100, Train metric: 4.0421
Estimator 63/100, Train metric: 4.0100
Estimator 64/100, Train metric: 3.9814
Estimator 65/100, Train metric: 3.9500
Estimator 66/100, Train metric: 3.9231
Estimator 67/100, Train metric: 3.8978
Estimator 68/100, Train metric: 3.8707

In [52]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_COP_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,
    T_burnin=50,
    scale=0.5,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Safe NumPy conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # Train base PGBM model
    # =========================================================
    model = model_class(**model_params)
    model.fit(Xtr, ytr)

    y_pred_test = model.predict(Xte).ravel()
    y_pred_train = model.predict(Xtr).ravel()

    # Absolute residuals (symmetric COP)
    scores_test = np.abs(yte - y_pred_test)
    scores_train = np.abs(ytr - y_pred_train)

    T_test = len(scores_test)

    # =========================================================
    # COP initialization
    # =========================================================
    init_q = np.quantile(scores_train, 1 - alpha)

    qs = np.zeros(T_test)
    qts = np.zeros(T_test)
    integrators = np.zeros(T_test)
    covereds = np.zeros(T_test)

    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # Online COP loop
    # =========================================================
    for t in range(T_test - 1):

        covereds[t] = 1 if qs[t] >= scores_test[t] else 0

        # Standard COP gradient
        grad = alpha if covereds[t] else -(1 - alpha)

        # Distribution-informed (optimistic) gradient
        if t < T_burnin:
            grad_i = 0.0
        else:
            window_s = scores_test[t - T_burnin : t]
            target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= target) - (1 - alpha)

        # Updates
        integrator = -scale * grad_i
        qts[t + 1] = qts[t] - lr * grad
        integrators[t + 1] = lr * integrator
        qs[t + 1] = max(0.0, qts[t + 1] + integrators[t + 1])

    covereds[-1] = 1 if qs[-1] >= scores_test[-1] else 0

    # =========================================================
    # Prediction intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== COP (PGBM) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale,
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score": scores_test,
        "adaptive_q": qs,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Predicted mean")


    ax.set_title(f"COP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("str")
    ax.legend(loc="upper left")

    plt.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary ----
        sheet_name = "COP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1
        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))

    return summary_df

conformal_predictions_COP_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/PGBM.xlsx",
    alpha=0.05,
)

Training on CPU
Estimator 0/100, Train metric: 9.7862
Estimator 1/100, Train metric: 9.5276
Estimator 2/100, Train metric: 9.3246
Estimator 3/100, Train metric: 9.1083
Estimator 4/100, Train metric: 8.9585
Estimator 5/100, Train metric: 8.7616
Estimator 6/100, Train metric: 8.5626
Estimator 7/100, Train metric: 8.3759
Estimator 8/100, Train metric: 8.2146
Estimator 9/100, Train metric: 8.1378
Estimator 10/100, Train metric: 7.9641
Estimator 11/100, Train metric: 7.7932
Estimator 12/100, Train metric: 7.7220
Estimator 13/100, Train metric: 7.5836
Estimator 14/100, Train metric: 7.4620
Estimator 15/100, Train metric: 7.3932
Estimator 16/100, Train metric: 7.2816
Estimator 17/100, Train metric: 7.1584
Estimator 18/100, Train metric: 7.0412
Estimator 19/100, Train metric: 6.9517
Estimator 20/100, Train metric: 6.8483
Estimator 21/100, Train metric: 6.7380
Estimator 22/100, Train metric: 6.6463
Estimator 23/100, Train metric: 6.5593
Estimator 24/100, Train metric: 6.4619
Estimator 25/100, Train metric: 6.4233
Estimator 26/100, Train metric: 6.3270
Estimator 27/100, Train metric: 6.2786
Estimator 28/100, Train metric: 6.2388
Estimator 29/100, Train metric: 6.1978
Estimator 30/100, Train metric: 6.1271
Estimator 31/100, Train metric: 6.0552
Estimator 32/100, Train metric: 6.0042
Estimator 33/100, Train metric: 5.9273
Estimator 34/100, Train metric: 5.8459
Estimator 35/100, Train metric: 5.7792
Estimator 36/100, Train metric: 5.7314
Estimator 37/100, Train metric: 5.6672
Estimator 38/100, Train metric: 5.5995
Estimator 39/100, Train metric: 5.5368
Estimator 40/100, Train metric: 5.5051
Estimator 41/100, Train metric: 5.4403
Estimator 42/100, Train metric: 5.4084
Estimator 43/100, Train metric: 5.3502
Estimator 44/100, Train metric: 5.2955
Estimator 45/100, Train metric: 5.2402
Estimator 46/100, Train metric: 5.1745
Estimator 47/100, Train metric: 5.1452
Estimator 48/100, Train metric: 5.0968
Estimator 49/100, Train metric: 5.0469
Estimator 50/100, Train metric: 5.0007
Estimator 51/100, Train metric: 4.9706
Estimator 52/100, Train metric: 4.9358
Estimator 53/100, Train metric: 4.8900
Estimator 54/100, Train metric: 4.8570
Estimator 55/100, Train metric: 4.8163
Estimator 56/100, Train metric: 4.7776
Estimator 57/100, Train metric: 4.7421
Estimator 58/100, Train metric: 4.7208
Estimator 59/100, Train metric: 4.6840
Estimator 60/100, Train metric: 4.6399
Estimator 61/100, Train metric: 4.5914
Estimator 62/100, Train metric: 4.5582
Estimator 63/100, Train metric: 4.5289
Estimator 64/100, Train metric: 4.5027
Estimator 65/100, Train metric: 4.4780
Estimator 66/100, Train metric: 4.4424
Estimator 67/100, Train metric: 4.4113
Estimator 68/100, Train metric: 4.3781
Estimator 69/100, Train metric: 4.3547
Estimator 70/100, Train metric: 4.3280
Estimator 71/100, Train metric: 4.2929
Estimator 72/100, Train metric: 4.2608
Estimator 73/100, Train metric: 4.2338
Estimator 74/100, Train metric: 4.2093
Estimator 75/100, Train metric: 4.1850
Estimator 76/100, Train metric: 4.1607
Estimator 77/100, Train metric: 4.1346
Estimator 78/100, Train metric: 4.1089
Estimator 79/100, Train metric: 4.0955
Estimator 80/100, Train metric: 4.0738
Estimator 81/100, Train metric: 4.0465
Estimator 82/100, Train metric: 4.0320
Estimator 83/100, Train metric: 4.0088
Estimator 84/100, Train metric: 3.9787
Estimator 85/100, Train metric: 3.9632
Estimator 86/100, Train metric: 3.9442
Estimator 87/100, Train metric: 3.9288
Estimator 88/100, Train metric: 3.9087
Estimator 89/100, Train metric: 3.8956
Estimator 90/100, Train metric: 3.8706
Estimator 91/100, Train metric: 3.8575
Estimator 92/100, Train metric: 3.8428
Estimator 93/100, Train metric: 3.8291
Estimator 94/100, Train metric: 3.8013
Estimator 95/100, Train metric: 3.7802
Estimator 96/100, Train metric: 3.7621
Estimator 97/100, Train metric: 3.7412
Estimator 98/100, Train metric: 3.7262
Estimator 99/100, Train metric: 3.7123

===== COP (PGBM) =====
Coverage : 93.684%
Width    : 15.280
RMSE     : 4.209
Final q  : 7.715

  Strategy  Coverage      Width     RMSE  Alpha    LR  Scale
0      COP  0.936842  15.279692  4.20898   0.05  0.05    0.5

In [53]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_EXTREME_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Train / calibration split
    # --------------------------------------------------------
    X_fit, X_cal, y_fit, y_cal = train_test_split(
        Xtr, ytr, test_size=calib_size, random_state=random_state, shuffle=True
    )

    # --------------------------------------------------------
    # Train model
    # --------------------------------------------------------
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(Xte)
    y_pred_cal = model.predict(X_cal)

    # --------------------------------------------------------
    # Upper-tail nonconformity scores
    # --------------------------------------------------------
    scores = y_cal - y_pred_cal
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few exceedances for EVT fitting.")

    # --------------------------------------------------------
    # Peaks-over-threshold
    # --------------------------------------------------------
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # --------------------------------------------------------
    # Bootstrap EVT quantile
    # --------------------------------------------------------
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        res = np.random.choice(excesses, size=n_exc, replace=True)
        xi, _, sigma = genpareto.fit(res, floc=0)
        q = u + (sigma / xi) * ((n_scores / (n_scores * alpha)) ** xi - 1)
        boot_q.append(q)

    q_extreme = np.quantile(boot_q, 0.95)

    # --------------------------------------------------------
    # FINITE prediction intervals (for plotting & width)
    # --------------------------------------------------------
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # --------------------------------------------------------
    # Metrics (one-sided coverage)
    # --------------------------------------------------------
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(yte <= ymax)
    width = q_extreme

    print(f"\n===== EXTREME CP (PGBM) =====")
    print(f"Coverage     : {coverage*100:.3f}%")
    print(f"Width        : {width:.3f}")
    print(f"RMSE         : {rmse:.3f}")
    print(f"q_extreme    : {q_extreme:.3f}")
    print(f"threshold_u  : {u:.3f}")
    print(f"#Exceedances : {len(scores)}")

    # --------------------------------------------------------
    # Summary table
    # --------------------------------------------------------
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # --------------------------------------------------------
    # Values table
    # --------------------------------------------------------
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (yte <= ymax).astype(int),
        "residual": yte - y_pred_test,
    })

    # --------------------------------------------------------
    # Plot (SAVE ONLY — NO SHOW)
    # --------------------------------------------------------
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme CP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("str")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # --------------------------------------------------------
    # Excel export (append-safe)
    # --------------------------------------------------------
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        # ---- Summary ----
        sheet_name = "EXTREMECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))


conformal_predictions_EXTREME_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/PGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

Training on CPU
Estimator 0/100, Train metric: 8.8046
Estimator 1/100, Train metric: 8.6221
Estimator 2/100, Train metric: 8.4708
Estimator 3/100, Train metric: 8.3151
Estimator 4/100, Train metric: 8.2405
Estimator 5/100, Train metric: 8.0814
Estimator 6/100, Train metric: 8.0219
Estimator 7/100, Train metric: 7.8654
Estimator 8/100, Train metric: 7.7273
Estimator 9/100, Train metric: 7.5952
Estimator 10/100, Train metric: 7.5271
Estimator 11/100, Train metric: 7.4143
Estimator 12/100, Train metric: 7.2975
Estimator 13/100, Train metric: 7.1773
Estimator 14/100, Train metric: 7.0622
Estimator 15/100, Train metric: 7.0025
Estimator 16/100, Train metric: 6.9607
Estimator 17/100, Train metric: 6.8822
Estimator 18/100, Train metric: 6.7686
Estimator 19/100, Train metric: 6.7193
Estimator 20/100, Train metric: 6.6247
Estimator 21/100, Train metric: 6.5395
Estimator 22/100, Train metric: 6.4774
Estimator 23/100, Train metric: 6.4329
Estimator 24/100, Train metric: 6.3622
Estimator 25/100, Train metric: 6.2798
Estimator 26/100, Train metric: 6.1993
Estimator 27/100, Train metric: 6.1064
Estimator 28/100, Train metric: 6.0495
Estimator 29/100, Train metric: 5.9745
Estimator 30/100, Train metric: 5.8951
Estimator 31/100, Train metric: 5.8514
Estimator 32/100, Train metric: 5.8257
Estimator 33/100, Train metric: 5.7905
Estimator 34/100, Train metric: 5.7589
Estimator 35/100, Train metric: 5.6894
Estimator 36/100, Train metric: 5.6526
Estimator 37/100, Train metric: 5.5950
Estimator 38/100, Train metric: 5.5603
Estimator 39/100, Train metric: 5.5361
Estimator 40/100, Train metric: 5.4963
Estimator 41/100, Train metric: 5.4239
Estimator 42/100, Train metric: 5.3667
Estimator 43/100, Train metric: 5.3444
Estimator 44/100, Train metric: 5.2761
Estimator 45/100, Train metric: 5.2298
Estimator 46/100, Train metric: 5.1956
Estimator 47/100, Train metric: 5.1826
Estimator 48/100, Train metric: 5.1424
Estimator 49/100, Train metric: 5.0850
Estimator 50/100, Train metric: 5.0350
Estimator 51/100, Train metric: 5.0007
Estimator 52/100, Train metric: 4.9640
Estimator 53/100, Train metric: 4.9459
Estimator 54/100, Train metric: 4.9155
Estimator 55/100, Train metric: 4.8722
Estimator 56/100, Train metric: 4.8348
Estimator 57/100, Train metric: 4.7879
Estimator 58/100, Train metric: 4.7423
Estimator 59/100, Train metric: 4.7048
Estimator 60/100, Train metric: 4.6708
Estimator 61/100, Train metric: 4.6366
Estimator 62/100, Train metric: 4.6149
Estimator 63/100, Train metric: 4.5769
Estimator 64/100, Train metric: 4.5625
Estimator 65/100, Train metric: 4.5274
Estimator 66/100, Train metric: 4.4836
Estimator 67/100, Train metric: 4.4474
Estimator 68/100, Train metric: 4.4181
Estimator 69/100, Train metric: 4.3965
Estimator 70/100, Train metric: 4.3666
Estimator 71/100, Train metric: 4.3413
Estimator 72/100, Train metric: 4.3228
Estimator 73/100, Train metric: 4.3064
Estimator 74/100, Train metric: 4.2870
Estimator 75/100, Train metric: 4.2709
Estimator 76/100, Train metric: 4.2437
Estimator 77/100, Train metric: 4.2308
Estimator 78/100, Train metric: 4.2057
Estimator 79/100, Train metric: 4.1757
Estimator 80/100, Train metric: 4.1571
Estimator 81/100, Train metric: 4.1314
Estimator 82/100, Train metric: 4.1059
Estimator 83/100, Train metric: 4.0875
Estimator 84/100, Train metric: 4.0706
Estimator 85/100, Train metric: 4.0387
Estimator 86/100, Train metric: 4.0159
Estimator 87/100, Train metric: 3.9985
Estimator 88/100, Train metric: 3.9717
Estimator 89/100, Train metric: 3.9600
Estimator 90/100, Train metric: 3.9460
Estimator 91/100, Train metric: 3.9282
Estimator 92/100, Train metric: 3.9184
Estimator 93/100, Train metric: 3.8963
Estimator 94/100, Train metric: 3.8774
Estimator 95/100, Train metric: 3.8630
Estimator 96/100, Train metric: 3.8462
Estimator 97/100, Train metric: 3.8248
Estimator 98/100, Train metric: 3.8064
Estimator 99/100, Train metric: 3.7926

===== EXTREME CP (PGBM) =====
Coverage     : 100.000%
Width        : 18.780
RMSE         : 5.364
q_extreme    : 18.780
threshold_u  : 16.951
#Exceedances : 32

In [54]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_AlphaNet_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # data conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base PGBM model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    def _safe_predict(m, X):
        p = m.predict(X)
        return p.ravel() if hasattr(p, "ravel") else np.asarray(p).ravel()

    # =========================================================
    # 3. PRECOMPUTE all LOO scores
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(_safe_predict(base_model, loo_X) - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        Dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(Dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")
    scores_calib = np.abs(_safe_predict(base_model, X_calib) - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small; fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = _safe_predict(base_model, Xte)
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("str")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(_ensure_excel_file(excel_file_path))
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet PGBM complete in {_fmt_time(total_time)}")
    return summary_df

In [55]:
conformal_predictions_AlphaNet_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/PGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base PGBM model...
Training on CPU
Estimator 0/100, Train metric: 10.5993
Estimator 1/100, Train metric: 10.4400
Estimator 2/100, Train metric: 10.2223
Estimator 3/100, Train metric: 10.0421
Estimator 4/100, Train metric: 9.8403
Estimator 5/100, Train metric: 9.7243
Estimator 6/100, Train metric: 9.5713
Estimator 7/100, Train metric: 9.4024
Estimator 8/100, Train metric: 9.3277
Estimator 9/100, Train metric: 9.2032
Estimator 10/100, Train metric: 9.0730
Estimator 11/100, Train metric: 8.9191
Estimator 12/100, Train metric: 8.8375
Estimator 13/100, Train metric: 8.7028
Estimator 14/100, Train metric: 8.6195
Estimator 15/100, Train metric: 8.5121
Estimator 16/100, Train metric: 8.3797
Estimator 17/100, Train metric: 8.2778
Estimator 18/100, Train metric: 8.1882
Estimator 19/100, Train metric: 8.1351
Estimator 20/100, Train metric: 8.0403
Estimator 21/100, Train metric: 7.9556
Estimator 22/100, Train metric: 7.8881
Estimator 23/100, Train metric: 7.8054
Estimator 24/100, Train metric: 7.7266
Estimator 25/100, Train metric: 7.6230
Estimator 26/100, Train metric: 7.5826
Estimator 27/100, Train metric: 7.5284
Estimator 28/100, Train metric: 7.4695
Estimator 29/100, Train metric: 7.4050
Estimator 30/100, Train metric: 7.3436
Estimator 31/100, Train metric: 7.3139
Estimator 32/100, Train metric: 7.2404
Estimator 33/100, Train metric: 7.1661
Estimator 34/100, Train metric: 7.1132
Estimator 35/100, Train metric: 7.0628
Estimator 36/100, Train metric: 7.0237
Estimator 37/100, Train metric: 6.9688
Estimator 38/100, Train metric: 6.9288
Estimator 39/100, Train metric: 6.8758
Estimator 40/100, Train metric: 6.8320
Estimator 41/100, Train metric: 6.7884
Estimator 42/100, Train metric: 6.7490
Estimator 43/100, Train metric: 6.7063
Estimator 44/100, Train metric: 6.6716
Estimator 45/100, Train metric: 6.6341
Estimator 46/100, Train metric: 6.6000
Estimator 47/100, Train metric: 6.5408
Estimator 48/100, Train metric: 6.4907
Estimator 49/100, Train metric: 6.4261
Estimator 50/100, Train metric: 6.4041
Estimator 51/100, Train metric: 6.3516
Estimator 52/100, Train metric: 6.3149
Estimator 53/100, Train metric: 6.2660
Estimator 54/100, Train metric: 6.2290
Estimator 55/100, Train metric: 6.2071
Estimator 56/100, Train metric: 6.1885
Estimator 57/100, Train metric: 6.1579
Estimator 58/100, Train metric: 6.1342
Estimator 59/100, Train metric: 6.1005
Estimator 60/100, Train metric: 6.0693
Estimator 61/100, Train metric: 6.0412
Estimator 62/100, Train metric: 5.9900
Estimator 63/100, Train metric: 5.9592
Estimator 64/100, Train metric: 5.9307
Estimator 65/100, Train metric: 5.9108
Estimator 66/100, Train metric: 5.8933
Estimator 67/100, Train metric: 5.8644
Estimator 68/100, Train metric: 5.8486
Estimator 69/100, Train metric: 5.8126
Estimator 70/100, Train metric: 5.7782
Estimator 71/100, Train metric: 5.7435
Estimator 72/100, Train metric: 5.6943
Estimator 73/100, Train metric: 5.6703
Estimator 74/100, Train metric: 5.6353
Estimator 75/100, Train metric: 5.6166
Estimator 76/100, Train metric: 5.5902
Estimator 77/100, Train metric: 5.5608
Estimator 78/100, Train metric: 5.5290
Estimator 79/100, Train metric: 5.5052
Estimator 80/100, Train metric: 5.4774
Estimator 81/100, Train metric: 5.4532
Estimator 82/100, Train metric: 5.4383
Estimator 83/100, Train metric: 5.4236
Estimator 84/100, Train metric: 5.4072
Estimator 85/100, Train metric: 5.3829
Estimator 86/100, Train metric: 5.3657
Estimator 87/100, Train metric: 5.3389
Estimator 88/100, Train metric: 5.3186
Estimator 89/100, Train metric: 5.2941
Estimator 90/100, Train metric: 5.2810
Estimator 91/100, Train metric: 5.2588
Estimator 92/100, Train metric: 5.2403
Estimator 93/100, Train metric: 5.2332
Estimator 94/100, Train metric: 5.2182
Estimator 95/100, Train metric: 5.2020
Estimator 96/100, Train metric: 5.1864
Estimator 97/100, Train metric: 5.1657
Estimator 98/100, Train metric: 5.1375
Estimator 99/100, Train metric: 5.1115
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 35.9744 | Size: 25.1301 | α̃: 0.5422 | ⏱ 0.05s/epoch | ETA: 13s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 29.0410 | Size: 9.0411 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 7s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 29.0410 | Size: 9.0410 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 29.0409 | Size: 9.0410 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 29.0410 | Size: 9.0410 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 29.0409 | Size: 9.0409 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 6s
  ✓ Run 1 complete | Final loss: 29.0409

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 28.9479 | Size: 9.1219 | α̃: 0.9913 | ⏱ 0.07s/epoch | ETA: 6s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 29.0412 | Size: 9.0414 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 6s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 29.0409 | Size: 9.0410 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 29.0408 | Size: 9.0409 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 29.0407 | Size: 9.0408 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 29.0411 | Size: 9.0413 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  ✓ Run 2 complete | Final loss: 29.0411

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 29.0408 | Size: 9.0411 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 29.0110 | Size: 9.0663 | α̃: 0.9972 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 28.9724 | Size: 9.1000 | α̃: 0.9936 | ⏱ 0.04s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 27.1812 | Size: 14.9571 | α̃: 0.6112 | ⏱ 0.04s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 26.9781 | Size: 13.1561 | α̃: 0.6911 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 26.9674 | Size: 13.4443 | α̃: 0.6762 | ⏱ 0.03s/epoch | ETA: 2s
  ✓ Run 3 complete | Final loss: 26.9674

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 28.8670 | Size: 9.2006 | α̃: 0.9833 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 29.0409 | Size: 9.0410 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 29.0412 | Size: 9.0412 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 29.0412 | Size: 9.0412 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 29.0409 | Size: 9.0409 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 29.0411 | Size: 9.0412 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 29.0411
  [Step 4/9] Training done in 8s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (PGBM)
=======================================================
  Learned α̃     : 0.6782
  Half-width (r) : 6.6992
  Coverage       : 83.158%
  Avg Width      : 13.3985
  RMSE           : 5.3553
  Total time     : 9s
    ├─ Precompute: 1s
    └─ Training  : 8s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet PGBM complete in 9s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.831579,13.398486,5.35531,0.05,0.678172,20.0,9.49

# **Conformal Predictions with TabNet**

In [56]:
best_params = get_best_model_params(best_scores_autosampler, 'TabNet')
print(best_params)

{'n_d': 64, 'n_a': 64, 'n_steps': 10, 'gamma': 1.0, 'lambda_sparse': 0.001, 'optimizer_params': {'lr': 0.02}, 'mask_type': 'sparsemax', 'n_shared': 2, 'n_independent': 3, 'scheduler_params': {'step_size': 10, 'gamma': 0.9}, 'scheduler_fn': <class 'torch.optim.lr_scheduler.StepLR'>, 'seed': 42, 'verbose': 0}

In [57]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.mean((y_arr >= int_pred[strat_name][:, 0]) & (y_arr <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.sqrt(mean_squared_error(y_arr, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        y_arr = np.array(y_test)
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_arr[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) &
                                           (y_arr[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan)
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages
class visualize:
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        y_true_np = np.array(y_true).ravel()
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')
        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)],
                 linestyle='--', color='blue', label='Ideal Prediction Line')
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')
        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()
        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]
        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

class TabNetRegressorCP(TabNetRegressor):
    def fit(self, X, y, *args, **kwargs):
        y = np.asarray(y)
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        return super().fit(X, y, *args, **kwargs)

    def predict(self, X, *args, **kwargs):
        return super().predict(X).flatten()

In [58]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_NEXCP_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):
    warnings.filterwarnings("ignore")

    SEED = 123
    rng = np.random.default_rng(SEED)
    np.random.seed(SEED)

    if "verbose" in best_params:
        best_params = dict(best_params)
        best_params.pop("verbose", None)

    model_class = TabNetRegressorCP

    strategies = {
        "NEXCP-Split": "NexCP Split",
        "NEXCP-Full": "NexCP Full",
        "NEXCP-J+aB": "NexCP Jackknife+ aB",
        "NEXCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    y_train_np = np.asarray(y_train).ravel()
    y_test_np = np.asarray(y_test).ravel()

    # =========================
    # NexCP – Split (Weighted)
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    residuals = np.abs(y_train_np - yhat_train)
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NEXCP-Split"] = yhat_test
    int_pred["NEXCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Full
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train_np - yhat_train), 1 - alpha)

    y_pred["NEXCP-Full"] = yhat_test
    int_pred["NEXCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Jackknife+ aB
    # =========================
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train_np[idx])

        yhat_boot_train = model.predict(X_train[idx])
        yhat_test = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train_np[idx] - yhat_boot_train),
            1 - alpha,
        )

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NEXCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # =========================
    # NexCP – CV+
    # =========================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers, uppers, preds = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train_np[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train_np[cal] - y_cal), 1 - alpha)

        yhat_test = model.predict(X_test)

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NEXCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # =========================
    # Metrics
    # =========================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    summary = []

    print("\n===== NEXCP TABNET RESULTS =====")
    for s in strategies:
        cov = coverage(y_test_np, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_test_np, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_test_np, alpha)

        summary.append([strategies[s], cov, wid, rmse, cwc_val])
        print(f"{strategies[s]} | Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================
    # Plot + Excel Export
    # =========================
    if excel_file_path:
        wb = load_workbook(_ensure_excel_file(excel_file_path))

        sheet = "NEXCP_TabNet_Summary"
        base = sheet
        i = 1
        while sheet in wb.sheetnames:
            sheet = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        for s in strategies:
            fig, ax = plt.subplots(figsize=(10, 4))
            idx = np.arange(len(y_test_np))

            ax.scatter(idx, y_test_np, s=10, alpha=0.7, label="True")
            ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1], alpha=0.4)
            ax.plot(idx, y_pred[s], linewidth=1, label="Pred")

            ax.set_title(f"{strategies[s]} ({model_name})")
            ax.legend()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            plt.close(fig)

            img = Image(buf)
            ps = f"NEXCP_TabNet_{s}"
            base = ps
            i = 1
            while ps in wb.sheetnames:
                ps = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(ps)
            ws.add_image(img, "A1")

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))

    return summary_df


conformal_predictions_NEXCP_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/TabNet.xlsx",
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50
)

Streaming output truncated to the last 5000 lines.
epoch 6  | loss: 61.94366|  0:00:00s
epoch 7  | loss: 78.41142|  0:00:00s
epoch 8  | loss: 42.91524|  0:00:00s
epoch 9  | loss: 43.23763|  0:00:00s
epoch 10 | loss: 38.2358 |  0:00:00s
epoch 11 | loss: 44.82186|  0:00:00s
epoch 12 | loss: 29.49792|  0:00:00s
epoch 13 | loss: 36.90619|  0:00:00s
epoch 14 | loss: 51.03562|  0:00:01s
epoch 15 | loss: 30.54856|  0:00:01s
epoch 16 | loss: 32.37353|  0:00:01s
epoch 17 | loss: 28.4866 |  0:00:01s
epoch 18 | loss: 22.69848|  0:00:01s
epoch 19 | loss: 30.04466|  0:00:01s
epoch 20 | loss: 22.2205 |  0:00:01s
epoch 21 | loss: 21.75086|  0:00:01s
epoch 22 | loss: 22.3456 |  0:00:01s
epoch 23 | loss: 18.08376|  0:00:01s
epoch 24 | loss: 18.33099|  0:00:01s
epoch 25 | loss: 17.46242|  0:00:01s
epoch 26 | loss: 15.82227|  0:00:01s
epoch 27 | loss: 17.51656|  0:00:01s
epoch 28 | loss: 16.38688|  0:00:01s
epoch 29 | loss: 14.41595|  0:00:02s
epoch 30 | loss: 13.30899|  0:00:02s
epoch 31 | loss: 16.86388|  0:00:02s
epoch 32 | loss: 15.63855|  0:00:02s
epoch 33 | loss: 14.49632|  0:00:02s
epoch 34 | loss: 12.00366|  0:00:02s
epoch 35 | loss: 11.65994|  0:00:02s
epoch 36 | loss: 13.24413|  0:00:02s
epoch 37 | loss: 12.66937|  0:00:02s
epoch 38 | loss: 12.27749|  0:00:02s
epoch 39 | loss: 13.24773|  0:00:02s
epoch 40 | loss: 11.80192|  0:00:02s
epoch 41 | loss: 11.46354|  0:00:02s
epoch 42 | loss: 10.22689|  0:00:02s
epoch 43 | loss: 11.0231 |  0:00:02s
epoch 44 | loss: 10.15429|  0:00:03s
epoch 45 | loss: 10.09531|  0:00:03s
epoch 46 | loss: 10.5526 |  0:00:03s
epoch 47 | loss: 9.26667 |  0:00:03s
epoch 48 | loss: 11.34163|  0:00:03s
epoch 49 | loss: 10.45659|  0:00:03s
epoch 50 | loss: 11.58844|  0:00:03s
epoch 51 | loss: 12.92277|  0:00:03s
epoch 52 | loss: 10.58424|  0:00:03s
epoch 53 | loss: 9.63959 |  0:00:03s
epoch 54 | loss: 9.94783 |  0:00:03s
epoch 55 | loss: 9.95031 |  0:00:03s
epoch 56 | loss: 11.72883|  0:00:03s
epoch 57 | loss: 10.4049 |  0:00:03s
epoch 58 | loss: 10.68693|  0:00:03s
epoch 59 | loss: 9.63803 |  0:00:04s
epoch 60 | loss: 9.92692 |  0:00:04s
epoch 61 | loss: 9.89617 |  0:00:04s
epoch 62 | loss: 9.65802 |  0:00:04s
epoch 63 | loss: 9.71709 |  0:00:04s
epoch 64 | loss: 11.83783|  0:00:04s
epoch 65 | loss: 11.08485|  0:00:04s
epoch 66 | loss: 13.05621|  0:00:04s
epoch 67 | loss: 9.48911 |  0:00:04s
epoch 68 | loss: 11.01413|  0:00:04s
epoch 69 | loss: 10.56493|  0:00:04s
epoch 70 | loss: 9.00415 |  0:00:04s
epoch 71 | loss: 9.03772 |  0:00:04s
epoch 72 | loss: 9.25902 |  0:00:04s
epoch 73 | loss: 10.42117|  0:00:04s
epoch 74 | loss: 9.72896 |  0:00:04s
epoch 75 | loss: 9.63687 |  0:00:05s
epoch 76 | loss: 11.76482|  0:00:05s
epoch 77 | loss: 10.82516|  0:00:05s
epoch 78 | loss: 8.21734 |  0:00:05s
epoch 79 | loss: 8.81054 |  0:00:05s
epoch 80 | loss: 9.06426 |  0:00:05s
epoch 81 | loss: 8.61905 |  0:00:05s
epoch 82 | loss: 7.42004 |  0:00:05s
epoch 83 | loss: 7.47419 |  0:00:05s
epoch 84 | loss: 7.05188 |  0:00:05s
epoch 85 | loss: 7.92033 |  0:00:05s
epoch 86 | loss: 7.02972 |  0:00:05s
epoch 87 | loss: 6.40226 |  0:00:05s
epoch 88 | loss: 6.04559 |  0:00:05s
epoch 89 | loss: 6.38559 |  0:00:06s
epoch 90 | loss: 6.19843 |  0:00:06s
epoch 91 | loss: 5.70005 |  0:00:06s
epoch 92 | loss: 6.85572 |  0:00:06s
epoch 93 | loss: 6.84935 |  0:00:06s
epoch 94 | loss: 6.4115  |  0:00:06s
epoch 95 | loss: 6.06317 |  0:00:06s
epoch 96 | loss: 6.25823 |  0:00:06s
epoch 97 | loss: 5.12654 |  0:00:06s
epoch 98 | loss: 8.2609  |  0:00:06s
epoch 99 | loss: 11.16509|  0:00:06s
epoch 0  | loss: 1311.68652|  0:00:00s
epoch 1  | loss: 722.64648|  0:00:00s
epoch 2  | loss: 389.75061|  0:00:00s
epoch 3  | loss: 156.24539|  0:00:00s
epoch 4  | loss: 83.08135|  0:00:00s
epoch 5  | loss: 104.14712|  0:00:00s
epoch 6  | loss: 64.06303|  0:00:00s
epoch 7  | loss: 42.94114|  0:00:00s
epoch 8  | loss: 52.34543|  0:00:00s
epoch 9  | loss: 33.47087|  0:00:00s
epoch 10 | loss: 49.11789|  0:00:00s
epoch 11 | loss: 28.21344|  0:00:00s
epoch 12 | loss: 34.02258|  0:00:00s
epoch 13 | loss: 46.33523|  0:00:00s
epoch 14 | loss: 38.83342|  0:00:01s
epoch 15 | loss: 27.21105|  0:00:01s
epoch 16 | loss: 21.24319|  0:00:01s
epoch 17 | loss: 19.86618|  0:00:01s
epoch 18 | loss: 20.07052|  0:00:01s
epoch 19 | loss: 14.04741|  0:00:01s
epoch 20 | loss: 13.30158|  0:00:01s
epoch 21 | loss: 16.16055|  0:00:01s
epoch 22 | loss: 15.43074|  0:00:01s
epoch 23 | loss: 17.6093 |  0:00:01s
epoch 24 | loss: 16.66923|  0:00:01s
epoch 25 | loss: 12.44884|  0:00:01s
epoch 26 | loss: 11.32038|  0:00:01s
epoch 27 | loss: 9.5821  |  0:00:01s
epoch 28 | loss: 19.14485|  0:00:02s
epoch 29 | loss: 24.4922 |  0:00:02s
epoch 30 | loss: 37.65469|  0:00:02s
epoch 31 | loss: 37.14978|  0:00:02s
epoch 32 | loss: 18.38413|  0:00:02s
epoch 33 | loss: 16.27767|  0:00:02s
epoch 34 | loss: 13.76169|  0:00:02s
epoch 35 | loss: 12.62145|  0:00:02s
epoch 36 | loss: 13.57697|  0:00:02s
epoch 37 | loss: 9.65444 |  0:00:02s
epoch 38 | loss: 11.64837|  0:00:02s
epoch 39 | loss: 11.94287|  0:00:03s
epoch 40 | loss: 15.07663|  0:00:03s
epoch 41 | loss: 15.58352|  0:00:03s
epoch 42 | loss: 14.89151|  0:00:03s
epoch 43 | loss: 12.6101 |  0:00:03s
epoch 44 | loss: 10.90626|  0:00:03s
epoch 45 | loss: 10.70026|  0:00:03s
epoch 46 | loss: 10.78204|  0:00:03s
epoch 47 | loss: 12.80003|  0:00:03s
epoch 48 | loss: 8.94268 |  0:00:03s
epoch 49 | loss: 8.9425  |  0:00:03s
epoch 50 | loss: 8.38507 |  0:00:04s
epoch 51 | loss: 7.67255 |  0:00:04s
epoch 52 | loss: 7.34693 |  0:00:04s
epoch 53 | loss: 7.59017 |  0:00:04s
epoch 54 | loss: 7.59159 |  0:00:04s
epoch 55 | loss: 6.81372 |  0:00:04s
epoch 56 | loss: 6.04289 |  0:00:04s
epoch 57 | loss: 5.7571  |  0:00:04s
epoch 58 | loss: 6.135   |  0:00:04s
epoch 59 | loss: 5.72583 |  0:00:04s
epoch 60 | loss: 5.05319 |  0:00:04s
epoch 61 | loss: 5.22713 |  0:00:05s
epoch 62 | loss: 4.78912 |  0:00:05s
epoch 63 | loss: 4.88529 |  0:00:05s
epoch 64 | loss: 4.6364  |  0:00:05s
epoch 65 | loss: 4.88481 |  0:00:05s
epoch 66 | loss: 4.28872 |  0:00:05s
epoch 67 | loss: 4.35217 |  0:00:05s
epoch 68 | loss: 4.01206 |  0:00:05s
epoch 69 | loss: 3.56135 |  0:00:05s
epoch 70 | loss: 3.40528 |  0:00:05s
epoch 71 | loss: 3.07163 |  0:00:05s
epoch 72 | loss: 3.37331 |  0:00:05s
epoch 73 | loss: 2.91743 |  0:00:06s
epoch 74 | loss: 2.88286 |  0:00:06s
epoch 75 | loss: 2.98649 |  0:00:06s
epoch 76 | loss: 2.7952  |  0:00:06s
epoch 77 | loss: 2.63321 |  0:00:06s
epoch 78 | loss: 2.28965 |  0:00:06s
epoch 79 | loss: 2.9764  |  0:00:06s
epoch 80 | loss: 3.22454 |  0:00:06s
epoch 81 | loss: 3.20955 |  0:00:06s
epoch 82 | loss: 3.3766  |  0:00:06s
epoch 83 | loss: 2.31293 |  0:00:06s
epoch 84 | loss: 3.83138 |  0:00:06s
epoch 85 | loss: 3.37475 |  0:00:06s
epoch 86 | loss: 2.63366 |  0:00:06s
epoch 87 | loss: 2.97543 |  0:00:07s
epoch 88 | loss: 1.9844  |  0:00:07s
epoch 89 | loss: 2.1757  |  0:00:07s
epoch 90 | loss: 1.63636 |  0:00:07s
epoch 91 | loss: 2.02971 |  0:00:07s
epoch 92 | loss: 1.33058 |  0:00:07s
epoch 93 | loss: 5.63943 |  0:00:07s
epoch 94 | loss: 4.35739 |  0:00:07s
epoch 95 | loss: 4.47631 |  0:00:07s
epoch 96 | loss: 3.82686 |  0:00:07s
epoch 97 | loss: 2.89756 |  0:00:07s
epoch 98 | loss: 3.10591 |  0:00:07s
epoch 99 | loss: 2.38107 |  0:00:07s
epoch 0  | loss: 1384.19897|  0:00:00s
epoch 1  | loss: 772.59784|  0:00:00s
epoch 2  | loss: 487.65125|  0:00:00s
epoch 3  | loss: 267.41541|  0:00:00s
epoch 4  | loss: 138.90337|  0:00:00s
epoch 5  | loss: 83.20153|  0:00:00s
epoch 6  | loss: 75.77863|  0:00:00s
epoch 7  | loss: 93.8515 |  0:00:00s
epoch 8  | loss: 42.65284|  0:00:00s
epoch 9  | loss: 37.21418|  0:00:00s
epoch 10 | loss: 67.84523|  0:00:00s
epoch 11 | loss: 57.27752|  0:00:00s
epoch 12 | loss: 33.09009|  0:00:00s
epoch 13 | loss: 32.62116|  0:00:00s
epoch 14 | loss: 32.49548|  0:00:01s
epoch 15 | loss: 18.61091|  0:00:01s
epoch 16 | loss: 21.60337|  0:00:01s
epoch 17 | loss: 19.62313|  0:00:01s
epoch 18 | loss: 17.58906|  0:00:01s
epoch 19 | loss: 20.79572|  0:00:01s
epoch 20 | loss: 17.53811|  0:00:01s
epoch 21 | loss: 15.5384 |  0:00:01s
epoch 22 | loss: 16.76625|  0:00:01s
epoch 23 | loss: 17.72132|  0:00:01s
epoch 24 | loss: 21.44712|  0:00:01s
epoch 25 | loss: 26.60438|  0:00:01s
epoch 26 | loss: 25.55361|  0:00:01s
epoch 27 | loss: 20.17512|  0:00:01s
epoch 28 | loss: 15.86672|  0:00:01s
epoch 29 | loss: 15.20068|  0:00:01s
epoch 30 | loss: 13.70582|  0:00:02s
epoch 31 | loss: 15.38457|  0:00:02s
epoch 32 | loss: 10.70219|  0:00:02s
epoch 33 | loss: 15.01421|  0:00:02s
epoch 34 | loss: 19.14396|  0:00:02s
epoch 35 | loss: 15.5456 |  0:00:02s
epoch 36 | loss: 13.77255|  0:00:02s
epoch 37 | loss: 11.37196|  0:00:02s
epoch 38 | loss: 12.68803|  0:00:02s
epoch 39 | loss: 17.00052|  0:00:02s
epoch 40 | loss: 16.59749|  0:00:02s
epoch 41 | loss: 14.75083|  0:00:02s
epoch 42 | loss: 16.77325|  0:00:02s
epoch 43 | loss: 15.18761|  0:00:02s
epoch 44 | loss: 13.63064|  0:00:03s
epoch 45 | loss: 10.99437|  0:00:03s
epoch 46 | loss: 14.65992|  0:00:03s
epoch 47 | loss: 15.27279|  0:00:03s
epoch 48 | loss: 12.46189|  0:00:03s
epoch 49 | loss: 13.95043|  0:00:03s
epoch 50 | loss: 11.7044 |  0:00:03s
epoch 51 | loss: 11.61683|  0:00:03s
epoch 52 | loss: 10.51361|  0:00:03s
epoch 53 | loss: 10.39213|  0:00:03s
epoch 54 | loss: 12.45127|  0:00:03s
epoch 55 | loss: 11.32216|  0:00:03s
epoch 56 | loss: 10.43851|  0:00:03s
epoch 57 | loss: 9.73316 |  0:00:03s
epoch 58 | loss: 9.28382 |  0:00:03s
epoch 59 | loss: 9.36905 |  0:00:04s
epoch 60 | loss: 8.68459 |  0:00:04s
epoch 61 | loss: 9.10067 |  0:00:04s
epoch 62 | loss: 8.18632 |  0:00:04s
epoch 63 | loss: 6.83481 |  0:00:04s
epoch 64 | loss: 6.86936 |  0:00:04s
epoch 65 | loss: 7.41875 |  0:00:04s
epoch 66 | loss: 6.64146 |  0:00:04s
epoch 67 | loss: 7.05068 |  0:00:04s
epoch 68 | loss: 6.85237 |  0:00:04s
epoch 69 | loss: 5.76921 |  0:00:04s
epoch 70 | loss: 5.6848  |  0:00:04s
epoch 71 | loss: 6.67573 |  0:00:04s
epoch 72 | loss: 5.6076  |  0:00:04s
epoch 73 | loss: 7.02248 |  0:00:04s
epoch 74 | loss: 7.55328 |  0:00:05s
epoch 75 | loss: 5.11413 |  0:00:05s
epoch 76 | loss: 5.93259 |  0:00:05s
epoch 77 | loss: 6.53234 |  0:00:05s
epoch 78 | loss: 4.41876 |  0:00:05s
epoch 79 | loss: 5.85422 |  0:00:05s
epoch 80 | loss: 4.89926 |  0:00:05s
epoch 81 | loss: 5.28958 |  0:00:05s
epoch 82 | loss: 5.16392 |  0:00:05s
epoch 83 | loss: 4.47766 |  0:00:05s
epoch 84 | loss: 4.62497 |  0:00:05s
epoch 85 | loss: 4.3244  |  0:00:05s
epoch 86 | loss: 3.99204 |  0:00:05s
epoch 87 | loss: 6.97676 |  0:00:05s
epoch 88 | loss: 7.39874 |  0:00:06s
epoch 89 | loss: 5.2689  |  0:00:06s
epoch 90 | loss: 4.45778 |  0:00:06s
epoch 91 | loss: 5.53683 |  0:00:06s
epoch 92 | loss: 5.07201 |  0:00:06s
epoch 93 | loss: 5.23146 |  0:00:06s
epoch 94 | loss: 4.6764  |  0:00:06s
epoch 95 | loss: 4.08787 |  0:00:06s
epoch 96 | loss: 3.77667 |  0:00:06s
epoch 97 | loss: 3.9351  |  0:00:06s
epoch 98 | loss: 4.78602 |  0:00:06s
epoch 99 | loss: 4.06916 |  0:00:06s
epoch 0  | loss: 1279.41223|  0:00:00s
epoch 1  | loss: 778.63788|  0:00:00s
epoch 2  | loss: 422.85889|  0:00:00s
epoch 3  | loss: 220.09923|  0:00:00s
epoch 4  | loss: 108.73819|  0:00:00s
epoch 5  | loss: 93.82261|  0:00:00s
epoch 6  | loss: 94.47766|  0:00:00s
epoch 7  | loss: 83.80611|  0:00:00s
epoch 8  | loss: 43.54926|  0:00:00s
epoch 9  | loss: 26.66288|  0:00:00s
epoch 10 | loss: 35.49708|  0:00:00s
epoch 11 | loss: 32.96797|  0:00:00s
epoch 12 | loss: 19.56149|  0:00:00s
epoch 13 | loss: 25.12529|  0:00:01s
epoch 14 | loss: 18.37274|  0:00:01s
epoch 15 | loss: 26.02983|  0:00:01s
epoch 16 | loss: 29.87605|  0:00:01s
epoch 17 | loss: 24.46496|  0:00:01s
epoch 18 | loss: 22.59257|  0:00:01s
epoch 19 | loss: 19.37625|  0:00:01s
epoch 20 | loss: 16.65376|  0:00:01s
epoch 21 | loss: 17.80756|  0:00:01s
epoch 22 | loss: 24.75112|  0:00:01s
epoch 23 | loss: 13.90201|  0:00:01s
epoch 24 | loss: 18.91578|  0:00:02s
epoch 25 | loss: 32.3899 |  0:00:02s
epoch 26 | loss: 30.3451 |  0:00:02s
epoch 27 | loss: 18.01196|  0:00:02s
epoch 28 | loss: 14.80646|  0:00:02s
epoch 29 | loss: 22.92182|  0:00:02s
epoch 30 | loss: 25.39841|  0:00:02s
epoch 31 | loss: 18.60072|  0:00:02s
epoch 32 | loss: 11.97134|  0:00:02s
epoch 33 | loss: 18.17066|  0:00:02s
epoch 34 | loss: 16.03302|  0:00:02s
epoch 35 | loss: 19.37843|  0:00:03s
epoch 36 | loss: 13.20501|  0:00:03s
epoch 37 | loss: 14.07665|  0:00:03s
epoch 38 | loss: 12.03758|  0:00:03s
epoch 39 | loss: 16.72037|  0:00:03s
epoch 40 | loss: 13.40378|  0:00:03s
epoch 41 | loss: 10.15486|  0:00:03s
epoch 42 | loss: 9.61679 |  0:00:03s
epoch 43 | loss: 9.47201 |  0:00:03s
epoch 44 | loss: 8.1476  |  0:00:03s
epoch 45 | loss: 8.99575 |  0:00:04s
epoch 46 | loss: 8.42691 |  0:00:04s
epoch 47 | loss: 8.07331 |  0:00:04s
epoch 48 | loss: 8.11007 |  0:00:04s
epoch 49 | loss: 8.88994 |  0:00:04s
epoch 50 | loss: 7.48053 |  0:00:04s
epoch 51 | loss: 5.9756  |  0:00:04s
epoch 52 | loss: 5.94772 |  0:00:04s
epoch 53 | loss: 5.43416 |  0:00:04s
epoch 54 | loss: 4.74484 |  0:00:04s
epoch 55 | loss: 4.86717 |  0:00:04s
epoch 56 | loss: 4.8626  |  0:00:05s
epoch 57 | loss: 4.29148 |  0:00:05s
epoch 58 | loss: 3.88902 |  0:00:05s
epoch 59 | loss: 4.52311 |  0:00:05s
epoch 60 | loss: 4.19465 |  0:00:05s
epoch 61 | loss: 3.86348 |  0:00:05s
epoch 62 | loss: 4.04983 |  0:00:05s
epoch 63 | loss: 3.16677 |  0:00:05s
epoch 64 | loss: 3.1216  |  0:00:05s
epoch 65 | loss: 3.84091 |  0:00:05s
epoch 66 | loss: 3.52258 |  0:00:05s
epoch 67 | loss: 3.61293 |  0:00:05s
epoch 68 | loss: 3.02309 |  0:00:05s
epoch 69 | loss: 3.58567 |  0:00:05s
epoch 70 | loss: 2.92675 |  0:00:05s
epoch 71 | loss: 4.03494 |  0:00:06s
epoch 72 | loss: 4.11382 |  0:00:06s
epoch 73 | loss: 2.17891 |  0:00:06s
epoch 74 | loss: 5.07314 |  0:00:06s
epoch 75 | loss: 6.41037 |  0:00:06s
epoch 76 | loss: 3.99107 |  0:00:06s
epoch 77 | loss: 4.58395 |  0:00:06s
epoch 78 | loss: 3.91677 |  0:00:06s
epoch 79 | loss: 3.56782 |  0:00:06s
epoch 80 | loss: 3.82957 |  0:00:06s
epoch 81 | loss: 4.35647 |  0:00:06s
epoch 82 | loss: 2.81482 |  0:00:06s
epoch 83 | loss: 3.7647  |  0:00:06s
epoch 84 | loss: 3.86522 |  0:00:06s
epoch 85 | loss: 3.0029  |  0:00:06s
epoch 86 | loss: 2.32017 |  0:00:07s
epoch 87 | loss: 2.29796 |  0:00:07s
epoch 88 | loss: 2.81544 |  0:00:07s
epoch 89 | loss: 2.2119  |  0:00:07s
epoch 90 | loss: 2.4843  |  0:00:07s
epoch 91 | loss: 3.26037 |  0:00:07s
epoch 92 | loss: 2.48257 |  0:00:07s
epoch 93 | loss: 2.23655 |  0:00:07s
epoch 94 | loss: 3.16082 |  0:00:07s
epoch 95 | loss: 2.20473 |  0:00:07s
epoch 96 | loss: 2.32303 |  0:00:07s
epoch 97 | loss: 1.95994 |  0:00:07s
epoch 98 | loss: 2.85395 |  0:00:07s
epoch 99 | loss: 2.03451 |  0:00:07s
epoch 0  | loss: 1299.92517|  0:00:00s
epoch 1  | loss: 817.48676|  0:00:00s
epoch 2  | loss: 477.35297|  0:00:00s
epoch 3  | loss: 190.60335|  0:00:00s
epoch 4  | loss: 119.8587|  0:00:00s
epoch 5  | loss: 58.27916|  0:00:00s
epoch 6  | loss: 75.6938 |  0:00:00s
epoch 7  | loss: 88.87155|  0:00:00s
epoch 8  | loss: 32.34822|  0:00:00s
epoch 9  | loss: 44.63344|  0:00:00s
epoch 10 | loss: 48.03196|  0:00:00s
epoch 11 | loss: 28.585  |  0:00:00s
epoch 12 | loss: 30.762  |  0:00:00s
epoch 13 | loss: 19.20514|  0:00:00s
epoch 14 | loss: 22.54976|  0:00:01s
epoch 15 | loss: 24.70875|  0:00:01s
epoch 16 | loss: 13.85385|  0:00:01s
epoch 17 | loss: 15.99946|  0:00:01s
epoch 18 | loss: 15.29957|  0:00:01s
epoch 19 | loss: 20.00269|  0:00:01s
epoch 20 | loss: 16.79977|  0:00:01s
epoch 21 | loss: 13.90395|  0:00:01s
epoch 22 | loss: 24.67917|  0:00:01s
epoch 23 | loss: 29.80195|  0:00:01s
epoch 24 | loss: 18.48637|  0:00:01s
epoch 25 | loss: 11.30957|  0:00:01s
epoch 26 | loss: 15.0903 |  0:00:01s
epoch 27 | loss: 13.11045|  0:00:01s
epoch 28 | loss: 17.45823|  0:00:01s
epoch 29 | loss: 22.71502|  0:00:02s
epoch 30 | loss: 17.48051|  0:00:02s
epoch 31 | loss: 14.07721|  0:00:02s
epoch 32 | loss: 10.89397|  0:00:02s
epoch 33 | loss: 9.08649 |  0:00:02s
epoch 34 | loss: 11.65104|  0:00:02s
epoch 35 | loss: 11.68395|  0:00:02s
epoch 36 | loss: 9.31558 |  0:00:02s
epoch 37 | loss: 8.50462 |  0:00:02s
epoch 38 | loss: 8.38892 |  0:00:02s
epoch 39 | loss: 8.55433 |  0:00:02s
epoch 40 | loss: 14.11642|  0:00:02s
epoch 41 | loss: 10.28608|  0:00:02s
epoch 42 | loss: 7.96199 |  0:00:02s
epoch 43 | loss: 8.2932  |  0:00:02s
epoch 44 | loss: 6.86152 |  0:00:03s
epoch 45 | loss: 6.77779 |  0:00:03s
epoch 46 | loss: 7.56376 |  0:00:03s
epoch 47 | loss: 6.43061 |  0:00:03s
epoch 48 | loss: 6.10084 |  0:00:03s
epoch 49 | loss: 6.55303 |  0:00:03s
epoch 50 | loss: 7.27236 |  0:00:03s
epoch 51 | loss: 6.11314 |  0:00:03s
epoch 52 | loss: 5.49258 |  0:00:03s
epoch 53 | loss: 4.31928 |  0:00:03s
epoch 54 | loss: 5.54025 |  0:00:03s
epoch 55 | loss: 4.83466 |  0:00:03s
epoch 56 | loss: 4.06851 |  0:00:03s
epoch 57 | loss: 4.40405 |  0:00:03s
epoch 58 | loss: 4.85698 |  0:00:03s
epoch 59 | loss: 3.69551 |  0:00:04s
epoch 60 | loss: 4.02045 |  0:00:04s
epoch 61 | loss: 3.43012 |  0:00:04s
epoch 62 | loss: 6.40129 |  0:00:04s
epoch 63 | loss: 6.60955 |  0:00:04s
epoch 64 | loss: 6.66206 |  0:00:04s
epoch 65 | loss: 6.73006 |  0:00:04s
epoch 66 | loss: 6.01843 |  0:00:04s
epoch 67 | loss: 5.14876 |  0:00:04s
epoch 68 | loss: 4.05904 |  0:00:04s
epoch 69 | loss: 3.98534 |  0:00:04s
epoch 70 | loss: 4.72567 |  0:00:04s
epoch 71 | loss: 4.52155 |  0:00:04s
epoch 72 | loss: 3.74637 |  0:00:04s
epoch 73 | loss: 5.04894 |  0:00:05s
epoch 74 | loss: 3.85678 |  0:00:05s
epoch 75 | loss: 4.2295  |  0:00:05s
epoch 76 | loss: 6.21489 |  0:00:05s
epoch 77 | loss: 4.18878 |  0:00:05s
epoch 78 | loss: 7.79253 |  0:00:05s
epoch 79 | loss: 5.41167 |  0:00:05s
epoch 80 | loss: 5.29333 |  0:00:05s
epoch 81 | loss: 4.64601 |  0:00:05s
epoch 82 | loss: 4.39423 |  0:00:05s
epoch 83 | loss: 4.01245 |  0:00:05s
epoch 84 | loss: 3.82992 |  0:00:05s
epoch 85 | loss: 4.04573 |  0:00:05s
epoch 86 | loss: 4.02883 |  0:00:05s
epoch 87 | loss: 3.9193  |  0:00:05s
epoch 88 | loss: 3.72143 |  0:00:05s
epoch 89 | loss: 2.74482 |  0:00:06s
epoch 90 | loss: 3.93196 |  0:00:06s
epoch 91 | loss: 3.82291 |  0:00:06s
epoch 92 | loss: 3.2395  |  0:00:06s
epoch 93 | loss: 3.43338 |  0:00:06s
epoch 94 | loss: 2.91623 |  0:00:06s
epoch 95 | loss: 3.09808 |  0:00:06s
epoch 96 | loss: 2.95348 |  0:00:06s
epoch 97 | loss: 2.53723 |  0:00:06s
epoch 98 | loss: 2.7759  |  0:00:06s
epoch 99 | loss: 2.40395 |  0:00:06s
epoch 0  | loss: 1283.67773|  0:00:00s
epoch 1  | loss: 806.43884|  0:00:00s
epoch 2  | loss: 493.0369|  0:00:00s
epoch 3  | loss: 273.29861|  0:00:00s
epoch 4  | loss: 182.88948|  0:00:00s
epoch 5  | loss: 102.34862|  0:00:00s
epoch 6  | loss: 78.22689|  0:00:00s
epoch 7  | loss: 78.19835|  0:00:00s
epoch 8  | loss: 57.85492|  0:00:00s
epoch 9  | loss: 54.7304 |  0:00:00s
epoch 10 | loss: 75.44983|  0:00:01s
epoch 11 | loss: 38.24383|  0:00:01s
epoch 12 | loss: 29.41724|  0:00:01s
epoch 13 | loss: 43.2492 |  0:00:01s
epoch 14 | loss: 28.2578 |  0:00:01s
epoch 15 | loss: 26.00418|  0:00:01s
epoch 16 | loss: 30.29843|  0:00:01s
epoch 17 | loss: 35.4569 |  0:00:01s
epoch 18 | loss: 22.76829|  0:00:01s
epoch 19 | loss: 17.88168|  0:00:01s
epoch 20 | loss: 16.89661|  0:00:01s
epoch 21 | loss: 22.75349|  0:00:02s
epoch 22 | loss: 21.33752|  0:00:02s
epoch 23 | loss: 17.65223|  0:00:02s
epoch 24 | loss: 38.23634|  0:00:02s
epoch 25 | loss: 26.93644|  0:00:02s
epoch 26 | loss: 32.93941|  0:00:02s
epoch 27 | loss: 21.95239|  0:00:02s
epoch 28 | loss: 23.55681|  0:00:02s
epoch 29 | loss: 17.76752|  0:00:02s
epoch 30 | loss: 15.87113|  0:00:02s
epoch 31 | loss: 12.53422|  0:00:02s
epoch 32 | loss: 11.81432|  0:00:03s
epoch 33 | loss: 9.68539 |  0:00:03s
epoch 34 | loss: 15.92048|  0:00:03s
epoch 35 | loss: 11.17339|  0:00:03s
epoch 36 | loss: 12.87624|  0:00:03s
epoch 37 | loss: 13.99769|  0:00:03s
epoch 38 | loss: 8.99225 |  0:00:03s
epoch 39 | loss: 10.99332|  0:00:03s
epoch 40 | loss: 9.795   |  0:00:03s
epoch 41 | loss: 9.8208  |  0:00:03s
epoch 42 | loss: 8.31778 |  0:00:03s
epoch 43 | loss: 9.3358  |  0:00:03s

              Strategy  Coverage      Width      RMSE        CWC
0          NexCP Split  0.947368  23.860382  6.392841  23.860382
1           NexCP Full  0.947368  24.433651  6.392841  24.433651
2  NexCP Jackknife+ aB  1.000000  55.378075  5.229787  55.378075
3            NexCP CV+  1.000000  26.118694  5.091944  26.118694

In [59]:
y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

conformal_predictions_online_super(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/TabNet.xlsx",
    alpha=0.1,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.947368  24.433651  6.392840  24.433651
1            Online CV+  0.947368  23.653528  6.392840  23.653528
2  Online Jackknife+ aB  1.000000  58.023674  5.718804  58.023674
3                 SAOCP  0.926316  21.782488  6.392840  21.782488
4                SF-OGD  1.000000  45.543749  6.392840  45.543749
5                  FACI  0.863158  19.762112  6.392840  22.466401
6            MFCS Split  0.947368  24.433651  6.392840  24.433651
7             MFCS Full  0.863158  18.091464  6.324356  20.567138

               Strategy  Coverage      Width      RMSE        CWC
0          Online Split  0.947368  24.433651  6.392840  24.433651
1            Online CV+  0.947368  23.653528  6.392840  23.653528
2  Online Jackknife+ aB  1.000000  58.023674  5.718804  58.023674
3                 SAOCP  0.926316  21.782488  6.392840  21.782488
4                SF-OGD  1.000000  45.543749  6.392840  45.543749
5                  FACI  0.863158  19.762112  6.392840  22.466401
6            MFCS Split  0.947368  24.433651  6.392840  24.433651
7             MFCS Full  0.863158  18.091464  6.324356  20.567138

In [60]:
conformal_predictions_COP(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/TabNet.xlsx",
    alpha=0.1,
    lr=0.05,
    T_burnin=50,
    scale=0.5
)

===== CONFORMAL OPTIMISTIC PREDICTION (TabNet) =====
Coverage : 94.737%
Avg Width: 24.240
RMSE     : 6.393
Final q  : 11.996

  Strategy  Coverage      Width      RMSE  Alpha    LR  Scale
0      COP  0.947368  24.240419  6.392841    0.1  0.05    0.5

In [61]:
conformal_predictions_EXTREME(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/TabNet.xlsx",
    alpha=0.05,
    calib_size=0.4,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30
)

===== EXTREME CONFORMAL PREDICTION (TabNet) =====
Coverage : 98.947%
Width    : 23.195
RMSE     : 7.788
q_extreme: 23.195
u        : 15.745
#Exceed. : 38

In [62]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def conformal_predictions_AlphaNet_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet — TabNet-specific variant.

    Handles:
    - TabNetRegressorCP wrapper (y reshape, predict flatten)
    - Removes 'verbose' from best_params if present
    - Precomputed LOO scores for speed
    - Progress tracking with tqdm + ETA
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # TabNet-specific: clean params & set model class
    # =========================================================
    tabnet_params = dict(best_params)
    tabnet_params.pop("verbose", None)           # TabNet doesn't use verbose here
    model_class = TabNetRegressorCP

    # =========================================================
    # data conversion
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    # alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base TabNet model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**tabnet_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =========================================================
    # 3. PRECOMPUTE all LOO scores (KEY SPEEDUP)
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = (
        tqdm(range(n_calib), desc="    LOO precompute", leave=False)
        if HAS_TQDM else range(n_calib)
    )

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        preds_loo = base_model.predict(loo_X).ravel()
        scores_loo = np.abs(preds_loo - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet (multiple runs, keep best)
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        Dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(Dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores — no predict() call here
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")

    calib_preds = base_model.predict(X_calib).ravel()
    scores_calib = np.abs(calib_preds - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(Xte).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    # --- Prediction-interval plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("str")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training-curves plot ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export (append-safe)
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(_ensure_excel_file(excel_file_path))
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        # ---- Summary ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- PI Plot ----
        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        # ---- Training Curves Plot ----
        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        # ---- Values ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        _ensure_parent_dir(excel_file_path)
        wb.save(_ensure_parent_dir(excel_file_path))
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet TabNet complete in {_fmt_time(total_time)}")
    return summary_df

In [63]:
conformal_predictions_AlphaNet_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/streamflow_uncertainty_analysis/conformal_predictions_nexcp_adaptivecp_mfcs/TabNet.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base TabNet model...
epoch 0  | loss: 1353.26331|  0:00:00s
epoch 1  | loss: 769.82202|  0:00:00s
epoch 2  | loss: 468.79492|  0:00:00s
epoch 3  | loss: 241.74883|  0:00:00s
epoch 4  | loss: 108.64077|  0:00:00s
epoch 5  | loss: 60.82613|  0:00:00s
epoch 6  | loss: 71.73137|  0:00:00s
epoch 7  | loss: 44.77955|  0:00:00s
epoch 8  | loss: 43.27402|  0:00:00s
epoch 9  | loss: 59.04054|  0:00:00s
epoch 10 | loss: 32.75611|  0:00:00s
epoch 11 | loss: 28.35504|  0:00:00s
epoch 12 | loss: 23.52588|  0:00:00s
epoch 13 | loss: 16.66097|  0:00:00s
epoch 14 | loss: 32.95393|  0:00:01s
epoch 15 | loss: 59.57652|  0:00:01s
epoch 16 | loss: 22.54505|  0:00:01s
epoch 17 | loss: 20.81719|  0:00:01s
epoch 18 | loss: 15.90426|  0:00:01s
epoch 19 | loss: 20.61304|  0:00:01s
epoch 20 | loss: 17.04655|  0:00:01s
epoch 21 | loss: 17.96544|  0:00:01s
epoch 22 | loss: 24.18632|  0:00:01s
epoch 23 | loss: 14.162  |  0:00:01s
epoch 24 | loss: 14.68985|  0:00:01s
epoch 25 | loss: 17.97585|  0:00:01s
epoch 26 | loss: 10.96784|  0:00:01s
epoch 27 | loss: 10.12253|  0:00:01s
epoch 28 | loss: 11.09955|  0:00:01s
epoch 29 | loss: 9.68584 |  0:00:02s
epoch 30 | loss: 8.57737 |  0:00:02s
epoch 31 | loss: 9.48191 |  0:00:02s
epoch 32 | loss: 9.43899 |  0:00:02s
epoch 33 | loss: 8.30807 |  0:00:02s
epoch 34 | loss: 8.54661 |  0:00:02s
epoch 35 | loss: 7.62673 |  0:00:02s
epoch 36 | loss: 7.27039 |  0:00:02s
epoch 37 | loss: 7.97308 |  0:00:02s
epoch 38 | loss: 8.17105 |  0:00:02s
epoch 39 | loss: 7.22247 |  0:00:02s
epoch 40 | loss: 8.2853  |  0:00:02s
epoch 41 | loss: 8.4929  |  0:00:02s
epoch 42 | loss: 7.25802 |  0:00:02s
epoch 43 | loss: 7.89562 |  0:00:02s
epoch 44 | loss: 8.06159 |  0:00:03s
epoch 45 | loss: 8.44318 |  0:00:03s
epoch 46 | loss: 8.80531 |  0:00:03s
epoch 47 | loss: 7.21839 |  0:00:03s
epoch 48 | loss: 6.50377 |  0:00:03s
epoch 49 | loss: 5.39597 |  0:00:03s
epoch 50 | loss: 6.41251 |  0:00:03s
epoch 51 | loss: 5.98348 |  0:00:03s
epoch 52 | loss: 5.2659  |  0:00:03s
epoch 53 | loss: 5.05534 |  0:00:03s
epoch 54 | loss: 4.79619 |  0:00:03s
epoch 55 | loss: 4.57346 |  0:00:03s
epoch 56 | loss: 4.10725 |  0:00:03s
epoch 57 | loss: 5.33731 |  0:00:03s
epoch 58 | loss: 4.43223 |  0:00:03s
epoch 59 | loss: 4.94041 |  0:00:04s
epoch 60 | loss: 4.50106 |  0:00:04s
epoch 61 | loss: 5.01004 |  0:00:04s
epoch 62 | loss: 6.06361 |  0:00:04s
epoch 63 | loss: 4.48192 |  0:00:04s
epoch 64 | loss: 3.98493 |  0:00:04s
epoch 65 | loss: 5.26691 |  0:00:04s
epoch 66 | loss: 6.4755  |  0:00:04s
epoch 67 | loss: 5.74454 |  0:00:04s
epoch 68 | loss: 6.24562 |  0:00:04s
epoch 69 | loss: 10.60266|  0:00:04s
epoch 70 | loss: 6.89506 |  0:00:04s
epoch 71 | loss: 4.98645 |  0:00:04s
epoch 72 | loss: 4.84595 |  0:00:04s
epoch 73 | loss: 5.37763 |  0:00:04s
epoch 74 | loss: 4.56164 |  0:00:05s
epoch 75 | loss: 4.87294 |  0:00:05s
epoch 76 | loss: 4.26031 |  0:00:05s
epoch 77 | loss: 4.02784 |  0:00:05s
epoch 78 | loss: 3.71696 |  0:00:05s
epoch 79 | loss: 3.60525 |  0:00:05s
epoch 80 | loss: 3.12521 |  0:00:05s
epoch 81 | loss: 2.95101 |  0:00:05s
epoch 82 | loss: 2.88792 |  0:00:05s
epoch 83 | loss: 2.80807 |  0:00:05s
epoch 84 | loss: 3.02494 |  0:00:05s
epoch 85 | loss: 2.9674  |  0:00:05s
epoch 86 | loss: 2.91396 |  0:00:05s
epoch 87 | loss: 3.02897 |  0:00:05s
epoch 88 | loss: 2.56939 |  0:00:05s
epoch 89 | loss: 3.06091 |  0:00:06s
epoch 90 | loss: 3.59384 |  0:00:06s
epoch 91 | loss: 2.84968 |  0:00:06s
epoch 92 | loss: 2.67226 |  0:00:06s
epoch 93 | loss: 2.78027 |  0:00:06s
epoch 94 | loss: 2.89276 |  0:00:06s
epoch 95 | loss: 2.41492 |  0:00:06s
epoch 96 | loss: 2.04671 |  0:00:06s
epoch 97 | loss: 2.28911 |  0:00:06s
epoch 98 | loss: 2.88706 |  0:00:06s
epoch 99 | loss: 3.21864 |  0:00:06s
  [Step 2/9] Done in 7s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 3s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 67.5930 | Size: 53.4830 | α̃: 0.7055 | ⏱ 0.06s/epoch | ETA: 15s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 37.0421 | Size: 17.0421 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 37.0428 | Size: 17.0428 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 9s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 37.0414 | Size: 17.0414 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 8s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 37.0416 | Size: 17.0416 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 8s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 37.0422 | Size: 17.0422 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 7s
  ✓ Run 1 complete | Final loss: 37.0422

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 37.0068 | Size: 17.4295 | α̃: 0.9789 | ⏱ 0.07s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 37.0428 | Size: 17.0428 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 37.0420 | Size: 17.0420 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 6s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 37.0413 | Size: 17.0413 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 37.0417 | Size: 17.0417 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 5s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 37.0424 | Size: 17.0424 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 4s
  ✓ Run 2 complete | Final loss: 37.0424

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 37.0418 | Size: 17.0418 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 37.0424 | Size: 17.0424 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 37.0425 | Size: 17.0425 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 37.0426 | Size: 17.0426 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 37.0427 | Size: 17.0427 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 37.0421 | Size: 17.0421 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  ✓ Run 3 complete | Final loss: 37.0421

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 37.1101 | Size: 18.3507 | α̃: 0.9380 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 37.0418 | Size: 17.0418 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 37.0423 | Size: 17.0423 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 37.0425 | Size: 17.0425 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 37.0416 | Size: 17.0416 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 37.0423 | Size: 17.0423 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 37.0423
  [Step 4/9] Training done in 8s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (TabNet)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 8.5211
  Coverage       : 69.474%
  Avg Width      : 17.0422
  RMSE           : 10.5804
  Total time     : 18s
    ├─ Precompute: 3s
    └─ Training  : 8s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet TabNet complete in 18s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.694737,17.042221,10.580379,0.05,1.0,20.0,18.05