# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install git+https://github.com/DaneshSelwal/treeffuser.git

Collecting git+https://github.com/DaneshSelwal/treeffuser.git
  Cloning https://github.com/DaneshSelwal/treeffuser.git to /tmp/pip-req-build-twp4u4jl
  Running command git clone --filter=blob:none --quiet https://github.com/DaneshSelwal/treeffuser.git /tmp/pip-req-build-twp4u4jl
  Resolved https://github.com/DaneshSelwal/treeffuser.git to commit 9717581990db9e7dedaa8c593ec724997e52bdb8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: einops<0.9.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.8.2)
Collecting jaxtyping<0.3.0,>=0.2.19 (from treeffuser==0.1.3)
  Downloading jaxtyping-0.2.38-py3-none-any.whl.metadata (6.6 kB)
Collecting lightgbm==4.3.0 (from treeffuser==0.1.3)
  Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting ml-collections<0.2.0,>=0.1.1 (from treeffuser==0.1.3)
  Downloading ml_collections-0.1.1.tar.gz (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy<2.0,>=1.24 (from treeffuser==0.1.3)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.9 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (2.2.2)
Collecting scikit-learn==1.5.0 (from treeffuser==0.1.3)
  Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy<2.0,>=1.13 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (1.16.3)
Requirement already satisfied: tqdm<5.0.0,>=4.66.4 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (3.6.0)
Collecting wadler-lindig>=0.1.3 (from jaxtyping<0.3.0,>=0.2.19->treeffuser==0.1.3)
  Downloading wadler_lindig-0.1.7-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (6.0.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.17.0)
Collecting contextlib2 (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3)
  Downloading contextlib2-21.6.0-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2026.1)
Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 56.4 MB/s eta 0:00:00
Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 88.5 MB/s eta 0:00:00
Downloading jaxtyping-0.2.38-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 4.5 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 82.1 MB/s eta 0:00:00
Downloading wadler_lindig-0.1.7-py3-none-any.whl (20 kB)
Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Building wheels for collected packages: treeffuser, ml-collections
  Building wheel for treeffuser (pyproject.toml) ... done
  Created wheel for treeffuser: filename=treeffuser-0.1.3-py3-none-any.whl size=27752 sha256=bbd69aae1e7b4f3e34763d597e0b56622df8d79b3097ee5326cb1e1f1d3f0869
  Stored in directory: /tmp/pip-ephem-wheel-cache-wrv4sbgh/wheels/5f/d1/1a/e628d7eb76d35fc5915026a0d96591b38160a883cc5a7d2116
  Building wheel for ml-collections (setup.py) ... done
  Created wheel for ml-collections: filename=ml_collections-0.1.1-py3-none-any.whl size=94507 sha256=db6a18b1b933f1f2361c5a74ac356637b18ff714d6b72d37deff8861aa991566
  Stored in directory: /root/.cache/pip/wheels/3e/53/7b/1a6f4bfa9dac09618feedc8b1f28a55d4ab9d4bb8835dc0b7e
Successfully built treeffuser ml-collections
Installing collected packages: wadler-lindig, numpy, contextlib2, ml-collections, jaxtyping, scikit-learn, lightgbm, treeffuser
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 4.6.0
    Uninstalling lightgbm-4.6.0:
      Successfully uninstalled lightgbm-4.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
Successfully installed contextlib2-21.6.0 jaxtyping-0.2.38 lightgbm-4.3.0 ml-collections-0.1.1 numpy-1.26.4 scikit-learn-1.5.0 treeffuser-0.1.3 wadler-lindig-0.1.7

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-Datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, which is not installed.
cufflinks 0.17.3 requires plotly>=4.1.1, which is not installed.
imbalanced-learn 0.14.1 requires scikit-learn<2,>=1.4.2, which is not installed.
libpysal 4.14.1 requires scikit-learn>=1.4.0, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
geemap 0.37.2 requires plotly, which is not installed.
esda 2.9.0 requires scikit-learn>=1.4, which is not installed.
mapclassify 2.10.0 requires scikit-learn>=1.4, which is not installed.
keras-hub 0.26.0 requires tensorflow-text; platform_system != "Windows", which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow>=2.2.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow-probability>=0.13.0, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
accelerate 1.13.0 requires torch>=2.0.0, which is not installed.
cuml-cu12 26.2.0 requires scikit-learn>=1.5, which is not installed.
sentence-transformers 5.4.1 requires scikit-learn>=0.22.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
peft 0.19.1 requires torch>=1.13.0, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
spreg 1.9.0 requires scikit-learn>=0.22, which is not installed.
umap-learn 0.5.12 requires scikit-learn>=1.6, which is not installed.
hdbscan 0.8.42 requires scikit-learn>=1.6, which is not installed.
pysal 25.7 requires scikit-learn>=1.1, which is not installed.
spopt 0.7.0 requires scikit-learn>=1.4.0, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
segregation 2.5.4 requires scikit-learn>=0.21.3, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
ydf-tf 2.20.0 requires tensorflow==2.20.0, which is not installed.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 105.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 6.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
timm 1.0.26 requires torchvision, which is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 53.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, but you have lightgbm 4.6.0 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 101.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 41.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 14.0 MB/s eta 0:00:00
  Building wheel for autograd-gamma (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 26.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 20.1 MB/s eta 0:00:00
  Building wheel for pgbm (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.7/449.7 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 52.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 23.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for shap (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.0/244.0 kB 25.5 MB/s eta 0:00:00
  Building wheel for lime (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 62.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 81.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 93.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 103.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 90.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 778.9/778.9 kB 52.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 92.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 23.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 28.1 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 14.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
distributed 2026.1.1 requires dask<2026.1.2,>=2026.1.1, but you have dask 2025.12.0 which is incompatible.
rapids-dask-dependency 26.2.0 requires dask==2026.1.1, but you have dask 2025.12.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 52.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 97.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for cp (setup.py) ... done

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ngboost
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from pathlib import Path
from scipy.stats import norm, kstest
from pytorch_tabnet import TabNetRegressor
from treeffuser import Treeffuser, Samples
from treeffuser._score_models import TreeBasedScoreModel

In [2]:
# Go to find & replace button and replace (streamflow_uncertainty_analysis) with your folder name. Rename your train and test Dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (str) with actual data label name.

In [3]:
feature_names = ['pH', 'Salinity', 'Turbidity ', 'Water Temperature']

In [4]:
train_data_path = "./drive/MyDrive/streamflow_uncertainty_analysis/data/train.csv"
test_data_path = "./drive/MyDrive/streamflow_uncertainty_analysis/data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (189, 8)
First 5 rows of training data:
         C    mp     FA      CA       F       W_P    Adm    str
0  280.80  70.2  858.0  1183.0    0.00  0.450000  0.610  21.56
1  372.15   0.0  975.0   525.0   52.85  0.493081  7.000  34.00
2  360.00  75.0  975.0   525.0   40.00  0.509722  7.000  28.00
3  364.30   0.0  975.0   525.0  110.40  0.503706  7.000  42.00
4  315.00  31.5  780.0  1110.0    0.00  0.370000  5.355  25.82

Shape of test data: (95, 8)
First 5 rows of test data:
         C     mp     FA     CA      F       W_P   Adm   str
0  364.30    0.0  975.0  525.0  60.40  0.503706   7.0  34.0
1  344.30   75.0  975.0  525.0  55.40  0.532965   7.0  36.0
2  390.00    0.0  975.0  525.0  60.00  0.470513   7.0  36.0
3  352.15   75.0  975.0  525.0  47.85  0.521085   7.0  35.0
4  400.00  160.0  801.0  801.0  40.00  0.300000  10.3  44.6

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (189, 7)
Shape of y_train: (189,)
Shape of X_test: (95, 7)
Shape of y_test: (95,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[-1.56879184  0.95792014 -0.09685034  1.33138508 -0.85369002  0.16810471
  -0.08799752]
 [ 0.40300047 -0.7708921   0.73537613 -0.93459372  0.061075    0.78285857
  -0.0664621 ]
 [ 0.14074238  1.07612953  0.73537613 -0.93459372 -0.16134185  1.020321
  -0.0664621 ]
 [ 0.233558   -0.7708921   0.73537613 -0.93459372  1.05719093  0.93447436
  -0.0664621 ]
 [-0.83058388  0.00485698 -0.65166799  1.07999229 -0.85369002 -0.97347298
  -0.07200604]]

First five rows of normalized X_test:
[[ 0.233558   -0.7708921   0.73537613 -0.93459372  0.19175572  0.93447436
  -0.0664621 ]
 [-0.19814256  1.07612953  0.73537613 -0.93459372  0.1052122   1.35199213
  -0.0664621 ]
 [ 0.78829322 -0.7708921   0.73537613 -0.93459372  0.18483223  0.4608195
  -0.0664621 ]
 [-0.02870009  1.07612953  0.73537613 -0.93459372 -0.02546852  1.18246784
  -0.0664621 ]
 [ 1.0041435   3.1694207  -0.50229401  0.01587763 -0.16134185 -1.97235346
  -0.05534052]]

# **Functions:**

In [8]:
# Define the model classes
model_classes = {
    'Random Forest': RandomForestRegressor,
    'Gradient Boosting': GradientBoostingRegressor,
    'XGBoost': XGBRegressor,
    'LightGBM': LGBMRegressor,
    'GPBoost': GPBoostRegressor,
    'CatBoost': CatBoostRegressor,
    'HistGradientBoosting': HistGradientBoostingRegressor,
    'TabNet': TabNetRegressor,
    'NGBoost': NGBRegressor
}

def _ensure_excel_file(path):
    import os
    import pandas as pd
    if not os.path.exists(path):
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        pd.DataFrame().to_excel(path)
    return path

In [9]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [10]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_plots(predictions_df, y_test, excel_path):
    # 1. Predicted vs. Actual Plot
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x='Actual', y='Mean', data=predictions_df)
    plt.plot([predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             [predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             color='red', linestyle='--')
    plt.title('Predicted str vs. Actual str')
    plt.xlabel('Actual str')
    plt.ylabel('Predicted Mean str')
    plt.tight_layout()
    predicted_vs_actual_path = 'predicted_vs_actual.png'
    _ensure_parent_dir(predicted_vs_actual_path)
    plt.savefig(_ensure_parent_dir(predicted_vs_actual_path))
    plt.close()

    # 2. Uncertainty Bands
    plt.figure(figsize=(12, 8))
    plt.errorbar(x=range(len(predictions_df)), y=predictions_df['Mean'],
                 yerr=predictions_df['StdDev'], fmt='o', markersize=4, ecolor='red', elinewidth=1, capsize=5, alpha=0.7)
    plt.plot(range(len(predictions_df)), predictions_df['Mean'], color='black', linewidth=0.5, alpha=0.7)
    plt.title('Predicted Mean with Uncertainty Bands', fontsize=16)
    plt.xlabel('Sample Number', fontsize=14)
    plt.ylabel('Predicted Mean str')
    plt.tight_layout()
    uncertainty_bands_path = 'uncertainty_bands.png'
    _ensure_parent_dir(uncertainty_bands_path)
    plt.savefig(_ensure_parent_dir(uncertainty_bands_path))
    plt.close()

    # 3. Histogram of Standard Deviations
    plt.figure(figsize=(12, 8))
    sns.histplot(predictions_df['StdDev'], bins=20, kde=True)
    plt.title('Distribution of Predicted Standard Deviations')
    plt.xlabel('Standard Deviation')
    plt.ylabel('Frequency')
    plt.tight_layout()
    histogram_stddev_path = 'histogram_stddev.png'
    _ensure_parent_dir(histogram_stddev_path)
    plt.savefig(_ensure_parent_dir(histogram_stddev_path))
    plt.close()

    # 4. Residual Plot
    residuals = predictions_df['Actual'] - predictions_df['Mean']
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x=predictions_df['Mean'], y=residuals)
    plt.axhline(0, color='red', linestyle='--')
    plt.title('Residual Plot')
    plt.xlabel('Predicted Mean str')
    plt.ylabel('Residuals')
    plt.tight_layout()
    residual_plot_path = 'residual_plot.png'
    _ensure_parent_dir(residual_plot_path)
    plt.savefig(_ensure_parent_dir(residual_plot_path))
    plt.close()

    # Plot the standard deviation of the predictions
    plt.figure(figsize=(12, 6))
    plt.plot(
        predictions_df['StdDev'],
        label='Standard Deviation',
        color='green',
        marker='o',
        linestyle='dashed'
    )
    plt.xlabel('Sample Number')
    plt.ylabel('Standard Deviation')
    plt.title('Standard Deviation of Predictions')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    stddev_plot_path = 'stddev_plot.png'
    _ensure_parent_dir(stddev_plot_path)
    plt.savefig(_ensure_parent_dir(stddev_plot_path))
    plt.close()

    # Plot the actual vs predicted mean with confidence intervals
    plt.figure(figsize=(12, 6))
    plt.plot(
        y_test,
        label='Actual str',
        color='black',
        marker='o',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    plt.plot(
        predictions_df['Mean'],
        label='Predicted Mean str',
        color='red',
        marker='x',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    confidence_interval = 1.96 * predictions_df['StdDev']
    plt.fill_between(
        np.arange(len(predictions_df)),
        predictions_df['Mean'] - confidence_interval,
        predictions_df['Mean'] + confidence_interval,
        color='blue',
        alpha=0.2,
        label='95% Confidence Interval'
    )
    plt.xlabel('Sample Number')
    plt.ylabel(' str')
    plt.title('Predictions with Confidence Intervals')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    prediction_plot_path = 'prediction_plot.png'
    _ensure_parent_dir(prediction_plot_path)
    plt.savefig(_ensure_parent_dir(prediction_plot_path))
    plt.close()

    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(_ensure_parent_dir(excel_path), engine='xlsxwriter')

    # Write the dataframe to a worksheet.
    writer
    predictions_df.to_excel(writer, sheet_name='Predictions', index=False)

    # Access the XlsxWriter workbook and worksheet objects from the writer object.
    workbook = writer.book

    # Insert the plots into new worksheets.
    worksheet_predicted_vs_actual = workbook.add_worksheet('Predicted vs Actual')
    worksheet_predicted_vs_actual.insert_image('A1', predicted_vs_actual_path)

    worksheet_uncertainty_bands = workbook.add_worksheet('Uncertainty Bands')
    worksheet_uncertainty_bands.insert_image('A1', uncertainty_bands_path)

    worksheet_histogram_stddev = workbook.add_worksheet('Histogram StdDev')
    worksheet_histogram_stddev.insert_image('A1', histogram_stddev_path)

    worksheet_residual_plot = workbook.add_worksheet('Residual Plot')
    worksheet_residual_plot.insert_image('A1', residual_plot_path)

    worksheet_stddev = workbook.add_worksheet('StdDev Plot')
    worksheet_stddev.insert_image('A1', stddev_plot_path)

    worksheet_prediction = workbook.add_worksheet('Predictions Plot')
    worksheet_prediction.insert_image('A1', prediction_plot_path)

    # Close the Pandas Excel writer and output the Excel file.
    writer.close()
    print(f"Excel file saved at {excel_path}")

    # Optionally, remove the image files now that they're embedded in the Excel file
    if os.path.exists(str(predicted_vs_actual_path)): os.remove(str(predicted_vs_actual_path))
    if os.path.exists(str(uncertainty_bands_path)): os.remove(str(uncertainty_bands_path))
    if os.path.exists(str(histogram_stddev_path)): os.remove(str(histogram_stddev_path))
    if os.path.exists(str(residual_plot_path)): os.remove(str(residual_plot_path))
    if os.path.exists(str(stddev_plot_path)): os.remove(str(stddev_plot_path))
    if os.path.exists(str(prediction_plot_path)): os.remove(str(prediction_plot_path))

In [11]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_crps_decomposition(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    # -------------------------------
    # Total CRPS
    # -------------------------------
    crps_values = ps.crps_gaussian(
        y_true, mu=mu_pred, sig=sigma_pred
    )
    total_crps = np.mean(crps_values)

    # -------------------------------
    # Uncertainty (climatology)
    # -------------------------------
    global_mu = np.mean(y_true)
    global_sigma = np.std(y_true)

    uncertainty = np.mean(
        ps.crps_gaussian(y_true, mu=global_mu, sig=global_sigma)
    )

    # -------------------------------
    # Reliability & Resolution
    # -------------------------------
    sort_idx = np.argsort(mu_pred)
    y_sorted = y_true[sort_idx]
    mu_sorted = mu_pred[sort_idx]
    sigma_sorted = sigma_pred[sort_idx]

    bins = np.array_split(np.arange(len(y_true)), n_bins)

    bin_results = []
    reliability_sum = 0.0

    for i, b in enumerate(bins):
        bin_y = y_sorted[b]
        bin_mu = mu_sorted[b]
        bin_sigma = sigma_sorted[b]

        bin_crps = np.mean(
            ps.crps_gaussian(bin_y, mu=bin_mu, sig=bin_sigma)
        )

        reliability_sum += bin_crps

        bin_results.append({
            "Bin": i + 1,
            "Bin_Size": len(b),
            "Mean_Pred_Mu": np.mean(bin_mu),
            "Mean_Pred_Sigma": np.mean(bin_sigma),
            "Bin_CRPS": bin_crps
        })

    reliability = reliability_sum / n_bins
    resolution = uncertainty - (total_crps - reliability)

    # -------------------------------
    # Summary table
    # -------------------------------
    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Total_CRPS": total_crps,
        "Reliability": reliability,
        "Resolution": resolution,
        "Uncertainty": uncertainty,
        "Num_Bins": n_bins
    }])

    bin_df = pd.DataFrame(bin_results)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_summary = f"CRPS_Summary_{model_name}"
    sheet_bins = f"CRPS_Bins_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)
        writer
        bin_df.to_excel(writer, sheet_name=sheet_bins, index=False)

    print(f"✅ CRPS decomposition saved to:\n{excel_path}")
    print(f"   Sheets: {sheet_summary}, {sheet_bins}")

    return summary_df

In [12]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_pit_results(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):
    """
    Generate PIT values, histogram, calibration diagnostics,
    and save everything to Excel with the PIT plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Compute PIT values
    # -------------------------------
    pit_values = norm.cdf(y_true, loc=mu_pred, scale=sigma_pred)

    pit_df = pd.DataFrame({"PIT_Value": pit_values})

    # -------------------------------
    # Histogram data
    # -------------------------------
    hist_density, bin_edges = np.histogram(
        pit_values, bins=n_bins, range=(0, 1), density=True
    )
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    hist_df = pd.DataFrame({
        "Bin_Center": bin_centers,
        "Density": hist_density
    })

    # -------------------------------
    # Calibration diagnostics
    # -------------------------------
    pit_mean = pit_values.mean()
    pit_var = pit_values.var()
    ks_stat, ks_pvalue = kstest(pit_values, 'uniform')

    if ks_pvalue > 0.05:
        diagnosis = "Well-calibrated (Uniform PIT)"
    elif pit_var < 1/12:
        diagnosis = "Over-dispersed (Under-confident)"
    elif pit_var > 1/12:
        diagnosis = "Under-dispersed (Over-confident)"
    else:
        diagnosis = "Biased or miscalibrated"

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_PIT": pit_mean,
        "Variance_PIT": pit_var,
        "Ideal_Variance_(1/12)": 1/12,
        "KS_Statistic": ks_stat,
        "KS_pvalue": ks_pvalue,
        "Calibration_Diagnosis": diagnosis
    }])

    # -------------------------------
    # Create PIT plot in memory
    # -------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(
        pit_values,
        bins=n_bins,
        density=True,
        color="skyblue",
        edgecolor="black",
        alpha=0.75
    )
    ax.axhline(1, color="red", linestyle="--", label="Perfect Calibration")
    ax.set_xlabel("PIT Value")
    ax.set_ylabel("Density")
    ax.set_title(f"PIT Histogram – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_values = f"PIT_Values_{model_name}"
    sheet_hist = f"PIT_Histogram_{model_name}"
    sheet_summary = f"PIT_Summary_{model_name}"
    sheet_plot = f"PIT_Plot_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        writer
        pit_df.to_excel(writer, sheet_name=sheet_values, index=False)
        writer
        hist_df.to_excel(writer, sheet_name=sheet_hist, index=False)
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        # Create empty sheet for plot
        workbook = writer.book
        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print(f"✅ PIT values, histogram, summary, and EMBEDDED plot saved to:")
    print(f"   {excel_path}")

    return pit_df

In [13]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_calibration_curve(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_quantiles=10
):
    """
    Generate quantile calibration curve (reliability diagram),
    compute calibration errors, and save everything to Excel
    with the plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()
    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Quantiles
    # -------------------------------
    quantiles = np.linspace(0, 1, n_quantiles + 1)

    observed_freq = []
    predicted_q = []

    for q in quantiles:
        # Predicted value at quantile q
        thresh = norm.ppf(q, loc=mu_pred, scale=sigma_pred)

        # Observed frequency
        obs = np.mean(y_true <= thresh)

        predicted_q.append(q)
        observed_freq.append(obs)

    predicted_q = np.array(predicted_q)
    observed_freq = np.array(observed_freq)

    # -------------------------------
    # Calibration metrics
    # -------------------------------
    mce = np.mean(np.abs(observed_freq - predicted_q))
    rmsce = np.sqrt(np.mean((observed_freq - predicted_q) ** 2))

    calib_df = pd.DataFrame({
        "Predicted_Quantile": predicted_q,
        "Observed_Frequency": observed_freq,
        "Absolute_Error": np.abs(observed_freq - predicted_q)
    })

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_Calibration_Error (MCE)": mce,
        "RMS_Calibration_Error (RMSCE)": rmsce,
        "Num_Quantiles": n_quantiles
    }])

    # -------------------------------
    # Create calibration plot
    # -------------------------------
    fig, ax = plt.subplots(figsize=(7, 7))

    ax.plot([0, 1], [0, 1], 'k--', label="Perfect Calibration")
    ax.plot(
        predicted_q,
        observed_freq,
        'o-',
        color='teal',
        label=f"{model_name}"
    )

    ax.set_xlabel("Predicted Quantile (Confidence Level)")
    ax.set_ylabel("Observed Frequency")
    ax.set_title(f"Quantile Calibration Curve – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_curve = f"Calibration_Curve_{model_name}"
    sheet_summary = f"Calibration_Summary_{model_name}"
    sheet_plot = f"Calibration_Plot_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        writer
        calib_df.to_excel(writer, sheet_name=sheet_curve, index=False)
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        workbook = writer.book

        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print("✅ Calibration curve & metrics saved to Excel:")
    print(f"   {excel_path}")

    return calib_df

In [14]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
# Define the path to the folder
folder_path = "/content/drive/MyDrive/streamflow_uncertainty_analysis"

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

def plot_metrics_and_save_to_excel(writer, predictions_df, y_true, model_name):
    # Calculate metrics
    mean_pred = predictions_df['Mean']
    std_pred = predictions_df['StdDev']

    # Sharpness is the standard deviation
    sharpness = std_pred.mean()

    # CRPS for each prediction
    crps_values = ps.crps_gaussian(y_true, mean_pred, std_pred)

    # Negative Log Likelihood (NLL) for each prediction
    nll_values = -norm.logpdf(y_true, loc=mean_pred, scale=std_pred)
    nll = nll_values.mean()

    # Calibration (Validity)
    percentiles = np.linspace(0, 100, 101)
    calibration = [np.mean((y_true <= np.percentile(mean_pred + std_pred * np.random.randn(*mean_pred.shape), p))) for p in percentiles]

    # Create a DataFrame to store the metrics
    metrics_df = pd.DataFrame({
        'Mean Prediction': mean_pred,
        'Standard Deviation': std_pred,
        'CRPS': crps_values,
        'NLL': nll_values
    })

    # Add summary statistics
    summary_df = pd.DataFrame({
        'Metric': ['Sharpness', 'Mean CRPS', 'Mean NLL'],
        'Value': [sharpness, crps_values.mean(), nll]
    })

    # Write the metrics and summary to the Excel sheet
    metrics_sheet_name = f'{model_name} Metrics'
    writer
    metrics_df.to_excel(writer, sheet_name=metrics_sheet_name, index=False)

    summary_sheet_name = f'{model_name} Summary'
    writer
    summary_df.to_excel(writer, sheet_name=summary_sheet_name, index=False)

    # Plotting
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    # Sharpness plot
    axs[0, 0].hist(std_pred, bins=30, color='skyblue', edgecolor='black')
    axs[0, 0].set_title(f'Sharpness (StdDev) for {model_name}')
    axs[0, 0].set_xlabel('Standard Deviation')
    axs[0, 0].set_ylabel('Frequency')

    # CRPS plot (distribution)
    axs[0, 1].hist(crps_values, bins=30, color='lightgreen', edgecolor='black')
    axs[0, 1].set_title(f'CRPS Distribution for {model_name}')
    axs[0, 1].set_xlabel('CRPS')
    axs[0, 1].set_ylabel('Frequency')

    # NLL plot (distribution)
    axs[1, 0].hist(nll_values, bins=30, color='salmon', edgecolor='black')
    axs[1, 0].set_title(f'NLL Distribution for {model_name}')
    axs[1, 0].set_xlabel('NLL')
    axs[1, 0].set_ylabel('Frequency')

    # Calibration plot
    axs[1, 1].plot(percentiles, calibration, label='Calibration Curve')
    axs[1, 1].plot(percentiles, percentiles / 100, linestyle='--', label='Perfect Calibration')
    axs[1, 1].set_title(f'Calibration (Validity) for {model_name}')
    axs[1, 1].set_xlabel('Predicted Percentile')
    axs[1, 1].set_ylabel('Observed Frequency')
    axs[1, 1].legend()

    plt.tight_layout()

    # Save plots to images
    plot_image_path = f'{model_name}_plots.png'
    fig.savefig(_ensure_parent_dir(plot_image_path))
    plt.close(fig)

    # Insert the plot image into the Excel sheet
    sheet_name = f'{model_name} Plots'
    if sheet_name not in writer.sheets:  # Check if sheet already exists
        # If sheet doesn't exist, create a new one
        worksheet = writer.book.add_worksheet(sheet_name)
    else:
        # If sheet exists, get the existing sheet object to avoid duplicates
        worksheet = writer.sheets[sheet_name]
    worksheet.insert_image('A1', plot_image_path)

# **Tuned Parameters**

In [14]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 11396.714504124559,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 11396.714504124559,
  'test_rmse': 106.75539566750038,
  'test_corr_coef': 0.8545175710230449,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11396.714504124559,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 11396.714504124559,
  'test_rmse': 106.75539566750038,
  'test_corr_coef': 0.8545175710230445,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 12070.291743991513,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'log2',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 12070.291743991513,
  'test_rmse': 109.86487948380734,
  'test_corr_coef': 0.8452553059844832,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 11716.981138270823,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 11716.981138270823,
  'test_rmse': 108.24500514236591,
  'test_corr_coef': 0.8433099870855542,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 11439.192756209346, 'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05}, 'test_mse': 11439.192756209346, 'test_rmse': 106.9541619396335, 'test_corr_coef': 0.8533935563954336, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 11504.645347044134,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11504.645347044134,
  'test_rmse': 107.2597098030949,
  'test_corr_coef': 0.8532357616223099,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 11439.192756209348,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 11439.192756209348,
  'test_rmse': 106.95416193963351,
  'test_corr_coef': 0.8533935563954336,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 11734.35251996622,
  'best_params': {'n_estimators': 200,
   'criterion': 'poisson',
   'max_depth': 40,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'log2',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11734.35251996622,
  'test_rmse': 108.32521645473975,
  'test_corr_coef': 0.8529602600912333,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 7894.46813379009,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 1.0,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7894.46813379009,
  'test_rmse': 88.85081954484207,
  'test_corr_coef': 0.8941590289814214,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7979.404009165202,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 7979.404009165202,
  'test_rmse': 89.3275098117327,
  'test_corr_coef': 0.9028811706719992,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 8035.925747823539,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 8035.925747823539,
  'test_rmse': 89.64332517161297,
  'test_corr_coef': 0.8908089630271125,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 9421.813509142628,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 9421.813509142628,
  'test_rmse': 97.06602654452601,
  'test_corr_coef': 0.8749406418115374,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7832.37345464286, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.01}, 'test_mse': 7832.37345464286, 'test_rmse': 88.5006974811095, 'test_corr_coef': 0.8959547030435522, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 8915.412611307433,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.01,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 8915.412611307433,
  'test_rmse': 94.4214626624023,
  'test_corr_coef': 0.8893245816512504,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7908.923722871204,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 200,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'log2',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7908.923722871204,
  'test_rmse': 88.93212986806964,
  'test_corr_coef': 0.8933287186955804,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 7826.507523618409,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 7826.507523618409,
  'test_rmse': 88.46755068169577,
  'test_corr_coef': 0.9025977077608344,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 9592.75,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9592.75,
  'test_rmse': 97.94258522215962,
  'test_corr_coef': 0.8744618085762377,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 10609.2060546875,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 10609.2060546875,
  'test_rmse': 103.00100026061641,
  'test_corr_coef': 0.8661842817660108,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 9704.4892578125,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9704.4892578125,
  'test_rmse': 98.51136613514453,
  'test_corr_coef': 0.8697166555588549,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 10378.65234375,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 10378.65234375,
  'test_rmse': 101.8756710100601,
  'test_corr_coef': 0.8599670105990299,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 9919.0126953125,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9919.0126953125,
  'test_rmse': 99.59424027177727,
  'test_corr_coef': 0.8679753126698246,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 9796.1591796875,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9796.1591796875,
  'test_rmse': 98.97554839296168,
  'test_corr_coef': 0.8695228483465185,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 9558.4912109375,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 9558.4912109375,
  'test_rmse': 97.76753659030946,
  'test_corr_coef': 0.8742564436069653,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 10723.3310546875,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 10723.3310546875,
  'test_rmse': 103.55351782864501,
  'test_corr_coef': 0.8554622717330934,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 8093.7407934217545,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8093.7407934217545,
  'test_rmse': 89.96521990981712,
  'test_corr_coef': 0.8889794794195334,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 9544.473558946216,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 9544.473558946216,
  'test_rmse': 97.69582160433585,
  'test_corr_coef': 0.8763579708230304,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 10096.33246815347,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 10096.33246815347,
  'test_rmse': 100.4805079015501,
  'test_corr_coef': 0.8671432153117224,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 7404.388873890984,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 63,
   'max_depth': 3,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7404.388873890984,
  'test_rmse': 86.04875870046577,
  'test_corr_coef': 0.9036610692100672,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 7826.370797911004,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 31,
   'max_depth': 5,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7826.370797911004,
  'test_rmse': 88.46677793336323,
  'test_corr_coef': 0.8968692934394386,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 7716.182725214737,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.001,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7716.182725214737,
  'test_rmse': 87.8418051113178,
  'test_corr_coef': 0.8996131442228372,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 7852.782654987631,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 10,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7852.782654987631,
  'test_rmse': 88.61592777253777,
  'test_corr_coef': 0.8942173174465775,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 8390.306495329174,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8390.306495329174,
  'test_rmse': 91.59861623042771,
  'test_corr_coef': 0.8848324592834348,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 7544.111602140408,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7544.111602140408,
  'test_rmse': 86.85684545354158,
  'test_corr_coef': 0.899140689349327,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 8298.997243869338,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8298.997243869338,
  'test_rmse': 91.09883228598125,
  'test_corr_coef': 0.8859850624403404,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 7404.2396920244355,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 1.0,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7404.2396920244355,
  'test_rmse': 86.0478918511339,
  'test_corr_coef': 0.90198786970229,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 7421.776367870293,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7421.776367870293,
  'test_rmse': 86.14973225652122,
  'test_corr_coef': 0.9027127769989374,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 7694.459345833749,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 10,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 7694.459345833749,
  'test_rmse': 87.7180673854238,
  'test_corr_coef': 0.8952650394354964,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 8137.497471873475,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.8,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8137.497471873475,
  'test_rmse': 90.20807875059458,
  'test_corr_coef': 0.9025758228683337,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 8523.395691254658,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 10,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8523.395691254658,
  'test_rmse': 92.32223833537972,
  'test_corr_coef': 0.8844228113820186,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 8901.75039358178,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 8901.75039358178,
  'test_rmse': 94.34908793190202,
  'test_corr_coef': 0.8769681275078564,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 12059.717630039499,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12059.717630039499,
  'test_rmse': 109.81674567223115,
  'test_corr_coef': 0.834682576760058,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 12200.843128318063,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 128,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12200.843128318063,
  'test_rmse': 110.45742676849784,
  'test_corr_coef': 0.828657462741331,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 11828.352768700503,
  'best_params': {'iterations': 200,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 1,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 11828.352768700503,
  'test_rmse': 108.75823080898522,
  'test_corr_coef': 0.8402340352771763,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 12266.04121988882,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12266.04121988882,
  'test_rmse': 110.75216124251851,
  'test_corr_coef': 0.8284396615075661,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 12200.843128318063,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12200.843128318063,
  'test_rmse': 110.45742676849784,
  'test_corr_coef': 0.828657462741331,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 12200.843128318063,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 128,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12200.843128318063,
  'test_rmse': 110.45742676849784,
  'test_corr_coef': 0.828657462741331,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 12295.893812610366,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.01,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12295.893812610366,
  'test_rmse': 110.88685139641385,
  'test_corr_coef': 0.8292402939039899,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 12469.34371865179,
  'best_params': {'iterations': 500,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 9,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 12469.34371865179,
  'test_rmse': 111.66621565474398,
  'test_corr_coef': 0.8262490043890625,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 12061.97957465404,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12061.97957465404,
  'test_rmse': 109.8270439129363,
  'test_corr_coef': 0.8313969676088081,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 11887.17702290286,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 11887.17702290286,
  'test_rmse': 109.02833128550974,
  'test_corr_coef': 0.835197276506235,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 12187.317404589345,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12187.317404589345,
  'test_rmse': 110.39618383164041,
  'test_corr_coef': 0.8296624201996675,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 12090.956098491108,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12090.956098491108,
  'test_rmse': 109.9588836724487,
  'test_corr_coef': 0.8280868500336911,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 12186.9424450075,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12186.9424450075,
  'test_rmse': 110.39448557336323,
  'test_corr_coef': 0.8265686728872818,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 12328.252116504349,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12328.252116504349,
  'test_rmse': 111.03266238591394,
  'test_corr_coef': 0.8267596939517394,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 12168.541471178041,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 12168.541471178041,
  'test_rmse': 110.3111121835785,
  'test_corr_coef': 0.8303252321842222,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 11952.222521790789,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 11952.222521790789,
  'test_rmse': 109.32622065081546,
  'test_corr_coef': 0.8343780376436447,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 10192.0947265625,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.3,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 10192.0947265625,
  'test_rmse': 100.95590486228382,
  'test_corr_coef': 0.8680742873891645,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 7993.10546875,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 1.3,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 7993.10546875,
  'test_rmse': 89.40416919109533,
  'test_corr_coef': 0.9007085605894374,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 9981.9013671875,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 5,
   'gamma': 1.3,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9981.9013671875,
  'test_rmse': 99.90946585377934,
  'test_corr_coef': 0.8959780812686795,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 9387.9111328125,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 5,
   'gamma': 1.5,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9387.9111328125,
  'test_rmse': 96.89123351889221,
  'test_corr_coef': 0.8799101544458534,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 10727.46875,
  'best_params': {'n_d': 32,
   'n_a': 32,
   'n_steps': 7,
   'gamma': 1.5,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 10727.46875,
  'test_rmse': 103.5734944375249,
  'test_corr_coef': 0.8761904698139649,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 7730.98291015625,
  'best_params': {'n_d': 16,
   'n_a': 64,
   'n_steps': 7,
   'gamma': 2.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 7730.98291015625,
  'test_rmse': 87.92600815547269,
  'test_corr_coef': 0.8954141726546125,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 9506.19921875,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 7,
   'gamma': 1.5,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 3,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9506.19921875,
  'test_rmse': 97.49973958298555,
  'test_corr_coef': 0.8727852275919926,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 9029.6494140625,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 9029.6494140625,
  'test_rmse': 95.02446744950744,
  'test_corr_coef': 0.8804388946225445,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 8849.916118658877,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 500,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 1.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8849.916118658877,
  'test_rmse': 94.07399278577941,
  'test_corr_coef': 0.8792088280317188,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 13912.001349439612,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 13912.001349439612,
  'test_rmse': 117.94914730272369,
  'test_corr_coef': 0.8016637520482625,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 9029.10721281066,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 100,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 9029.10721281066,
  'test_rmse': 95.02161445066412,
  'test_corr_coef': 0.8773438467284207,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 8317.046438364536, 'best_params': {'learning_rate': 0.01,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 1.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 8317.046438364536, 'test_rmse': 91.1978422900703, 'test_corr_coef': 0.886267177095813, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 8062.298200739737, 'best_params': {'learning_rate': 0.01,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 8062.298200739737, 'test_rmse': 89.7903012621059, 'test_corr_coef': 0.9036784928536276, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting', 'HyperbandPruner'): {'best_score': 8062.298200739737,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8062.298200739737,
  'test_rmse': 89.7903012621059,
  'test_corr_coef': 0.9036784928536276,
  'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting', 'ThresholdPruner'): {'best_score': 8104.540855275137,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8104.540855275137,
  'test_rmse': 90.02522343918474,
  'test_corr_coef': 0.9033273747525989,
  'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 8349.441232137877,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 8349.441232137877,
  'test_rmse': 91.37527691962349,
  'test_corr_coef': 0.8854457951837483,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 8845.042530599296,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_leaves': 32,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 8845.042530599296,
  'test_rmse': 94.04808626760725,
  'test_corr_coef': 0.8777931131479602,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 9175.70378659374,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_leaves': 44,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'studentt'},
  'test_mse': 9175.70378659374,
  'test_rmse': 95.78989396900771,
  'test_corr_coef': 0.8755252327260262,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 8644.407437002892,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_leaves': 33,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 10,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 8644.407437002892,
  'test_rmse': 92.97530552250362,
  'test_corr_coef': 0.8825926843420658,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 8490.129698451294,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 42,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 8490.129698451294,
  'test_rmse': 92.14189979836152,
  'test_corr_coef': 0.8829833457176368,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 7773.717983434995,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_leaves': 24,
   'min_split_gain': 0.5,
   'reg_lambda': 1.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 10,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 7773.717983434995,
  'test_rmse': 88.16869049404667,
  'test_corr_coef': 0.8954213036678549,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 7763.821071455185,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_leaves': 31,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 256,
   'distribution': 'studentt'},
  'test_mse': 7763.821071455185,
  'test_rmse': 88.11254775260551,
  'test_corr_coef': 0.8964381399574919,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 7663.838249707027,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_leaves': 36,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 5,
   'max_bin': 256,
   'distribution': 'normal'},
  'test_mse': 7663.838249707027,
  'test_rmse': 87.54335068814208,
  'test_corr_coef': 0.9023151129811368,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 7710.988354850527,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_leaves': 28,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 7710.988354850527,
  'test_rmse': 87.81223351475879,
  'test_corr_coef': 0.9001164496423207,
  'pruner': 'WilcoxonPruner'}}

In [16]:
best_scores_autosampler

{('Random Forest', 'MedianPruner'): {'best_score': 13.182650929420474,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.182650929420474,
  'test_rmse': 3.63079205262715,
  'test_corr_coef': 0.9362480867949565,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11.272303056476819,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11.272303056476819,
  'test_rmse': 3.3574250634194085,
  'test_corr_coef': 0.9440478855010435,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 11.437119799459747,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 11.437119799459747,
  'test_rmse': 3.3818811036847154,
  'test_corr_coef': 0.9432772188634867,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 10.941206762081073,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 10.941206762081073,
  'test_rmse': 3.3077495011081286,
  'test_corr_coef': 0.94500835984303,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 10.880552388940954, 'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001}, 'test_mse': 10.880552388940954, 'test_rmse': 3.298568233179504, 'test_corr_coef': 0.9451752554913052, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 12.352278459566854,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 12.352278459566854,
  'test_rmse': 3.5145808369657474,
  'test_corr_coef': 0.9402669188906791,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 12.342074924476556,
  'best_params': {'n_estimators': 700,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 12.342074924476556,
  'test_rmse': 3.5131289365004177,
  'test_corr_coef': 0.9395016962237023,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 10.774834068806634,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 10.774834068806634,
  'test_rmse': 3.2825042374392503,
  'test_corr_coef': 0.9460418459494322,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 6.893508647469353,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 6.893508647469353,
  'test_rmse': 2.6255492087312615,
  'test_corr_coef': 0.9651848123284126,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7.763276701627249,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 7.763276701627249,
  'test_rmse': 2.786265727030939,
  'test_corr_coef': 0.960299321352052,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 7.502699891774882,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 7.502699891774882,
  'test_rmse': 2.739105673714485,
  'test_corr_coef': 0.9619355831635854,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 6.834971436808225,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 6.834971436808225,
  'test_rmse': 2.614377829772932,
  'test_corr_coef': 0.9651111711288763,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7.689690948162852, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0}, 'test_mse': 7.689690948162852, 'test_rmse': 2.7730292007411053, 'test_corr_coef': 0.9608862446607661, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 7.33313968984125,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 7.33313968984125,
  'test_rmse': 2.7079770475100506,
  'test_corr_coef': 0.9630585579097957,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7.477744369168925,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7.477744369168925,
  'test_rmse': 2.7345464649862734,
  'test_corr_coef': 0.9619684919611741,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 6.721076366834078,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 6.721076366834078,
  'test_rmse': 2.5925038798108053,
  'test_corr_coef': 0.9662115898059317,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 7.2354047049265535,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.2354047049265535,
  'test_rmse': 2.6898707598928526,
  'test_corr_coef': 0.9632217709829815,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 7.849364083074588,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.849364083074588,
  'test_rmse': 2.8016716586842554,
  'test_corr_coef': 0.9615165743735467,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 7.802370007652632,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.802370007652632,
  'test_rmse': 2.7932722759610513,
  'test_corr_coef': 0.9601176613813349,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 7.5038561309289245,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.5038561309289245,
  'test_rmse': 2.739316727019518,
  'test_corr_coef': 0.9620933960059359,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 7.753185403631509,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.753185403631509,
  'test_rmse': 2.7844542380207127,
  'test_corr_coef': 0.9605410174421329,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 7.342762082653903,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.342762082653903,
  'test_rmse': 2.7097531405376953,
  'test_corr_coef': 0.9624799383766623,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 7.946463097455834,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.946463097455834,
  'test_rmse': 2.8189471611677708,
  'test_corr_coef': 0.9595107073054235,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 7.68912600041155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.68912600041155,
  'test_rmse': 2.772927334138338,
  'test_corr_coef': 0.9608967677017526,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 6.942836699007481,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.942836699007481,
  'test_rmse': 2.634926317567055,
  'test_corr_coef': 0.9649381803805447,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 6.339384073454502,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.339384073454502,
  'test_rmse': 2.5178133515919128,
  'test_corr_coef': 0.9677038688754944,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 6.758719441603299,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.758719441603299,
  'test_rmse': 2.5997537271063385,
  'test_corr_coef': 0.9660330847044307,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 6.613581221431991,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.613581221431991,
  'test_rmse': 2.571688398976826,
  'test_corr_coef': 0.9663576043350901,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 6.471978196181523,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.471978196181523,
  'test_rmse': 2.5440082932611525,
  'test_corr_coef': 0.9670652131417232,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 6.417986013529069,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.417986013529069,
  'test_rmse': 2.533374432161395,
  'test_corr_coef': 0.9674069314589737,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 6.4359570823775485,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.4359570823775485,
  'test_rmse': 2.536918816670638,
  'test_corr_coef': 0.967215553727604,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 6.9216779919281155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.9216779919281155,
  'test_rmse': 2.6309082066708664,
  'test_corr_coef': 0.9648241722428089,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 6.791909837287244,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.791909837287244,
  'test_rmse': 2.606129282535163,
  'test_corr_coef': 0.9653900561558387,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 6.91595927653158,

In [17]:
best_scores_autosampler

{('Random Forest', 'MedianPruner'): {'best_score': 13.182650929420474,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.182650929420474,
  'test_rmse': 3.63079205262715,
  'test_corr_coef': 0.9362480867949565,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11.272303056476819,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11.272303056476819,
  'test_rmse': 3.3574250634194085,
  'test_corr_coef': 0.9440478855010435,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 11.437119799459747,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 11.437119799459747,
  'test_rmse': 3.3818811036847154,
  'test_corr_coef': 0.9432772188634867,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 10.941206762081073,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 10.941206762081073,
  'test_rmse': 3.3077495011081286,
  'test_corr_coef': 0.94500835984303,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 10.880552388940954, 'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001}, 'test_mse': 10.880552388940954, 'test_rmse': 3.298568233179504, 'test_corr_coef': 0.9451752554913052, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 12.352278459566854,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 12.352278459566854,
  'test_rmse': 3.5145808369657474,
  'test_corr_coef': 0.9402669188906791,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 12.342074924476556,
  'best_params': {'n_estimators': 700,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 12.342074924476556,
  'test_rmse': 3.5131289365004177,
  'test_corr_coef': 0.9395016962237023,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 10.774834068806634,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 10.774834068806634,
  'test_rmse': 3.2825042374392503,
  'test_corr_coef': 0.9460418459494322,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 6.893508647469353,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 6.893508647469353,
  'test_rmse': 2.6255492087312615,
  'test_corr_coef': 0.9651848123284126,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7.763276701627249,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 7.763276701627249,
  'test_rmse': 2.786265727030939,
  'test_corr_coef': 0.960299321352052,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 7.502699891774882,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 7.502699891774882,
  'test_rmse': 2.739105673714485,
  'test_corr_coef': 0.9619355831635854,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 6.834971436808225,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 6.834971436808225,
  'test_rmse': 2.614377829772932,
  'test_corr_coef': 0.9651111711288763,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7.689690948162852, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0}, 'test_mse': 7.689690948162852, 'test_rmse': 2.7730292007411053, 'test_corr_coef': 0.9608862446607661, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 7.33313968984125,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 7.33313968984125,
  'test_rmse': 2.7079770475100506,
  'test_corr_coef': 0.9630585579097957,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7.477744369168925,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7.477744369168925,
  'test_rmse': 2.7345464649862734,
  'test_corr_coef': 0.9619684919611741,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 6.721076366834078,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 6.721076366834078,
  'test_rmse': 2.5925038798108053,
  'test_corr_coef': 0.9662115898059317,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 7.2354047049265535,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.2354047049265535,
  'test_rmse': 2.6898707598928526,
  'test_corr_coef': 0.9632217709829815,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 7.849364083074588,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.849364083074588,
  'test_rmse': 2.8016716586842554,
  'test_corr_coef': 0.9615165743735467,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 7.802370007652632,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.802370007652632,
  'test_rmse': 2.7932722759610513,
  'test_corr_coef': 0.9601176613813349,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 7.5038561309289245,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.5038561309289245,
  'test_rmse': 2.739316727019518,
  'test_corr_coef': 0.9620933960059359,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 7.753185403631509,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.753185403631509,
  'test_rmse': 2.7844542380207127,
  'test_corr_coef': 0.9605410174421329,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 7.342762082653903,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.342762082653903,
  'test_rmse': 2.7097531405376953,
  'test_corr_coef': 0.9624799383766623,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 7.946463097455834,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.946463097455834,
  'test_rmse': 2.8189471611677708,
  'test_corr_coef': 0.9595107073054235,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 7.68912600041155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.68912600041155,
  'test_rmse': 2.772927334138338,
  'test_corr_coef': 0.9608967677017526,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 6.942836699007481,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.942836699007481,
  'test_rmse': 2.634926317567055,
  'test_corr_coef': 0.9649381803805447,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 6.339384073454502,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.339384073454502,
  'test_rmse': 2.5178133515919128,
  'test_corr_coef': 0.9677038688754944,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 6.758719441603299,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.758719441603299,
  'test_rmse': 2.5997537271063385,
  'test_corr_coef': 0.9660330847044307,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 6.613581221431991,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.613581221431991,
  'test_rmse': 2.571688398976826,
  'test_corr_coef': 0.9663576043350901,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 6.471978196181523,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.471978196181523,
  'test_rmse': 2.5440082932611525,
  'test_corr_coef': 0.9670652131417232,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 6.417986013529069,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.417986013529069,
  'test_rmse': 2.533374432161395,
  'test_corr_coef': 0.9674069314589737,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 6.4359570823775485,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.4359570823775485,
  'test_rmse': 2.536918816670638,
  'test_corr_coef': 0.967215553727604,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 6.9216779919281155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.9216779919281155,
  'test_rmse': 2.6309082066708664,
  'test_corr_coef': 0.9648241722428089,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 6.791909837287244,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.791909837287244,
  'test_rmse': 2.606129282535163,
  'test_corr_coef': 0.9653900561558387,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 6.91595927653158,

# **Probabilistic distributions using NGBoost**

In [18]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize NGBoost model with best_params
ngb_model = NGBRegressor(Dist=Normal, **best_params)

# Fit the model
ngb_model.fit(X_train, y_train)

# Predict the distribution
pred_dist = ngb_model.pred_dist(X_test)

# Extract mean and standard deviation
predictions_NGB_df = pd.DataFrame({
    'Mean': pred_dist.loc,
    'StdDev': pred_dist.scale,
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, pred_dist.loc)
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_NGB_df.head())

Mean Squared Error: 7.29
        Mean    StdDev  Actual
0  33.389155  0.308892    34.0
1  35.293097  0.366243    36.0
2  34.343520  0.463604    36.0
3  35.666789  0.226376    35.0
4  43.400828  0.065594    44.6

In [19]:
generate_and_save_plots(predictions_NGB_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx

In [20]:
generate_and_save_crps_decomposition(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx
   Sheets: CRPS_Summary_NGBoost, CRPS_Bins_NGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  NGBoost    1.735078     1.751975    5.557449     5.540551        10

In [21]:
generate_and_save_pit_results(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx

        PIT_Value
0    9.760095e-01
1    9.732056e-01
2    9.998236e-01
3    1.612233e-03
4    1.000000e+00
..            ...
90  3.510378e-123
91   8.286416e-01
92   9.999663e-01
93   2.222444e-01
94   3.515360e-01

[95 rows x 1 columns]

In [22]:
generate_and_save_calibration_curve(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.347368        0.247368
2                  0.2            0.400000        0.200000
3                  0.3            0.421053        0.121053
4                  0.4            0.452632        0.052632
5                  0.5            0.463158        0.036842
6                  0.6            0.484211        0.115789
7                  0.7            0.505263        0.194737
8                  0.8            0.515789        0.284211
9                  0.9            0.589474        0.310526
10                 1.0            1.000000        0.000000

# **Probabilistic distributions using PGBM**

In [23]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
# Note: Adjust the incompatible keys based on PGBM's requirements
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()

def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)
# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params = best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Extract mean and standard deviation
# Note: PGBM might return predictions in a different format, adjust accordingly
predictions_PGBM_df = pd.DataFrame({
    'Mean': pred_dist.mean(axis=0),
    'StdDev': pred_dist.std(axis=0),
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, predictions_PGBM_df['Mean'])
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/200, Train metric: 9.2850
Estimator 1/200, Train metric: 8.6234
Estimator 2/200, Train metric: 8.2641
Estimator 3/200, Train metric: 7.8237
Estimator 4/200, Train metric: 7.5665
Estimator 5/200, Train metric: 7.2251
Estimator 6/200, Train metric: 6.8984
Estimator 7/200, Train metric: 6.4854
Estimator 8/200, Train metric: 6.1831
Estimator 9/200, Train metric: 5.9803
Estimator 10/200, Train metric: 5.7623
Estimator 11/200, Train metric: 5.4730
Estimator 12/200, Train metric: 5.2343
Estimator 13/200, Train metric: 5.0966
Estimator 14/200, Train metric: 4.9185
Estimator 15/200, Train metric: 4.7081
Estimator 16/200, Train metric: 4.5379
Estimator 17/200, Train metric: 4.4048
Estimator 18/200, Train metric: 4.2659
Estimator 19/200, Train metric: 4.1441
Estimator 20/200, Train metric: 3.9917
Estimator 21/200, Train metric: 3.8925
Estimator 22/200, Train metric: 3.8015
Estimator 23/200, Train metric: 3.6790
Estimator 24/200, Train metric: 3.5467
Estimator 25/200, Train metric: 3.4621
Estimator 26/200, Train metric: 3.3903
Estimator 27/200, Train metric: 3.3242
Estimator 28/200, Train metric: 3.2372
Estimator 29/200, Train metric: 3.1548
Estimator 30/200, Train metric: 3.0856
Estimator 31/200, Train metric: 3.0020
Estimator 32/200, Train metric: 2.9601
Estimator 33/200, Train metric: 2.9059
Estimator 34/200, Train metric: 2.8599
Estimator 35/200, Train metric: 2.8133
Estimator 36/200, Train metric: 2.7392
Estimator 37/200, Train metric: 2.6822
Estimator 38/200, Train metric: 2.6457
Estimator 39/200, Train metric: 2.5941
Estimator 40/200, Train metric: 2.5326
Estimator 41/200, Train metric: 2.4931
Estimator 42/200, Train metric: 2.4567
Estimator 43/200, Train metric: 2.4240
Estimator 44/200, Train metric: 2.3960
Estimator 45/200, Train metric: 2.3648
Estimator 46/200, Train metric: 2.3504
Estimator 47/200, Train metric: 2.3074
Estimator 48/200, Train metric: 2.2681
Estimator 49/200, Train metric: 2.2563
Estimator 50/200, Train metric: 2.2209
Estimator 51/200, Train metric: 2.1959
Estimator 52/200, Train metric: 2.1728
Estimator 53/200, Train metric: 2.1518
Estimator 54/200, Train metric: 2.1081
Estimator 55/200, Train metric: 2.0553
Estimator 56/200, Train metric: 2.0327
Estimator 57/200, Train metric: 2.0068
Estimator 58/200, Train metric: 1.9750
Estimator 59/200, Train metric: 1.9457
Estimator 60/200, Train metric: 1.9224
Estimator 61/200, Train metric: 1.8970
Estimator 62/200, Train metric: 1.8703
Estimator 63/200, Train metric: 1.8407
Estimator 64/200, Train metric: 1.8215
Estimator 65/200, Train metric: 1.8121
Estimator 66/200, Train metric: 1.7846
Estimator 67/200, Train metric: 1.7645
Estimator 68/200, Train metric: 1.7445
Estimator 69/200, Train metric: 1.7242
Estimator 70/200, Train metric: 1.7076
Estimator 71/200, Train metric: 1.6936
Estimator 72/200, Train metric: 1.6746
Estimator 73/200, Train metric: 1.6515
Estimator 74/200, Train metric: 1.6326
Estimator 75/200, Train metric: 1.6207
Estimator 76/200, Train metric: 1.6109
Estimator 77/200, Train metric: 1.6016
Estimator 78/200, Train metric: 1.5847
Estimator 79/200, Train metric: 1.5664
Estimator 80/200, Train metric: 1.5499
Estimator 81/200, Train metric: 1.5280
Estimator 82/200, Train metric: 1.5121
Estimator 83/200, Train metric: 1.5065
Estimator 84/200, Train metric: 1.4921
Estimator 85/200, Train metric: 1.4764
Estimator 86/200, Train metric: 1.4684
Estimator 87/200, Train metric: 1.4583
Estimator 88/200, Train metric: 1.4535
Estimator 89/200, Train metric: 1.4428
Estimator 90/200, Train metric: 1.4296
Estimator 91/200, Train metric: 1.4172
Estimator 92/200, Train metric: 1.4082
Estimator 93/200, Train metric: 1.3946
Estimator 94/200, Train metric: 1.3869
Estimator 95/200, Train metric: 1.3801
Estimator 96/200, Train metric: 1.3673
Estimator 97/200, Train metric: 1.3522
Estimator 98/200, Train metric: 1.3418
Estimator 99/200, Train metric: 1.3262
Estimator 100/200, Train metric: 1.3099
Estimator 101/200, Train metric: 1.3002
Estimator 102/200, Train metric: 1.2903
Estimator 103/200, Train metric: 1.2864
Estimator 104/200, Train metric: 1.2779
Estimator 105/200, Train metric: 1.2703
Estimator 106/200, Train metric: 1.2632
Estimator 107/200, Train metric: 1.2491
Estimator 108/200, Train metric: 1.2428
Estimator 109/200, Train metric: 1.2371
Estimator 110/200, Train metric: 1.2337
Estimator 111/200, Train metric: 1.2235
Estimator 112/200, Train metric: 1.2193
Estimator 113/200, Train metric: 1.2040
Estimator 114/200, Train metric: 1.1954
Estimator 115/200, Train metric: 1.1834
Estimator 116/200, Train metric: 1.1688
Estimator 117/200, Train metric: 1.1615
Estimator 118/200, Train metric: 1.1593
Estimator 119/200, Train metric: 1.1511
Estimator 120/200, Train metric: 1.1432
Estimator 121/200, Train metric: 1.1385
Estimator 122/200, Train metric: 1.1309
Estimator 123/200, Train metric: 1.1242
Estimator 124/200, Train metric: 1.1195
Estimator 125/200, Train metric: 1.1105
Estimator 126/200, Train metric: 1.1050
Estimator 127/200, Train metric: 1.0985
Estimator 128/200, Train metric: 1.0915
Estimator 129/200, Train metric: 1.0821
Estimator 130/200, Train metric: 1.0755
Estimator 131/200, Train metric: 1.0717
Estimator 132/200, Train metric: 1.0678
Estimator 133/200, Train metric: 1.0602
Estimator 134/200, Train metric: 1.0491
Estimator 135/200, Train metric: 1.0443
Estimator 136/200, Train metric: 1.0405
Estimator 137/200, Train metric: 1.0343
Estimator 138/200, Train metric: 1.0300
Estimator 139/200, Train metric: 1.0263
Estimator 140/200, Train metric: 1.0201
Estimator 141/200, Train metric: 1.0168
Estimator 142/200, Train metric: 1.0157
Estimator 143/200, Train metric: 1.0142
Estimator 144/200, Train metric: 1.0080
Estimator 145/200, Train metric: 1.0032
Estimator 146/200, Train metric: 0.9969
Estimator 147/200, Train metric: 0.9921
Estimator 148/200, Train metric: 0.9874
Estimator 149/200, Train metric: 0.9842
Estimator 150/200, Train metric: 0.9741
Estimator 151/200, Train metric: 0.9664
Estimator 152/200, Train metric: 0.9658
Estimator 153/200, Train metric: 0.9644
Estimator 154/200, Train metric: 0.9613
Estimator 155/200, Train metric: 0.9564
Estimator 156/200, Train metric: 0.9506
Estimator 157/200, Train metric: 0.9466
Estimator 158/200, Train metric: 0.9401
Estimator 159/200, Train metric: 0.9371
Estimator 160/200, Train metric: 0.9306
Estimator 161/200, Train metric: 0.9265
Estimator 162/200, Train metric: 0.9220
Estimator 163/200, Train metric: 0.9194
Estimator 164/200, Train metric: 0.9159
Estimator 165/200, Train metric: 0.9068
Estimator 166/200, Train metric: 0.9020
Estimator 167/200, Train metric: 0.9015
Estimator 168/200, Train metric: 0.8997
Estimator 169/200, Train metric: 0.8953
Estimator 170/200, Train metric: 0.8910
Estimator 171/200, Train metric: 0.8860
Estimator 172/200, Train metric: 0.8820
Estimator 173/200, Train metric: 0.8758
Estimator 174/200, Train metric: 0.8704
Estimator 175/200, Train metric: 0.8681
Estimator 176/200, Train metric: 0.8632
Estimator 177/200, Train metric: 0.8582
Estimator 178/200, Train metric: 0.8553
Estimator 179/200, Train metric: 0.8533
Estimator 180/200, Train metric: 0.8509
Estimator 181/200, Train metric: 0.8494
Estimator 182/200, Train metric: 0.8472
Estimator 183/200, Train metric: 0.8449
Estimator 184/200, Train metric: 0.8413
Estimator 185/200, Train metric: 0.8390
Estimator 186/200, Train metric: 0.8347
Estimator 187/200, Train metric: 0.8318
Estimator 188/200, Train metric: 0.8311
Estimator 189/200, Train metric: 0.8284
Estimator 190/200, Train metric: 0.8251
Estimator 191/200, Train metric: 0.8225
Estimator 192/200, Train metric: 0.8212
Estimator 193/200, Train metric: 0.8185
Estimator 194/200, Train metric: 0.8155
Estimator 195/200, Train metric: 0.8118
Estimator 196/200, Train metric: 0.8095
Estimator 197/200, Train metric: 0.8073
Estimator 198/200, Train metric: 0.8032
Estimator 199/200, Train metric: 0.8006
Mean Squared Error: 6.70
        Mean    StdDev  Actual
0  32.572739  1.670101    34.0
1  36.512100  1.882481    36.0
2  34.220406  2.185976    36.0
3  36.337196  3.055833    35.0
4  43.927353  3.091106    44.6

In [24]:
generate_and_save_plots(predictions_PGBM_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx

In [25]:
generate_and_save_crps_decomposition(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx
   Sheets: CRPS_Summary_PGBM, CRPS_Bins_PGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  PGBM    1.395889     1.404574    5.549237     5.540551        10

In [26]:
generate_and_save_pit_results(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx

    PIT_Value
0    0.803613
1    0.392798
2    0.792205
3    0.330842
4    0.586132
..        ...
90   0.028027
91   0.571042
92   0.598802
93   0.668793
94   0.467536

[95 rows x 1 columns]

In [27]:
generate_and_save_calibration_curve(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.136842        0.036842
2                  0.2            0.168421        0.031579
3                  0.3            0.242105        0.057895
4                  0.4            0.347368        0.052632
5                  0.5            0.484211        0.015789
6                  0.6            0.578947        0.021053
7                  0.7            0.726316        0.026316
8                  0.8            0.768421        0.031579
9                  0.9            0.863158        0.036842
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using GPBoost (Treeffuser)**

In [28]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

gpboost_score_engine = TreeBasedScoreModel(
    model_name='gpboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

# The fix is in the line below: '_score_model' has been corrected to 'score_model'.
model = Treeffuser(score_model=gpboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GPBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GPBoost_TF_df.head())

[1]	valid_0's l2: 0.814828
[2]	valid_0's l2: 0.745379
[3]	valid_0's l2: 0.684604
[4]	valid_0's l2: 0.638056
[5]	valid_0's l2: 0.593349
[6]	valid_0's l2: 0.591225
[7]	valid_0's l2: 0.560197
[8]	valid_0's l2: 0.562464
[9]	valid_0's l2: 0.542792
[10]	valid_0's l2: 0.51594
[11]	valid_0's l2: 0.488099
[12]	valid_0's l2: 0.472809
[13]	valid_0's l2: 0.461828
[14]	valid_0's l2: 0.464055
[15]	valid_0's l2: 0.469978
[16]	valid_0's l2: 0.471244
[17]	valid_0's l2: 0.466536
[18]	valid_0's l2: 0.455016
[19]	valid_0's l2: 0.459887
[20]	valid_0's l2: 0.462735
[21]	valid_0's l2: 0.461649
[22]	valid_0's l2: 0.458729
[23]	valid_0's l2: 0.462537
[24]	valid_0's l2: 0.456796
[25]	valid_0's l2: 0.456662
[26]	valid_0's l2: 0.463371
[27]	valid_0's l2: 0.468652
[28]	valid_0's l2: 0.470828
[29]	valid_0's l2: 0.476277
[30]	valid_0's l2: 0.481216
[31]	valid_0's l2: 0.488197
[32]	valid_0's l2: 0.490014
[33]	valid_0's l2: 0.48697
[34]	valid_0's l2: 0.486202
[35]	valid_0's l2: 0.489545
[36]	valid_0's l2: 0.492337
[37]	valid_0's l2: 0.492481
[38]	valid_0's l2: 0.493215
[39]	valid_0's l2: 0.491974
[40]	valid_0's l2: 0.485544
[41]	valid_0's l2: 0.485466
[42]	valid_0's l2: 0.485479
[43]	valid_0's l2: 0.483957
[44]	valid_0's l2: 0.487563
[45]	valid_0's l2: 0.488314
[46]	valid_0's l2: 0.486778
[47]	valid_0's l2: 0.487218
[48]	valid_0's l2: 0.486425
[49]	valid_0's l2: 0.487368
[50]	valid_0's l2: 0.48893
[51]	valid_0's l2: 0.489433
[52]	valid_0's l2: 0.486727
[53]	valid_0's l2: 0.489625
[54]	valid_0's l2: 0.488825
[55]	valid_0's l2: 0.489109
[56]	valid_0's l2: 0.490023
[57]	valid_0's l2: 0.49196
[58]	valid_0's l2: 0.496063
[59]	valid_0's l2: 0.497253
[60]	valid_0's l2: 0.497246
[61]	valid_0's l2: 0.500208
[62]	valid_0's l2: 0.500202
[63]	valid_0's l2: 0.500841
[64]	valid_0's l2: 0.500583
[65]	valid_0's l2: 0.494124
[66]	valid_0's l2: 0.493491
[67]	valid_0's l2: 0.497452
[68]	valid_0's l2: 0.495558
[69]	valid_0's l2: 0.496023
[70]	valid_0's l2: 0.496942
[71]	valid_0's l2: 0.496772
[72]	valid_0's l2: 0.502901
[73]	valid_0's l2: 0.502383
[74]	valid_0's l2: 0.5007
[75]	valid_0's l2: 0.500367
[76]	valid_0's l2: 0.500633
[77]	valid_0's l2: 0.502186
[78]	valid_0's l2: 0.503338
[79]	valid_0's l2: 0.50292
[80]	valid_0's l2: 0.504888
[81]	valid_0's l2: 0.501297
[82]	valid_0's l2: 0.5027
[83]	valid_0's l2: 0.502454
[84]	valid_0's l2: 0.505093
[85]	valid_0's l2: 0.503872
[86]	valid_0's l2: 0.50352
[87]	valid_0's l2: 0.501316
[88]	valid_0's l2: 0.504008
[89]	valid_0's l2: 0.504875
[90]	valid_0's l2: 0.504702
[91]	valid_0's l2: 0.506397
[92]	valid_0's l2: 0.512085
[93]	valid_0's l2: 0.511882
[94]	valid_0's l2: 0.512553
[95]	valid_0's l2: 0.513082
[96]	valid_0's l2: 0.512988
[97]	valid_0's l2: 0.51297
[98]	valid_0's l2: 0.512608
[99]	valid_0's l2: 0.519976
[100]	valid_0's l2: 0.519566
[101]	valid_0's l2: 0.520791
[102]	valid_0's l2: 0.521301
[103]	valid_0's l2: 0.521297
[104]	valid_0's l2: 0.522836
[105]	valid_0's l2: 0.522876
[106]	valid_0's l2: 0.522008
[107]	valid_0's l2: 0.523823
[108]	valid_0's l2: 0.526335
[109]	valid_0's l2: 0.528387
[110]	valid_0's l2: 0.526882
[111]	valid_0's l2: 0.532427
[112]	valid_0's l2: 0.532432
[113]	valid_0's l2: 0.534707
[114]	valid_0's l2: 0.54031
[115]	valid_0's l2: 0.538332
[116]	valid_0's l2: 0.539447
[117]	valid_0's l2: 0.541174
[118]	valid_0's l2: 0.544873
[119]	valid_0's l2: 0.543036
[120]	valid_0's l2: 0.542923
[121]	valid_0's l2: 0.550991
[122]	valid_0's l2: 0.547371
[123]	valid_0's l2: 0.54978
[124]	valid_0's l2: 0.550792
[125]	valid_0's l2: 0.54943
[126]	valid_0's l2: 0.550685
[127]	valid_0's l2: 0.557244
[128]	valid_0's l2: 0.55609
[129]	valid_0's l2: 0.555172
[130]	valid_0's l2: 0.556392
[131]	valid_0's l2: 0.568104
[132]	valid_0's l2: 0.565877
[133]	valid_0's l2: 0.566631
[134]	valid_0's l2: 0.567377
[135]	valid_0's l2: 0.566945
[136]	valid_0's l2: 0.567642
[137]	valid_0's l2: 0.567718
[138]	valid_0's l2: 0.567492
[139]	valid_0's l2: 0.567306
[140]	valid_0's l2: 0.567361
[141]	valid_0's l2: 0.567575
[142]	valid_0's l2: 0.567193
[143]	valid_0's l2: 0.567858
[144]	valid_0's l2: 0.563991
[145]	valid_0's l2: 0.564929
[146]	valid_0's l2: 0.565545
[147]	valid_0's l2: 0.583135
[148]	valid_0's l2: 0.583531
[149]	valid_0's l2: 0.580783
[150]	valid_0's l2: 0.579601
[151]	valid_0's l2: 0.581056
[152]	valid_0's l2: 0.582551
[153]	valid_0's l2: 0.582055
[154]	valid_0's l2: 0.582619
[155]	valid_0's l2: 0.586197
[156]	valid_0's l2: 0.587792
[157]	valid_0's l2: 0.588241
[158]	valid_0's l2: 0.589658
[159]	valid_0's l2: 0.590218
[160]	valid_0's l2: 0.590218
[161]	valid_0's l2: 0.59113
[162]	valid_0's l2: 0.593293
[163]	valid_0's l2: 0.593736
[164]	valid_0's l2: 0.599928
[165]	valid_0's l2: 0.600018
[166]	valid_0's l2: 0.601927
[167]	valid_0's l2: 0.601051
[168]	valid_0's l2: 0.602426
[169]	valid_0's l2: 0.603206
[170]	valid_0's l2: 0.602869
[171]	valid_0's l2: 0.602676
[172]	valid_0's l2: 0.602393
[173]	valid_0's l2: 0.603189
[174]	valid_0's l2: 0.603122
[175]	valid_0's l2: 0.604116
[176]	valid_0's l2: 0.604216
[177]	valid_0's l2: 0.603425
[178]	valid_0's l2: 0.601231
[179]	valid_0's l2: 0.600352
[180]	valid_0's l2: 0.600675
[181]	valid_0's l2: 0.603011
[182]	valid_0's l2: 0.60014
[183]	valid_0's l2: 0.599884
[184]	valid_0's l2: 0.599388
[185]	valid_0's l2: 0.598485
[186]	valid_0's l2: 0.600743
[187]	valid_0's l2: 0.600955
[188]	valid_0's l2: 0.600701
[189]	valid_0's l2: 0.600957
[190]	valid_0's l2: 0.600854
[191]	valid_0's l2: 0.602243
[192]	valid_0's l2: 0.604203
[193]	valid_0's l2: 0.609041
[194]	valid_0's l2: 0.609069
[195]	valid_0's l2: 0.609545
[196]	valid_0's l2: 0.610645
[197]	valid_0's l2: 0.610559
[198]	valid_0's l2: 0.613698
[199]	valid_0's l2: 0.614694
[200]	valid_0's l2: 0.614604
[201]	valid_0's l2: 0.619748
[202]	valid_0's l2: 0.620131
[203]	valid_0's l2: 0.620604
[204]	valid_0's l2: 0.631114
[205]	valid_0's l2: 0.630746
[206]	valid_0's l2: 0.64227
[207]	valid_0's l2: 0.642192
[208]	valid_0's l2: 0.647601
[209]	valid_0's l2: 0.647907
[210]	valid_0's l2: 0.648369
[211]	valid_0's l2: 0.650368
[212]	valid_0's l2: 0.652494
[213]	valid_0's l2: 0.656042
[214]	valid_0's l2: 0.65565
[215]	valid_0's l2: 0.671043
[216]	valid_0's l2: 0.671443
[217]	valid_0's l2: 0.669706
[218]	valid_0's l2: 0.669065
[219]	valid_0's l2: 0.669491
[220]	valid_0's l2: 0.669839
[221]	valid_0's l2: 0.668276
[222]	valid_0's l2: 0.663663
[223]	valid_0's l2: 0.663374
[224]	valid_0's l2: 0.667892
[225]	valid_0's l2: 0.666953
[226]	valid_0's l2: 0.666087
[227]	valid_0's l2: 0.667128
[228]	valid_0's l2: 0.667866
[229]	valid_0's l2: 0.667439
[230]	valid_0's l2: 0.667483
[231]	valid_0's l2: 0.66754
[232]	valid_0's l2: 0.671948
[233]	valid_0's l2: 0.670838
[234]	valid_0's l2: 0.671527
[235]	valid_0's l2: 0.6714
[236]	valid_0's l2: 0.672783
[237]	valid_0's l2: 0.67344
[238]	valid_0's l2: 0.67149
[239]	valid_0's l2: 0.671165
[240]	valid_0's l2: 0.671143
[241]	valid_0's l2: 0.668777
[242]	valid_0's l2: 0.668725
[243]	valid_0's l2: 0.66958
[244]	valid_0's l2: 0.669517
[245]	valid_0's l2: 0.671604
[246]	valid_0's l2: 0.671722
[247]	valid_0's l2: 0.671994
[248]	valid_0's l2: 0.678165
[249]	valid_0's l2: 0.678723
[250]	valid_0's l2: 0.679427
[251]	valid_0's l2: 0.67793
[252]	valid_0's l2: 0.682136
[253]	valid_0's l2: 0.682029
[254]	valid_0's l2: 0.681992
[255]	valid_0's l2: 0.689442
[256]	valid_0's l2: 0.689753
[257]	valid_0's l2: 0.688686
[258]	valid_0's l2: 0.689072
[259]	valid_0's l2: 0.688664
[260]	valid_0's l2: 0.689859
[261]	valid_0's l2: 0.689357
[262]	valid_0's l2: 0.689349
[263]	valid_0's l2: 0.688292
[264]	valid_0's l2: 0.688348
[265]	valid_0's l2: 0.68822
[266]	valid_0's l2: 0.687572
[267]	valid_0's l2: 0.688637
[268]	valid_0's l2: 0.688668
[269]	valid_0's l2: 0.687575
[270]	valid_0's l2: 0.688615
[271]	valid_0's l2: 0.688981
[272]	valid_0's l2: 0.687699
[273]	valid_0's l2: 0.686338
[274]	valid_0's l2: 0.686708
[275]	valid_0's l2: 0.692831
[276]	valid_0's l2: 0.69298
[277]	valid_0's l2: 0.693115
[278]	valid_0's l2: 0.698694
[279]	valid_0's l2: 0.697732
[280]	valid_0's l2: 0.697263
[281]	valid_0's l2: 0.696511
[282]	valid_0's l2: 0.697118
[283]	valid_0's l2: 0.697183
[284]	valid_0's l2: 0.697526
[285]	valid_0's l2: 0.697484
[286]	valid_0's l2: 0.696328
[287]	valid_0's l2: 0.704652
[288]	valid_0's l2: 0.702933
[289]	valid_0's l2: 0.703414
[290]	valid_0's l2: 0.705945
[291]	valid_0's l2: 0.705914
[292]	valid_0's l2: 0.703361
[293]	valid_0's l2: 0.701026
[294]	valid_0's l2: 0.700399
[295]	valid_0's l2: 0.700207
[296]	valid_0's l2: 0.700906
[297]	valid_0's l2: 0.702485
[298]	valid_0's l2: 0.701987
[299]	valid_0's l2: 0.701828
[300]	valid_0's l2: 0.701529
        Mean     StdDev  Actual
0  36.436057  10.131030    34.0
1  33.894860   8.526657    36.0
2  35.185981   9.053880    36.0
3  31.429645   7.532484    35.0
4  58.743829  19.478956    44.6

In [29]:
generate_and_save_plots(predictions_GPBoost_TF_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx

In [30]:
generate_and_save_crps_decomposition(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_GPBoost, CRPS_Bins_GPBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  GPBoost    3.547005     3.565784    5.559331     5.540551        10

In [31]:
generate_and_save_pit_results(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx

    PIT_Value
0    0.404989
1    0.597503
2    0.535820
3    0.682248
4    0.233886
..        ...
90   0.186616
91   0.727441
92   0.456154
93   0.508840
94   0.522415

[95 rows x 1 columns]

In [32]:
generate_and_save_calibration_curve(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.010526        0.089474
2                  0.2            0.021053        0.178947
3                  0.3            0.126316        0.173684
4                  0.4            0.294737        0.105263
5                  0.5            0.515789        0.015789
6                  0.6            0.694737        0.094737
7                  0.7            0.915789        0.215789
8                  0.8            0.978947        0.178947
9                  0.9            0.989474        0.089474
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Gradient Boosting (Treeffuser)**

In [33]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

gbr_score_engine = TreeBasedScoreModel(
    model_name='gradient_boosting',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=gbr_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GBR_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GBR_TF_df.head())

        Mean     StdDev  Actual
0  32.855607  10.989951    34.0
1  29.771483  16.390009    36.0
2  38.302360  13.853211    36.0
3  28.568296  13.413677    35.0
4  63.617934  26.785633    44.6

In [34]:
generate_and_save_plots(predictions_GBR_TF_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx

In [35]:
generate_and_save_crps_decomposition(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx",
    model_name="Gradient Boosting",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx
   Sheets: CRPS_Summary_Gradient Boosting, CRPS_Bins_Gradient Boosting

,Model,Total_CRPS,Reliability,Resolution,Uncertainty,Num_Bins
0,Gradient Boosting,4.780373,4.815235,5.575414,5.540551,10

In [36]:
generate_and_save_pit_results(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx

    PIT_Value
0    0.541467
1    0.648034
2    0.434001
3    0.684204
4    0.238851
..        ...
90   0.259202
91   0.607242
92   0.495894
93   0.391151
94   0.483736

[95 rows x 1 columns]

In [37]:
generate_and_save_calibration_curve(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.010526        0.189474
3                  0.3            0.063158        0.236842
4                  0.4            0.231579        0.168421
5                  0.5            0.568421        0.068421
6                  0.6            0.789474        0.189474
7                  0.7            0.926316        0.226316
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Catboost (Treeffuser)**

In [38]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

catboost_score_engine = TreeBasedScoreModel(
    model_name='catboost',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=catboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_CatBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_CatBoost_TF_df.head())

        Mean     StdDev  Actual
0  30.030201  70.091306    34.0
1  26.202049  59.999699    36.0
2  34.285219  73.305203    36.0
3  20.016409  75.344554    35.0
4  54.206983  84.005036    44.6

In [39]:
generate_and_save_plots(predictions_CatBoost_TF_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx

In [40]:
generate_and_save_crps_decomposition(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_CatBoost, CRPS_Bins_CatBoost

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  CatBoost   17.841253    17.891136    5.590434     5.540551        10

In [41]:
generate_and_save_pit_results(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx

    PIT_Value
0    0.522583
1    0.564859
2    0.509331
3    0.578817
4    0.454475
..        ...
90   0.417939
91   0.433379
92   0.515272
93   0.381408
94   0.490469

[95 rows x 1 columns]

In [42]:
generate_and_save_calibration_curve(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.063158        0.336842
5                  0.5            0.684211        0.184211
6                  0.6            1.000000        0.400000
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using XGBoost (Treeffuser)**

In [43]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

xgb_score_engine = TreeBasedScoreModel(
    model_name='xgboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=xgb_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_XGB_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_XGB_TF_df.head())

[0]	validation_0-rmse:0.88741
[1]	validation_0-rmse:0.86686
[2]	validation_0-rmse:0.85869
[3]	validation_0-rmse:0.84120
[4]	validation_0-rmse:0.84248
[5]	validation_0-rmse:0.83068
[6]	validation_0-rmse:0.81900
[7]	validation_0-rmse:0.80689
[8]	validation_0-rmse:0.79660
[9]	validation_0-rmse:0.78771
[10]	validation_0-rmse:0.77834
[11]	validation_0-rmse:0.76440
[12]	validation_0-rmse:0.75886
[13]	validation_0-rmse:0.75579
[14]	validation_0-rmse:0.75362
[15]	validation_0-rmse:0.75676
[16]	validation_0-rmse:0.75651
[17]	validation_0-rmse:0.74636
[18]	validation_0-rmse:0.75285
[19]	validation_0-rmse:0.75798
[20]	validation_0-rmse:0.74948
[21]	validation_0-rmse:0.74978
[22]	validation_0-rmse:0.74564
[23]	validation_0-rmse:0.74451
[24]	validation_0-rmse:0.74285
[25]	validation_0-rmse:0.74409
[26]	validation_0-rmse:0.75175
[27]	validation_0-rmse:0.75370
[28]	validation_0-rmse:0.75124
[29]	validation_0-rmse:0.75509
[30]	validation_0-rmse:0.76076
[31]	validation_0-rmse:0.75908
[32]	validation_0-rmse:0.75591
[33]	validation_0-rmse:0.75150
[34]	validation_0-rmse:0.74736
[35]	validation_0-rmse:0.75017
[36]	validation_0-rmse:0.74459
[37]	validation_0-rmse:0.74942
[38]	validation_0-rmse:0.74762
[39]	validation_0-rmse:0.74647
[40]	validation_0-rmse:0.74769
[41]	validation_0-rmse:0.74340
[42]	validation_0-rmse:0.74976
[43]	validation_0-rmse:0.74912
[44]	validation_0-rmse:0.74609
[45]	validation_0-rmse:0.74900
[46]	validation_0-rmse:0.74853
[47]	validation_0-rmse:0.74785
[48]	validation_0-rmse:0.74269
[49]	validation_0-rmse:0.74442
[50]	validation_0-rmse:0.74981
[51]	validation_0-rmse:0.75335
[52]	validation_0-rmse:0.75046
[53]	validation_0-rmse:0.75241
[54]	validation_0-rmse:0.75151
[55]	validation_0-rmse:0.74713
[56]	validation_0-rmse:0.75453
[57]	validation_0-rmse:0.75395
[58]	validation_0-rmse:0.75428
[59]	validation_0-rmse:0.75052
[60]	validation_0-rmse:0.75209
[61]	validation_0-rmse:0.75212
[62]	validation_0-rmse:0.75480
[63]	validation_0-rmse:0.75475
[64]	validation_0-rmse:0.75547
[65]	validation_0-rmse:0.75535
[66]	validation_0-rmse:0.75621
[67]	validation_0-rmse:0.75626
[68]	validation_0-rmse:0.75618
[69]	validation_0-rmse:0.75609
[70]	validation_0-rmse:0.75600
[71]	validation_0-rmse:0.74905
[72]	validation_0-rmse:0.74873
[73]	validation_0-rmse:0.75019
[74]	validation_0-rmse:0.75173
[75]	validation_0-rmse:0.74741
[76]	validation_0-rmse:0.75233
[77]	validation_0-rmse:0.75279
[78]	validation_0-rmse:0.75273
[79]	validation_0-rmse:0.75260
[80]	validation_0-rmse:0.75324
[81]	validation_0-rmse:0.75319
[82]	validation_0-rmse:0.75636
[83]	validation_0-rmse:0.75644
[84]	validation_0-rmse:0.75449
[85]	validation_0-rmse:0.75486
[86]	validation_0-rmse:0.75484
[87]	validation_0-rmse:0.75496
[88]	validation_0-rmse:0.75864
[89]	validation_0-rmse:0.76337
[90]	validation_0-rmse:0.76452
[91]	validation_0-rmse:0.76462
[92]	validation_0-rmse:0.76512
[93]	validation_0-rmse:0.76806
[94]	validation_0-rmse:0.77050
[95]	validation_0-rmse:0.77052
[96]	validation_0-rmse:0.77417
[97]	validation_0-rmse:0.77459
[98]	validation_0-rmse:0.77454
[99]	validation_0-rmse:0.77267
[100]	validation_0-rmse:0.77526
[101]	validation_0-rmse:0.77662
[102]	validation_0-rmse:0.78576
[103]	validation_0-rmse:0.78596
[104]	validation_0-rmse:0.77741
[105]	validation_0-rmse:0.77745
[106]	validation_0-rmse:0.77750
[107]	validation_0-rmse:0.77737
[108]	validation_0-rmse:0.77772
[109]	validation_0-rmse:0.77795
[110]	validation_0-rmse:0.77879
[111]	validation_0-rmse:0.78188
[112]	validation_0-rmse:0.78181
[113]	validation_0-rmse:0.78183
[114]	validation_0-rmse:0.78195
[115]	validation_0-rmse:0.78185
[116]	validation_0-rmse:0.78131
[117]	validation_0-rmse:0.78423
[118]	validation_0-rmse:0.78421
[119]	validation_0-rmse:0.78216
[120]	validation_0-rmse:0.78240
[121]	validation_0-rmse:0.78242
[122]	validation_0-rmse:0.78306
[123]	validation_0-rmse:0.78179
[124]	validation_0-rmse:0.78088
[125]	validation_0-rmse:0.78912
[126]	validation_0-rmse:0.78923
[127]	validation_0-rmse:0.79261
[128]	validation_0-rmse:0.79255
[129]	validation_0-rmse:0.79260
[130]	validation_0-rmse:0.79228
[131]	validation_0-rmse:0.79282
[132]	validation_0-rmse:0.79273
[133]	validation_0-rmse:0.79137
[134]	validation_0-rmse:0.79138
[135]	validation_0-rmse:0.79126
[136]	validation_0-rmse:0.78963
[137]	validation_0-rmse:0.78964
[138]	validation_0-rmse:0.78981
[139]	validation_0-rmse:0.78979
[140]	validation_0-rmse:0.78980
[141]	validation_0-rmse:0.79333
[142]	validation_0-rmse:0.79328
[143]	validation_0-rmse:0.79484
[144]	validation_0-rmse:0.79542
[145]	validation_0-rmse:0.79563
[146]	validation_0-rmse:0.79784
[147]	validation_0-rmse:0.79685
[148]	validation_0-rmse:0.79738
[149]	validation_0-rmse:0.79735
[150]	validation_0-rmse:0.79642
[151]	validation_0-rmse:0.79625
[152]	validation_0-rmse:0.79611
[153]	validation_0-rmse:0.79623
[154]	validation_0-rmse:0.79617
[155]	validation_0-rmse:0.79651
[156]	validation_0-rmse:0.79930
[157]	validation_0-rmse:0.79938
[158]	validation_0-rmse:0.79919
[159]	validation_0-rmse:0.79920
[160]	validation_0-rmse:0.80306
[161]	validation_0-rmse:0.80323
[162]	validation_0-rmse:0.80325
[163]	validation_0-rmse:0.80308
[164]	validation_0-rmse:0.80316
[165]	validation_0-rmse:0.80320
[166]	validation_0-rmse:0.80375
[167]	validation_0-rmse:0.80386
[168]	validation_0-rmse:0.80694
[169]	validation_0-rmse:0.80716
[170]	validation_0-rmse:0.80710
[171]	validation_0-rmse:0.80727
[172]	validation_0-rmse:0.80718
[173]	validation_0-rmse:0.80725
[174]	validation_0-rmse:0.80609
[175]	validation_0-rmse:0.80659
[176]	validation_0-rmse:0.80656
[177]	validation_0-rmse:0.80647
[178]	validation_0-rmse:0.80649
[179]	validation_0-rmse:0.80581
[180]	validation_0-rmse:0.80585
[181]	validation_0-rmse:0.80568
[182]	validation_0-rmse:0.80556
[183]	validation_0-rmse:0.80569
[184]	validation_0-rmse:0.80332
[185]	validation_0-rmse:0.80316
[186]	validation_0-rmse:0.80322
[187]	validation_0-rmse:0.80325
[188]	validation_0-rmse:0.80318
[189]	validation_0-rmse:0.80317
[190]	validation_0-rmse:0.80196
[191]	validation_0-rmse:0.80413
[192]	validation_0-rmse:0.80414
[193]	validation_0-rmse:0.80388
[194]	validation_0-rmse:0.80583
[195]	validation_0-rmse:0.80579
[196]	validation_0-rmse:0.80594
[197]	validation_0-rmse:0.80594
[198]	validation_0-rmse:0.80586
[199]	validation_0-rmse:0.80572
[200]	validation_0-rmse:0.80882
[201]	validation_0-rmse:0.80879
[202]	validation_0-rmse:0.80881
[203]	validation_0-rmse:0.80886
[204]	validation_0-rmse:0.81318
[205]	validation_0-rmse:0.80895
[206]	validation_0-rmse:0.80286
[207]	validation_0-rmse:0.80030
[208]	validation_0-rmse:0.79966
[209]	validation_0-rmse:0.79882
[210]	validation_0-rmse:0.79801
[211]	validation_0-rmse:0.79792
[212]	validation_0-rmse:0.79803
[213]	validation_0-rmse:0.79729
[214]	validation_0-rmse:0.80060
[215]	validation_0-rmse:0.80042
[216]	validation_0-rmse:0.80053
[217]	validation_0-rmse:0.80064
[218]	validation_0-rmse:0.80054
[219]	validation_0-rmse:0.80049
[220]	validation_0-rmse:0.79660
[221]	validation_0-rmse:0.79787
[222]	validation_0-rmse:0.79778
[223]	validation_0-rmse:0.79714
[224]	validation_0-rmse:0.80348
[225]	validation_0-rmse:0.80336
[226]	validation_0-rmse:0.80192
[227]	validation_0-rmse:0.80262
[228]	validation_0-rmse:0.80399
[229]	validation_0-rmse:0.80401
[230]	validation_0-rmse:0.80397
[231]	validation_0-rmse:0.80499
[232]	validation_0-rmse:0.80497
[233]	validation_0-rmse:0.80504
[234]	validation_0-rmse:0.80633
[235]	validation_0-rmse:0.80632
[236]	validation_0-rmse:0.80698
[237]	validation_0-rmse:0.80300
[238]	validation_0-rmse:0.80256
[239]	validation_0-rmse:0.80256
[240]	validation_0-rmse:0.80298
[241]	validation_0-rmse:0.80275
[242]	validation_0-rmse:0.80257
[243]	validation_0-rmse:0.80153
[244]	validation_0-rmse:0.80142
[245]	validation_0-rmse:0.80147
[246]	validation_0-rmse:0.79828
[247]	validation_0-rmse:0.79837
[248]	validation_0-rmse:0.79624
[249]	validation_0-rmse:0.79640
[250]	validation_0-rmse:0.79689
[251]	validation_0-rmse:0.79672
[252]	validation_0-rmse:0.79663
[253]	validation_0-rmse:0.79665
[254]	validation_0-rmse:0.79659
[255]	validation_0-rmse:0.79651
[256]	validation_0-rmse:0.79653
[257]	validation_0-rmse:0.79669
[258]	validation_0-rmse:0.79894
[259]	validation_0-rmse:0.79889
[260]	validation_0-rmse:0.79892
[261]	validation_0-rmse:0.79895
[262]	validation_0-rmse:0.79884
[263]	validation_0-rmse:0.79870
[264]	validation_0-rmse:0.79843
[265]	validation_0-rmse:0.79839
[266]	validation_0-rmse:0.79848
[267]	validation_0-rmse:0.79739
[268]	validation_0-rmse:0.79885
[269]	validation_0-rmse:0.79676
[270]	validation_0-rmse:0.79705
[271]	validation_0-rmse:0.79693
[272]	validation_0-rmse:0.79669
[273]	validation_0-rmse:0.79240
[274]	validation_0-rmse:0.79586
[275]	validation_0-rmse:0.79595
[276]	validation_0-rmse:0.79600
[277]	validation_0-rmse:0.79393
[278]	validation_0-rmse:0.79260
[279]	validation_0-rmse:0.79228
[280]	validation_0-rmse:0.79229
[281]	validation_0-rmse:0.79226
[282]	validation_0-rmse:0.79211
[283]	validation_0-rmse:0.79232
[284]	validation_0-rmse:0.79245
[285]	validation_0-rmse:0.79252
[286]	validation_0-rmse:0.79256
[287]	validation_0-rmse:0.79267
[288]	validation_0-rmse:0.79260
[289]	validation_0-rmse:0.79249
[290]	validation_0-rmse:0.79252
[291]	validation_0-rmse:0.79250
[292]	validation_0-rmse:0.79233
[293]	validation_0-rmse:0.79962
[294]	validation_0-rmse:0.80004
[295]	validation_0-rmse:0.80007
[296]	validation_0-rmse:0.80010
[297]	validation_0-rmse:0.79835
[298]	validation_0-rmse:0.79691
[299]	validation_0-rmse:0.79598
[300]	validation_0-rmse:0.79620
[301]	validation_0-rmse:0.79699
[302]	validation_0-rmse:0.79707
[303]	validation_0-rmse:0.79697
[304]	validation_0-rmse:0.79601
[305]	validation_0-rmse:0.79617
[306]	validation_0-rmse:0.79624
[307]	validation_0-rmse:0.79643
[308]	validation_0-rmse:0.79644
[309]	validation_0-rmse:0.79276
[310]	validation_0-rmse:0.79258
[311]	validation_0-rmse:0.79281
[312]	validation_0-rmse:0.79255
[313]	validation_0-rmse:0.79262
[314]	validation_0-rmse:0.79270
[315]	validation_0-rmse:0.79277
[316]	validation_0-rmse:0.79293
[317]	validation_0-rmse:0.79289
[318]	validation_0-rmse:0.79197
[319]	validation_0-rmse:0.79175
[320]	validation_0-rmse:0.79195
[321]	validation_0-rmse:0.79165
[322]	validation_0-rmse:0.79154
[323]	validation_0-rmse:0.79510
[324]	validation_0-rmse:0.79526
[325]	validation_0-rmse:0.79514
[326]	validation_0-rmse:0.79519
[327]	validation_0-rmse:0.79147
[328]	validation_0-rmse:0.79133
[329]	validation_0-rmse:0.79142
[330]	validation_0-rmse:0.79173
[331]	validation_0-rmse:0.78962
[332]	validation_0-rmse:0.78944
[333]	validation_0-rmse:0.78957
[334]	validation_0-rmse:0.79365
[335]	validation_0-rmse:0.79302
[336]	validation_0-rmse:0.79311
[337]	validation_0-rmse:0.79342
[338]	validation_0-rmse:0.79328
[339]	validation_0-rmse:0.79270
[340]	validation_0-rmse:0.79246
[341]	validation_0-rmse:0.79268
[342]	validation_0-rmse:0.79835
[343]	validation_0-rmse:0.79823
[344]	validation_0-rmse:0.79838
[345]	validation_0-rmse:0.79844
[346]	validation_0-rmse:0.79835
[347]	validation_0-rmse:0.79859
[348]	validation_0-rmse:0.79846
[349]	validation_0-rmse:0.79841
[350]	validation_0-rmse:0.79836
[351]	validation_0-rmse:0.79825
[352]	validation_0-rmse:0.79831
[353]	validation_0-rmse:0.79806
[354]	validation_0-rmse:0.80141
[355]	validation_0-rmse:0.80155
[356]	validation_0-rmse:0.80135
[357]	validation_0-rmse:0.80128
[358]	validation_0-rmse:0.80121
[359]	validation_0-rmse:0.80223
[360]	validation_0-rmse:0.80370
[361]	validation_0-rmse:0.80416
[362]	validation_0-rmse:0.80404
[363]	validation_0-rmse:0.80671
[364]	validation_0-rmse:0.80702
[365]	validation_0-rmse:0.80794
[366]	validation_0-rmse:0.80810
[367]	validation_0-rmse:0.80845
[368]	validation_0-rmse:0.80802
[369]	validation_0-rmse:0.80785
[370]	validation_0-rmse:0.80807
[371]	validation_0-rmse:0.80827
[372]	validation_0-rmse:0.80814
[373]	validation_0-rmse:0.80791
[374]	validation_0-rmse:0.80751
[375]	validation_0-rmse:0.80740
[376]	validation_0-rmse:0.80742
[377]	validation_0-rmse:0.80732
[378]	validation_0-rmse:0.81022
[379]	validation_0-rmse:0.81007
[380]	validation_0-rmse:0.81025
[381]	validation_0-rmse:0.80906
[382]	validation_0-rmse:0.80914
[383]	validation_0-rmse:0.80906
[384]	validation_0-rmse:0.80877
[385]	validation_0-rmse:0.80887
[386]	validation_0-rmse:0.80869
[387]	validation_0-rmse:0.80891
[388]	validation_0-rmse:0.80266
[389]	validation_0-rmse:0.80256
[390]	validation_0-rmse:0.80241
[391]	validation_0-rmse:0.80240
[392]	validation_0-rmse:0.80234
[393]	validation_0-rmse:0.80240
[394]	validation_0-rmse:0.80255
[395]	validation_0-rmse:0.80247
[396]	validation_0-rmse:0.80315
[397]	validation_0-rmse:0.79917
[398]	validation_0-rmse:0.79917
[399]	validation_0-rmse:0.80123
        Mean     StdDev  Actual
0  33.008890  13.705512    34.0
1  34.733856  13.418917    36.0
2  34.453857  13.420212    36.0
3  34.411837  15.389450    35.0
4  58.657791  35.803417    44.6

In [44]:
generate_and_save_plots(predictions_XGB_TF_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx

In [45]:
generate_and_save_crps_decomposition(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx
   Sheets: CRPS_Summary_XGBoost, CRPS_Bins_XGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  XGBoost    4.283455     4.302145    5.559241     5.540551        10

In [46]:
generate_and_save_pit_results(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx

    PIT_Value
0    0.528824
1    0.537586
2    0.545861
3    0.515243
4    0.347293
..        ...
90   0.276789
91   0.700863
92   0.591558
93   0.406140
94   0.578530

[95 rows x 1 columns]

In [47]:
generate_and_save_calibration_curve(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.010526        0.189474
3                  0.3            0.063158        0.236842
4                  0.4            0.200000        0.200000
5                  0.5            0.515789        0.015789
6                  0.6            0.831579        0.231579
7                  0.7            0.936842        0.236842
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using LGBM (Treeffuser)**

In [48]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

lgbm_score_engine = TreeBasedScoreModel(
    model_name='lightgbm',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=lgbm_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_LGBM_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_LGBM_TF_df.head())

        Mean    StdDev  Actual
0  36.248061  5.055493    34.0
1  34.288940  5.003845    36.0
2  35.530766  6.185587    36.0
3  30.337966  4.822265    35.0
4  51.873981  7.740601    44.6

In [49]:
generate_and_save_plots(predictions_LGBM_TF_df, y_test, "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx

In [50]:
generate_and_save_crps_decomposition(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx
   Sheets: CRPS_Summary_LightGBM, CRPS_Bins_LightGBM

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LightGBM       2.538     2.562972    5.565523     5.540551        10

In [51]:
generate_and_save_pit_results(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx

    PIT_Value
0    0.328277
1    0.633805
2    0.530234
3    0.833171
4    0.173681
..        ...
90   0.058582
91   0.845343
92   0.617338
93   0.596812
94   0.384381

[95 rows x 1 columns]

In [52]:
generate_and_save_calibration_curve(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.031579        0.068421
2                  0.2            0.073684        0.126316
3                  0.3            0.189474        0.110526
4                  0.4            0.326316        0.073684
5                  0.5            0.463158        0.036842
6                  0.6            0.663158        0.063158
7                  0.7            0.852632        0.152632
8                  0.8            0.926316        0.126316
9                  0.9            0.978947        0.078947
10                 1.0            1.000000        0.000000

# **IBUG Installation**

In [53]:
# Clone the repository
!git clone https://github.com/jjbrophy47/ibug.git
%cd ibug

# Build extensions if needed
!python setup.py build_ext --inplace

# Install the package
!pip install .

# Verify installation
try:
    from ibug import IBUGWrapper
    print("IBUGWrapper imported successfully!")
except ImportError as e:
    print("Error importing IBUGWrapper:", e)

Cloning into 'ibug'...
remote: Enumerating objects: 1763, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1763 (delta 18), reused 15 (delta 4), pack-reused 1726 (from 1)
Receiving objects: 100% (1763/1763), 1.31 MiB | 4.17 MiB/s, done.
Resolving deltas: 100% (967/967), done.
/content/ibug
Compiling ibug/parsers/_tree32.pyx because it changed.
Compiling ibug/parsers/_tree64.pyx because it changed.
[1/2] Cythonizing ibug/parsers/_tree32.pyx
performance hint: ibug/parsers/_tree32.pyx:84:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:112:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:140:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:238:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:266:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:312:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:344:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:352:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:355:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:400:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:401:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:417:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:418:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:434:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:435:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:464:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:465:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
[2/2] Cythonizing ibug/parsers/_tree64.pyx
performance hint: ibug/parsers/_tree64.pyx:93:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:121:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:149:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:247:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:275:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:321:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:353:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:361:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:364:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:409:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:410:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:426:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:427:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:443:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:444:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:473:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:474:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
running build_ext
building 'ibug.parsers._tree32' extension
creating build/temp.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree32.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree32.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
creating build/lib.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so
building 'ibug.parsers._tree64' extension
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree64.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree64.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
Processing /content/ibug
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.26.4)
Collecting uncertainty-toolbox>=0.1.0 (from ibug==0.0.12)
  Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: joblib>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.5.3)
Requirement already satisfied: scikit-learn>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.6.1)
Requirement already satisfied: scipy>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.16.3)
Requirement already satisfied: pandas>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (2.2.2)
Requirement already satisfied: Cython>=0.29.23 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.0.12)
Requirement already satisfied: xgboost>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2026.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.5.0->ibug==0.0.12) (3.6.0)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.10.0)
Requirement already satisfied: tqdm>=4.54.0 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.67.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost>=1.6.1->ibug==0.0.12) (2.27.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.3->ibug==0.0.12) (1.17.0)
Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl (24 kB)
Building wheels for collected packages: ibug
  Building wheel for ibug (pyproject.toml) ... done
  Created wheel for ibug: filename=ibug-0.0.12-cp312-cp312-linux_x86_64.whl size=1457992 sha256=8f43b36dff8c4cb4bff5f6aee43431f2243466e8bb5f21930e4cc085a6b29eaa
  Stored in directory: /tmp/pip-ephem-wheel-cache-kuefef11/wheels/bc/4c/24/9707d9556afa0b36e8ea6c7b2641eb7474f791664f4bb187cd
Successfully built ibug
Installing collected packages: uncertainty-toolbox, ibug
Successfully installed ibug-0.0.12 uncertainty-toolbox-0.1.1
IBUGWrapper imported successfully!

In [54]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3)

# **Probabilistic Distributions using LGBM (IBUG)**

In [55]:
# y_train = y_train.to_numpy()
# y_val = y_val.to_numpy()

In [56]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

# --- Ensure IBUG compatibility ---
best_params['reg_alpha'] = 0
best_params['class_weight'] = None
best_params['boosting_type'] = 'gbdt'

# Initialize and train the LightGBM regressor using the best_params
model = LGBMRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location2, scale2, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

dev = scale**0.5
# Create a DataFrame for clarity
predictions_LGBM_df = pd.DataFrame({
    'Mean': location,
    'StdDev': dev,
    'Actual': y_test,
})

print(predictions_LGBM_df.head())

        Mean    StdDev  Actual
0  31.819947  2.411891    34.0
1  36.913643  2.680171    36.0
2  34.804534  1.660364    36.0
3  35.148829  2.680171    35.0
4  52.700883  2.379904    44.6

In [57]:
%cd ..

/content

In [58]:
%cd ..

/

In [59]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx

In [60]:
generate_and_save_crps_decomposition(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx
   Sheets: CRPS_Summary_LGBM, CRPS_Bins_LGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LGBM    2.005299     2.018137     5.55339     5.540551        10

In [61]:
generate_and_save_pit_results(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx

    PIT_Value
0    0.816970
1    0.366593
2    0.764238
3    0.477858
4    0.000332
..        ...
90   0.015240
91   0.664117
92   0.718525
93   0.723759
94   0.287921

[95 rows x 1 columns]

In [62]:
generate_and_save_calibration_curve(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.136842        0.036842
2                  0.2            0.200000        0.000000
3                  0.3            0.284211        0.015789
4                  0.4            0.347368        0.052632
5                  0.5            0.442105        0.057895
6                  0.6            0.505263        0.094737
7                  0.7            0.589474        0.110526
8                  0.8            0.673684        0.126316
9                  0.9            0.747368        0.152632
10                 1.0            1.000000        0.000000

# **Probabilistic Distributions using XGBoost (IBUG)**

In [63]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

best_params['reg_alpha'] = 0
best_params['scale_pos_weight'] = 1
best_params['base_score'] = 0.5

# Initialize and train the XGBoost regressor using the best_params
model = XGBRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
# This returns the predicted mean (location) and uncertainty (scale, variance proxy)
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location, scale, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

# Calculate the standard deviation from the variance (scale)
std_dev = scale ** 0.5

# Create a DataFrame for clarity
predictions_XGB_df = pd.DataFrame({
    'Mean': location,
    'StdDev': std_dev,
    'Actual': y_test
})

print(predictions_XGB_df.head())

        Mean    StdDev  Actual
0  32.288765  2.562268    34.0
1  37.074501  2.611769    36.0
2  34.904522  1.931511    36.0
3  36.725964  2.611769    35.0
4  49.893444  3.251505    44.6

In [64]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx

In [65]:
generate_and_save_crps_decomposition(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx
   Sheets: CRPS_Summary_XGB, CRPS_Bins_XGB

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0   XGB    1.916152     1.930797    5.555197     5.540551        10

In [66]:
generate_and_save_pit_results(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx

    PIT_Value
0    0.747888
1    0.340387
2    0.714698
3    0.254357
4    0.051763
..        ...
90   0.042149
91   0.453701
92   0.762517
93   0.308535
94   0.437697

[95 rows x 1 columns]

In [67]:
generate_and_save_calibration_curve(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.147368        0.047368
2                  0.2            0.252632        0.052632
3                  0.3            0.315789        0.015789
4                  0.4            0.389474        0.010526
5                  0.5            0.452632        0.047368
6                  0.6            0.515789        0.084211
7                  0.7            0.600000        0.100000
8                  0.8            0.694737        0.105263
9                  0.9            0.778947        0.121053
10                 1.0            1.000000        0.000000

# **Matrix Evaulation**

In [68]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

# Create a Pandas Excel writer using XlsxWriter as the engine.
folder_path = "/content/drive/MyDrive/streamflow_uncertainty_analysis"
excel_path = os.path.join(folder_path, "/content/drive/MyDrive/streamflow_uncertainty_analysis/probabilistic_distribution/Matrix Evaluation.xlsx")
with pd.ExcelWriter(_ensure_parent_dir(excel_path), engine='xlsxwriter') as writer:
    plot_metrics_and_save_to_excel(writer, predictions_NGB_df, y_test, 'NGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_PGBM_df, y_test, 'PGBM')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_df, y_test, 'LGBM')
    plot_metrics_and_save_to_excel(writer, predictions_XGB_df, y_test, 'XGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_TF_df, y_test, "LightGBM_TF")
    plot_metrics_and_save_to_excel(writer, predictions_XGB_TF_df, y_test, "XGBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_CatBoost_TF_df, y_test, "CatBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GPBoost_TF_df, y_test, "GPBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GBR_TF_df, y_test, "GradientBoosting_TF")