# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install git+https://github.com/DaneshSelwal/treeffuser.git

Collecting git+https://github.com/DaneshSelwal/treeffuser.git
  Cloning https://github.com/DaneshSelwal/treeffuser.git to /tmp/pip-req-build-rz4_gaue
  Running command git clone --filter=blob:none --quiet https://github.com/DaneshSelwal/treeffuser.git /tmp/pip-req-build-rz4_gaue
  Resolved https://github.com/DaneshSelwal/treeffuser.git to commit 9717581990db9e7dedaa8c593ec724997e52bdb8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: einops<0.9.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.8.2)
Collecting jaxtyping<0.3.0,>=0.2.19 (from treeffuser==0.1.3)
  Downloading jaxtyping-0.2.38-py3-none-any.whl.metadata (6.6 kB)
Collecting lightgbm==4.3.0 (from treeffuser==0.1.3)
  Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting ml-collections<0.2.0,>=0.1.1 (from treeffuser==0.1.3)
  Downloading ml_collections-0.1.1.tar.gz (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy<2.0,>=1.24 (from treeffuser==0.1.3)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (2.2.2)
Collecting scikit-learn==1.5.0 (from treeffuser==0.1.3)
  Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy<2.0,>=1.13 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (1.16.3)
Requirement already satisfied: tqdm<5.0.0,>=4.66.4 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (3.6.0)
Collecting wadler-lindig>=0.1.3 (from jaxtyping<0.3.0,>=0.2.19->treeffuser==0.1.3)
  Downloading wadler_lindig-0.1.7-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (6.0.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.17.0)
Collecting contextlib2 (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3)
  Downloading contextlib2-21.6.0-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2026.1)
Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 22.0 MB/s eta 0:00:00
Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 21.4 MB/s eta 0:00:00
Downloading jaxtyping-0.2.38-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 1.4 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 21.0 MB/s eta 0:00:00
Downloading wadler_lindig-0.1.7-py3-none-any.whl (20 kB)
Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Building wheels for collected packages: treeffuser, ml-collections
  Building wheel for treeffuser (pyproject.toml) ... done
  Created wheel for treeffuser: filename=treeffuser-0.1.3-py3-none-any.whl size=27752 sha256=bbd69aae1e7b4f3e34763d597e0b56622df8d79b3097ee5326cb1e1f1d3f0869
  Stored in directory: /tmp/pip-ephem-wheel-cache-eu1c30bb/wheels/5f/d1/1a/e628d7eb76d35fc5915026a0d96591b38160a883cc5a7d2116
  Building wheel for ml-collections (setup.py) ... done
  Created wheel for ml-collections: filename=ml_collections-0.1.1-py3-none-any.whl size=94507 sha256=f8b7609f2cd5500a1eb1388d23f4e29a872fc9dcef1e36b36874456520bd712b
  Stored in directory: /root/.cache/pip/wheels/3e/53/7b/1a6f4bfa9dac09618feedc8b1f28a55d4ab9d4bb8835dc0b7e
Successfully built treeffuser ml-collections
Installing collected packages: wadler-lindig, numpy, contextlib2, ml-collections, jaxtyping, scikit-learn, lightgbm, treeffuser
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 4.6.0
    Uninstalling lightgbm-4.6.0:
      Successfully uninstalled lightgbm-4.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed contextlib2-21.6.0 jaxtyping-0.2.38 lightgbm-4.3.0 ml-collections-0.1.1 numpy-1.26.4 scikit-learn-1.5.0 treeffuser-0.1.3 wadler-lindig-0.1.7

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, which is not installed.
spopt 0.7.0 requires scikit-learn>=1.4.0, which is not installed.
accelerate 1.13.0 requires torch>=2.0.0, which is not installed.
cufflinks 0.17.3 requires plotly>=4.1.1, which is not installed.
peft 0.19.1 requires torch>=1.13.0, which is not installed.
spreg 1.9.0 requires scikit-learn>=0.22, which is not installed.
sentence-transformers 5.4.1 requires scikit-learn>=0.22.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
fastai 2.8.7 requires scikit-learn, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
umap-learn 0.5.12 requires scikit-learn>=1.6, which is not installed.
dopamine-rl 4.1.2 requires tensorflow>=2.2.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow-probability>=0.13.0, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
hdbscan 0.8.42 requires scikit-learn>=1.6, which is not installed.
pynndescent 0.6.0 requires scikit-learn>=0.18, which is not installed.
imbalanced-learn 0.14.1 requires scikit-learn<2,>=1.4.2, which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
geemap 0.37.2 requires plotly, which is not installed.
mapclassify 2.10.0 requires scikit-learn>=1.4, which is not installed.
keras-hub 0.26.0 requires tensorflow-text; platform_system != "Windows", which is not installed.
esda 2.9.0 requires scikit-learn>=1.4, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
ydf-tf 2.20.0 requires tensorflow==2.20.0, which is not installed.
segregation 2.5.4 requires scikit-learn>=0.21.3, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
libpysal 4.14.1 requires scikit-learn>=1.4.0, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
pysal 25.7 requires scikit-learn>=1.1, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 89.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
sentence-transformers 5.4.1 requires torch>=1.11.0, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
segregation 2.5.4 requires seaborn, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 52.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 37.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 7.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
timm 1.0.26 requires torchvision, which is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 14.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, but you have lightgbm 4.6.0 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 96.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 25.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 7.4 MB/s eta 0:00:00
  Building wheel for autograd-gamma (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 18.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 12.2 MB/s eta 0:00:00
  Building wheel for pgbm (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.7/449.7 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 14.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for shap (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 5.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.0/244.0 kB 17.6 MB/s eta 0:00:00
  Building wheel for lime (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 35.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 69.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 64.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 89.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 68.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 778.9/778.9 kB 34.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 101.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 17.9 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 18.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 30.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 33.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for cp (setup.py) ... done

# **Imports**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ngboost
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from pathlib import Path
from scipy.stats import norm, kstest
from pytorch_tabnet import TabNetRegressor
from treeffuser import Treeffuser, Samples
from treeffuser._score_models import TreeBasedScoreModel

In [ ]:
# Go to find & replace button and replace (concrete_uncertainty_analysis) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (str) with actual data label name.

In [ ]:
feature_names = ['C', 'mp', 'FA', 'CA', 'F', 'W_P', 'Adm']

In [ ]:
train_data_path = "./drive/MyDrive/concrete_uncertainty_analysis/data/train.csv"
test_data_path = "./drive/MyDrive/concrete_uncertainty_analysis/data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [ ]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (1095, 4)
First 5 rows of training data:
       Qt   Qt-1    St-1      St
0  12.40  11.80  5930.0  5630.0
1   7.93  12.40  5630.0  1960.0
2   5.66   7.93  1960.0   491.0
3   5.04   5.66   491.0   692.0
4   4.84   5.04   692.0   452.0

Shape of test data: (365, 4)
First 5 rows of test data:
      Qt  Qt-1  St-1    St
0  5.27  5.49  45.0  44.0
1  5.13  5.27  44.0  29.0
2  4.84  5.13  29.0  23.0
3  5.04  4.84  23.0  26.0
4  5.21  5.04  26.0  30.0

In [ ]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (1095, 3)
Shape of y_train: (1095,)
Shape of X_test: (365, 3)
Shape of y_test: (365,)

In [ ]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[-0.13088871 -0.15525695  1.01508124]
 [-0.31063021 -0.131129    0.95334642]
 [-0.40190834 -0.31088224  0.19812377]
 [-0.42683893 -0.40216633 -0.10417107]
 [-0.43488105 -0.42709855 -0.06280874]]

First five rows of normalized X_test:
[[-0.41759048 -0.40900259 -0.19595018]
 [-0.42321997 -0.4178495  -0.19615596]
 [-0.43488105 -0.42347936 -0.1992427 ]
 [-0.42683893 -0.4351412  -0.2004774 ]
 [-0.42000312 -0.42709855 -0.19986005]]

# **Functions:**

In [ ]:
# Define the model classes
model_classes = {
    'Random Forest': RandomForestRegressor,
    'Gradient Boosting': GradientBoostingRegressor,
    'XGBoost': XGBRegressor,
    'LightGBM': LGBMRegressor,
    'GPBoost': GPBoostRegressor,
    'CatBoost': CatBoostRegressor,
    'HistGradientBoosting': HistGradientBoostingRegressor,
    'TabNet': TabNetRegressor,
    'NGBoost': NGBRegressor
}

def _ensure_excel_file(path):
    if not os.path.exists(path):
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        pd.DataFrame().to_excel(path)
    return path

In [ ]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [ ]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_plots(predictions_df, y_test, excel_path):
    # 1. Predicted vs. Actual Plot
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x='Actual', y='Mean', data=predictions_df)
    plt.plot([predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             [predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             color='red', linestyle='--')
    plt.title('Predicted str vs. Actual str')
    plt.xlabel('Actual str')
    plt.ylabel('Predicted Mean str')
    plt.tight_layout()
    predicted_vs_actual_path = 'predicted_vs_actual.png'
    _ensure_parent_dir(predicted_vs_actual_path)
    plt.savefig(_ensure_parent_dir(predicted_vs_actual_path))
    plt.close()

    # 2. Uncertainty Bands
    plt.figure(figsize=(12, 8))
    plt.errorbar(x=range(len(predictions_df)), y=predictions_df['Mean'],
                 yerr=predictions_df['StdDev'], fmt='o', markersize=4, ecolor='red', elinewidth=1, capsize=5, alpha=0.7)
    plt.plot(range(len(predictions_df)), predictions_df['Mean'], color='black', linewidth=0.5, alpha=0.7)
    plt.title('Predicted Mean with Uncertainty Bands', fontsize=16)
    plt.xlabel('Sample Number', fontsize=14)
    plt.ylabel('Predicted Mean str')
    plt.tight_layout()
    uncertainty_bands_path = 'uncertainty_bands.png'
    _ensure_parent_dir(uncertainty_bands_path)
    plt.savefig(_ensure_parent_dir(uncertainty_bands_path))
    plt.close()

    # 3. Histogram of Standard Deviations
    plt.figure(figsize=(12, 8))
    sns.histplot(predictions_df['StdDev'], bins=20, kde=True)
    plt.title('Distribution of Predicted Standard Deviations')
    plt.xlabel('Standard Deviation')
    plt.ylabel('Frequency')
    plt.tight_layout()
    histogram_stddev_path = 'histogram_stddev.png'
    _ensure_parent_dir(histogram_stddev_path)
    plt.savefig(_ensure_parent_dir(histogram_stddev_path))
    plt.close()

    # 4. Residual Plot
    residuals = predictions_df['Actual'] - predictions_df['Mean']
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x=predictions_df['Mean'], y=residuals)
    plt.axhline(0, color='red', linestyle='--')
    plt.title('Residual Plot')
    plt.xlabel('Predicted Mean str')
    plt.ylabel('Residuals')
    plt.tight_layout()
    residual_plot_path = 'residual_plot.png'
    _ensure_parent_dir(residual_plot_path)
    plt.savefig(_ensure_parent_dir(residual_plot_path))
    plt.close()

    # Plot the standard deviation of the predictions
    plt.figure(figsize=(12, 6))
    plt.plot(
        predictions_df['StdDev'],
        label='Standard Deviation',
        color='green',
        marker='o',
        linestyle='dashed'
    )
    plt.xlabel('Sample Number')
    plt.ylabel('Standard Deviation')
    plt.title('Standard Deviation of Predictions')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    stddev_plot_path = 'stddev_plot.png'
    _ensure_parent_dir(stddev_plot_path)
    plt.savefig(_ensure_parent_dir(stddev_plot_path))
    plt.close()

    # Plot the actual vs predicted mean with confidence intervals
    plt.figure(figsize=(12, 6))
    plt.plot(
        y_test,
        label='Actual str',
        color='black',
        marker='o',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    plt.plot(
        predictions_df['Mean'],
        label='Predicted Mean str',
        color='red',
        marker='x',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    confidence_interval = 1.96 * predictions_df['StdDev']
    plt.fill_between(
        np.arange(len(predictions_df)),
        predictions_df['Mean'] - confidence_interval,
        predictions_df['Mean'] + confidence_interval,
        color='blue',
        alpha=0.2,
        label='95% Confidence Interval'
    )
    plt.xlabel('Sample Number')
    plt.ylabel(' str')
    plt.title('Predictions with Confidence Intervals')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    prediction_plot_path = 'prediction_plot.png'
    _ensure_parent_dir(prediction_plot_path)
    plt.savefig(_ensure_parent_dir(prediction_plot_path))
    plt.close()

    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(_ensure_parent_dir(excel_path), engine='xlsxwriter')

    # Write the dataframe to a worksheet.
    writer
    predictions_df.to_excel(writer, sheet_name='Predictions', index=False)

    # Access the XlsxWriter workbook and worksheet objects from the writer object.
    workbook = writer.book

    # Insert the plots into new worksheets.
    worksheet_predicted_vs_actual = workbook.add_worksheet('Predicted vs Actual')
    worksheet_predicted_vs_actual.insert_image('A1', predicted_vs_actual_path)

    worksheet_uncertainty_bands = workbook.add_worksheet('Uncertainty Bands')
    worksheet_uncertainty_bands.insert_image('A1', uncertainty_bands_path)

    worksheet_histogram_stddev = workbook.add_worksheet('Histogram StdDev')
    worksheet_histogram_stddev.insert_image('A1', histogram_stddev_path)

    worksheet_residual_plot = workbook.add_worksheet('Residual Plot')
    worksheet_residual_plot.insert_image('A1', residual_plot_path)

    worksheet_stddev = workbook.add_worksheet('StdDev Plot')
    worksheet_stddev.insert_image('A1', stddev_plot_path)

    worksheet_prediction = workbook.add_worksheet('Predictions Plot')
    worksheet_prediction.insert_image('A1', prediction_plot_path)

    # Close the Pandas Excel writer and output the Excel file.
    writer.close()
    print(f"Excel file saved at {excel_path}")

    # Optionally, remove the image files now that they're embedded in the Excel file
    if os.path.exists(str(predicted_vs_actual_path)): os.remove(str(predicted_vs_actual_path))
    if os.path.exists(str(uncertainty_bands_path)): os.remove(str(uncertainty_bands_path))
    if os.path.exists(str(histogram_stddev_path)): os.remove(str(histogram_stddev_path))
    if os.path.exists(str(residual_plot_path)): os.remove(str(residual_plot_path))
    if os.path.exists(str(stddev_plot_path)): os.remove(str(stddev_plot_path))
    if os.path.exists(str(prediction_plot_path)): os.remove(str(prediction_plot_path))

In [ ]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_crps_decomposition(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    # -------------------------------
    # Total CRPS
    # -------------------------------
    crps_values = ps.crps_gaussian(
        y_true, mu=mu_pred, sig=sigma_pred
    )
    total_crps = np.mean(crps_values)

    # -------------------------------
    # Uncertainty (climatology)
    # -------------------------------
    global_mu = np.mean(y_true)
    global_sigma = np.std(y_true)

    uncertainty = np.mean(
        ps.crps_gaussian(y_true, mu=global_mu, sig=global_sigma)
    )

    # -------------------------------
    # Reliability & Resolution
    # -------------------------------
    sort_idx = np.argsort(mu_pred)
    y_sorted = y_true[sort_idx]
    mu_sorted = mu_pred[sort_idx]
    sigma_sorted = sigma_pred[sort_idx]

    bins = np.array_split(np.arange(len(y_true)), n_bins)

    bin_results = []
    reliability_sum = 0.0

    for i, b in enumerate(bins):
        bin_y = y_sorted[b]
        bin_mu = mu_sorted[b]
        bin_sigma = sigma_sorted[b]

        bin_crps = np.mean(
            ps.crps_gaussian(bin_y, mu=bin_mu, sig=bin_sigma)
        )

        reliability_sum += bin_crps

        bin_results.append({
            "Bin": i + 1,
            "Bin_Size": len(b),
            "Mean_Pred_Mu": np.mean(bin_mu),
            "Mean_Pred_Sigma": np.mean(bin_sigma),
            "Bin_CRPS": bin_crps
        })

    reliability = reliability_sum / n_bins
    resolution = uncertainty - (total_crps - reliability)

    # -------------------------------
    # Summary table
    # -------------------------------
    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Total_CRPS": total_crps,
        "Reliability": reliability,
        "Resolution": resolution,
        "Uncertainty": uncertainty,
        "Num_Bins": n_bins
    }])

    bin_df = pd.DataFrame(bin_results)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_summary = f"CRPS_Summary_{model_name}"
    sheet_bins = f"CRPS_Bins_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)
        writer
        bin_df.to_excel(writer, sheet_name=sheet_bins, index=False)

    print(f"✅ CRPS decomposition saved to:\n{excel_path}")
    print(f"   Sheets: {sheet_summary}, {sheet_bins}")

    return summary_df

In [ ]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_pit_results(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):
    """
    Generate PIT values, histogram, calibration diagnostics,
    and save everything to Excel with the PIT plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Compute PIT values
    # -------------------------------
    pit_values = norm.cdf(y_true, loc=mu_pred, scale=sigma_pred)

    pit_df = pd.DataFrame({"PIT_Value": pit_values})

    # -------------------------------
    # Histogram data
    # -------------------------------
    hist_density, bin_edges = np.histogram(
        pit_values, bins=n_bins, range=(0, 1), density=True
    )
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    hist_df = pd.DataFrame({
        "Bin_Center": bin_centers,
        "Density": hist_density
    })

    # -------------------------------
    # Calibration diagnostics
    # -------------------------------
    pit_mean = pit_values.mean()
    pit_var = pit_values.var()
    ks_stat, ks_pvalue = kstest(pit_values, 'uniform')

    if ks_pvalue > 0.05:
        diagnosis = "Well-calibrated (Uniform PIT)"
    elif pit_var < 1/12:
        diagnosis = "Over-dispersed (Under-confident)"
    elif pit_var > 1/12:
        diagnosis = "Under-dispersed (Over-confident)"
    else:
        diagnosis = "Biased or miscalibrated"

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_PIT": pit_mean,
        "Variance_PIT": pit_var,
        "Ideal_Variance_(1/12)": 1/12,
        "KS_Statistic": ks_stat,
        "KS_pvalue": ks_pvalue,
        "Calibration_Diagnosis": diagnosis
    }])

    # -------------------------------
    # Create PIT plot in memory
    # -------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(
        pit_values,
        bins=n_bins,
        density=True,
        color="skyblue",
        edgecolor="black",
        alpha=0.75
    )
    ax.axhline(1, color="red", linestyle="--", label="Perfect Calibration")
    ax.set_xlabel("PIT Value")
    ax.set_ylabel("Density")
    ax.set_title(f"PIT Histogram – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_values = f"PIT_Values_{model_name}"
    sheet_hist = f"PIT_Histogram_{model_name}"
    sheet_summary = f"PIT_Summary_{model_name}"
    sheet_plot = f"PIT_Plot_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        writer
        pit_df.to_excel(writer, sheet_name=sheet_values, index=False)
        writer
        hist_df.to_excel(writer, sheet_name=sheet_hist, index=False)
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        # Create empty sheet for plot
        workbook = writer.book
        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print(f"✅ PIT values, histogram, summary, and EMBEDDED plot saved to:")
    print(f"   {excel_path}")

    return pit_df

In [ ]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
def generate_and_save_calibration_curve(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_quantiles=10
):
    """
    Generate quantile calibration curve (reliability diagram),
    compute calibration errors, and save everything to Excel
    with the plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()
    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Quantiles
    # -------------------------------
    quantiles = np.linspace(0, 1, n_quantiles + 1)

    observed_freq = []
    predicted_q = []

    for q in quantiles:
        # Predicted value at quantile q
        thresh = norm.ppf(q, loc=mu_pred, scale=sigma_pred)

        # Observed frequency
        obs = np.mean(y_true <= thresh)

        predicted_q.append(q)
        observed_freq.append(obs)

    predicted_q = np.array(predicted_q)
    observed_freq = np.array(observed_freq)

    # -------------------------------
    # Calibration metrics
    # -------------------------------
    mce = np.mean(np.abs(observed_freq - predicted_q))
    rmsce = np.sqrt(np.mean((observed_freq - predicted_q) ** 2))

    calib_df = pd.DataFrame({
        "Predicted_Quantile": predicted_q,
        "Observed_Frequency": observed_freq,
        "Absolute_Error": np.abs(observed_freq - predicted_q)
    })

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_Calibration_Error (MCE)": mce,
        "RMS_Calibration_Error (RMSCE)": rmsce,
        "Num_Quantiles": n_quantiles
    }])

    # -------------------------------
    # Create calibration plot
    # -------------------------------
    fig, ax = plt.subplots(figsize=(7, 7))

    ax.plot([0, 1], [0, 1], 'k--', label="Perfect Calibration")
    ax.plot(
        predicted_q,
        observed_freq,
        'o-',
        color='teal',
        label=f"{model_name}"
    )

    ax.set_xlabel("Predicted Quantile (Confidence Level)")
    ax.set_ylabel("Observed Frequency")
    ax.set_title(f"Quantile Calibration Curve – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_curve = f"Calibration_Curve_{model_name}"
    sheet_summary = f"Calibration_Summary_{model_name}"
    sheet_plot = f"Calibration_Plot_{model_name}"

    with pd.ExcelWriter(_ensure_parent_dir(_ensure_excel_file(
        excel_path)),
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        writer
        calib_df.to_excel(writer, sheet_name=sheet_curve, index=False)
        writer
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        workbook = writer.book

        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print("✅ Calibration curve & metrics saved to Excel:")
    print(f"   {excel_path}")

    return calib_df

In [ ]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

import os
# Define the path to the folder
folder_path = "/content/drive/MyDrive/concrete_uncertainty_analysis"

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

def plot_metrics_and_save_to_excel(writer, predictions_df, y_true, model_name):
    # Calculate metrics
    mean_pred = predictions_df['Mean']
    std_pred = predictions_df['StdDev']

    # Sharpness is the standard deviation
    sharpness = std_pred.mean()

    # CRPS for each prediction
    crps_values = ps.crps_gaussian(y_true, mean_pred, std_pred)

    # Negative Log Likelihood (NLL) for each prediction
    nll_values = -norm.logpdf(y_true, loc=mean_pred, scale=std_pred)
    nll = nll_values.mean()

    # Calibration (Validity)
    percentiles = np.linspace(0, 100, 101)
    calibration = [np.mean((y_true <= np.percentile(mean_pred + std_pred * np.random.randn(*mean_pred.shape), p))) for p in percentiles]

    # Create a DataFrame to store the metrics
    metrics_df = pd.DataFrame({
        'Mean Prediction': mean_pred,
        'Standard Deviation': std_pred,
        'CRPS': crps_values,
        'NLL': nll_values
    })

    # Add summary statistics
    summary_df = pd.DataFrame({
        'Metric': ['Sharpness', 'Mean CRPS', 'Mean NLL'],
        'Value': [sharpness, crps_values.mean(), nll]
    })

    # Write the metrics and summary to the Excel sheet
    metrics_sheet_name = f'{model_name} Metrics'
    writer
    metrics_df.to_excel(writer, sheet_name=metrics_sheet_name, index=False)

    summary_sheet_name = f'{model_name} Summary'
    writer
    summary_df.to_excel(writer, sheet_name=summary_sheet_name, index=False)

    # Plotting
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    # Sharpness plot
    axs[0, 0].hist(std_pred, bins=30, color='skyblue', edgecolor='black')
    axs[0, 0].set_title(f'Sharpness (StdDev) for {model_name}')
    axs[0, 0].set_xlabel('Standard Deviation')
    axs[0, 0].set_ylabel('Frequency')

    # CRPS plot (distribution)
    axs[0, 1].hist(crps_values, bins=30, color='lightgreen', edgecolor='black')
    axs[0, 1].set_title(f'CRPS Distribution for {model_name}')
    axs[0, 1].set_xlabel('CRPS')
    axs[0, 1].set_ylabel('Frequency')

    # NLL plot (distribution)
    axs[1, 0].hist(nll_values, bins=30, color='salmon', edgecolor='black')
    axs[1, 0].set_title(f'NLL Distribution for {model_name}')
    axs[1, 0].set_xlabel('NLL')
    axs[1, 0].set_ylabel('Frequency')

    # Calibration plot
    axs[1, 1].plot(percentiles, calibration, label='Calibration Curve')
    axs[1, 1].plot(percentiles, percentiles / 100, linestyle='--', label='Perfect Calibration')
    axs[1, 1].set_title(f'Calibration (Validity) for {model_name}')
    axs[1, 1].set_xlabel('Predicted Percentile')
    axs[1, 1].set_ylabel('Observed Frequency')
    axs[1, 1].legend()

    plt.tight_layout()

    # Save plots to images
    plot_image_path = f'{model_name}_plots.png'
    fig.savefig(_ensure_parent_dir(plot_image_path))
    plt.close(fig)

    # Insert the plot image into the Excel sheet
    sheet_name = f'{model_name} Plots'
    if sheet_name not in writer.sheets:  # Check if sheet already exists
        # If sheet doesn't exist, create a new one
        worksheet = writer.book.add_worksheet(sheet_name)
    else:
        # If sheet exists, get the existing sheet object to avoid duplicates
        worksheet = writer.sheets[sheet_name]
    worksheet.insert_image('A1', plot_image_path)

# **Tuned Parameters**

In [ ]:
{('Random Forest', 'MedianPruner'): {'best_score': 13.182650929420474,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.182650929420474,
  'test_rmse': 3.63079205262715,
  'test_corr_coef': 0.9362480867949565,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11.272303056476819,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11.272303056476819,
  'test_rmse': 3.3574250634194085,
  'test_corr_coef': 0.9440478855010435,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 11.437119799459747,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 11.437119799459747,
  'test_rmse': 3.3818811036847154,
  'test_corr_coef': 0.9432772188634867,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 10.941206762081073,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 10.941206762081073,
  'test_rmse': 3.3077495011081286,
  'test_corr_coef': 0.94500835984303,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 10.880552388940954, 'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001}, 'test_mse': 10.880552388940954, 'test_rmse': 3.298568233179504, 'test_corr_coef': 0.9451752554913052, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 12.352278459566854,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 12.352278459566854,
  'test_rmse': 3.5145808369657474,
  'test_corr_coef': 0.9402669188906791,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 12.342074924476556,
  'best_params': {'n_estimators': 700,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 12.342074924476556,
  'test_rmse': 3.5131289365004177,
  'test_corr_coef': 0.9395016962237023,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 10.774834068806634,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 10.774834068806634,
  'test_rmse': 3.2825042374392503,
  'test_corr_coef': 0.9460418459494322,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 6.893508647469353,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 6.893508647469353,
  'test_rmse': 2.6255492087312615,
  'test_corr_coef': 0.9651848123284126,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7.763276701627249,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 7.763276701627249,
  'test_rmse': 2.786265727030939,
  'test_corr_coef': 0.960299321352052,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 7.502699891774882,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 7.502699891774882,
  'test_rmse': 2.739105673714485,
  'test_corr_coef': 0.9619355831635854,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 6.834971436808225,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 6.834971436808225,
  'test_rmse': 2.614377829772932,
  'test_corr_coef': 0.9651111711288763,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7.689690948162852, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0}, 'test_mse': 7.689690948162852, 'test_rmse': 2.7730292007411053, 'test_corr_coef': 0.9608862446607661, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 7.33313968984125,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 7.33313968984125,
  'test_rmse': 2.7079770475100506,
  'test_corr_coef': 0.9630585579097957,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7.477744369168925,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7.477744369168925,
  'test_rmse': 2.7345464649862734,
  'test_corr_coef': 0.9619684919611741,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 6.721076366834078,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 6.721076366834078,
  'test_rmse': 2.5925038798108053,
  'test_corr_coef': 0.9662115898059317,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 7.2354047049265535,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.2354047049265535,
  'test_rmse': 2.6898707598928526,
  'test_corr_coef': 0.9632217709829815,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 7.849364083074588,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.849364083074588,
  'test_rmse': 2.8016716586842554,
  'test_corr_coef': 0.9615165743735467,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 7.802370007652632,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.802370007652632,
  'test_rmse': 2.7932722759610513,
  'test_corr_coef': 0.9601176613813349,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 7.5038561309289245,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.5038561309289245,
  'test_rmse': 2.739316727019518,
  'test_corr_coef': 0.9620933960059359,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 7.753185403631509,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.753185403631509,
  'test_rmse': 2.7844542380207127,
  'test_corr_coef': 0.9605410174421329,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 7.342762082653903,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.342762082653903,
  'test_rmse': 2.7097531405376953,
  'test_corr_coef': 0.9624799383766623,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 7.946463097455834,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.946463097455834,
  'test_rmse': 2.8189471611677708,
  'test_corr_coef': 0.9595107073054235,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 7.68912600041155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.68912600041155,
  'test_rmse': 2.772927334138338,
  'test_corr_coef': 0.9608967677017526,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 6.942836699007481,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.942836699007481,
  'test_rmse': 2.634926317567055,
  'test_corr_coef': 0.9649381803805447,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 6.339384073454502,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.339384073454502,
  'test_rmse': 2.5178133515919128,
  'test_corr_coef': 0.9677038688754944,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 6.758719441603299,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.758719441603299,
  'test_rmse': 2.5997537271063385,
  'test_corr_coef': 0.9660330847044307,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 6.613581221431991,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.613581221431991,
  'test_rmse': 2.571688398976826,
  'test_corr_coef': 0.9663576043350901,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 6.471978196181523,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.471978196181523,
  'test_rmse': 2.5440082932611525,
  'test_corr_coef': 0.9670652131417232,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 6.417986013529069,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.417986013529069,
  'test_rmse': 2.533374432161395,
  'test_corr_coef': 0.9674069314589737,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 6.4359570823775485,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.4359570823775485,
  'test_rmse': 2.536918816670638,
  'test_corr_coef': 0.967215553727604,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 6.9216779919281155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.9216779919281155,
  'test_rmse': 2.6309082066708664,
  'test_corr_coef': 0.9648241722428089,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 6.791909837287244,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.791909837287244,
  'test_rmse': 2.606129282535163,
  'test_corr_coef': 0.9653900561558387,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 6.91595927653158,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 5,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.91595927653158,
  'test_rmse': 2.629821149152843,
  'test_corr_coef': 0.9648515786821914,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 6.637421657872717,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.637421657872717,
  'test_rmse': 2.5763194013694646,
  'test_corr_coef': 0.9661244350949006,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 6.981840317927532,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.981840317927532,
  'test_rmse': 2.6423172250749025,
  'test_corr_coef': 0.9644025830408257,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 6.800522852492671,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.800522852492671,
  'test_rmse': 2.607781212543083,
  'test_corr_coef': 0.9653714985141384,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 6.783683738250894,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.783683738250894,
  'test_rmse': 2.6045505827783213,
  'test_corr_coef': 0.9655492785886066,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 6.6942049830778245,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.6942049830778245,
  'test_rmse': 2.5873161737750228,
  'test_corr_coef': 0.965893811326036,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 6.9867218571446,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.9867218571446,
  'test_rmse': 2.6432407868267696,
  'test_corr_coef': 0.964703797234493,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 9.035186244423537,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 6,
   'l2_leaf_reg': 7,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 9.035186244423537,
  'test_rmse': 3.005858653433913,
  'test_corr_coef': 0.9552278367535287,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 8.343074054901802,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 0.8,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 8.343074054901802,
  'test_rmse': 2.8884379956824073,
  'test_corr_coef': 0.9577106066495047,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 9.296767024256646,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 6,
   'l2_leaf_reg': 7,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 9.296767024256646,
  'test_rmse': 3.049060023065575,
  'test_corr_coef': 0.9538042100847459,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 8.468465973062987,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 8.468465973062987,
  'test_rmse': 2.910062881290194,
  'test_corr_coef': 0.9573193591785231,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 8.858038028261644,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 32,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 8.858038028261644,
  'test_rmse': 2.976245626332216,
  'test_corr_coef': 0.9555608145155611,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 8.065492487905287,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 128,
   'min_data_in_leaf': 5,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 8.065492487905287,
  'test_rmse': 2.8399810717512337,
  'test_corr_coef': 0.9591866054335858,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 8.468465973062987,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 8.468465973062987,
  'test_rmse': 2.910062881290194,
  'test_corr_coef': 0.9573193591785231,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 8.468465973062987,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 8.468465973062987,
  'test_rmse': 2.910062881290194,
  'test_corr_coef': 0.9573193591785231,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 6.6047378917594495,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 6.6047378917594495,
  'test_rmse': 2.5699684612382794,
  'test_corr_coef': 0.9663963757035304,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 6.293004523413356,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 6.293004523413356,
  'test_rmse': 2.508586160253093,
  'test_corr_coef': 0.967928045275244,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 6.408298514668425,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 6.408298514668425,
  'test_rmse': 2.531461734782579,
  'test_corr_coef': 0.967313795872684,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 7.3055893885657746,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.3055893885657746,
  'test_rmse': 2.702885382062246,
  'test_corr_coef': 0.9627184230098423,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 7.256071126182388,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.256071126182388,
  'test_rmse': 2.6937095474795325,
  'test_corr_coef': 0.9629438977217578,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 6.05342993358606,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 6.05342993358606,
  'test_rmse': 2.460371909607582,
  'test_corr_coef': 0.9691779486007454,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 6.446423616710878,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 6.446423616710878,
  'test_rmse': 2.538980822438578,
  'test_corr_coef': 0.9675295478887768,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 6.758097580770275,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 6.758097580770275,
  'test_rmse': 2.59963412440487,
  'test_corr_coef': 0.9655177093742602,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 29.748139001731996,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 29.748139001731996,
  'test_rmse': 5.454185457218337,
  'test_corr_coef': 0.8416970792661294,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 23.199777293401414,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 23.199777293401414,
  'test_rmse': 4.816614712991004,
  'test_corr_coef': 0.8894447746865505,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 29.134691912775462,
  'best_params': {'n_d': 32,
   'n_a': 32,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 29.134691912775462,
  'test_rmse': 5.39765614992058,
  'test_corr_coef': 0.8561179691375683,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 28.023707069823285,
  'best_params': {'n_d': 64,
   'n_a': 32,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 28.023707069823285,
  'test_rmse': 5.293742255703736,
  'test_corr_coef': 0.8619148631546711,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 27.147522906259738,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 27.147522906259738,
  'test_rmse': 5.210328483527669,
  'test_corr_coef': 0.872476295813559,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 23.823451877728704,
  'best_params': {'n_d': 8,
   'n_a': 8,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 23.823451877728704,
  'test_rmse': 4.880927358374503,
  'test_corr_coef': 0.8866238340368057,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 20.061086699947932,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 20.061086699947932,
  'test_rmse': 4.478960448580444,
  'test_corr_coef': 0.8968312069653815,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 25.77890292588716,
  'best_params': {'n_d': 32,
   'n_a': 32,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 25.77890292588716,
  'test_rmse': 5.077292873755379,
  'test_corr_coef': 0.8754712747987742,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 7.543467275831011,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 400,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 1.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.543467275831011,
  'test_rmse': 2.746537324674655,
  'test_corr_coef': 0.9616114377144743,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 7.323067966858103,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.1,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.323067966858103,
  'test_rmse': 2.7061167688882355,
  'test_corr_coef': 0.9627605114567329,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 7.185115606850218,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 400,
   'max_depth': 7,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.1,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.185115606850218,
  'test_rmse': 2.6805065951887186,
  'test_corr_coef': 0.9635854689537728,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 7.323067966858103, 'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 7.323067966858103, 'test_rmse': 2.7061167688882355, 'test_corr_coef': 0.9627605114567329, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 7.323067966858103, 'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 7.323067966858103, 'test_rmse': 2.7061167688882355, 'test_corr_coef': 0.9627605114567329, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting', 'HyperbandPruner'): {'best_score': 7.084038147266376,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 100,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.084038147266376,
  'test_rmse': 2.6615856452998794,
  'test_corr_coef': 0.9638241814772153,
  'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting', 'ThresholdPruner'): {'best_score': 7.516099651812948,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.516099651812948,
  'test_rmse': 2.741550592605022,
  'test_corr_coef': 0.9616950051683296,
  'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 7.183181192498337,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 100,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 7.183181192498337,
  'test_rmse': 2.680145740906329,
  'test_corr_coef': 0.9634064407281163,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 7.411087162654288,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_leaves': 15,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 7.411087162654288,
  'test_rmse': 2.7223312000295423,
  'test_corr_coef': 0.9620991973469349,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 6.962272728215163,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_leaves': 25,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'studentt'},
  'test_mse': 6.962272728215163,
  'test_rmse': 2.638611894200275,
  'test_corr_coef': 0.9648235653869933,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 7.07871143085572,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_leaves': 44,
   'min_split_gain': 0.1,
   'reg_lambda': 1.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 7.07871143085572,
  'test_rmse': 2.660584791141925,
  'test_corr_coef': 0.963927642925922,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 6.8496223951523225,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_leaves': 26,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 256,
   'distribution': 'studentt'},
  'test_mse': 6.8496223951523225,
  'test_rmse': 2.617178326968249,
  'test_corr_coef': 0.9650678810916228,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 7.386352397360811,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_leaves': 17,
   'min_split_gain': 0.5,
   'reg_lambda': 1.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 7.386352397360811,
  'test_rmse': 2.7177844648464697,
  'test_corr_coef': 0.962229427551159,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 6.9223305669589,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 47,
   'min_split_gain': 0.1,
   'reg_lambda': 1.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 6.9223305669589,
  'test_rmse': 2.631032224614305,
  'test_corr_coef': 0.9651073798359422,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 6.676373983537216,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_leaves': 25,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'studentt'},
  'test_mse': 6.676373983537216,
  'test_rmse': 2.583868027500092,
  'test_corr_coef': 0.9661443221631455,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 7.351888809415018,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_leaves': 20,
   'min_split_gain': 0.1,
   'reg_lambda': 0.1,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 7.351888809415018,
  'test_rmse': 2.7114366688925298,
  'test_corr_coef': 0.9625146907375025,
  'pruner': 'WilcoxonPruner'}}

In [ ]:
best_scores_autosampler

{('Random Forest', 'MedianPruner'): {'best_score': 13.182650929420474,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.182650929420474,
  'test_rmse': 3.63079205262715,
  'test_corr_coef': 0.9362480867949565,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11.272303056476819,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11.272303056476819,
  'test_rmse': 3.3574250634194085,
  'test_corr_coef': 0.9440478855010435,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 11.437119799459747,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 11.437119799459747,
  'test_rmse': 3.3818811036847154,
  'test_corr_coef': 0.9432772188634867,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 10.941206762081073,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 10.941206762081073,
  'test_rmse': 3.3077495011081286,
  'test_corr_coef': 0.94500835984303,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 10.880552388940954, 'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001}, 'test_mse': 10.880552388940954, 'test_rmse': 3.298568233179504, 'test_corr_coef': 0.9451752554913052, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 12.352278459566854,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 12.352278459566854,
  'test_rmse': 3.5145808369657474,
  'test_corr_coef': 0.9402669188906791,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 12.342074924476556,
  'best_params': {'n_estimators': 700,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 12.342074924476556,
  'test_rmse': 3.5131289365004177,
  'test_corr_coef': 0.9395016962237023,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 10.774834068806634,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 10.774834068806634,
  'test_rmse': 3.2825042374392503,
  'test_corr_coef': 0.9460418459494322,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 6.893508647469353,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 6.893508647469353,
  'test_rmse': 2.6255492087312615,
  'test_corr_coef': 0.9651848123284126,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7.763276701627249,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 7.763276701627249,
  'test_rmse': 2.786265727030939,
  'test_corr_coef': 0.960299321352052,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 7.502699891774882,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 7.502699891774882,
  'test_rmse': 2.739105673714485,
  'test_corr_coef': 0.9619355831635854,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 6.834971436808225,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 6.834971436808225,
  'test_rmse': 2.614377829772932,
  'test_corr_coef': 0.9651111711288763,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7.689690948162852, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0}, 'test_mse': 7.689690948162852, 'test_rmse': 2.7730292007411053, 'test_corr_coef': 0.9608862446607661, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 7.33313968984125,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 7.33313968984125,
  'test_rmse': 2.7079770475100506,
  'test_corr_coef': 0.9630585579097957,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7.477744369168925,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7.477744369168925,
  'test_rmse': 2.7345464649862734,
  'test_corr_coef': 0.9619684919611741,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 6.721076366834078,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 6.721076366834078,
  'test_rmse': 2.5925038798108053,
  'test_corr_coef': 0.9662115898059317,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 7.2354047049265535,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.2354047049265535,
  'test_rmse': 2.6898707598928526,
  'test_corr_coef': 0.9632217709829815,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 7.849364083074588,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.849364083074588,
  'test_rmse': 2.8016716586842554,
  'test_corr_coef': 0.9615165743735467,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 7.802370007652632,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.802370007652632,
  'test_rmse': 2.7932722759610513,
  'test_corr_coef': 0.9601176613813349,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 7.5038561309289245,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.5038561309289245,
  'test_rmse': 2.739316727019518,
  'test_corr_coef': 0.9620933960059359,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 7.753185403631509,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.753185403631509,
  'test_rmse': 2.7844542380207127,
  'test_corr_coef': 0.9605410174421329,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 7.342762082653903,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.342762082653903,
  'test_rmse': 2.7097531405376953,
  'test_corr_coef': 0.9624799383766623,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 7.946463097455834,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.946463097455834,
  'test_rmse': 2.8189471611677708,
  'test_corr_coef': 0.9595107073054235,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 7.68912600041155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.68912600041155,
  'test_rmse': 2.772927334138338,
  'test_corr_coef': 0.9608967677017526,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 6.942836699007481,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.942836699007481,
  'test_rmse': 2.634926317567055,
  'test_corr_coef': 0.9649381803805447,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 6.339384073454502,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.339384073454502,
  'test_rmse': 2.5178133515919128,
  'test_corr_coef': 0.9677038688754944,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 6.758719441603299,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.758719441603299,
  'test_rmse': 2.5997537271063385,
  'test_corr_coef': 0.9660330847044307,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 6.613581221431991,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.613581221431991,
  'test_rmse': 2.571688398976826,
  'test_corr_coef': 0.9663576043350901,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 6.471978196181523,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.471978196181523,
  'test_rmse': 2.5440082932611525,
  'test_corr_coef': 0.9670652131417232,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 6.417986013529069,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.417986013529069,
  'test_rmse': 2.533374432161395,
  'test_corr_coef': 0.9674069314589737,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 6.4359570823775485,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.4359570823775485,
  'test_rmse': 2.536918816670638,
  'test_corr_coef': 0.967215553727604,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 6.9216779919281155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.9216779919281155,
  'test_rmse': 2.6309082066708664,
  'test_corr_coef': 0.9648241722428089,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 6.791909837287244,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.791909837287244,
  'test_rmse': 2.606129282535163,
  'test_corr_coef': 0.9653900561558387,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 6.91595927653158,

In [ ]:
best_scores_autosampler

{('Random Forest', 'MedianPruner'): {'best_score': 13.182650929420474,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 13.182650929420474,
  'test_rmse': 3.63079205262715,
  'test_corr_coef': 0.9362480867949565,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 11.272303056476819,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 11.272303056476819,
  'test_rmse': 3.3574250634194085,
  'test_corr_coef': 0.9440478855010435,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 11.437119799459747,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 11.437119799459747,
  'test_rmse': 3.3818811036847154,
  'test_corr_coef': 0.9432772188634867,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 10.941206762081073,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 10.941206762081073,
  'test_rmse': 3.3077495011081286,
  'test_corr_coef': 0.94500835984303,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 10.880552388940954, 'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001}, 'test_mse': 10.880552388940954, 'test_rmse': 3.298568233179504, 'test_corr_coef': 0.9451752554913052, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 12.352278459566854,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 12.352278459566854,
  'test_rmse': 3.5145808369657474,
  'test_corr_coef': 0.9402669188906791,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 12.342074924476556,
  'best_params': {'n_estimators': 700,
   'criterion': 'poisson',
   'max_depth': 20,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 12.342074924476556,
  'test_rmse': 3.5131289365004177,
  'test_corr_coef': 0.9395016962237023,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 10.774834068806634,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 10.774834068806634,
  'test_rmse': 3.2825042374392503,
  'test_corr_coef': 0.9460418459494322,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 6.893508647469353,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 6.893508647469353,
  'test_rmse': 2.6255492087312615,
  'test_corr_coef': 0.9651848123284126,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 7.763276701627249,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 7.763276701627249,
  'test_rmse': 2.786265727030939,
  'test_corr_coef': 0.960299321352052,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 7.502699891774882,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 7.502699891774882,
  'test_rmse': 2.739105673714485,
  'test_corr_coef': 0.9619355831635854,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 6.834971436808225,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 6.834971436808225,
  'test_rmse': 2.614377829772932,
  'test_corr_coef': 0.9651111711288763,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 7.689690948162852, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0}, 'test_mse': 7.689690948162852, 'test_rmse': 2.7730292007411053, 'test_corr_coef': 0.9608862446607661, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 7.33313968984125,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 7.33313968984125,
  'test_rmse': 2.7079770475100506,
  'test_corr_coef': 0.9630585579097957,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 7.477744369168925,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 7.477744369168925,
  'test_rmse': 2.7345464649862734,
  'test_corr_coef': 0.9619684919611741,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 6.721076366834078,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 6.721076366834078,
  'test_rmse': 2.5925038798108053,
  'test_corr_coef': 0.9662115898059317,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 7.2354047049265535,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.2354047049265535,
  'test_rmse': 2.6898707598928526,
  'test_corr_coef': 0.9632217709829815,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 7.849364083074588,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.849364083074588,
  'test_rmse': 2.8016716586842554,
  'test_corr_coef': 0.9615165743735467,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 7.802370007652632,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.802370007652632,
  'test_rmse': 2.7932722759610513,
  'test_corr_coef': 0.9601176613813349,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 7.5038561309289245,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.5038561309289245,
  'test_rmse': 2.739316727019518,
  'test_corr_coef': 0.9620933960059359,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 7.753185403631509,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.753185403631509,
  'test_rmse': 2.7844542380207127,
  'test_corr_coef': 0.9605410174421329,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 7.342762082653903,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.1,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.342762082653903,
  'test_rmse': 2.7097531405376953,
  'test_corr_coef': 0.9624799383766623,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 7.946463097455834,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.946463097455834,
  'test_rmse': 2.8189471611677708,
  'test_corr_coef': 0.9595107073054235,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 7.68912600041155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 7.68912600041155,
  'test_rmse': 2.772927334138338,
  'test_corr_coef': 0.9608967677017526,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 6.942836699007481,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.942836699007481,
  'test_rmse': 2.634926317567055,
  'test_corr_coef': 0.9649381803805447,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 6.339384073454502,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.339384073454502,
  'test_rmse': 2.5178133515919128,
  'test_corr_coef': 0.9677038688754944,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 6.758719441603299,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.758719441603299,
  'test_rmse': 2.5997537271063385,
  'test_corr_coef': 0.9660330847044307,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 6.613581221431991,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.613581221431991,
  'test_rmse': 2.571688398976826,
  'test_corr_coef': 0.9663576043350901,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 6.471978196181523,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.471978196181523,
  'test_rmse': 2.5440082932611525,
  'test_corr_coef': 0.9670652131417232,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 6.417986013529069,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.417986013529069,
  'test_rmse': 2.533374432161395,
  'test_corr_coef': 0.9674069314589737,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 6.4359570823775485,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.4359570823775485,
  'test_rmse': 2.536918816670638,
  'test_corr_coef': 0.967215553727604,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 6.9216779919281155,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.9216779919281155,
  'test_rmse': 2.6309082066708664,
  'test_corr_coef': 0.9648241722428089,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 6.791909837287244,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 6.791909837287244,
  'test_rmse': 2.606129282535163,
  'test_corr_coef': 0.9653900561558387,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 6.91595927653158,

# **Probabilistic distributions using NGBoost**

In [ ]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize NGBoost model with best_params
ngb_model = NGBRegressor(Dist=Normal, **best_params)

# Fit the model
ngb_model.fit(X_train, y_train)

# Predict the distribution
pred_dist = ngb_model.pred_dist(X_test)

# Extract mean and standard deviation
predictions_NGB_df = pd.DataFrame({
    'Mean': pred_dist.loc,
    'StdDev': pred_dist.scale,
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, pred_dist.loc)
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_NGB_df.head())

Mean Squared Error: 130903.25
        Mean     StdDev  Actual
0  33.827940  16.038047    44.0
1  33.827940  15.581435    29.0
2  31.104331  15.655097    23.0
3  31.104331  17.540864    26.0
4  31.104331  15.880841    30.0

In [ ]:
generate_and_save_plots(predictions_NGB_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution//NGBoost_Prob.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution//NGBoost_Prob.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx
   Sheets: CRPS_Summary_NGBoost, CRPS_Bins_NGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  NGBoost   80.995741    81.950387  544.562204   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx

     PIT_Value
0     0.737040
1     0.378337
2     0.302341
3     0.385527
4     0.472280
..         ...
360   0.300034
361   0.255772
362   0.246518
363   0.232340
364   0.390560

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/NGBoost_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.046575        0.053425
2                  0.2            0.427397        0.227397
3                  0.3            0.536986        0.236986
4                  0.4            0.671233        0.271233
5                  0.5            0.747945        0.247945
6                  0.6            0.821918        0.221918
7                  0.7            0.871233        0.171233
8                  0.8            0.906849        0.106849
9                  0.9            0.931507        0.031507
10                 1.0            1.000000        0.000000

# **Probabilistic distributions using PGBM**

In [ ]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
# Note: Adjust the incompatible keys based on PGBM's requirements
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()

def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)
# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params = best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Extract mean and standard deviation
# Note: PGBM might return predictions in a different format, adjust accordingly
predictions_PGBM_df = pd.DataFrame({
    'Mean': pred_dist.mean(axis=0),
    'StdDev': pred_dist.std(axis=0),
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, predictions_PGBM_df['Mean'])
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/100, Train metric: 4785.5781
Estimator 1/100, Train metric: 4716.0503
Estimator 2/100, Train metric: 4644.9238
Estimator 3/100, Train metric: 4567.3071
Estimator 4/100, Train metric: 4485.7036
Estimator 5/100, Train metric: 4414.1963
Estimator 6/100, Train metric: 4342.2041
Estimator 7/100, Train metric: 4294.3203
Estimator 8/100, Train metric: 4232.3247
Estimator 9/100, Train metric: 4175.2485
Estimator 10/100, Train metric: 4117.8438
Estimator 11/100, Train metric: 4074.5427
Estimator 12/100, Train metric: 4027.6052
Estimator 13/100, Train metric: 3969.5894
Estimator 14/100, Train metric: 3934.0879
Estimator 15/100, Train metric: 3884.0276
Estimator 16/100, Train metric: 3849.3979
Estimator 17/100, Train metric: 3796.5886
Estimator 18/100, Train metric: 3756.7878
Estimator 19/100, Train metric: 3707.1123
Estimator 20/100, Train metric: 3662.5784
Estimator 21/100, Train metric: 3627.9343
Estimator 22/100, Train metric: 3589.0693
Estimator 23/100, Train metric: 3559.3635
Estimator 24/100, Train metric: 3519.8503
Estimator 25/100, Train metric: 3486.7107
Estimator 26/100, Train metric: 3455.1050
Estimator 27/100, Train metric: 3425.0452
Estimator 28/100, Train metric: 3410.2742
Estimator 29/100, Train metric: 3380.3259
Estimator 30/100, Train metric: 3368.2126
Estimator 31/100, Train metric: 3338.4089
Estimator 32/100, Train metric: 3314.2478
Estimator 33/100, Train metric: 3298.9172
Estimator 34/100, Train metric: 3274.0374
Estimator 35/100, Train metric: 3259.7502
Estimator 36/100, Train metric: 3242.4282
Estimator 37/100, Train metric: 3222.9932
Estimator 38/100, Train metric: 3209.1711
Estimator 39/100, Train metric: 3196.1951
Estimator 40/100, Train metric: 3181.8035
Estimator 41/100, Train metric: 3170.4497
Estimator 42/100, Train metric: 3156.1653
Estimator 43/100, Train metric: 3139.1514
Estimator 44/100, Train metric: 3124.4719
Estimator 45/100, Train metric: 3112.9504
Estimator 46/100, Train metric: 3102.4482
Estimator 47/100, Train metric: 3091.2197
Estimator 48/100, Train metric: 3077.9343
Estimator 49/100, Train metric: 3065.4868
Estimator 50/100, Train metric: 3069.4087
Estimator 51/100, Train metric: 3057.7764
Estimator 52/100, Train metric: 3047.5630
Estimator 53/100, Train metric: 3035.9792
Estimator 54/100, Train metric: 3026.7917
Estimator 55/100, Train metric: 3020.9639
Estimator 56/100, Train metric: 3010.0757
Estimator 57/100, Train metric: 3005.9148
Estimator 58/100, Train metric: 3001.2415
Estimator 59/100, Train metric: 2995.9473
Estimator 60/100, Train metric: 2985.3713
Estimator 61/100, Train metric: 2980.9819
Estimator 62/100, Train metric: 2975.9624
Estimator 63/100, Train metric: 2971.2502
Estimator 64/100, Train metric: 2966.4805
Estimator 65/100, Train metric: 2960.4290
Estimator 66/100, Train metric: 2957.1323
Estimator 67/100, Train metric: 2950.0166
Estimator 68/100, Train metric: 2945.8262
Estimator 69/100, Train metric: 2941.5364
Estimator 70/100, Train metric: 2939.0271
Estimator 71/100, Train metric: 2934.4133
Estimator 72/100, Train metric: 2930.0994
Estimator 73/100, Train metric: 2926.9014
Estimator 74/100, Train metric: 2922.0410
Estimator 75/100, Train metric: 2919.2212
Estimator 76/100, Train metric: 2915.2844
Estimator 77/100, Train metric: 2913.6797
Estimator 78/100, Train metric: 2912.4202
Estimator 79/100, Train metric: 2908.8772
Estimator 80/100, Train metric: 2904.2393
Estimator 81/100, Train metric: 2900.8198
Estimator 82/100, Train metric: 2898.2141
Estimator 83/100, Train metric: 2896.2488
Estimator 84/100, Train metric: 2894.7161
Estimator 85/100, Train metric: 2891.2788
Estimator 86/100, Train metric: 2889.5957
Estimator 87/100, Train metric: 2888.5396
Estimator 88/100, Train metric: 2885.8940
Estimator 89/100, Train metric: 2882.8940
Estimator 90/100, Train metric: 2881.8862
Estimator 91/100, Train metric: 2878.5588
Estimator 92/100, Train metric: 2875.9741
Estimator 93/100, Train metric: 2872.4604
Estimator 94/100, Train metric: 2870.9814
Estimator 95/100, Train metric: 2870.4788
Estimator 96/100, Train metric: 2871.1038
Estimator 97/100, Train metric: 2867.2288
Estimator 98/100, Train metric: 2864.3069
Estimator 99/100, Train metric: 2864.2512
Mean Squared Error: 83963.54
        Mean     StdDev  Actual
0  41.141579  29.968269    44.0
1  42.696686  29.601389    29.0
2  26.050650  22.847107    23.0
3  26.480965  37.977989    26.0
4  29.922554  28.062950    30.0

In [ ]:
generate_and_save_plots(predictions_PGBM_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx
   Sheets: CRPS_Summary_PGBM, CRPS_Bins_PGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  PGBM   67.852606    68.656423  544.411374   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx

     PIT_Value
0     0.537994
1     0.321788
2     0.446889
3     0.494948
4     0.501101
..         ...
360   0.403690
361   0.406501
362   0.458692
363   0.400353
364   0.469947

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/PGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.049315        0.050685
2                  0.2            0.117808        0.082192
3                  0.3            0.372603        0.072603
4                  0.4            0.643836        0.243836
5                  0.5            0.819178        0.319178
6                  0.6            0.884932        0.284932
7                  0.7            0.906849        0.206849
8                  0.8            0.934247        0.134247
9                  0.9            0.947945        0.047945
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using GPBoost (Treeffuser)**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

gpboost_score_engine = TreeBasedScoreModel(
    model_name='gpboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

# The fix is in the line below: '_score_model' has been corrected to 'score_model'.
model = Treeffuser(score_model=gpboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GPBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GPBoost_TF_df.head())

[1]	valid_0's l2: 1.07941
[2]	valid_0's l2: 1.06672
[3]	valid_0's l2: 1.05422
[4]	valid_0's l2: 1.04202
[5]	valid_0's l2: 1.03002
[6]	valid_0's l2: 1.01846
[7]	valid_0's l2: 1.00691
[8]	valid_0's l2: 0.995807
[9]	valid_0's l2: 0.984914
[10]	valid_0's l2: 0.973904
[11]	valid_0's l2: 0.96325
[12]	valid_0's l2: 0.952629
[13]	valid_0's l2: 0.942276
[14]	valid_0's l2: 0.931946
[15]	valid_0's l2: 0.921832
[16]	valid_0's l2: 0.912138
[17]	valid_0's l2: 0.902217
[18]	valid_0's l2: 0.892703
[19]	valid_0's l2: 0.883149
[20]	valid_0's l2: 0.873691
[21]	valid_0's l2: 0.864897
[22]	valid_0's l2: 0.856192
[23]	valid_0's l2: 0.847621
[24]	valid_0's l2: 0.839271
[25]	valid_0's l2: 0.831449
[26]	valid_0's l2: 0.823494
[27]	valid_0's l2: 0.815965
[28]	valid_0's l2: 0.808191
[29]	valid_0's l2: 0.800525
[30]	valid_0's l2: 0.793437
[31]	valid_0's l2: 0.786201
[32]	valid_0's l2: 0.779022
[33]	valid_0's l2: 0.771996
[34]	valid_0's l2: 0.764821
[35]	valid_0's l2: 0.758019
[36]	valid_0's l2: 0.751125
[37]	valid_0's l2: 0.74456
[38]	valid_0's l2: 0.738418
[39]	valid_0's l2: 0.731988
[40]	valid_0's l2: 0.725787
[41]	valid_0's l2: 0.720111
[42]	valid_0's l2: 0.714235
[43]	valid_0's l2: 0.708765
[44]	valid_0's l2: 0.703078
[45]	valid_0's l2: 0.697637
[46]	valid_0's l2: 0.69187
[47]	valid_0's l2: 0.686826
[48]	valid_0's l2: 0.681185
[49]	valid_0's l2: 0.676219
[50]	valid_0's l2: 0.670982
[51]	valid_0's l2: 0.665988
[52]	valid_0's l2: 0.661594
[53]	valid_0's l2: 0.656572
[54]	valid_0's l2: 0.652097
[55]	valid_0's l2: 0.647467
[56]	valid_0's l2: 0.64303
[57]	valid_0's l2: 0.638714
[58]	valid_0's l2: 0.634248
[59]	valid_0's l2: 0.629493
[60]	valid_0's l2: 0.625464
[61]	valid_0's l2: 0.620945
[62]	valid_0's l2: 0.616632
[63]	valid_0's l2: 0.612291
[64]	valid_0's l2: 0.607918
[65]	valid_0's l2: 0.603792
[66]	valid_0's l2: 0.599362
[67]	valid_0's l2: 0.594982
[68]	valid_0's l2: 0.591456
[69]	valid_0's l2: 0.58737
[70]	valid_0's l2: 0.583581
[71]	valid_0's l2: 0.579902
[72]	valid_0's l2: 0.57602
[73]	valid_0's l2: 0.572839
[74]	valid_0's l2: 0.569035
[75]	valid_0's l2: 0.565847
[76]	valid_0's l2: 0.562457
[77]	valid_0's l2: 0.558911
[78]	valid_0's l2: 0.555766
[79]	valid_0's l2: 0.552742
[80]	valid_0's l2: 0.549274
[81]	valid_0's l2: 0.546389
[82]	valid_0's l2: 0.543295
[83]	valid_0's l2: 0.540402
[84]	valid_0's l2: 0.537637
[85]	valid_0's l2: 0.534793
[86]	valid_0's l2: 0.531813
[87]	valid_0's l2: 0.528771
[88]	valid_0's l2: 0.525541
[89]	valid_0's l2: 0.52288
[90]	valid_0's l2: 0.52044
[91]	valid_0's l2: 0.51772
[92]	valid_0's l2: 0.514864
[93]	valid_0's l2: 0.512294
[94]	valid_0's l2: 0.509716
[95]	valid_0's l2: 0.507175
[96]	valid_0's l2: 0.504916
[97]	valid_0's l2: 0.502466
[98]	valid_0's l2: 0.499893
[99]	valid_0's l2: 0.497559
[100]	valid_0's l2: 0.495276
[101]	valid_0's l2: 0.49299
[102]	valid_0's l2: 0.490792
[103]	valid_0's l2: 0.488641
[104]	valid_0's l2: 0.486174
[105]	valid_0's l2: 0.484196
[106]	valid_0's l2: 0.482093
[107]	valid_0's l2: 0.479883
[108]	valid_0's l2: 0.477743
[109]	valid_0's l2: 0.475665
[110]	valid_0's l2: 0.473362
[111]	valid_0's l2: 0.471273
[112]	valid_0's l2: 0.46939
[113]	valid_0's l2: 0.467314
[114]	valid_0's l2: 0.46548
[115]	valid_0's l2: 0.463632
[116]	valid_0's l2: 0.46184
[117]	valid_0's l2: 0.459609
[118]	valid_0's l2: 0.458085
[119]	valid_0's l2: 0.456403
[120]	valid_0's l2: 0.454909
[121]	valid_0's l2: 0.453332
[122]	valid_0's l2: 0.451381
[123]	valid_0's l2: 0.44936
[124]	valid_0's l2: 0.447831
[125]	valid_0's l2: 0.446044
[126]	valid_0's l2: 0.444579
[127]	valid_0's l2: 0.443062
[128]	valid_0's l2: 0.441341
[129]	valid_0's l2: 0.43993
[130]	valid_0's l2: 0.438054
[131]	valid_0's l2: 0.436914
[132]	valid_0's l2: 0.435284
[133]	valid_0's l2: 0.433746
[134]	valid_0's l2: 0.432382
[135]	valid_0's l2: 0.43108
[136]	valid_0's l2: 0.429426
[137]	valid_0's l2: 0.428211
[138]	valid_0's l2: 0.426454
[139]	valid_0's l2: 0.425197
[140]	valid_0's l2: 0.423707
[141]	valid_0's l2: 0.422094
[142]	valid_0's l2: 0.420885
[143]	valid_0's l2: 0.419436
[144]	valid_0's l2: 0.418389
[145]	valid_0's l2: 0.416807
[146]	valid_0's l2: 0.415645
[147]	valid_0's l2: 0.41461
[148]	valid_0's l2: 0.413584
[149]	valid_0's l2: 0.412581
[150]	valid_0's l2: 0.411421
[151]	valid_0's l2: 0.410364
[152]	valid_0's l2: 0.409
[153]	valid_0's l2: 0.407571
[154]	valid_0's l2: 0.406377
[155]	valid_0's l2: 0.405421
[156]	valid_0's l2: 0.404257
[157]	valid_0's l2: 0.403268
[158]	valid_0's l2: 0.402188
[159]	valid_0's l2: 0.4012
[160]	valid_0's l2: 0.400098
[161]	valid_0's l2: 0.399265
[162]	valid_0's l2: 0.398293
[163]	valid_0's l2: 0.397205
[164]	valid_0's l2: 0.396133
[165]	valid_0's l2: 0.395278
[166]	valid_0's l2: 0.394294
[167]	valid_0's l2: 0.393269
[168]	valid_0's l2: 0.392165
[169]	valid_0's l2: 0.391499
[170]	valid_0's l2: 0.390572
[171]	valid_0's l2: 0.38958
[172]	valid_0's l2: 0.388526
[173]	valid_0's l2: 0.387485
[174]	valid_0's l2: 0.386714
[175]	valid_0's l2: 0.385675
[176]	valid_0's l2: 0.384661
[177]	valid_0's l2: 0.383637
[178]	valid_0's l2: 0.382933
[179]	valid_0's l2: 0.38176
[180]	valid_0's l2: 0.380885
[181]	valid_0's l2: 0.379998
[182]	valid_0's l2: 0.378905
[183]	valid_0's l2: 0.377852
[184]	valid_0's l2: 0.376677
[185]	valid_0's l2: 0.375629
[186]	valid_0's l2: 0.374663
[187]	valid_0's l2: 0.374004
[188]	valid_0's l2: 0.373021
[189]	valid_0's l2: 0.372189
[190]	valid_0's l2: 0.371554
[191]	valid_0's l2: 0.370648
[192]	valid_0's l2: 0.369733
[193]	valid_0's l2: 0.368773
[194]	valid_0's l2: 0.367892
[195]	valid_0's l2: 0.367248
[196]	valid_0's l2: 0.366555
[197]	valid_0's l2: 0.365687
[198]	valid_0's l2: 0.36478
[199]	valid_0's l2: 0.364152
[200]	valid_0's l2: 0.363447
[201]	valid_0's l2: 0.362853
[202]	valid_0's l2: 0.362007
[203]	valid_0's l2: 0.361197
[204]	valid_0's l2: 0.360566
[205]	valid_0's l2: 0.359793
[206]	valid_0's l2: 0.359099
[207]	valid_0's l2: 0.358364
[208]	valid_0's l2: 0.357638
[209]	valid_0's l2: 0.356874
[210]	valid_0's l2: 0.356144
[211]	valid_0's l2: 0.355384
[212]	valid_0's l2: 0.354422
[213]	valid_0's l2: 0.353524
[214]	valid_0's l2: 0.352811
[215]	valid_0's l2: 0.352021
[216]	valid_0's l2: 0.351394
[217]	valid_0's l2: 0.350532
[218]	valid_0's l2: 0.349865
[219]	valid_0's l2: 0.349326
[220]	valid_0's l2: 0.348753
[221]	valid_0's l2: 0.348089
[222]	valid_0's l2: 0.347443
[223]	valid_0's l2: 0.346869
[224]	valid_0's l2: 0.346316
[225]	valid_0's l2: 0.345691
[226]	valid_0's l2: 0.345064
[227]	valid_0's l2: 0.344452
[228]	valid_0's l2: 0.3439
[229]	valid_0's l2: 0.343298
[230]	valid_0's l2: 0.342717
[231]	valid_0's l2: 0.341861
[232]	valid_0's l2: 0.341368
[233]	valid_0's l2: 0.340742
[234]	valid_0's l2: 0.340155
[235]	valid_0's l2: 0.339414
[236]	valid_0's l2: 0.338977
[237]	valid_0's l2: 0.338467
[238]	valid_0's l2: 0.338076
[239]	valid_0's l2: 0.337575
[240]	valid_0's l2: 0.336832
[241]	valid_0's l2: 0.336381
[242]	valid_0's l2: 0.335762
[243]	valid_0's l2: 0.335385
[244]	valid_0's l2: 0.334883
[245]	valid_0's l2: 0.334266
[246]	valid_0's l2: 0.333714
[247]	valid_0's l2: 0.333189
[248]	valid_0's l2: 0.332542
[249]	valid_0's l2: 0.331941
[250]	valid_0's l2: 0.331543
[251]	valid_0's l2: 0.331058
[252]	valid_0's l2: 0.330619
[253]	valid_0's l2: 0.330043
[254]	valid_0's l2: 0.329362
[255]	valid_0's l2: 0.328943
[256]	valid_0's l2: 0.328537
[257]	valid_0's l2: 0.328161
[258]	valid_0's l2: 0.327729
[259]	valid_0's l2: 0.326972
[260]	valid_0's l2: 0.326532
[261]	valid_0's l2: 0.325878
[262]	valid_0's l2: 0.325352
[263]	valid_0's l2: 0.324838
[264]	valid_0's l2: 0.324277
[265]	valid_0's l2: 0.323895
[266]	valid_0's l2: 0.32361
[267]	valid_0's l2: 0.323087
[268]	valid_0's l2: 0.322566
[269]	valid_0's l2: 0.322246
[270]	valid_0's l2: 0.321967
[271]	valid_0's l2: 0.32171
[272]	valid_0's l2: 0.321175
[273]	valid_0's l2: 0.320869
[274]	valid_0's l2: 0.320251
[275]	valid_0's l2: 0.319823
[276]	valid_0's l2: 0.319311
[277]	valid_0's l2: 0.319045
[278]	valid_0's l2: 0.318848
[279]	valid_0's l2: 0.31837
[280]	valid_0's l2: 0.317892
[281]	valid_0's l2: 0.317393
[282]	valid_0's l2: 0.317144
[283]	valid_0's l2: 0.316833
[284]	valid_0's l2: 0.316368
[285]	valid_0's l2: 0.315922
[286]	valid_0's l2: 0.315359
[287]	valid_0's l2: 0.315065
[288]	valid_0's l2: 0.314579
[289]	valid_0's l2: 0.314299
[290]	valid_0's l2: 0.313907
[291]	valid_0's l2: 0.313478
[292]	valid_0's l2: 0.313071
[293]	valid_0's l2: 0.312864
[294]	valid_0's l2: 0.312543
[295]	valid_0's l2: 0.312152
[296]	valid_0's l2: 0.31168
[297]	valid_0's l2: 0.311508
[298]	valid_0's l2: 0.311136
[299]	valid_0's l2: 0.31076
[300]	valid_0's l2: 0.31054
[301]	valid_0's l2: 0.310332
[302]	valid_0's l2: 0.309929
[303]	valid_0's l2: 0.309671
[304]	valid_0's l2: 0.309377
[305]	valid_0's l2: 0.309221
[306]	valid_0's l2: 0.308842
[307]	valid_0's l2: 0.308362
[308]	valid_0's l2: 0.307913
[309]	valid_0's l2: 0.307686
[310]	valid_0's l2: 0.307338
[311]	valid_0's l2: 0.307136
[312]	valid_0's l2: 0.306777
[313]	valid_0's l2: 0.306524
[314]	valid_0's l2: 0.306186
[315]	valid_0's l2: 0.305883
[316]	valid_0's l2: 0.305713
[317]	valid_0's l2: 0.30551
[318]	valid_0's l2: 0.304606
[319]	valid_0's l2: 0.304229
[320]	valid_0's l2: 0.303899
[321]	valid_0's l2: 0.30355
[322]	valid_0's l2: 0.303213
[323]	valid_0's l2: 0.302387
[324]	valid_0's l2: 0.301617
[325]	valid_0's l2: 0.301377
[326]	valid_0's l2: 0.301021
[327]	valid_0's l2: 0.300676
[328]	valid_0's l2: 0.300382
[329]	valid_0's l2: 0.299779
[330]	valid_0's l2: 0.29894
[331]	valid_0's l2: 0.298415
[332]	valid_0's l2: 0.298051
[333]	valid_0's l2: 0.297748
[334]	valid_0's l2: 0.29751
[335]	valid_0's l2: 0.297285
[336]	valid_0's l2: 0.29689
[337]	valid_0's l2: 0.296563
[338]	valid_0's l2: 0.296311
[339]	valid_0's l2: 0.295497
[340]	valid_0's l2: 0.295181
[341]	valid_0's l2: 0.294886
[342]	valid_0's l2: 0.294002
[343]	valid_0's l2: 0.293468
[344]	valid_0's l2: 0.29303
[345]	valid_0's l2: 0.292814
[346]	valid_0's l2: 0.292634
[347]	valid_0's l2: 0.292367
[348]	valid_0's l2: 0.292005
[349]	valid_0's l2: 0.29169
[350]	valid_0's l2: 0.291344
[351]	valid_0's l2: 0.291091
[352]	valid_0's l2: 0.290843
[353]	valid_0's l2: 0.2903
[354]	valid_0's l2: 0.289745
[355]	valid_0's l2: 0.289461
[356]	valid_0's l2: 0.289108
[357]	valid_0's l2: 0.288941
[358]	valid_0's l2: 0.288193
[359]	valid_0's l2: 0.287873
[360]	valid_0's l2: 0.287305
[361]	valid_0's l2: 0.287085
[362]	valid_0's l2: 0.286969
[363]	valid_0's l2: 0.286783
[364]	valid_0's l2: 0.286663
[365]	valid_0's l2: 0.286274
[366]	valid_0's l2: 0.285935
[367]	valid_0's l2: 0.285259
[368]	valid_0's l2: 0.285063
[369]	valid_0's l2: 0.284751
[370]	valid_0's l2: 0.284524
[371]	valid_0's l2: 0.284292
[372]	valid_0's l2: 0.283791
[373]	valid_0's l2: 0.283722
[374]	valid_0's l2: 0.283268
[375]	valid_0's l2: 0.283131
[376]	valid_0's l2: 0.283023
[377]	valid_0's l2: 0.282774
[378]	valid_0's l2: 0.282583
[379]	valid_0's l2: 0.28237
[380]	valid_0's l2: 0.282163
[381]	valid_0's l2: 0.281945
[382]	valid_0's l2: 0.281755
[383]	valid_0's l2: 0.281639
[384]	valid_0's l2: 0.281419
[385]	valid_0's l2: 0.280772
[386]	valid_0's l2: 0.280639
[387]	valid_0's l2: 0.280389
[388]	valid_0's l2: 0.280082
[389]	valid_0's l2: 0.279949
[390]	valid_0's l2: 0.27977
[391]	valid_0's l2: 0.279601
[392]	valid_0's l2: 0.279402
[393]	valid_0's l2: 0.279312
[394]	valid_0's l2: 0.27875
[395]	valid_0's l2: 0.278224
[396]	valid_0's l2: 0.278002
[397]	valid_0's l2: 0.277795
[398]	valid_0's l2: 0.277645
[399]	valid_0's l2: 0.277438
[400]	valid_0's l2: 0.277259
[401]	valid_0's l2: 0.276606
[402]	valid_0's l2: 0.276124
[403]	valid_0's l2: 0.275445
[404]	valid_0's l2: 0.275355
[405]	valid_0's l2: 0.274684
[406]	valid_0's l2: 0.274412
[407]	valid_0's l2: 0.274214
[408]	valid_0's l2: 0.274119
[409]	valid_0's l2: 0.273884
[410]	valid_0's l2: 0.273689
[411]	valid_0's l2: 0.273418
[412]	valid_0's l2: 0.273226
[413]	valid_0's l2: 0.273111
[414]	valid_0's l2: 0.27281
[415]	valid_0's l2: 0.272383
[416]	valid_0's l2: 0.272261
[417]	valid_0's l2: 0.271741
[418]	valid_0's l2: 0.271493
[419]	valid_0's l2: 0.271315
[420]	valid_0's l2: 0.271198
[421]	valid_0's l2: 0.270997
[422]	valid_0's l2: 0.27036
[423]	valid_0's l2: 0.270184
[424]	valid_0's l2: 0.269894
[425]	valid_0's l2: 0.269788
[426]	valid_0's l2: 0.269744
[427]	valid_0's l2: 0.269543
[428]	valid_0's l2: 0.269374
[429]	valid_0's l2: 0.26873
[430]	valid_0's l2: 0.268311
[431]	valid_0's l2: 0.268103
[432]	valid_0's l2: 0.267499
[433]	valid_0's l2: 0.267349
[434]	valid_0's l2: 0.267144
[435]	valid_0's l2: 0.267104
[436]	valid_0's l2: 0.26698
[437]	valid_0's l2: 0.266852
[438]	valid_0's l2: 0.266629
[439]	valid_0's l2: 0.266359
[440]	valid_0's l2: 0.266257
[441]	valid_0's l2: 0.266021
[442]	valid_0's l2: 0.265792
[443]	valid_0's l2: 0.265638
[444]	valid_0's l2: 0.265513
[445]	valid_0's l2: 0.265414
[446]	valid_0's l2: 0.265254
[447]	valid_0's l2: 0.265184
[448]	valid_0's l2: 0.264773
[449]	valid_0's l2: 0.264403
[450]	valid_0's l2: 0.264203
[451]	valid_0's l2: 0.264098
[452]	valid_0's l2: 0.264022
[453]	valid_0's l2: 0.263988
[454]	valid_0's l2: 0.263812
[455]	valid_0's l2: 0.263313
[456]	valid_0's l2: 0.262731
[457]	valid_0's l2: 0.262575
[458]	valid_0's l2: 0.262475
[459]	valid_0's l2: 0.262175
[460]	valid_0's l2: 0.262038
[461]	valid_0's l2: 0.261861
[462]	valid_0's l2: 0.261758
[463]	valid_0's l2: 0.261565
[464]	valid_0's l2: 0.261477
[465]	valid_0's l2: 0.261143
[466]	valid_0's l2: 0.260605
[467]	valid_0's l2: 0.260387
[468]	valid_0's l2: 0.260242
[469]	valid_0's l2: 0.260111
[470]	valid_0's l2: 0.260116
[471]	valid_0's l2: 0.259826
[472]	valid_0's l2: 0.259728
[473]	valid_0's l2: 0.259641
[474]	valid_0's l2: 0.259556
[475]	valid_0's l2: 0.259467
[476]	valid_0's l2: 0.259328
[477]	valid_0's l2: 0.259225
[478]	valid_0's l2: 0.259106
[479]	valid_0's l2: 0.259028
[480]	valid_0's l2: 0.2586
[481]	valid_0's l2: 0.258153
[482]	valid_0's l2: 0.257603
[483]	valid_0's l2: 0.257557
[484]	valid_0's l2: 0.257221
[485]	valid_0's l2: 0.257222
[486]	valid_0's l2: 0.257146
[487]	valid_0's l2: 0.257059
[488]	valid_0's l2: 0.256916
[489]	valid_0's l2: 0.256882
[490]	valid_0's l2: 0.256825
[491]	valid_0's l2: 0.256716
[492]	valid_0's l2: 0.256626
[493]	valid_0's l2: 0.256533
[494]	valid_0's l2: 0.256439
[495]	valid_0's l2: 0.25646
[496]	valid_0's l2: 0.256365
[497]	valid_0's l2: 0.256262
[498]	valid_0's l2: 0.256175
[499]	valid_0's l2: 0.256105
[500]	valid_0's l2: 0.255626
          Mean       StdDev  Actual
0  1191.566973  5804.755891    44.0
1  -686.284276  9652.164185    29.0
2   729.265734  5102.821600    23.0
3  -163.672920  5218.732064    26.0
4   175.163239  3670.557976    30.0

In [ ]:
generate_and_save_plots(predictions_GPBoost_TF_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_GPBoost, CRPS_Bins_GPBoost

     Model   Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  GPBoost  1579.749289  1583.355653  547.213921   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx

     PIT_Value
0     0.421642
1     0.529537
2     0.444959
3     0.514496
4     0.484227
..         ...
360   0.458038
361   0.462783
362   0.493571
363   0.421308
364   0.469068

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GPBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.008219        0.291781
4                  0.4            0.090411        0.309589
5                  0.5            0.830137        0.330137
6                  0.6            1.000000        0.400000
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Gradient Boosting (Treeffuser)**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

gbr_score_engine = TreeBasedScoreModel(
    model_name='gradient_boosting',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=gbr_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GBR_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GBR_TF_df.head())

          Mean        StdDev  Actual
0  -919.624683   8179.779253    44.0
1 -1980.260427  15555.350323    29.0
2  -280.650557   8239.103273    23.0
3 -2717.366526  22488.748202    26.0
4 -1023.047871  10556.305150    30.0

In [ ]:
generate_and_save_plots(predictions_GBR_TF_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx",
    model_name="Gradient Boosting",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx
   Sheets: CRPS_Summary_Gradient Boosting, CRPS_Bins_Gradient Boosting

,Model,Total_CRPS,Reliability,Resolution,Uncertainty,Num_Bins
0,Gradient Boosting,4194.957011,4193.491633,542.14218,543.607558,10

In [ ]:
generate_and_save_pit_results(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx

     PIT_Value
0     0.546889
1     0.551388
2     0.514700
3     0.548546
4     0.539731
..         ...
360   0.482538
361   0.545500
362   0.523306
363   0.518499
364   0.567571

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/GBoosting_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.046575        0.353425
5                  0.5            0.295890        0.204110
6                  0.6            1.000000        0.400000
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Catboost (Treeffuser)**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

catboost_score_engine = TreeBasedScoreModel(
    model_name='catboost',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=catboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_CatBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_CatBoost_TF_df.head())

         Mean        StdDev  Actual
0   26.579073   2467.359155    44.0
1   94.721037   1118.682131    29.0
2 -527.910239  10632.645485    23.0
3   90.106132    582.469862    26.0
4  703.442203   8854.869899    30.0

In [ ]:
generate_and_save_plots(predictions_CatBoost_TF_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_CatBoost, CRPS_Bins_CatBoost

      Model   Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  CatBoost  1026.542024  1028.079496   545.14503   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx

     PIT_Value
0     0.502817
1     0.476576
2     0.520661
3     0.456181
4     0.469688
..         ...
360   0.509734
361   0.471634
362   0.463006
363   0.503125
364   0.523491

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/CatBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.002740        0.297260
4                  0.4            0.041096        0.358904
5                  0.5            0.578082        0.078082
6                  0.6            0.991781        0.391781
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using XGBoost (Treeffuser)**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

xgb_score_engine = TreeBasedScoreModel(
    model_name='xgboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=xgb_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_XGB_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_XGB_TF_df.head())

[0]	validation_0-rmse:1.01636
[1]	validation_0-rmse:0.99024
[2]	validation_0-rmse:0.99057
[3]	validation_0-rmse:0.99128
[4]	validation_0-rmse:0.99144
[5]	validation_0-rmse:0.99128
[6]	validation_0-rmse:0.96061
[7]	validation_0-rmse:0.93591
[8]	validation_0-rmse:0.91252
[9]	validation_0-rmse:0.89353
[10]	validation_0-rmse:0.87183
[11]	validation_0-rmse:0.85418
[12]	validation_0-rmse:0.85607
[13]	validation_0-rmse:0.83509
[14]	validation_0-rmse:0.81782
[15]	validation_0-rmse:0.79914
[16]	validation_0-rmse:0.78274
[17]	validation_0-rmse:0.78286
[18]	validation_0-rmse:0.78267
[19]	validation_0-rmse:0.76572
[20]	validation_0-rmse:0.75094
[21]	validation_0-rmse:0.73936
[22]	validation_0-rmse:0.72914
[23]	validation_0-rmse:0.71550
[24]	validation_0-rmse:0.70469
[25]	validation_0-rmse:0.69578
[26]	validation_0-rmse:0.68533
[27]	validation_0-rmse:0.68262
[28]	validation_0-rmse:0.67390
[29]	validation_0-rmse:0.66490
[30]	validation_0-rmse:0.66495
[31]	validation_0-rmse:0.66566
[32]	validation_0-rmse:0.66629
[33]	validation_0-rmse:0.65435
[34]	validation_0-rmse:0.64872
[35]	validation_0-rmse:0.64232
[36]	validation_0-rmse:0.63216
[37]	validation_0-rmse:0.62581
[38]	validation_0-rmse:0.61682
[39]	validation_0-rmse:0.61023
[40]	validation_0-rmse:0.60617
[41]	validation_0-rmse:0.59851
[42]	validation_0-rmse:0.59407
[43]	validation_0-rmse:0.58968
[44]	validation_0-rmse:0.58905
[45]	validation_0-rmse:0.58233
[46]	validation_0-rmse:0.58164
[47]	validation_0-rmse:0.57712
[48]	validation_0-rmse:0.57388
[49]	validation_0-rmse:0.56901
[50]	validation_0-rmse:0.56917
[51]	validation_0-rmse:0.56344
[52]	validation_0-rmse:0.56124
[53]	validation_0-rmse:0.55385
[54]	validation_0-rmse:0.55210
[55]	validation_0-rmse:0.54959
[56]	validation_0-rmse:0.54952
[57]	validation_0-rmse:0.54756
[58]	validation_0-rmse:0.54753
[59]	validation_0-rmse:0.54760
[60]	validation_0-rmse:0.54424
[61]	validation_0-rmse:0.54136
[62]	validation_0-rmse:0.53667
[63]	validation_0-rmse:0.53204
[64]	validation_0-rmse:0.52881
[65]	validation_0-rmse:0.52576
[66]	validation_0-rmse:0.52167
[67]	validation_0-rmse:0.52163
[68]	validation_0-rmse:0.52160
[69]	validation_0-rmse:0.51981
[70]	validation_0-rmse:0.51525
[71]	validation_0-rmse:0.51528
[72]	validation_0-rmse:0.51073
[73]	validation_0-rmse:0.50880
[74]	validation_0-rmse:0.50534
[75]	validation_0-rmse:0.50325
[76]	validation_0-rmse:0.50266
[77]	validation_0-rmse:0.50121
[78]	validation_0-rmse:0.50118
[79]	validation_0-rmse:0.50117
[80]	validation_0-rmse:0.49872
[81]	validation_0-rmse:0.49606
[82]	validation_0-rmse:0.49498
[83]	validation_0-rmse:0.49495
[84]	validation_0-rmse:0.49500
[85]	validation_0-rmse:0.48946
[86]	validation_0-rmse:0.48695
[87]	validation_0-rmse:0.48697
[88]	validation_0-rmse:0.48644
[89]	validation_0-rmse:0.48541
[90]	validation_0-rmse:0.48514
[91]	validation_0-rmse:0.48515
[92]	validation_0-rmse:0.48545
[93]	validation_0-rmse:0.48415
[94]	validation_0-rmse:0.48418
[95]	validation_0-rmse:0.48351
[96]	validation_0-rmse:0.48354
[97]	validation_0-rmse:0.48315
[98]	validation_0-rmse:0.48335
[99]	validation_0-rmse:0.47896
          Mean        StdDev  Actual
0 -1806.472697  10439.802190    44.0
1 -1155.396071  15577.663633    29.0
2  -171.943684  13524.488444    23.0
3 -1229.912381  13662.577214    26.0
4  -486.337367   8731.967440    30.0

In [ ]:
generate_and_save_plots(predictions_XGB_TF_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx
   Sheets: CRPS_Summary_XGBoost, CRPS_Bins_XGBoost

     Model   Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  XGBoost  2913.560052  2912.167456  542.214961   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx

     PIT_Value
0     0.570345
1     0.530303
2     0.505750
3     0.536621
4     0.523576
..         ...
360   0.475157
361   0.471732
362   0.527981
363   0.509273
364   0.522308

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.027397        0.372603
5                  0.5            0.367123        0.132877
6                  0.6            1.000000        0.400000
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using LGBM (Treeffuser)**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

lgbm_score_engine = TreeBasedScoreModel(
    model_name='lightgbm',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=lgbm_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_LGBM_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_LGBM_TF_df.head())

          Mean        StdDev  Actual
0   274.321916  12172.680803    44.0
1  -616.080903  11419.335189    29.0
2   347.481700   9651.154944    23.0
3  1097.848933  10911.586156    26.0
4  -270.758735  11704.215125    30.0

In [ ]:
generate_and_save_plots(predictions_LGBM_TF_df, y_test, "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx
   Sheets: CRPS_Summary_LightGBM, CRPS_Bins_LightGBM

      Model   Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LightGBM  2686.176232  2687.317514   544.74884   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx

     PIT_Value
0     0.492452
1     0.522524
2     0.486590
3     0.460875
4     0.510250
..         ...
360   0.466477
361   0.461376
362   0.475473
363   0.445189
364   0.469539

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.021918        0.378082
5                  0.5            0.602740        0.102740
6                  0.6            1.000000        0.400000
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **IBUG Installation**

In [ ]:
# Clone the repository
!git clone https://github.com/jjbrophy47/ibug.git
%cd ibug

# Build extensions if needed
!python setup.py build_ext --inplace

# Install the package
!pip install .

# Verify installation
try:
    from ibug import IBUGWrapper
    print("IBUGWrapper imported successfully!")
except ImportError as e:
    print("Error importing IBUGWrapper:", e)

Cloning into 'ibug'...
remote: Enumerating objects: 1763, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1763 (delta 18), reused 15 (delta 4), pack-reused 1726 (from 1)
Receiving objects: 100% (1763/1763), 1.31 MiB | 13.13 MiB/s, done.
Resolving deltas: 100% (967/967), done.
/content/ibug
Compiling ibug/parsers/_tree32.pyx because it changed.
Compiling ibug/parsers/_tree64.pyx because it changed.
[1/2] Cythonizing ibug/parsers/_tree32.pyx
performance hint: ibug/parsers/_tree32.pyx:84:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:112:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:140:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:238:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:266:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:312:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:344:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:352:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:355:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:400:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:401:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:417:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:418:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:434:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:435:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:464:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:465:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
[2/2] Cythonizing ibug/parsers/_tree64.pyx
performance hint: ibug/parsers/_tree64.pyx:93:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:121:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:149:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:247:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:275:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:321:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:353:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:361:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:364:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:409:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:410:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:426:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:427:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:443:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:444:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:473:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:474:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
running build_ext
building 'ibug.parsers._tree32' extension
creating build/temp.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree32.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree32.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
creating build/lib.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so
building 'ibug.parsers._tree64' extension
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree64.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree64.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
Processing /content/ibug
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.26.4)
Collecting uncertainty-toolbox>=0.1.0 (from ibug==0.0.12)
  Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: joblib>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.5.3)
Requirement already satisfied: scikit-learn>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.6.1)
Requirement already satisfied: scipy>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.16.3)
Requirement already satisfied: pandas>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (2.2.2)
Requirement already satisfied: Cython>=0.29.23 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.0.12)
Requirement already satisfied: xgboost>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.5.0->ibug==0.0.12) (3.6.0)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.10.0)
Requirement already satisfied: tqdm>=4.54.0 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.67.1)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost>=1.6.1->ibug==0.0.12) (2.29.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.3.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.3->ibug==0.0.12) (1.17.0)
Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl (24 kB)
Building wheels for collected packages: ibug
  Building wheel for ibug (pyproject.toml) ... done
  Created wheel for ibug: filename=ibug-0.0.12-cp312-cp312-linux_x86_64.whl size=1457999 sha256=4c7b883d01ba97cfd30506ea233f848df2684f467ea501a7e84abf007cf75858
  Stored in directory: /tmp/pip-ephem-wheel-cache-kuexnj3m/wheels/bc/4c/24/9707d9556afa0b36e8ea6c7b2641eb7474f791664f4bb187cd
Successfully built ibug
Installing collected packages: uncertainty-toolbox, ibug
Successfully installed ibug-0.0.12 uncertainty-toolbox-0.1.1
IBUGWrapper imported successfully!

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3)

# **Probabilistic Distributions using LGBM (IBUG)**

In [ ]:
# y_train = y_train.to_numpy()
# y_val = y_val.to_numpy()

In [ ]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

# --- Ensure IBUG compatibility ---
best_params['reg_alpha'] = 0
best_params['class_weight'] = None
best_params['boosting_type'] = 'gbdt'

# Initialize and train the LightGBM regressor using the best_params
model = LGBMRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location2, scale2, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

dev = scale**0.5
# Create a DataFrame for clarity
predictions_LGBM_df = pd.DataFrame({
    'Mean': location,
    'StdDev': dev,
    'Actual': y_test,
})

print(predictions_LGBM_df.head())

        Mean    StdDev  Actual
0  41.854782  6.797163    44.0
1  41.854782  6.797163    29.0
2  31.007820  6.813883    23.0
3  31.007820  6.813883    26.0
4  31.007820  6.813883    30.0

In [ ]:
%cd ..

/

In [ ]:
%cd ..

/

In [ ]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx
   Sheets: CRPS_Summary_LGBM, CRPS_Bins_LGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LGBM  121.658452   123.130562  545.079667   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx

     PIT_Value
0     0.623849
1     0.029299
2     0.119953
3     0.231187
4     0.441208
..         ...
360   0.070952
361   0.039013
362   0.028130
363   0.019902
364   0.231187

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/LGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.690411        0.590411
2                  0.2            0.739726        0.539726
3                  0.3            0.772603        0.472603
4                  0.4            0.805479        0.405479
5                  0.5            0.830137        0.330137
6                  0.6            0.852055        0.252055
7                  0.7            0.863014        0.163014
8                  0.8            0.876712        0.076712
9                  0.9            0.882192        0.017808
10                 1.0            1.000000        0.000000

# **Probabilistic Distributions using XGBoost (IBUG)**

In [ ]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

best_params['reg_alpha'] = 0
best_params['scale_pos_weight'] = 1
best_params['base_score'] = 0.5

# Initialize and train the XGBoost regressor using the best_params
model = XGBRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
# This returns the predicted mean (location) and uncertainty (scale, variance proxy)
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location, scale, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

# Calculate the standard deviation from the variance (scale)
std_dev = scale ** 0.5

# Create a DataFrame for clarity
predictions_XGB_df = pd.DataFrame({
    'Mean': location,
    'StdDev': std_dev,
    'Actual': y_test
})

print(predictions_XGB_df.head())

        Mean    StdDev  Actual
0  36.521221  8.143870    44.0
1  32.853024  8.278811    29.0
2  26.758286  8.278811    23.0
3  31.593449  8.278811    26.0
4  26.375904  8.278811    30.0

In [ ]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx

In [ ]:
generate_and_save_crps_decomposition(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx
   Sheets: CRPS_Summary_XGB, CRPS_Bins_XGB

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0   XGB   117.86125   119.384728  545.131035   543.607558        10

In [ ]:
generate_and_save_pit_results(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx

     PIT_Value
0     0.820778
1     0.320820
2     0.324927
3     0.249636
4     0.669218
..         ...
360   0.271599
361   0.197784
362   0.165935
363   0.148530
364   0.480321

[365 rows x 1 columns]

In [ ]:
generate_and_save_calibration_curve(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/XGB_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.449315        0.349315
2                  0.2            0.561644        0.361644
3                  0.3            0.638356        0.338356
4                  0.4            0.701370        0.301370
5                  0.5            0.761644        0.261644
6                  0.6            0.791781        0.191781
7                  0.7            0.819178        0.119178
8                  0.8            0.846575        0.046575
9                  0.9            0.865753        0.034247
10                 1.0            1.000000        0.000000

# **Matrix Evaulation**

In [ ]:
import os

def _ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    return path

# Create a Pandas Excel writer using XlsxWriter as the engine.
folder_path = "/content/drive/MyDrive/concrete_uncertainty_analysis"
excel_path = os.path.join(folder_path, "/content/drive/MyDrive/concrete_uncertainty_analysis/probabilistic_distribution/Matrix Evaluation.xlsx")
with pd.ExcelWriter(_ensure_parent_dir(excel_path), engine='xlsxwriter') as writer:
    plot_metrics_and_save_to_excel(writer, predictions_NGB_df, y_test, 'NGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_PGBM_df, y_test, 'PGBM')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_df, y_test, 'LGBM')
    plot_metrics_and_save_to_excel(writer, predictions_XGB_df, y_test, 'XGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_TF_df, y_test, "LightGBM_TF")
    plot_metrics_and_save_to_excel(writer, predictions_XGB_TF_df, y_test, "XGBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_CatBoost_TF_df, y_test, "CatBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GPBoost_TF_df, y_test, "GPBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GBR_TF_df, y_test, "GradientBoosting_TF")